975 enable trading as name to be piped into questions
ONSdigital/eq-survey-runner pull request #1010
Opened 2017-03-03 16:25 UTC by benjefferies

### What is the context of this PR?
Create a way of dynamically populated trad_as or ru_name from the metadata. See [trello](https://trello.com/c/JLIbPCgI/975-enable-trading-as-name-to-be-piped-into-questions)

### How to review 
- Open qbs with trad_as and ru_name
Expect to see trad_as populated

- Open qbs with only ru_name
Expect to see ru_name populated

- Open mwss with trad_as and ru_name
Expect to see trad_as populated

- Open mwss with only ru_name
Expect to see ru_name populated

2017-03-06 10:37 UTC, LJBabbage requested changes

2017-03-06 10:37 UTC, LJBabbage commented on app/templating/schema_context.py
> +        "display_name": metadata["trad_as"] or metadata["ru_name"],
I reckon we use trad_as_or_ru_name, just makes it clear

2017-03-06 15:29 UTC, benjefferies commented on app/templating/schema_context.py
> +        "display_name": metadata["trad_as"] or metadata["ru_name"],
Done

2017-03-06 16:04 UTC, LJBabbage approved these changes

2017-03-06 16:12 UTC, jonnyshaw89 commented on gulpfile.babel.js
> +    .on('error', (err) => {
Shouldn't this be a separate PR?
I don't really care but its a comment you often raise :)

2017-03-06 16:14 UTC, benjefferies commented on gulpfile.babel.js
> +    .on('error', (err) => {
Yes but didn't want to create a ticket for it 😆. Do you want me to?

2017-03-06 16:16 UTC, jonnyshaw89 commented on gulpfile.babel.js
> +    .on('error', (err) => {
No. I was just being annoying.

2017-03-07 11:35 UTC, jonnyshaw89 approved these changes

2017-03-07 12:22 UTC, merged