Remove or ignore remaining pylint issues and fail on any pylint problem
ONSdigital/eq-survey-runner pull request #1018
Opened 2017-03-07 13:34 UTC by collisdigital

### What is the context of this PR?
- Either fixed or set a disable flag for all remaining pylint issues
- Changed `run_lint.sh` to fail on ANY pylint issue (warning, error etc.)
- Changed `run_lint.sh` to stop doing full reports, they are noise and output in pretty colours

### How to review 
- Run `./scripts/run_lint.sh` and check it passes
- Review code changes or pylint disabled options added.

2017-03-07 13:35 UTC, collisdigital commented on app/forms/fields.py
> +            NumberRange(maximum=9999999999, messages=answer_errors),
min/max clash with the Python built-in with the same name

2017-03-07 13:35 UTC, collisdigital commented on app/forms/fields.py
> +        self.data = None
Pylint complained that self.data is used later in this class but not declared in `__init__`

2017-03-07 13:36 UTC, collisdigital commented on app/data_model/database.py
> +        except Exception as e:  # pylint: disable=broad-except
Hard to predict what can go wrong when trying to setup the database; so this retries x times before giving up and throwing the last exception caught.

2017-03-07 13:36 UTC, collisdigital commented on app/templating/summary_context.py
> +                link = url_for('questionnaire.get_block',
indent issue resolved

2017-03-07 13:36 UTC, collisdigital commented on app/validation/validators.py
> +    :param minimum:
min/max clash with the Python built-in with the same name

2017-03-07 13:37 UTC, collisdigital commented on scripts/run_lint.sh
> +pylint --reports=n --output-format=colorized --rcfile=.pylintrc -j 0 ./app ./tests
we only get errors or warnings output to console now; not the full code-tree and tabulated results etc. errors and warnings are coloured coded

2017-03-07 13:37 UTC, collisdigital commented on tests/app/parser/test_metadata_parser.py
> +            "user_id": "1",
indent issue

2017-03-07 13:37 UTC, collisdigital commented on tests/app/parser/test_metadata_parser.py
> +        valid, _ = is_valid_metadata(jwt)
unused field

2017-03-07 14:16 UTC, benjefferies requested changes
Looks good. Only thing is the linting doesn't run on travis anymore (my fault)

2017-03-07 14:16 UTC, benjefferies commented on scripts/run_lint.sh
> +pylint --reports=n --output-format=colorized --rcfile=.pylintrc -j 0 ./app ./tests
Much better output

2017-03-07 15:32 UTC, collisdigital commented
Going to rebase and squash this now

2017-03-07 15:56 UTC, benjefferies approved these changes

2017-03-07 15:58 UTC, collisdigital commented
There's a code coverage issue on this PR where an indent level has been changed and the line wasn't covered by a test; suggest we ignore it as unrelated to the change being made.

2017-03-08 15:07 UTC, ajmaddaford commented
`app/parser/parser_utils.py` isn't used, so may be worth removing that and the associated tests and  see if the coverage increases enough to hit the target?

2017-03-08 15:42 UTC, collisdigital commented
@ajmaddaford will remove `app/parser/parser_utils.py`

2017-03-08 16:04 UTC, collisdigital commented
@ajmaddaford removed but didn't change coverage %

2017-03-08 17:42 UTC, ajmaddaford approved these changes

2017-03-08 17:42 UTC, merged