Add support for dumping data by authorised users
ONSdigital/eq-survey-runner pull request #1025
Opened 2017-03-09 07:58 UTC by collisdigital

### What is the context of this PR?
Added a /dump route Blueprint that allows the answer store or submission data to be dumped as JSON at any time.
This requires a user to be logged-in and their metadata to contain a 'role' of 'dumper'.
The /dev page has been updated to always enable the 'dumper' role.
The 'role' metadata has been persisted to the user's metadata.

### How to test?
- Start a questionnaire and answer some questions.
- To dump the answer store go to: /dump/answers
- To dump the submission data go to: /dump/submission
- Check that an invalid dump gives an error e.g. /dump/nothing
- Save and complete later and verify you cannot get to /dump/answers or submission anymore (session expired)

- If you try dumping when there are no answer (e.g. on landing page) you'll get a
bad request because the answer store is empty.

### To review:
- The naming of things, is dump correct, what about the role?
- Are we happy to have the dump blueprint in Production?
- Are the URLs meaningful/standard?
- Is the output useful?

### To-do:
[ ] Add tests
[ ] code review
[ ] rebase and squash

2017-03-09 07:59 UTC, collisdigital commented on app/views/dump.py
> +def dump_data(store):
Should this be split into multiple routes?

2017-03-09 13:09 UTC, LJBabbage commented on app/views/dump.py
> +def dump_data(store):
Would get rid a of some of the logic which is always a win, and you then could put in in a role checker which could be used for the flusher as well

2017-03-10 11:32 UTC, benjefferies requested changes

2017-03-10 11:32 UTC, benjefferies commented on app/views/dump.py
> +                response['status'] = 'OK'
Response seems unnecessary since we get a message and the http code

2017-03-10 11:32 UTC, benjefferies commented on app/views/dump.py
> +def dump_data(store):
I'd agree with different routes

2017-03-10 11:32 UTC, benjefferies commented on app/views/dump.py
> +        if answer_store.answers:
Is the answer_store.answers check necessary?

2017-03-10 11:32 UTC, benjefferies commented on tests/integration/create_token.py
> +def create_token(form_type_id, eq_id, **metadata_kwargs):
Did a similar thing for jti claim branch, now that's in it's worth rebasing and resolving conflicts

2017-03-10 13:35 UTC, collisdigital commented on app/views/dump.py
> +                response['status'] = 'OK'
Agreed, will remove

2017-03-10 13:35 UTC, collisdigital commented on tests/integration/create_token.py
> +def create_token(form_type_id, eq_id, **metadata_kwargs):
Ah great minds, will merge it.

2017-03-10 13:35 UTC, collisdigital commented on app/views/dump.py
> +        if answer_store.answers:
Nope, tidying this all up as part of the route split

2017-03-10 13:35 UTC, collisdigital commented on app/views/dump.py
> +def dump_data(store):
On it

2017-03-10 13:37 UTC, benjefferies commented on app/views/dump.py
> +        if answer_store.answers:
Also we might want to submit answers for a survey which is completely optional (all questions optional)

2017-03-10 14:57 UTC, collisdigital commented on app/views/dump.py
> +def dump_data(store):
Done

2017-03-10 15:03 UTC, collisdigital commented on app/views/dump.py
> +        if answer_store.answers:
Done

2017-03-10 15:03 UTC, collisdigital commented on app/views/dump.py
> +                response['status'] = 'OK'
Done

2017-03-10 15:03 UTC, collisdigital commented on tests/integration/create_token.py
> +def create_token(form_type_id, eq_id, **metadata_kwargs):
Done

2017-03-10 15:07 UTC, benjefferies approved these changes

2017-03-10 15:07 UTC, benjefferies commented on app/views/dump.py
> +def dump_answers():
Much cleaner

2017-03-10 15:07 UTC, benjefferies commented on tests/app/views/test_dump.py
> +        self.assertIn('Forbidden', actual)
Probably will fail the test now

2017-03-10 15:07 UTC, benjefferies commented on tests/integration/create_token.py
> +    payload_vars = PAYLOAD.copy()
Good spot

2017-03-10 15:07 UTC, benjefferies commented on app/views/dump.py
> +@role_required('dumper')
Worth adding to flush now or later?

2017-03-10 15:08 UTC, collisdigital commented on app/views/dump.py
> +@role_required('dumper')
Not easy to do; flush doesn't use the normal login route or user/metadata; we should consider whether to update that later I think

2017-03-10 15:08 UTC, collisdigital commented on tests/app/views/test_dump.py
> +        self.assertIn('Forbidden', actual)
Passes 👍

2017-03-13 09:37 UTC, LJBabbage approved these changes
Sure you have enough tests?

2017-03-13 10:00 UTC, collisdigital commented
@LJBabbage it was a pain getting the decorator right; tests mostly helped me understand how it should/did behave in these various scenarios as it's functions returning functions retuning functions wrapping functions! Could possible remove some of the tests now it's working; but do we want to?

2017-03-13 13:39 UTC, merged