eq-868 Additional Analytics Events
ONSdigital/eq-survey-runner pull request #1027
Opened 2017-03-09 11:42 UTC by hamishtaplin

### What is the context of this PR?

WIP

### How to review 

WIP

2017-03-10 15:12 UTC, collisdigital commented on app/templates/partials/answer-guidance.html
> +    {{guidance_link|xmlattr}} {{helpers.track('click', 'Navigation', 'Guidance', answer_guidance.id)}}>{{_("Show further guidance")}}</a>
Maybe the category for this should be something else; 'Help' or 'Content' or something?

2017-03-10 15:12 UTC, collisdigital commented on app/templates/partials/navigation.html
> +          {{helpers.track('click', 'Navigation', 'Section link', nav_item.link_url)}}>{{nav_item.link_name}}</a>
Did you decide not to make the action's verbs in the end? e.g. `Section Link Clicked` ?

2017-03-10 15:12 UTC, collisdigital commented on app/themes/census/templates/partials/header.html
> +      {{helpers.track('click', 'Navigation', 'Help and support')}}>
Not sure about the category of this being Navigation?

2017-03-10 15:12 UTC, collisdigital commented on gulp/scripts.js
> +  gutil.log('sdfdsffsfs')
this meant to be here?

2017-03-10 15:17 UTC, hamishtaplin commented on app/templates/partials/answer-guidance.html
> +    {{guidance_link|xmlattr}} {{helpers.track('click', 'Navigation', 'Guidance', answer_guidance.id)}}>{{_("Show further guidance")}}</a>
Yeah I did wonder if 'Help' would be a category

2017-03-10 15:31 UTC, hamishtaplin commented on app/templates/partials/navigation.html
> +          {{helpers.track('click', 'Navigation', 'Section link', nav_item.link_url)}}>{{nav_item.link_name}}</a>
It felt a bit redundant but I can add it back in if necessary

2017-03-10 15:31 UTC, hamishtaplin commented on app/themes/census/templates/partials/header.html
> +      {{helpers.track('click', 'Navigation', 'Help and support')}}>
'Help' category I think

2017-03-10 15:31 UTC, hamishtaplin commented on gulp/scripts.js
> +  gutil.log('sdfdsffsfs')
yeah thats a new JS framework called 'sdfdsffsfs.js'

2017-03-10 15:46 UTC, collisdigital commented on app/templates/partials/questions/errors.html
> +      <li class="list__item venus" {{helpers.track('error', 'Error', error, question.id)}}>{{ form.question_errors[question.id] }}</li>
Should this be Error category with 'Error displayed' as the action and the label as the error?

2017-03-10 15:47 UTC, collisdigital commented on gulp/scripts.js
> +  gutil.log('sdfdsffsfs')
It wouldn't surprise me 🙄

2017-03-10 15:55 UTC, hamishtaplin commented on app/templates/partials/questions/errors.html
> +      <li class="list__item venus" {{helpers.track('error', 'Error', error, question.id)}}>{{ form.question_errors[question.id] }}</li>
That would be more consistent but don't we want to have the error message (action) as well as the question.id (label)

2017-03-13 11:55 UTC, bennpearson approved these changes

2017-03-13 13:00 UTC, ajmaddaford requested changes

2017-03-13 13:00 UTC, ajmaddaford commented on app/templates/partials/answer-guidance.html
> +  "id": "guidance-" ~ answer_guidance.id ~ "-body",
Looks like a duplicated line here?

2017-03-13 13:00 UTC, ajmaddaford commented on app/templates/partials/answer-guidance.html
> +    {{guidance_link|xmlattr}} {{helpers.track('click', 'Help', 'Guidance click', answer_guidance.id)}}>{{_("Show further guidance")}}</a>
Is it ok/good practice to have a new line within the `<a>` tag?

2017-03-13 13:00 UTC, ajmaddaford commented on app/templates/partials/navigation.html
> +          {{helpers.track('click', 'Navigation', 'Section link click', nav_item.link_url)}}>{{nav_item.link_name}}</a>
Is it ok/good practice to have a new line within the `<a>` tag?

2017-03-13 13:00 UTC, ajmaddaford commented on app/templates/partials/previous-link.html
> +  href="{{previous_location}}" id="{{position}}-previous">Previous</a>
Is it ok/good practice to have a new line within the `<a>` tag?

2017-03-13 13:01 UTC, collisdigital commented
Reviewed actual events going into GA with @hamishtaplin and @ajmaddaford; looks good. Code review comments, squash and re-base needed.

2017-03-13 15:22 UTC, hamishtaplin commented on app/templates/partials/answer-guidance.html
> +    {{guidance_link|xmlattr}} {{helpers.track('click', 'Help', 'Guidance click', answer_guidance.id)}}>{{_("Show further guidance")}}</a>
It doesn't matter as far as I know as browsers ignore them

2017-03-14 08:31 UTC, ajmaddaford approved these changes

2017-03-14 09:22 UTC, merged