Prevent apache restarts on logrotate
ONSdigital/eq-survey-runner pull request #1028
Opened 2017-03-09 13:35 UTC by jonnyshaw89

### What is the context of this PR?
Changed logrotate to copytruncate to prevent a new file being created and the apache process being restarted to switch to a new file.
Reverted Log format change in favour of default apache output
Removed unused logging configuration

### How to review 
Run in AWS and confirm that Logs are still being delivered to CloudWatch and that on the hour the apache process is not restarted.

2017-03-09 18:54 UTC, collisdigital commented on .ebextensions/cloudwatchlogs-apache/cwl-setup.config
> -########################################################################
hmm, had we added this ourselves? I guess EB now does this itself instead?

2017-03-09 20:14 UTC, jonnyshaw89 commented on .ebextensions/cloudwatchlogs-apache/cwl-setup.config
> -########################################################################
It made no difference when I took it out

2017-03-10 12:06 UTC, ajmaddaford approved these changes

2017-03-10 13:00 UTC, benjefferies commented on .ebextensions/deploy.config
> +                copytruncate
I take it we are happy with the small chance of losing logs here?

2017-03-10 13:00 UTC, benjefferies commented on .ebextensions/cloudwatchlogs-apache/cwl-setup.config
> -########################################################################
The docs around this is very wooly but I have tested and still getting application logs after deploying on this branch

2017-03-10 14:14 UTC, ajmaddaford commented on .ebextensions/deploy.config
> +                copytruncate
No, I think we need to take another look at this. I have separated out the log format change from this in #1029

2017-03-10 14:15 UTC, ajmaddaford requested changes
We need to look at alternatives that don't lose log lines

2017-03-10 14:41 UTC, ajmaddaford commented
Some options we should discuss:
- Apache piped logs (see http://httpd.apache.org/docs/2.2/logs.html#piped and http://tech.zarmory.com/2015/06/aws-elastic-beantalk-is-amateur.html)
- Change log rotation to happen daily
- Do nothing, and under high load accept slow requests on the hour when log rotation is happening

2017-03-14 09:56 UTC, benjefferies requested changes

2017-03-14 09:56 UTC, benjefferies commented on .ebextensions/deploy.config
> +        mode: "000644"
What is the default file permissions/owner of this file, do we actually need to configure it?

2017-03-14 11:01 UTC, jonnyshaw89 commented on .ebextensions/deploy.config
> +        mode: "000644"
These were set to the same as was already on the instance. I've removed as they are not needed.

2017-03-14 11:06 UTC, benjefferies approved these changes

2017-03-14 14:56 UTC, ajmaddaford approved these changes

2017-03-14 16:37 UTC, merged