Eq 1002 replace git ref
ONSdigital/eq-survey-runner pull request #1049
Opened 2017-03-22 10:40 UTC by LJBabbage

### What is the context of this PR?
Remove all references to EQ_GIT_REF and inject a plaintext file into the root of the app at build time

N.B Jenkins will need to be updated after this card has been merged

### How to review 
Make sure every is working as normal

2017-03-22 16:26 UTC, jonnyshaw89 commented
@LJBabbage if you look at the codecov report. There is some more code you can remove

2017-03-23 15:04 UTC, LJBabbage commented
The patch is complaining about things that haven't been changed due to line numbers changing

2017-03-23 17:32 UTC, collisdigital commented on app/__init__.py
> -    from healthcheck import HealthCheck
Does this mean a package can be removed from requirements.txt now?

2017-03-23 17:32 UTC, collisdigital commented on app/settings.py
> +def get_application_version_from_file():
I think there's already a function below that does this (although it might be key related) possible refactor to use a common one?

2017-03-27 09:49 UTC, LJBabbage commented on app/__init__.py
> -    from healthcheck import HealthCheck
Yep, has been removed

2017-03-27 11:09 UTC, benjefferies requested changes

2017-03-27 11:09 UTC, benjefferies commented on app/settings.py
> +        logger.error("reading from file", filename=file_name)
I guess the error level is an accident and should probably be debug

2017-03-27 11:09 UTC, benjefferies commented on app/settings.py
> +        contents = f.read().strip()
Do we need to strip the text read in?

2017-03-27 22:34 UTC, collisdigital commented on app/settings.py
> +def read_file(file_name):
:+1:

2017-03-29 09:44 UTC, benjefferies approved these changes
Good job on removing the redundant code

2017-03-30 07:29 UTC, collisdigital approved these changes
Squash and rebase then this is ready.

2017-03-30 10:58 UTC, merged