Non mandatory date of birth field retains date
ONSdigital/eq-survey-runner pull request #1058
Opened 2017-03-24 15:56 UTC by LJBabbage

### What is the context of this PR?
Non mandatory date of birth field retains date even after respondent deletes the date. A check to see if the dict keys all contain empty values, if they do we can remove the answer from the store

### How to review 
Using test_dates.json, fill out all of the questionnaire, including the last question. Check the summary page is right. Using previous, change the answer to the last question, taking out all values. Submit and make sure the summary screen changes to 'No answer provided'. Hit previous again and make sure the last question is still empty.

2017-03-24 16:08 UTC, yoganandkunche commented
Tested on branch and is working as expected.

2017-03-27 11:36 UTC, benjefferies requested changes

2017-03-27 11:36 UTC, benjefferies commented on app/views/questionnaire.py
> +                if answer_value_empty(answer_value):
Maybe it would be better to do this in `update_questionnaire_store_with_form_data` before it's added

2017-03-27 12:14 UTC, LJBabbage commented on app/views/questionnaire.py
> +                if answer_value_empty(answer_value):
It is in update_questionnaire_store_with_form_data and is before its stored ????

2017-03-27 15:24 UTC, benjefferies approved these changes

2017-03-28 08:25 UTC, jonnyshaw89 approved these changes

2017-03-28 08:56 UTC, merged