submission page loop fix
ONSdigital/eq-survey-runner pull request #1073
Opened 2017-03-30 09:35 UTC by yoganandkunche

### What is the context of this PR?
If the submission failed the user will be left in an infinite loop. 

fixes #1066 

### How to review 
Retest #1066

2017-03-30 10:22 UTC, benjefferies commented
@yoganandkunche your build is failing

2017-03-30 15:10 UTC, LJBabbage requested changes

2017-03-30 15:10 UTC, LJBabbage commented on tests/app/questionnaire/test_path_finder.py
> +    def test_given_no_completed_blocks_when_get_latest_location_then_get_to_first_block(self):
'go to first block' rather then 'get to first block'?

2017-03-30 15:10 UTC, LJBabbage commented on app/questionnaire/path_finder.py
>          return routing_path[0]
Not a fan of the multiple returns

2017-03-30 17:02 UTC, collisdigital approved these changes
Tested locally before and after the fix by enabling RabbitMQ settings; works.

2017-04-03 10:02 UTC, yoganandkunche commented on tests/app/questionnaire/test_path_finder.py
> +    def test_given_no_completed_blocks_when_get_latest_location_then_get_to_first_block(self):
Addressed. Please review

2017-04-03 10:02 UTC, yoganandkunche commented on app/questionnaire/path_finder.py
>          return routing_path[0]
Addressed. Please review

2017-04-03 12:41 UTC, LJBabbage approved these changes

2017-04-03 12:42 UTC, LJBabbage commented
Squash and rebase please

2017-04-03 14:08 UTC, LJBabbage requested changes

2017-04-03 14:08 UTC, LJBabbage commented on tests/app/questionnaire/test_path_finder.py
> +        # Then get to the first block
Still have some typos in here

2017-04-03 14:54 UTC, yoganandkunche commented on tests/app/questionnaire/test_path_finder.py
> +        # Then get to the first block
made the changes, please review

2017-04-03 15:20 UTC, LJBabbage approved these changes

2017-04-03 15:20 UTC, merged