Fixes error 500 issue on some test schemas
ONSdigital/eq-survey-runner pull request #1075
Opened 2017-03-30 15:59 UTC by yoganandkunche

### What is the context of this PR?
Fixes the error 500 issue when the test schemas do not have submission block. fixes #1074

### How to review 
Retest defect #1074

2017-03-30 16:45 UTC, collisdigital commented
You need to run the linting locally and fix the errors:

`./scripts/run_lint.sh`

This is what Travis is failing on above https://travis-ci.org/ONSdigital/eq-survey-runner/builds/216815837

2017-03-30 16:52 UTC, collisdigital commented on tests/app/data/test_schema_validation.py
> +                        confirmation_or_summary_in_block = True
You can `break` after this, there's no need to keep looping once you've found one.

2017-03-30 16:53 UTC, collisdigital approved these changes
Just need to fix the linting...

2017-03-31 10:58 UTC, jonnyshaw89 requested changes

2017-03-31 10:58 UTC, jonnyshaw89 commented on tests/app/data/test_schema_validation.py
> +            self.assertTrue(confirmation_or_summary_in_block, msg='{file} does not has a confirmation or summary page'.format(file=schema_file))
Typo `does not **have** a confirmation or summary page`

2017-03-31 10:58 UTC, jonnyshaw89 commented on tests/app/data/test_schema_validation.py
> +                        confirmation_or_summary_in_block = True
+1 this would be good practice and should be done.
However it should be the last block anyway.

2017-03-31 11:09 UTC, collisdigital commented on tests/app/data/test_schema_validation.py
> +                        confirmation_or_summary_in_block = True
Good point, maybe this should loop backwards through the blocks!

2017-03-31 13:10 UTC, jonnyshaw89 approved these changes

2017-03-31 13:10 UTC, jonnyshaw89 commented
@yoganandkunche squash, rebase?

2017-03-31 14:00 UTC, merged