QBS Increase test coverage of the downstream data
ONSdigital/eq-survey-runner pull request #1086
Opened 2017-04-06 10:25 UTC by yoganandkunche

### What is the context of this PR?
Dumps the answers that are going to be submitted and compares with the answers that were entered.

### How to review 
Run the integrations test.

2017-04-06 11:11 UTC, samiwel approved these changes
Looks good to me.

2017-04-06 13:44 UTC, collisdigital commented on tests/integration/mci/test_change_answers.py
> +        actual = json.loads(self.getResponseData())
I wonder if we should move this into the base class now so we can call `self.dumpAnswers()` which results the parsed json dict so move lines 53 through lines 59 into the IntegrationTestCase class and just call that here

`actual = self.dumpAnswers()`

2017-04-06 13:46 UTC, collisdigital commented on tests/integration/mci/test_change_answers.py
> +        self.get('/dump/answers')
We should test against the submitted data: `self.get('/dump/submission')`

2017-04-06 13:49 UTC, collisdigital commented on tests/integration/mci/test_change_answers.py
> +        actual = json.loads(self.getResponseData())
With above comment, it would be `actual = self.dumpSubmission()`

2017-04-06 13:50 UTC, collisdigital commented on tests/integration/mci/test_change_answers.py
> +import json
if `dumpSubmission` moves to the base class you'll need to remove this import.

2017-04-06 13:51 UTC, collisdigital requested changes
Looking good, some refactoring to reduce duplication needed and should be checking the submission dump instead of answer store.

2017-04-06 17:21 UTC, yoganandkunche commented
@collisdigital addressed all the comments

2017-04-06 19:01 UTC, collisdigital commented on tests/integration/integration_test_case.py
> +    def dumpSubmissions(self):
drop the 's' : Submission

2017-04-06 19:01 UTC, collisdigital commented on tests/integration/qbs/test_qbs_change_answers.py
> +        self.post(action='start_questionnaire')
Should this post be here? I'm interested why the test passes if this shouldn't be

2017-04-07 08:22 UTC, yoganandkunche commented on tests/integration/integration_test_case.py
> +    def dumpSubmissions(self):
made the change

2017-04-07 08:23 UTC, yoganandkunche commented on tests/integration/qbs/test_qbs_change_answers.py
> +        self.post(action='start_questionnaire')
removed the extra unnecessary post.. not sure yet why it still passes with an extra post.

2017-04-07 15:08 UTC, collisdigital approved these changes
Looks good, rebase, squash then ready to merge :+1:

2017-04-10 08:47 UTC, merged