eq-1044 Submission button
ONSdigital/eq-survey-runner pull request #1087
Opened 2017-04-06 15:27 UTC by hamishtaplin

WIP

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2017-04-11 09:45 UTC, armstrongb commented
Can we change this so that the spinner doesn't replace the copy entirely but is shown alongside copy: "[spinner] Submitting..."?
![submission-spinner](https://cloud.githubusercontent.com/assets/22910336/24903015/00248f1e-1ea4-11e7-92a2-971e362b6bcb.png)

2017-04-12 14:04 UTC, yoganandkunche commented
@hamishtaplin: as discussed please add the spinner 'submitting' to MWSS, UKIS and Census submission screens.

2017-04-12 15:50 UTC, yoganandkunche commented
@hamishtaplin timeout pop up displays '**Continuing**..' PFA -- Bug introduced on this branch.

<img width="589" alt="screen shot 2017-04-12 at 16 32 37" src="https://cloud.githubusercontent.com/assets/21335236/24966105/f2105a34-1f9d-11e7-8ddb-28185c64e4da.png">

2017-04-13 10:22 UTC, yoganandkunche commented
@collisdigital I had a discussion with @hamishtaplin and we want you to take a decision before we go ahead with this feature... as at the moment the "[spinner] Submitting..." thing comes up for 5 secs only and the scenario where it is misleading to the respondent is when the network is bad and it takes more than 5 secs before it get submitted the [Submit survey] button is displayed again which might confuse the respondent to click it again which result in 'Session timeout'.

2017-04-13 20:24 UTC, collisdigital commented
Show me on Tuesday

2017-04-18 08:51 UTC, collisdigital commented
Having seen it on a slow connection, can we increase the submitting timer to 10 seconds instead of 5?

2017-04-21 09:53 UTC, bennpearson requested changes
Animation appears to stop after 5 seconds. Not sure if this is something that chrome dev tools throttling is introducing though

2017-04-25 08:01 UTC, ajmaddaford commented
I've just tried this and the animation runs for 10 seconds. The button resizes when the text changes to "Submitting..." which we may not want?

2017-04-25 08:04 UTC, ajmaddaford requested changes

2017-04-25 08:04 UTC, ajmaddaford commented on app/assets/js/app/modules/submitter.js
> +    }, 10000)
We should use a constant for this as it's a little unclear using the value directly.

2017-04-25 13:30 UTC, hamishtaplin commented on app/assets/js/app/modules/submitter.js
> +    }, 10000)
Do we want to make this configurable or just more explicit?

2017-04-25 13:38 UTC, ajmaddaford commented on app/assets/js/app/modules/submitter.js
> +    }, 10000)
Just more explicit

2017-04-26 08:35 UTC, bennpearson approved these changes

2017-04-27 12:04 UTC, ajmaddaford approved these changes

2017-04-27 15:02 UTC, jonnyshaw89 commented
@hamishtaplin Can you update the description on this PR?

2017-04-27 15:43 UTC, jonnyshaw89 approved these changes

2017-04-27 16:46 UTC, merged