added unit tests in user.py and factory.py increase coverage
ONSdigital/eq-survey-runner pull request #1091
Opened 2017-04-11 13:09 UTC by dcdarrell9

### What is the context of this PR?
- Added 2 simple unit tests in user.py and factory.py to increase coverage.

### How to review 
- Check all unit tests/lint work.
- Suggest improvements?

2017-04-11 13:50 UTC, collisdigital commented on tests/app/authentication/test_user.py
> +                User("", "")
Worth a test passing None as well? And below...

2017-04-11 14:02 UTC, dcdarrell9 commented on tests/app/authentication/test_user.py
> +                User("", "")
Added...
Just a question, with this `if user_id and user_ik:` is it possible to have one and not have the other, or do they both have to be there?

2017-04-11 17:22 UTC, collisdigital commented on tests/app/authentication/test_user.py
> +                User("", "")
Both should be mandatory

2017-04-12 10:16 UTC, jonnyshaw89 requested changes

2017-04-12 10:16 UTC, jonnyshaw89 commented on tests/app/utilities/test_factory.py
> +    def test_create_value_error(self):
I can't find anywhere that we actually use `Factory` within the code.
Maybe it should just be removed?

2017-04-12 10:24 UTC, dcdarrell9 commented on tests/app/utilities/test_factory.py
> +    def test_create_value_error(self):
I think you're right, I can't seem to find it being used, 'SubmitterFactory' is used but that's a different thing.

2017-04-12 12:40 UTC, jonnyshaw89 approved these changes

2017-04-12 14:02 UTC, merged