Stage one of moving app settings to app.config
ONSdigital/eq-survey-runner pull request #1093
Opened 2017-04-11 15:50 UTC by adoublebarrel

### What is the context of this PR?

https://trello.com/c/4kjDSdfM/1049-move-app-config-from-settings-py-to-flask-application-factory

Removed settings from new_relic and jwt_decoder, plus associated
changes for their dependents.

### How to review 
Functionality should be unchanged, imports of settings.py should be reduced, config should be being accessed via the Flask applications config dictionary.

2017-04-11 17:18 UTC, collisdigital commented on tests/app/authentication/test_jwe.py
> -        decoder = JWTDecryptor()
Nice clean up 👍

2017-04-11 17:18 UTC, collisdigital commented on tests/app/authentication/test_jwe.py
> +            'digitaleq',
Not sure why this was originally declared directly here; might make sense to move it into a 'TEST_DO_NOT_USE_SR_PRIVATE_PEM_PASSWORD'?

2017-04-11 17:18 UTC, collisdigital commented on tests/app/authentication/test_jwt.py
> +            'digitaleq',
Same as above

2017-04-11 17:18 UTC, collisdigital commented on tests/app/authentication/test_jwt_decoder.py
> +        self.SR_PRIVATE_KEY_PASSWORD = 'digitaleq'
And again

2017-04-11 17:18 UTC, collisdigital commented on tests/app/authentication/test_jwt_decoder_using_rfc_example.py
> +            'digitaleq',
Here

2017-04-12 10:12 UTC, jonnyshaw89 requested changes

2017-04-12 10:12 UTC, jonnyshaw89 commented on app/__init__.py
> +    application.config['MAX_CONTENT_LENGTH'] = application.config['EQ_MAX_HTTP_POST_CONTENT_LENGTH']
Would it make sent to make `EQ_MAX_HTTP_POST_CONTENT_LENGTH` `MAX_CONTENT_LENGTH` so that this doesn't need to be set?

2017-04-12 10:28 UTC, adoublebarrel commented on app/__init__.py
> +    application.config['MAX_CONTENT_LENGTH'] = application.config['EQ_MAX_HTTP_POST_CONTENT_LENGTH']
That occurred to me too, as it's seconded I'll make the change now

2017-04-12 12:40 UTC, jonnyshaw89 approved these changes

2017-04-12 13:14 UTC, merged

2017-04-12 13:15 UTC, jonnyshaw89 commented
@adoublebarrel FYI we normally need 2 approvals to merge.

2017-04-12 15:09 UTC, collisdigital commented
@adoublebarrel also usually not the author who clicks the merge button but admitted by convention rather than standard; we should update the Dev workflow to explain or agree it isn't important?

2017-04-12 15:24 UTC, adoublebarrel commented
The merge button protocol is mentioned in the workflow, this was generally my bad. I was keen to get working on the next set of changes, saw green and didn't properly reference the Dev workflow doc.