WIP Summary Screen Changes
ONSdigital/eq-survey-runner pull request #1094
Opened 2017-04-12 14:00 UTC by hamishtaplin

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2017-04-13 15:06 UTC, samiwel commented
@hamishtaplin Over to you 👍

2017-04-18 08:47 UTC, ajmaddaford requested changes

2017-04-18 08:47 UTC, ajmaddaford commented on app/templating/summary_context.py
> +        if 'title' in group and group['title'] not in ('Introduction', 'Summary') \
We don't want to be using the title to determine behaviour here. Is this being done so that we don't add groups that don't contain any answers?

2017-04-18 08:47 UTC, ajmaddaford commented on app/data/test_language.json
> +}
It looks like some of the schemas have been reformatted, making it hard to see what the required changes are for this pull request. Please can any that have just been reformatted be reverted.

2017-04-18 14:25 UTC, samiwel commented on app/templating/summary_context.py
> +        if 'title' in group and group['title'] not in ('Introduction', 'Summary') \
There is no type to latch onto for the group. So any change here would require either looking at a block within the group (which could be problematic if there are multiple blocks in the group) or introducing some other property to identify that it should not be displayed in the summary (which may make more sense). Feel free to change this if it makes sense, I am not in for 3 weeks and won't get an opportunity to work on this, sorry.

2017-04-18 14:25 UTC, samiwel commented on app/data/test_language.json
> +}
I think they were all highlighted during a yarn lint, which was breaking my build locally. I think I made a separate commit for the JSON formatting, so feel free to revert that.

2017-04-20 10:57 UTC, bennpearson approved these changes
Frontend LGTM 👍  My changes need reviewing by @armstrongb

2017-04-24 10:03 UTC, ajmaddaford commented on app/templating/summary_context.py
> +        if 'title' in group and group['title'] not in ('Introduction', 'Summary') \
I've changed this so it checks if there are any `Questionnaire` blocks in a group.

2017-04-24 10:03 UTC, ajmaddaford commented on app/data/test_language.json
> +}
Fair enough 👍

2017-04-24 15:16 UTC, yoganandkunche commented
@bennpearson #965 still fails of a checkbox other fields.

2017-04-25 13:26 UTC, ajmaddaford approved these changes

2017-04-25 13:27 UTC, merged