Stage 2 of using Flask config for settings
ONSdigital/eq-survey-runner pull request #1096
Opened 2017-04-18 10:09 UTC by adoublebarrel

### What is the context of this PR?
[Trello Card] (https://trello.com/c/4kjDSdfM/1049-move-app-config-from-settings-py-to-flask-application-factory)

Apologies for some of the white space edits, the latest version of
flake8 is more fussy than its previous incarnations.

Reworked the submitter so that it only sends messages rather than
encrypting and sending them. The encryption step has been moved up
into the questionnaire blueprint.

While making the changes I started having trouble with the way the
submitter was being mocked out. I've introduced a helper which makes
the submitter available as a global. That global can then be reliably
overridden on a per-test basis, see test_downstream_data_typing.

### How to review 

All existing behaviour should be intact. Other than that special consideration should be given to:

- The changes to the design of the questionnaire view/blueprint + submitter 
- How the submitter is now being mocked out should also have a critical eye cast over it

2017-04-18 10:21 UTC, jonnyshaw89 commented on app/views/flush.py
> +        message = encrypter.encrypt(message)
Will this always encrypt the message?

2017-04-18 10:22 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> +        message = encrypter.encrypt(message)
Will this always encrypt the message?

2017-04-18 10:24 UTC, jonnyshaw89 commented
Have you not committed `app.helpers.submitter_helper`?

2017-04-18 13:00 UTC, adoublebarrel commented on app/views/questionnaire.py
> +        message = encrypter.encrypt(message)
Yes, I've updated the tests to decrypt the message when they need to.

I take your point though, is this something we want to switch off in some circumstances?

2017-04-18 13:06 UTC, adoublebarrel commented
🤦‍♂️Yes I have. I'll update it as soon as I'm back.

2017-04-18 13:06 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> +        message = encrypter.encrypt(message)
IIRC in dev mode it wouldn't encrypt the message to it was logged out so we could read it.

2017-04-18 13:06 UTC, adoublebarrel commented
*have forgotten to commit the helper

2017-04-20 13:33 UTC, ajmaddaford requested changes

2017-04-20 13:33 UTC, ajmaddaford commented on app/cryptography/jwt_encoder.py
>              raise Exception("EQ_USER_AUTHENTICATION_SR_PUBLIC_KEY is None (check EQ_DEV_MODE?)")
It looks like these three values no longer come from the settings so the exception text doesn't make sense now. It would be better to use something like `private_key missing`, `private_key_password missing` and `public_key missing`

2017-04-20 13:33 UTC, ajmaddaford commented on app/helpers/submitter_helper.py
> +    return g._submitter  # pylint: disable=protected-access
Making the submitter global so we can override it in the tests doesn't seem right. After a conversation with @adoublebarrel we're going to move the initialisation of the submitter to application startup. This suits how it is used (the type of submitter is never changed once the app is running) and also means each time we submit we don't need to supply the config.

2017-04-20 13:33 UTC, ajmaddaford commented on app/submitter/encrypter.py
>      # pylint: disable=maybe-no-member
I don't think this is needed now we no longer default the values from settings

2017-04-20 13:33 UTC, ajmaddaford commented on app/submitter/encrypter.py
> +    def __init__(self, private_key, private_key_password, public_key):
We should check that these parameters are provided in a similar way to the `Encoder` initialisation.

2017-04-20 16:06 UTC, adoublebarrel commented on app/cryptography/jwt_encoder.py
>              raise Exception("EQ_USER_AUTHENTICATION_SR_PUBLIC_KEY is None (check EQ_DEV_MODE?)")
Is there value in adding some stronger validation here as well? We could push the validation into encrypter and then this init method could be removed altogether from here

2017-04-26 13:45 UTC, ajmaddaford approved these changes

2017-04-27 08:55 UTC, jonnyshaw89 approved these changes

2017-05-02 12:44 UTC, merged