Added print tracking to GA
ONSdigital/eq-survey-runner pull request #1100
Opened 2017-04-20 13:55 UTC by dcdarrell9

### What is the context of this PR?
- Added the ability to track when a user opens up a print option (file > print || cmd + p) through Google Analytics

### How to review 
- Try a print option in a survey on dev_mode and check that it comes through on Google Analytics
- Suggest better place for code? (maybe in analytics.js?)

2017-04-21 10:53 UTC, bennpearson reviewed
This will be wrapped within {% if analytics_ua_id  %} {% endif %} tags. These have been implemented in #1087 so this will need merging. Maybe best option would be to put this inside app/assets/js/app/modules/analytics.js Lets check with @hamishtaplin

2017-04-24 08:52 UTC, hamishtaplin requested changes
I agree with Benn, this should be moved into the existing analytics code. There's a `trackEvent` function in there that should be used instead of the `ga` one. Could probably lose the `try/catch` then too as I think that just guards against errors when `ga` isn't available.

2017-04-24 12:39 UTC, dcdarrell9 commented
@hamishtaplin tried with dev_mode on Safari and Chrome and works, not sure about testing on other browsers.

2017-05-02 15:41 UTC, collisdigital commented
@hamishtaplin where are we at with this one?

2017-05-03 07:30 UTC, hamishtaplin approved these changes

2017-05-03 09:39 UTC, merged