Move development default settings from survey runner code to run app
ONSdigital/eq-survey-runner pull request #1111
Opened 2017-05-02 08:43 UTC by jonnyshaw89

### What is the context of this PR?
Removed all settings that default to developer values

### How to review 
Check that all default values in settings.py are not developer values.
Check that developer experience has not changed

2017-05-02 15:14 UTC, collisdigital requested changes

2017-05-02 15:14 UTC, collisdigital commented on app/settings.py
>  EQ_SERVER_SIDE_STORAGE_DATABASE_SETUP_RETRY_COUNT = os.getenv('EQ_SERVER_SIDE_STORAGE_DATABASE_CONNECT_RETRY_COUNT', 10)
any value in adding a `get_env_or_default()` to make these consistent now (i.e. that a decision has been made to either default or fail)?

2017-05-02 15:14 UTC, collisdigital commented on scripts/run_tests_unit.sh
> +if [ -z "$EQ_SERVER_SIDE_STORAGE_USER_IK_SALT" ]; then
Can this duplication with run_app.sh be removed (e.g. do a `source dev_vars.sh` or something?

2017-05-03 08:31 UTC, jonnyshaw89 commented on app/settings.py
>  EQ_SERVER_SIDE_STORAGE_DATABASE_SETUP_RETRY_COUNT = os.getenv('EQ_SERVER_SIDE_STORAGE_DATABASE_CONNECT_RETRY_COUNT', 10)
I don't think it would add a lot of value. its basically going to wrap the existing call and add nothing.

2017-05-03 09:47 UTC, collisdigital commented on app/settings.py
>  EQ_SERVER_SIDE_STORAGE_DATABASE_SETUP_RETRY_COUNT = os.getenv('EQ_SERVER_SIDE_STORAGE_DATABASE_CONNECT_RETRY_COUNT', 10)
Fair enough

2017-05-03 09:47 UTC, collisdigital approved these changes

2017-05-03 11:01 UTC, ajmaddaford requested changes

2017-05-03 11:01 UTC, ajmaddaford commented on tests/app/test_settings.py
> +            settings.get_env_or_fail("InvalidKey")
Minor point, but it would be clearer if this was something like `MISSING_ENVIRONMENT_VARIABLE` rather than `InvalidKey`.

2017-05-03 11:22 UTC, jonnyshaw89 commented on tests/app/test_settings.py
> +            settings.get_env_or_fail("InvalidKey")
Done

2017-05-03 13:01 UTC, ajmaddaford approved these changes

2017-05-03 13:28 UTC, merged