Fix developer page key overriding
ONSdigital/eq-survey-runner pull request #1116
Opened 2017-05-03 13:37 UTC by ajmaddaford

### What is the context of this PR?
Allows overriding of developer page keys and password. 
Fixes https://github.com/ONSdigital/eq-survey-runner/issues/1115

### How to review 
* Move `sdc-user-authentication-signing-rrm-private-key.pem` to a new location e.g. `mv ./jwt-test-keys/sdc-user-authentication-signing-rrm-private-key.pem ./jwt-test-keys/sdc-user-authentication-signing-rrm-private-key2.pem`
* Logs should contain `Did not load file because filename supplied was None or not a file` 
* Try to start a survey, you should get a 500 error
* Export the environment variable EQ_USER_AUTHENTICATION_RRM_PRIVATE_KEY to point to the new location e.g. `export EQ_USER_AUTHENTICATION_RRM_PRIVATE_KEY=./jwt-test-keys/sdc-user-authentication-signing-rrm-private-key2.pem`
* Logs should **not** contain `Did not load file because filename supplied was None or not a file` 
* You should be able to start a survey
* Try similar changes to `EQ_USER_AUTHENTICATION_RRM_PRIVATE_KEY_PASSWORD` and `EQ_USER_AUTHENTICATION_SR_PUBLIC_KEY`

2017-05-03 14:03 UTC, jonnyshaw89 approved these changes

2017-05-03 14:07 UTC, collisdigital commented
Kind of feel like the app should die on startup if this is missing, with this implementation it gets all the way into the encryption and blows up with `TypeError: object of type 'NoneType' has no len()` which isn't very safe/clean?

2017-05-03 14:07 UTC, collisdigital requested changes
Let's talk about the startup behaviour when the file is missing

2017-05-03 14:09 UTC, jonnyshaw89 commented
I think i probably agree with @collisdigital on this one. if the app starts Beanstalk will treat it as a successful deployment. If it fails to start then it won't break all the servers.

2017-05-03 14:11 UTC, dcdarrell9 approved these changes

2017-05-04 09:46 UTC, ajmaddaford commented
I agree we should not start the application if required keys or passwords are missing from the environment (or empty). I made the changes locally to do this, but this would also mean that in production the app wouldn't start as the developer page keys wouldn't be set. I think we should get this pull request merged as is, so that we can resume continual deployments to pre-prod, and create another card for separating out the developer page specific settings. We should also remove the default paths and passwords from the app.

2017-05-04 09:47 UTC, collisdigital approved these changes

2017-05-04 09:47 UTC, collisdigital commented
Approved

2017-05-04 09:47 UTC, merged