Show/Hide guidance
ONSdigital/eq-survey-runner pull request #1127
Opened 2017-05-09 14:50 UTC by dcdarrell9

### What is the context of this PR?
- Having the ability to customise Show/Hide further guidance to match the questions.
- Changed the html templates to be able to use the repeating answer, relationship, question_guidance(hacky) & answer_guidance.
- Census_household & 1_0112 have been changed to work with the new style.
- Tests fail as only part completed.

### How to review 
- Test Census_household & 1_0112 to see if 'custom' show/hide is available.
- The other surveys in theory shouldn't show the further guidance.
- Discussion on : 
Schema structure.
Naming.
Next steps.

2017-05-09 14:51 UTC, dcdarrell9 commented on app/templates/partials/questions/relationship.html
> +    }
'hacky' part

2017-05-10 09:31 UTC, yoganandkunche commented on data/en/census_household.json
> +                                    },
Content displayed incorrectly. (PFA)
<img width="706" alt="screen shot 2017-05-10 at 10 14 26" src="https://cloud.githubusercontent.com/assets/21335236/25891695/e32f7d88-3569-11e7-9007-bdaefac7be9d.png">

2017-05-10 09:31 UTC, yoganandkunche commented on data/en/census_household.json
> +                                },
Content displayed incorrectly. (PFA)
<img width="753" alt="screen shot 2017-05-10 at 10 18 52" src="https://cloud.githubusercontent.com/assets/21335236/25891762/1e94f2fe-356a-11e7-8fef-d077835f9dde.png">

2017-05-10 09:32 UTC, yoganandkunche requested changes
Made few comments and also need to add the 'schema_item' to 'household-relationships' block.. line 346 in census_communal.json

2017-05-10 10:08 UTC, dcdarrell9 commented on data/en/census_household.json
> +                                    },
So this was all on the one line with html inline and as it stands this is the only one with this structure, it looks like the better way to have it, but this is where the high level review would come in.

2017-05-10 10:08 UTC, dcdarrell9 commented on data/en/census_household.json
> +                                },
Fixed.

2017-05-10 12:15 UTC, hamishtaplin approved these changes
LGTM 👍

2017-05-12 12:15 UTC, dcdarrell9 commented
@yoganandkunche I haven't added anything to census_communal, so I don't think it should work on that, I've fixed those issues now hopefully.

2017-05-15 10:19 UTC, yoganandkunche approved these changes
Cenus_household & 0112 survey look good. 

###Note: The show and hide guidance links on all other surveys are broken. Also unit test need fixing before merging)

2017-05-15 10:52 UTC, closed without merging