WIP - Refactor settings in errors and user_id_generator (Part 4)
ONSdigital/eq-survey-runner pull request #1131
Opened 2017-05-15 11:57 UTC by samiwel

### What is the context of this PR?
This PR is a continuation of the work to refactor survey runner to use settings from Flask rather than referencing the settings module directly.
In particular, this PR is concerned with refactoring the following modules:
- `errors.py`
- `user_id_generator.py`

### How to review 
All existing automated tests should continue to run and pass. External behaviour should remain unchanged.

2017-05-16 08:46 UTC, adoublebarrel approved these changes
Looks good to me.

2017-05-16 13:12 UTC, collisdigital requested changes

2017-05-16 13:12 UTC, collisdigital commented on app/authentication/user_id_generator.py
> +        self.iterations = iterations
make this a private var?

2017-05-16 13:12 UTC, collisdigital commented on app/authentication/user_id_generator.py
>          collection_exercise_sid, eq_id, form_type, ru_ref = UserIDGenerator._get_token_data(metadata)
Worth adding a None check for metadata and salt and throwing `ValueError` (plus unit test) as this is critical stuff

2017-05-16 13:12 UTC, collisdigital commented on app/authentication/user_id_generator.py
> +    def generate_ik(self, token, salt):
Check inputs as above

2017-05-16 14:51 UTC, samiwel commented on app/authentication/user_id_generator.py
> +    def generate_ik(self, token, salt):
Inputs are now checked in my latest commit.

2017-05-17 08:13 UTC, jonnyshaw89 requested changes

2017-05-17 08:13 UTC, jonnyshaw89 commented on app/authentication/authenticator.py
> +    id_generator = UserIDGenerator(current_app.config['EQ_SERVER_SIDE_STORAGE_USER_ID_ITERATIONS'])
I think we should pass in `EQ_SERVER_SIDE_STORAGE_USER_ID_SALT` and `EQ_SERVER_SIDE_STORAGE_USER_IK_SALT` into the constructor as they never change during runtime

2017-05-17 08:13 UTC, jonnyshaw89 commented on app/views/flush.py
> +    id_generator = UserIDGenerator(current_app.config['EQ_SERVER_SIDE_STORAGE_USER_ID_ITERATIONS'])
As we are constructing this twice with the same arguments i think we should construct it once on application startup.

2017-05-17 14:06 UTC, jonnyshaw89 approved these changes

2017-05-17 14:07 UTC, jonnyshaw89 commented
@collisdigital your blocking this one now.

2017-05-18 09:27 UTC, collisdigital approved these changes
Please start a session on master, switch to this branch and check the data is restored correctly.

2017-05-18 09:36 UTC, samiwel commented
@collisdigital Chris, just checked this and can confirm session data was restored correctly. I'll squash the commits down now

2017-05-18 09:37 UTC, collisdigital commented
👍

2017-05-18 10:06 UTC, merged