Update MCI Survey (0215) with latest patterns
ONSdigital/eq-survey-runner pull request #1138
Opened 2017-05-19 10:27 UTC by dwyeradam

### What is the context of this PR?
For the respondent to have a more up to date pattern and functionality on the MCI survey (0215).

### How to review 
From the trello card https://trello.com/c/y4lXGGQi/1052-mci-refresh
Spec: https://docs.google.com/presentation/d/1VYmB1jJsxbJFRFvuOUh1zUZB_Rk2eIbjfX1d5hhF6u8/edit#slide=id.g1ba6eee5f3_0_82

On the refreshed MCI you will see:

Comments question broken into 3 questions as per the spec
Piping (trad_as or Ru, dates, values)
Highlighting (to be confirmed with DCM if any required)
Single question per page (except for totals with breakdowns)
Include 'Round to the nearest pound. Do not include pence.' This goes immediately above entry field
It will match the finalised, agreed specification
MCI will not use navigation
Summary screen will not be negatively impacted

2017-05-19 10:30 UTC, collisdigital requested changes
Please note we can't actually merge this until the next MCI period (end of June); unless we put this in under a different schema name `mci_refresh.json`? And rename it as a separate PR before it goes live?

2017-05-19 10:48 UTC, collisdigital commented
![image](https://cloud.githubusercontent.com/assets/14041600/26244726/efdb073e-3c88-11e7-8672-623020a563d1.png)

The value piped "2343453453" in the screenshot, should be highlighted (in green) and formatted as currency e.g. £2,343,453,453.00

2017-05-19 10:50 UTC, collisdigital commented on data/en/1_0215.json
> +                            "description": "<p>Round to the nearest (\u00a3) pound. Do not  include pence<p>",
do not put these answer descriptions in `<p>` tags otherwise we're getting strange spacing issues; applies for all below as well

2017-05-19 10:54 UTC, collisdigital commented
![image](https://cloud.githubusercontent.com/assets/14041600/26244931/ccbf9098-3c89-11e7-8abc-c7494a3177fd.png)

Add highlighting to the '7' here (i.e. total number of employees) I've updated the slides to match

2017-05-19 10:55 UTC, collisdigital commented
![image](https://cloud.githubusercontent.com/assets/14041600/26244971/f3b1de04-3c89-11e7-9434-027d4866ff4e.png)

We should discuss these screens, they don't have a question title so the `<head><title>` isn't showing the right text.

2017-05-22 11:34 UTC, yoganandkunche commented
the text '**working**' on employee questions are displayed in **bold** (not needed) according to the spec file and I also checked with Jenny.

<img width="580" alt="screen shot 2017-05-22 at 11 24 35" src="https://cloud.githubusercontent.com/assets/21335236/26306330/e07f0362-3eea-11e7-83cc-2025d9ee1141.png">

Also according to the spec file, most of the questions look like mandatory. I have raised it with 'Jenny' awaiting confirmation.

2017-05-22 12:24 UTC, armstrongb commented
![mci-refresh-22052017-clothing-sales](https://cloud.githubusercontent.com/assets/22910336/26308553/ad33e304-3ef1-11e7-9206-764358d5bbc7.png)

Specification lists handbags and umbrellas as a single list item but schema displays it as two.

2017-05-22 12:31 UTC, armstrongb commented
Guidance content is in two columns but should be one.

_Content review (to be agreed/discussed): re-prioritisation of include/exclude item order. NHS receipts top of include and bottom of exclude_

![mci-refresh-22052017-other-sales](https://cloud.githubusercontent.com/assets/22910336/26308823/9fe8c8da-3ef2-11e7-8f6f-6aa7bd318e71.png)

2017-05-22 12:33 UTC, armstrongb commented
### Other goods

Last item in include list 'Mobile phones' 
Uses sentence case when specification is all lower case

![mci-refresh-22052017-other-sales-mobilephones](https://cloud.githubusercontent.com/assets/22910336/26308911/0b14a43a-3ef3-11e7-96cd-834fdff3dddf.png)

2017-05-22 13:00 UTC, armstrongb commented
### Section titles

Section titles should be added as the summary screen is simply a list of inputs without them.

[RSI-Testing-22052017-summary-output.pdf](https://github.com/ONSdigital/eq-survey-runner/files/1018864/RSI-Testing-22052017-summary-output.pdf)

2017-05-22 13:04 UTC, armstrongb requested changes
See comments for details.

2017-05-22 15:31 UTC, yoganandkunche commented
@dwyeradam got confirmation on the mandatory questions. The below question on MCI refresh must be mandatory:

Q: Changes in total retail turnover Please indicate the reasons for any changes in the total retail turnover for {{trad_as_or_ru_name}} (**Checkboxes**) & Q: Please describe the changes in total retail turnover for Apple in more detail (**Comments**)

2017-05-22 16:05 UTC, yoganandkunche commented
@dwyeradam Please find below are the error messages for mandatory Checkboxes and Mandatory Comments fields.
Mandatory Checkbox:  **Please select all that apply to continue.**
Mandatory Comments field: **Please enter a comment to continue.**
<img width="440" alt="screen shot 2017-05-22 at 17 04 26" src="https://cloud.githubusercontent.com/assets/21335236/26317846/c1cae17c-3f10-11e7-8acf-5cc42a116636.png">
<img width="644" alt="screen shot 2017-05-22 at 17 04 09" src="https://cloud.githubusercontent.com/assets/21335236/26317858/cda8f6a0-3f10-11e7-882b-b9e3c2c4376c.png">

2017-05-22 16:40 UTC, yoganandkunche commented
Also, for the radio button question, the validation message is: **Please select an answer to continue.**

2017-05-23 13:24 UTC, yoganandkunche commented
LGTM :+1: apart from the missing Section titles on the summary page which will be dealt as a separate task

2017-05-23 16:12 UTC, dwyeradam commented
I have found a work around to allow for grouping of questions in the new MCI Refresh. These will now appear on the Summary page. Previously this was not possible as routing can not be done between groups. Therefore when selecting No to Significant Change in the Retail Turnover you would be unable to route to the Employees group. Instead I have used skips on the two Reason for change pages instead.

2017-05-24 13:49 UTC, armstrongb approved these changes

2017-05-24 13:50 UTC, armstrongb commented
@collisdigital the summary page changes LGTM but I can't comment on the logic implementation to enable it.

2017-06-07 13:42 UTC, yoganandkunche commented
@dwyeradam missing <previous> link on the 2nd question:   Retail Turnover, Changes in total retail turnover question with Yes/No options & the next question when 'No' is selected.

2017-06-07 13:49 UTC, yoganandkunche requested changes
@dwyeradam missing <previous> link on the 2nd question: Retail Turnover, Changes in total retail turnover question with Yes/No options & the next question when 'No' is selected.

2017-06-08 10:54 UTC, yoganandkunche approved these changes

2017-06-08 12:12 UTC, jonnyshaw89 commented
@dwyeradam is mci_refresh.json the correct name for this?

2017-06-08 13:32 UTC, dwyeradam commented
@jonnyshaw89  the name mci_refresh was chosen so that we can have both versions available until the refreshed version can go live. 

> See Chris' first comment to pull request
Please note we can't actually merge this until the next MCI period (end of June); unless we put this in under a different schema name mci_refresh.json? And rename it as a separate PR before it goes live?

2017-06-08 13:54 UTC, jonnyshaw89 commented
@dwyeradam you will need to address the failing functional test. if you rebase your branch it will should become clearer as to why its failing ;)

2017-06-08 14:53 UTC, collisdigital approved these changes

2017-06-12 08:11 UTC, jonnyshaw89 requested changes

2017-06-12 08:11 UTC, jonnyshaw89 commented on tests/functional/spec/mci-refresh.spec.js
> -    devPage.open()
Instead of removing this test you could call `openQuestionnaire('mci_refresh.json')`?

2017-06-12 08:40 UTC, jonnyshaw89 approved these changes

2017-06-12 10:11 UTC, jonnyshaw89 commented
@dwyeradam can you squash and rebase this branch?

2017-06-12 14:09 UTC, merged