Show/Hide further guidance
ONSdigital/eq-survey-runner pull request #1139
Opened 2017-05-19 13:58 UTC by dcdarrell9

### What is the context of this PR?
- Having the ability to customise Show/Hide further guidance to match the questions.
- Changed the html templates to be able to use the 'repeating answer', 'relationship', 'question_guidance' & 'answer_guidance', added new template called 'guidance'.
- All schemas have been changed to work with the new style.
- Not all schemas have full custom guidance text (need input for that)

### How to review 
- Test schemas to see if 'custom' show/hide is available. (census_household has the most custom).
- Naming suggestions.
- Check if there's anything missed.
- Check tests pass.

2017-05-19 14:02 UTC, collisdigital reviewed
Good work!

2017-05-19 14:02 UTC, collisdigital commented on app/templates/partials/guidance.html
> +    <h3 class="venus">{{item.title}}</h3>
Need confirmation that these should be h tags at these levels, has @hamishtaplin or @bennpearson been involved?

2017-05-19 14:02 UTC, collisdigital commented on app/templates/partials/guidance.html
> +    <h2 class="mars">{{item.description|safe}}</h2>
Check with @adoublebarrel about the use of `|safe` now, and below

2017-05-19 14:02 UTC, collisdigital commented on data/schema/schema_v1.json
> +                                                                        "type": "object",
Not sure but formatting looks off here (spaces?)

2017-05-19 14:05 UTC, dcdarrell9 commented on app/templates/partials/guidance.html
> +    <h3 class="venus">{{item.title}}</h3>
I spoke to Hamish about it and the only thing he said was about the mci and having div tags to separate into columns, but maybe worth asking again.

2017-05-19 14:07 UTC, dcdarrell9 commented on data/schema/schema_v1.json
> +                                                                        "type": "object",
I think it's just Git, and how far it's nested.

2017-05-22 16:33 UTC, ajmaddaford requested changes

2017-05-22 16:33 UTC, ajmaddaford commented on app/templates/partials/questions/relationship.html
> +            'hide_guidance': "Hide relationship guidance"
Could we have the text for `show_guidance` and  `hide_guidance` in the schema and reference them here?
```
'show_guidance': schema_item.guidance.show_guidance,
'hide_guidance': schema_item.guidance.hide_guidance
```

2017-05-22 16:33 UTC, ajmaddaford commented on app/templates/partials/questions/repeatinganswer.html
> +            'hide_guidance': "Hide naming guidance"
Same comment as the relationship question above, could we have the text in the schema?

2017-05-22 16:33 UTC, ajmaddaford commented on data/en/1_0102.json
> +                                "hide_guidance": "hide further guidance",
All occurrences of `show_guidance` and `hide_guidance` should be sentence cased e.g. "Show further guidance"

2017-05-22 16:33 UTC, ajmaddaford commented on data/schema/schema_v1.json
> +        },
The schema needs some work to make the guidance content a common element, I've created a gist to demonstrate what this looks like - https://gist.github.com/ajmaddaford/6130dd89bd5939a02b3e7cb1053481d7. We can have a look together tomorrow and discuss.

2017-05-24 12:28 UTC, ajmaddaford commented on app/templates/partials/guidance.html
> +    <h2 class="mars">{{item.description|safe}}</h2>
https://github.com/ONSdigital/eq-survey-runner/pull/1133 hasn't merged yet so this is still required

2017-05-25 08:52 UTC, ajmaddaford requested changes

2017-05-25 08:52 UTC, ajmaddaford commented on data/en/census_household.json
> +                                        "title": "This could be:"
This title should be moved into the same object as the list it's associated with:
```
{
    "title": "This could be:",
    "list": [ 
        ...
    ]
}
```
This applies to all other places where the title/description/list is related.

2017-05-31 14:10 UTC, dcdarrell9 commented
@adoublebarrel I think I've sorted all the conflicts with "|safe", do you want to have a check to see if everything looks fine?

2017-06-05 10:11 UTC, ajmaddaford approved these changes

2017-06-05 15:55 UTC, jonnyshaw89 approved these changes

2017-06-06 09:26 UTC, hamishtaplin requested changes
Few minor things to look at.

2017-06-06 09:26 UTC, hamishtaplin commented on app/templates/partials/guidance.html
> +    <h3 class="venus">{{item.title}}</h3>
Probably best if they're not `h3` as you can't rely on there being a `h2` above this. This was raised by DAC so a good time to fix it.

2017-06-06 09:26 UTC, hamishtaplin commented on app/templates/partials/guidance.html
> +    <h2 class="mars">{{item.description}}</h2>
This isn't a heading so `h2` isn't semantically correct. Looking at the schema, there's `p` tags in there so a `div` is the best choice here.

2017-06-07 14:36 UTC, hamishtaplin approved these changes

2017-06-12 15:51 UTC, merged