Generate JWT token in function tests
ONSdigital/eq-survey-runner pull request #1144
Opened 2017-05-25 10:16 UTC by jonnyshaw89

### What is the context of this PR?
Have removed the need for the functional tests to use the DevPage by implementing a function to generate a valid JWT within the tests.

### How to review 
Turn off `EQ_DEV_MODE` and check that the function tests still work.

2017-05-25 10:23 UTC, collisdigital commented on tests/functional/jwt_helper.js
> +const signingKey = '/Users/jonshaw/code/eq-survey-runner/tests/functional/sdc-user-authentication-signing-rrm-private-key.pem';
hmmmm jonshaw

2017-05-25 10:26 UTC, collisdigital commented on tests/functional/jwt_helper.js
> +    let form_type = schema.substr(schema.indexOf('_')+1).split('.', 1)[0]
use a regex here, this is too fragile, look at the 'go' version for a regex to steal

2017-05-30 15:27 UTC, adoublebarrel requested changes

2017-05-30 15:27 UTC, adoublebarrel commented on tests/functional/helpers.js
> +      browser.url('http://localhost:5000/session?token=' + token)
Can we get a return here so I can compose this promise with my work in https://trello.com/c/7H5ReU7v/1095-refactor-functional-test-page-objects?

2017-05-30 15:27 UTC, adoublebarrel commented on tests/functional/helpers.js
> +      browser.url('http://localhost:5000/session?token=' + token)
Return here too please

2017-05-30 15:30 UTC, adoublebarrel commented on tests/functional/helpers.js
> +  browser.pause(1000) // Shudder!!!
This will go away as part of my work on https://trello.com/c/7H5ReU7v/1095-refactor-functional-test-page-objects

2017-05-30 15:30 UTC, adoublebarrel commented on tests/functional/helpers.js
> +  browser.pause(1000) // Shudder!!!
This'll go too (https://trello.com/c/7H5ReU7v/1095-refactor-functional-test-page-objects)

2017-05-30 15:39 UTC, jonnyshaw89 commented on tests/functional/helpers.js
> +      browser.url('http://localhost:5000/session?token=' + token)
Do you want anything in particular returned?

2017-05-30 15:39 UTC, jonnyshaw89 commented on tests/functional/helpers.js
> +      browser.url('http://localhost:5000/session?token=' + token)
same as above

2017-05-30 15:50 UTC, adoublebarrel commented on tests/functional/helpers.js
> +      browser.url('http://localhost:5000/session?token=' + token)
Just the promise from browser.url i.e. return browser.url(...)

2017-05-30 16:23 UTC, adoublebarrel approved these changes
LGTM

2017-06-01 10:40 UTC, dcdarrell9 approved these changes

2017-06-01 11:24 UTC, merged