Remove dev page from Survey Runner application
ONSdigital/eq-survey-runner pull request #1147
Opened 2017-05-31 10:44 UTC by jonnyshaw89

### What is the context of this PR?
This removed the dev page (/dev) from the survey runner application. This is a move to making the test environments behave more like the production environment where the token is generated on a remote system and passed across by the user.

### How to review 
Follow the README to run survey runner and check that everything behaves as expected.

2017-05-31 10:45 UTC, collisdigital commented on app/settings.py
>          f = open(file_name, "r")
use `with` instead of `open` and `close` ?

2017-06-01 12:32 UTC, dcdarrell9 commented
Can run and make any dev changes pretty easy, everything as expected, all seems to be good 👍

2017-06-12 16:27 UTC, ajmaddaford requested changes

2017-06-12 16:27 UTC, ajmaddaford commented on docker-compose.yml
> +    image: collisdigital/go-launch-a-survey
We should move this to the ONSDigital github before merging this.

2017-06-13 08:33 UTC, jonnyshaw89 commented on docker-compose.yml
> +    image: collisdigital/go-launch-a-survey
@collisdigital can you transfer ownership?

2017-07-03 14:47 UTC, adoublebarrel approved these changes

2017-07-03 16:10 UTC, yoganandkunche commented
LGTM :+1:

2017-07-03 16:20 UTC, ajmaddaford requested changes
Looks good, we can merge this once we get https://github.com/ONSdigital/go-launch-a-survey running with a valid certificate and redirecting to the correct URL in pre-prod

2017-07-03 16:20 UTC, ajmaddaford commented on README.md
> +To launch a survey, Navigate to `http://localhost:8000/`
Navigate -> navigate

2017-07-03 16:20 UTC, ajmaddaford commented on README.md
> +
I think it would be useful to provide the docker command here to run the latest launcher

2017-07-04 09:13 UTC, dcdarrell9 approved these changes

2017-07-04 11:18 UTC, ajmaddaford approved these changes

2017-07-04 13:04 UTC, merged