Change semantic structure of surveys
ONSdigital/eq-survey-runner pull request #1148
Opened 2017-06-01 09:55 UTC by dcdarrell9

### What is the context of this PR?
- Changed the structure of how the surveys display questions.
- Changed parts in the Json schemas and in the Html templates.
- Worth noting that stuff can be done in a different way, but might need splitting into new tasks. (such as the interstitial/questionnaire templates)

### How to review 
- Check tests work correctly.
- Suggest improvements.
- Check now matches designs on Trello card - https://trello.com/c/R97kNZ4g

2017-06-05 09:29 UTC, jonnyshaw89 approved these changes
Im happy that this meets the acceptance criteria. But would probably be good for @hamishtaplin to have a look over the templates.

2017-06-05 10:55 UTC, armstrongb approved these changes
Census schema looks to be correct.
UKIS schema looks to be correct.
QBS schema looks to be correct.

2017-06-06 09:16 UTC, hamishtaplin requested changes
Need to ensure that every page has a visible `h1` tag. The existing `h1` has been demoted so the `h2` should now be `h1` and subsequent headings bumped up so that the logical heading structure is maintained.

Also, the interstitial page contains a lot of duplicate code from `questionnaire` template that can be shared across those templates.

2017-06-06 09:16 UTC, hamishtaplin commented on app/templates/partials/question.html
> +    <h2 class="question__title saturn">
This should be `h1`

2017-06-06 09:16 UTC, hamishtaplin commented on app/templates/partials/questions/relationship.html
> +  <h2 class="question__title saturn">
`h1`

2017-06-06 09:16 UTC, hamishtaplin commented on app/templates/partials/questions/repeatinganswer.html
> +  <h2 class="question__title saturn">
`h1`

2017-06-06 09:16 UTC, hamishtaplin commented on app/templates/interstitial.html
> +{% extends theme('layouts/_twocol.html') %}
This template contains pretty much the same stuff as the questionnaire template. It should extend and override that template where possible rather than duplicating code. Consider using `block` and `includes` to share code between the templates.

2017-06-06 09:16 UTC, hamishtaplin commented on app/templates/interstitial.html
> +          <h1 class="block__title saturn">Section {{block['section_number']}}: {{block['title']}}</h1>
`block__title` doesn't have any CSS so can be removed.

2017-06-06 09:16 UTC, hamishtaplin commented on tests/functional/pages/confirmation.page.js
> +    return browser.element('p[class="section__title neptune"]').getText()
Don't use styling hooks in tests (`section__title neptune`) as changing the styling will break the test.

Instead, add specific hooks for selecting elements for test using `data-qa` attributes or unique ids.

2017-06-06 09:16 UTC, hamishtaplin commented on tests/functional/pages/surveys/question.page.js
> +    return browser.getText('p[class="section__title neptune"]')
Another styling hook—although this issue was already in the code it's a good time to sort it out.

2017-06-06 09:16 UTC, hamishtaplin commented on tests/functional/pages/surveys/repeating_household/repeating-household.page.js
> +    return browser.getText('p[class="section__title neptune"]')
As before

2017-06-06 09:18 UTC, hamishtaplin commented on app/templates/interstitial.html
> +    {% if form and (form.errors or form.question_errors) %}
Not sure the interstitial pages can contain errors.

2017-06-06 09:23 UTC, dcdarrell9 commented on app/templates/interstitial.html
> +{% extends theme('layouts/_twocol.html') %}
@ajmaddaford and I tried doing it this way and using a block, similar to the submit button block, but for some reason it wouldn't work?

2017-06-06 09:44 UTC, dcdarrell9 commented on tests/functional/pages/confirmation.page.js
> +    return browser.element('p[class="section__title neptune"]').getText()
👍

2017-06-06 09:44 UTC, dcdarrell9 commented on app/templates/partials/question.html
> +    <h2 class="question__title saturn">
👍

2017-06-06 09:52 UTC, dcdarrell9 commented on app/templates/interstitial.html
> +    {% if form and (form.errors or form.question_errors) %}
If I can get extend and block to work then this can go.

2017-06-07 14:41 UTC, hamishtaplin requested changes
Just some comments around use of underscores in attributes.

2017-06-07 14:41 UTC, hamishtaplin commented on app/templates/partials/section.html
> +    <div class="section__description mars"data-qa="section_description">{{section['description']}}</div>
For the sake of consistency with code elsewhere, this should be `data-qa="section-description"`. Also, missing a space before the attribute.

2017-06-07 14:41 UTC, hamishtaplin commented on tests/functional/pages/confirmation.page.js
> +    return browser.element('[data-qa="section_title"]').getText()
Use hyphens in attributes.

2017-06-07 14:41 UTC, hamishtaplin commented on tests/functional/pages/surveys/question.page.js
> +    return browser.getText('[data-qa="section_title"]')
Use hyphens in attributes.

2017-06-07 14:41 UTC, hamishtaplin commented on tests/functional/pages/surveys/repeating_household/repeating-household.page.js
> +    return browser.getText('[data-qa="section_title"]')
Use hyphens in attributes.

2017-06-13 07:22 UTC, hamishtaplin approved these changes

2017-06-13 08:49 UTC, merged