Eq 1114 make question skip conditions consistent with groups
ONSdigital/eq-survey-runner pull request #1158
Opened 2017-06-16 13:22 UTC by dwyeradam

### What is the context of this PR?
Allow for Questions to be skipped with an array of possible (or) conditions in line with those used for Groups and Blocks.
Allow for the summary page to check if a question has been skipped by metadata values.

2017-06-19 15:30 UTC, ajmaddaford requested changes

2017-06-19 15:30 UTC, ajmaddaford commented on app/templating/summary/question.py
> +                        answer = answer_store.map().get(when_rule['id'])
We shouldn't use the map method to get an answer, we should be using the `filter` method on `answer_store` to return all matching answers.

2017-06-19 15:30 UTC, ajmaddaford commented on app/templating/summary/question.py
> +                            answer = answer.unescape()
`answer` isn't used

2017-06-19 15:30 UTC, ajmaddaford commented on app/templating/summary_context.py
> +            groups.extend([Group(group, answer_store, path, metadata, url_for)])
Changing this to use the answer_store rather than answers means answers aren't being escaped.

2017-06-19 15:31 UTC, ajmaddaford commented
I think it would be good to get together with @adoublebarrel tomorrow to review the changes to ensure we don't lose any of the escaping fixes he recently added.

2017-06-26 10:27 UTC, ajmaddaford approved these changes

2017-06-26 14:31 UTC, jonnyshaw89 submitted a review, later dismissed

2017-06-26 14:31 UTC, jonnyshaw89 commented on tests/functional/spec/skip-condition-question.spec.js
> +describe('Skip condition question', function() {
shouldn't we be making new tests under `functional_new`

2017-06-26 14:31 UTC, jonnyshaw89 commented on data/schema/schema_v1.json
>                                                          "skip_condition": {
Maybe this should be renamed to `skip_conditions`?

2017-06-26 14:32 UTC, jonnyshaw89 requested changes
See previous comments

2017-06-27 12:40 UTC, dcdarrell9 reviewed
Not sure if the tests should be under functional_new like Jon said, but everything else looks good.

2017-06-29 11:15 UTC, jonnyshaw89 approved these changes

2017-06-29 11:15 UTC, jonnyshaw89 commented
@dwyeradam squash?

2017-06-29 15:34 UTC, merged