Added Integration testing of naughty strings
ONSdigital/eq-survey-runner pull request #1173
Opened 2017-07-07 14:50 UTC by adoublebarrel

### What is the context of this PR?

[Trello Card](https://trello.com/c/y3bbPczC/1102-add-the-big-list-of-naughty-strings-to-our-user-input-tests-s)

Includes the addition of a schema with 507 text areas =:o This allows
all the naughty strings to be tested at once which is *much* faster
than doing 507 POSTs.

The strings are downloaded via curl into a temp directory as part of
the tests script and removed once the script finishes.

### How to review 
Run the tests and they should all pass.

2017-07-10 12:27 UTC, jonnyshaw89 commented on tests/integration/test_textarea.py
> +            answers[k] = NAUGHTY_STRINGS[i]
What happens if new strings get added? it won't be able to find the answer index e.g. 508?

2017-07-11 07:10 UTC, ajmaddaford requested changes

2017-07-11 07:10 UTC, ajmaddaford commented on scripts/run_tests_unit.sh
> +curl 'https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.json' --compressed --create-dirs -o "${temp_dir}"/blns.json
I don't think we should be curling the file down in the run tests script as this means you can't run the test independently of the script. It might be better to just include the file in the tests folder (this would also mean the issue Jon raised about additional strings wouldn't be a problem).

2017-07-12 09:39 UTC, adoublebarrel commented on tests/integration/test_textarea.py
> +            answers[k] = NAUGHTY_STRINGS[i]
Have added the list of naughty strings as a fixture, see Andrews comment below.

2017-07-12 09:47 UTC, adoublebarrel commented on scripts/run_tests_unit.sh
> +curl 'https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.json' --compressed --create-dirs -o "${temp_dir}"/blns.json
Ok, I've added a fixtures folder under the tests directory and added committed the json file. Seem sensible?

2017-07-12 09:56 UTC, jonnyshaw89 requested changes

2017-07-12 09:56 UTC, jonnyshaw89 commented on tests/integration/test_textarea.py
> +        self.assertEqual(200, self.last_response.status_code)
We are only testing that the summary page is rendered? not that any of these strings haven't broken our safe strings and are displaying "dodginess" on the summary page?

2017-07-12 10:04 UTC, adoublebarrel commented on tests/integration/test_textarea.py
> +        self.assertEqual(200, self.last_response.status_code)
Yes, this is a large grained test to make sure that the application doesn't fall over when handling "naughty" input. Finer grained tests, e.g. for XSS vectors, already exist. We should continue to review fine grained security test coverage as the platform evolves. For example, if we consider SQL injection to be a potential vector we should cover that in specific tests.

2017-07-12 10:06 UTC, jonnyshaw89 commented on tests/integration/test_textarea.py
> +        self.assertEqual(200, self.last_response.status_code)
Would it make the test really slow if we asserted that each of those strings is displayed as entered on the summary page?

2017-07-12 10:20 UTC, jonnyshaw89 commented on tests/integration/test_textarea.py
> +        self.assertEqual(200, self.last_response.status_code)
agreed with @adoublebarrel that this isn't the right test to verify the output

2017-07-12 11:15 UTC, jonnyshaw89 approved these changes

2017-07-12 17:39 UTC, ajmaddaford approved these changes

2017-07-13 09:51 UTC, merged