Added ADR to describe kid value in token headers
ONSdigital/eq-survey-runner pull request #1175
Opened 2017-07-11 10:00 UTC by jonnyshaw89

### What is the context of this PR?
Documented the decision to use the kid value in the header of the jwe and jwt tokens

2017-07-11 10:32 UTC, collisdigital approved these changes

2017-07-12 09:52 UTC, adoublebarrel requested changes

2017-07-12 09:52 UTC, adoublebarrel commented on doc/architecture/decisions/0004-use-kid-to-identify-key-pair.md
> +So during the crossover period the previous value of EDCRRM with be valid for the jwt header and a default key will be used if no kid is passed in the jwe header.
Typo pedantry; should "with" be "will"?

2017-07-12 18:13 UTC, ajmaddaford requested changes
All references to jwe and jwt should be JWE and JWT. Other than that it looks good.

2017-07-13 08:56 UTC, ajmaddaford approved these changes

2017-07-13 09:25 UTC, adoublebarrel approved these changes

2017-07-13 10:09 UTC, merged