Eq 1077 preview questions in introduction
ONSdigital/eq-survey-runner pull request #1181
Opened 2017-07-14 13:05 UTC by adoublebarrel

### What is the context of this PR?
[Trello Card](https://trello.com/c/0Pq1iOcn/1077-inform-respondents-what-questions-they-will-need-to-answer-m)

A request for comment on the first approach I've taken to displaying introductory content.

A "content" array has been added to the introduction block. Each object in the content array has a template property that gives the path to a partial template. The introduction template has been updated to use the template property to include the appropriate partial.

This allows all content to be processed in the same way in the introduction template with variations in display/content being handled by the included partials.

### How to review 

Comment and discuss. Bear in mind that the introduction template, styles etc. are very rough and ready. If we maybe iterate on this a few times and settle on something I could write an ADR...

2017-07-20 09:45 UTC, ajmaddaford commented on data/en/test_preview.json
> +                "type": "intro-preview",
We have a convention of using upper camel case for types (to distinguish them from ids), so we could have `Introduction`, `Basic` and `Definition`

2017-07-21 13:07 UTC, adoublebarrel commented on data/en/0_star_wars.json
> +                        "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
This has been moved out of the introduction template as it was part of the information to provide block, now appears in every schema that has an Introduction block with a  'information-to-provide' body object.

2017-07-25 11:47 UTC, ajmaddaford requested changes

2017-07-25 11:47 UTC, ajmaddaford commented on app/templates/introduction.html
> +      {% include 'partials/intro-preview.html' %}
I think it would be worth having a `partials/introducton` folder and highlight should be `partials/introduction/definition.html`

2017-07-25 11:47 UTC, ajmaddaford commented on data/en/2_0001.json
> +                        "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
Any reason not to use `<strong>` here?

2017-07-25 11:48 UTC, ajmaddaford commented
The content without the preview content looks odd - titles wrapping and empty area to the right of the introduction content.

![image](https://user-images.githubusercontent.com/1754822/28570750-7a2ed59a-7137-11e7-8446-7c59fc8dd848.png)

2017-07-25 13:07 UTC, adoublebarrel commented
One of the bits of feedback I had from Matthew was that content should sitting in the [grid](https://onsdigital.github.io/sdc-global-design-patterns/docs/grid.html). I'll confirm with him whether that applies without accordion/preview as well.

It'll be a bit horrible If the introduction using the grid is dependent on what it's displaying.

2017-07-25 13:24 UTC, adoublebarrel commented on data/en/2_0001.json
> +                        "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
You'll lose having that piece of text as a member of the the typography hierarchy; so changes to the hierarchy wont impact it.

The <p> adds some extra whitespace but if you mean doing <p><strong>If actual...</strong></p> then there'd be no visible difference.

2017-07-28 14:16 UTC, hamishtaplin requested changes

2017-07-28 14:16 UTC, hamishtaplin commented on app/templates/partials/introduction/preview.html
> +            <button class="accordion__control js-accordion-open-all u-hidden" data-ga="click" data-ga-category="Preview Survey" data-ga-action="Show all" tabindex="0" aria-hidden="true">Show all</but
Styling buttons as links has some accessibility issues as users of Dragon (for example) will see what looks like a link but the software will announce a button. Not a huge blocker but worth discussing with Matt?

2017-07-28 14:16 UTC, hamishtaplin commented on data/en/0_star_wars.json
> +                        "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
We shouldn't be putting classes in the schema, a `strong` tag would be semantically more appropriate too.

2017-07-28 14:16 UTC, hamishtaplin commented on data/en/1_0001.json
> +                            "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
`strong` tag/no classes

2017-07-28 14:16 UTC, hamishtaplin commented on data/en/2_0001.json
> +                        "description": "<p class=\"venus\">If actual figures are not available, please provide informed estimates.</p>"
I think this should be `<p><strong>If actual...</strong></p>` instead of adding a class to the schema

2017-07-28 14:16 UTC, hamishtaplin commented on app/assets/styles/partials/components/_accordion.scss
> +  border-radius: 3px;
Remove this, looks weird.

2017-07-28 14:16 UTC, hamishtaplin commented on app/templates/partials/introduction/preview.html
> +            <dt class="accordion__title venus js-accordion-title" data-js-accordion-event-label="{{question.question}}">
Although the `dl` makes sense, not sure if it's the best choice. The original accordion uses the pattern found here: http://heydonworks.com/practical_aria_examples/#progressive-collapsibles and tested very well with DAC.

2017-07-28 14:16 UTC, hamishtaplin commented
Would be good to sort out some of the alignment issues:

![screenshot 2017-07-28 15 07 29](https://user-images.githubusercontent.com/930398/28721303-befbe6f0-73a7-11e7-93cb-78647d59fb45.png)

2017-07-28 14:44 UTC, adoublebarrel commented on app/templates/partials/introduction/preview.html
> +            <dt class="accordion__title venus js-accordion-title" data-js-accordion-event-label="{{question.question}}">
Cool I'll have a read of that. I've heavily cribbed that from http://a11yproject.com/patterns.html (under accordions & tabs), will be interesting to compare.

2017-08-02 11:17 UTC, collisdigital commented on app/assets/img/icons/accordion.svg
> +            <g id="Group" transform="translate(0.000000, 110.000000)">
,jbkhv

2017-08-03 07:48 UTC, ajmaddaford requested changes

2017-08-03 07:48 UTC, ajmaddaford commented on app/templates/introduction.html
> +  {% endblock start_survey %}
Is this `start_survey` block ever overridden?

2017-08-03 11:34 UTC, adoublebarrel commented on app/templates/introduction.html
> +  {% endblock start_survey %}
It is now that we've lost the button (at the bottom) from MWSS. Sorry.

2017-08-08 07:48 UTC, hamishtaplin approved these changes

2017-08-09 08:09 UTC, ajmaddaford approved these changes

2017-08-09 08:09 UTC, merged