Removed default KID and added logging for KID use
ONSdigital/eq-survey-runner pull request #1183
Opened 2017-07-25 10:47 UTC by jonnyshaw89

### What is the context of this PR?
I have removed the default KID of `EQ_USER_AUTHENTICATION_SR_PRIVATE_KEY` when no KID is passed for the JWE.
This is because all upstream systems are passing a KID for the JWE

### How to review 
Check that you are still able to authenticate.

2017-07-25 11:19 UTC, ajmaddaford requested changes

2017-07-25 11:19 UTC, ajmaddaford commented on app/cryptography/token_helper.py
> +        logger.info("Decrypting JWE", KID=jwe_kid)
From the logging standards at https://digitaleq.atlassian.net/wiki/display/SDC/Logging, the keys should be lower case - KID -> kid

2017-07-25 11:22 UTC, jonnyshaw89 commented on app/cryptography/token_helper.py
> +        logger.info("Decrypting JWE", KID=jwe_kid)
I did have that originally, ill change it back :)

2017-07-25 13:17 UTC, ajmaddaford requested changes

2017-07-25 13:17 UTC, ajmaddaford commented on tests/app/cryptography/test_token_helper.py
> -    def test_missing_kid_uses_default(self):
Should this be converted to a test for an exception when kid is missing from the JWE header rather than removed?

2017-07-25 13:22 UTC, jonnyshaw89 commented on tests/app/cryptography/test_token_helper.py
> -    def test_missing_kid_uses_default(self):
yeh probably.

2017-07-25 15:01 UTC, ajmaddaford approved these changes

2017-07-26 14:22 UTC, adoublebarrel approved these changes

2017-07-26 14:54 UTC, merged