eq-survey-runner: #1053 - Failed requests for URLs containing <no source> (Issue)
ONSdigital/eq-survey-runner pull request #1185
Opened 2017-07-27 16:52 UTC by adoublebarrel

### What is the context of this PR?
[Trello Card](https://trello.com/c/SX3FWZrm/1025-eq-survey-runner-1053-failed-requests-for-urls-containing-no-source-issue-xs)

https://github.com/ONSdigital/eq-survey-runner/issues/1053

After some poking around (and upgrading the gulp sass plugin) it looks
like a problem with the globs + postCSS + cssnano was resulting in a <no
source> file being added to the gulp styles task. Seems like the likely root cause so I've fixed it.

I've also stopped source maps being generated if the EQ_DEV_MODE
environment variable is not 'True'. If we want source maps in the other
environments I'll reverse it out.

### How to review
You can run the app locally as usual and everything is fine.

Run 'EQ_DEV_MODE=True EQ_MINIMIZE_ASSETS=True yarn compile'
Change the dev_settings.sh EQ_MINIMIZE_ASSETS env var to 'True' and run the app.

- You'll get minified versions of the CSS and JS
- You should see a comment at the end of the minified files detailing the source map url.
- In chrome you can search for the mapped files using CMD-P (CTRL-P for non-OSX)

Run 'EQ_MINIMIZE_ASSETS=True yarn compile'

You should get the minified assets but the source map url comment should be missing.

2017-07-28 08:33 UTC, jonnyshaw89 commented on gulp/styles.js
> +  const doSourceMaps = process.env.EQ_DEV_MODE === 'True'
We are trying to stop the use of the generic "Dev Mode" so maybe if we want this feature it should have its own switch?

2017-07-28 14:34 UTC, hamishtaplin approved these changes

2017-07-28 15:00 UTC, ajmaddaford requested changes

2017-07-28 15:00 UTC, ajmaddaford commented on app/settings.py
> +EQ_MINIMIZE_ASSETS = parse_mode(os.getenv('EQ_MINIMIZE_ASSETS', 'TRUE'))
This should be 'True' to be consistent with the other `parse_mode` calls

2017-07-28 15:08 UTC, jonnyshaw89 requested changes

2017-07-28 15:08 UTC, jonnyshaw89 commented on docker-compose.yml
> +      EQ_MINIMIZE_ASSETS: "True"
No need to set this to True if the app defaults to True

2017-08-01 15:26 UTC, adoublebarrel commented on app/settings.py
> +EQ_MINIMIZE_ASSETS = parse_mode(os.getenv('EQ_MINIMIZE_ASSETS', 'TRUE'))
🤦‍♂️

2017-08-01 15:54 UTC, jonnyshaw89 requested changes

2017-08-01 15:54 UTC, jonnyshaw89 commented on scripts/dev_settings.sh
> +    export EQ_MINIMIZE_ASSETS=True
If the settings.py defaults this to on then there is no need to also set it here.

2017-08-01 16:02 UTC, jonnyshaw89 approved these changes

2017-08-02 07:43 UTC, ajmaddaford approved these changes

2017-08-02 08:14 UTC, jonnyshaw89 commented
@adoublebarrel squash?

2017-08-02 12:36 UTC, merged