fixes mwss preview content issue
ONSdigital/eq-survey-runner pull request #1195
Opened 2017-08-09 14:24 UTC by yoganandkunche

### What is the context of this PR?
Fixes #1194 

### How to review 
restest #1194

2017-08-09 14:32 UTC, adoublebarrel requested changes

2017-08-09 14:32 UTC, adoublebarrel commented on data/en/1_0005.json
> -                                "the percentage or number of employees who received a new pay rate"
Ah, I ran this change past Charlotte in person and didn't update the copy document. Sorry, my bad :(

2017-08-09 16:11 UTC, adoublebarrel approved these changes

2017-08-10 08:22 UTC, ajmaddaford approved these changes

2017-08-10 09:20 UTC, merged