Unit Patterns: Length, Area and Volume
ONSdigital/eq-survey-runner pull request #1196
Opened 2017-08-09 16:19 UTC by dwyeradam

- Allow for the display of Length, Area and Volume units
- New Unit schema type created with unit param
- Units defined by Unicode Common Locale Data Repository
- Allowable units can be found at http://unicode.org/repos/cldr/tags/latest/common/validity/unit.xml

2017-08-11 07:33 UTC, jonnyshaw89 requested changes
Other than the small change all looks good!

2017-08-11 07:33 UTC, jonnyshaw89 commented on requirements.txt
> +    --hash=sha256:e86ca5a3a6bb64b9bbb62b9dac37225ec0ab5dfaae3c2492ebd648266468042f
i think your missing a 2nd hash. if you run `hashin Babel` it will add the additional one.

2017-08-11 12:35 UTC, ajmaddaford requested changes

2017-08-11 12:35 UTC, ajmaddaford commented on app/templates/partials/summary/unit.html
> +{{answer.unit|format_unit (answer.value)}}
The syntax for this looks odd, if two arguments are used they should be passed like `format_unit(answer.unit, answer.value)`. This is done for the `format_start_end_date` filter (using a context processor).

2017-08-11 12:35 UTC, ajmaddaford commented on app/templates/partials/answers/unit.html
> +        <span class="input-type__type" id="{{answer.id}}-type">{{answer.unit| format_unit ('')}}</span>
The second argument to `format_unit` should default to `''` so you wouldn't need to pass an empty string here.

2017-08-11 12:35 UTC, ajmaddaford commented on data/schema/schema_units.json
> +{
- I think we should just name this file `units.json` as it's already in a `schema` folder
- I think the first line should be `"$schema": "http://json-schema.org/draft-04/schema"`
- `unit` should have a type of `string`

2017-08-11 14:14 UTC, ajmaddaford requested changes

2017-08-11 14:14 UTC, ajmaddaford commented on app/jinja_filters.py
> +def unit_check():
I think it would be clearer for this to be called `format_unit_processor`, I'm not sure why the others are called `_check`

2017-08-11 14:14 UTC, ajmaddaford commented on app/jinja_filters.py
> +@blueprint.app_template_filter()
I don't think this annotation is relevant now it's not a filter

2017-08-11 14:40 UTC, dwyeradam commented
@hamishtaplin  or @armstrongb  Could you give the couple of front end changes a review please.

2017-08-11 15:21 UTC, ajmaddaford approved these changes

2017-08-14 08:21 UTC, jonnyshaw89 approved these changes

2017-08-14 15:38 UTC, hamishtaplin submitted a review, later dismissed

2017-08-14 15:38 UTC, hamishtaplin commented on app/assets/styles/partials/components/_input-type.scss
> +.input-type--unit {
No need to duplicate the CSS from `.input-type--percentage`, just add the selector for `.input-type--unit` to that block instead:

```scss
  .input-type--percentage,
  .input-type--unit {
    // css
  }
```

2017-08-15 07:05 UTC, shahi645 commented on app/assets/styles/partials/components/_input-type.scss
> +.input-type--unit {
done

2017-08-15 10:13 UTC, jonnyshaw89 commented
@hamishtaplin this one is ready if you are happy with the fix?

2017-08-15 12:13 UTC, hamishtaplin approved these changes

2017-08-15 12:14 UTC, jonnyshaw89 commented
@dwyeradam Can you squash this on?

2017-08-15 14:04 UTC, merged