eq-1246- Remove Assertion Tests
ONSdigital/eq-survey-runner pull request #1200
Opened 2017-08-14 10:34 UTC by MIslam92

Context of this PR:
Refactoring of tests to remove all assertions in code and to be replaced with exceptions & also to add tests for these.
Also, new methods added to deal with "Location" in the answer_store

Trello Card: https://trello.com/c/93EgMm8q

How to review:
Run tests

2017-08-14 10:54 UTC, shahi645 reviewed
LGTM 👍🏿

2017-08-14 10:54 UTC, shahi645 approved these changes

2017-08-14 11:29 UTC, jonnyshaw89 requested changes

2017-08-14 11:29 UTC, jonnyshaw89 commented on app/submitter/converter.py
> +    :param flushed: writes file data to disk
Does it?

2017-08-14 11:52 UTC, MIslam92 commented on app/submitter/converter.py
> +    :param flushed: writes file data to disk
¯\_(ツ)_/¯

2017-08-16 10:26 UTC, jonnyshaw89 commented on app/forms/household_composition_form.py
> +logger = wrap_logger(logging.getLogger(__name__))
we should stick to the standard of
```
from structlog import get_logger
logger = get_logger()
```

2017-08-16 10:29 UTC, jonnyshaw89 requested changes

2017-08-16 10:29 UTC, jonnyshaw89 commented on app/helpers/schema_helper.py
> +                            raise AssertionError('Duplicate alias found: ' + answer['alias'])
Do we still want to throw this type of Error?

2017-08-16 10:29 UTC, jonnyshaw89 commented on tests/app/helpers/test_schema_helper.py
> +                                        {
Incorrect indentation

2017-08-16 12:54 UTC, jonnyshaw89 requested changes

2017-08-16 12:54 UTC, jonnyshaw89 commented on app/questionnaire/rules.py
> +                raise AssertionError("Multiple answers ({:d}) found evaluating when rule for answer ({})"
There was more than just the 1 AssertionError

2017-08-17 10:51 UTC, jonnyshaw89 approved these changes

2017-08-17 10:51 UTC, jonnyshaw89 commented
@MIslam92 Can you squash this branch?

2017-08-17 10:55 UTC, shahi645 commented
@jonnyshaw89 He is away until Tuesday, want me to do it ?

2017-08-17 15:10 UTC, merged