Apply Conditional dates to RSI
ONSdigital/eq-survey-runner pull request #1210
Opened 2017-08-29 08:30 UTC by jonnyshaw89

### What is the context of this PR?
Conditional date logic has been applied to the RSI questionnaires as per the Google Doc (https://drive.google.com/drive/folders/0BwTdPM-J8JFBa2F4RFQyTlN2bms)

### How to review 
Check that each of the RSI questionnaires matches the Google Doc

2017-08-29 10:14 UTC, MIslam92 approved these changes
Seems to match up with all surveys listed 👍

2017-09-01 11:17 UTC, ajmaddaford submitted a review, later dismissed

2017-09-01 11:17 UTC, ajmaddaford commented on data/en/1_0102.json
> +                "id": "reporting-period-block-1",
For the new id values I think we should have a clearer prefix of `reporting-period-choice` and drop the word `block`, so the id values would be:
```
reporting-period-choice
reporting-period-choice-question
reporting-period-choice-answer
```

2017-09-01 13:16 UTC, ajmaddaford requested changes

2017-09-01 13:16 UTC, ajmaddaford commented on data/en/1_0102.json
> +                        "description": "",
Can we remove the empty values?

2017-09-01 13:21 UTC, ajmaddaford requested changes

2017-09-01 13:21 UTC, ajmaddaford commented on data/en/1_0102.json
> +                                "id": "reporting-period-answer-1",
The routing is broken as this id has been changed

2017-09-04 15:58 UTC, jonnyshaw89 commented
@ajmaddaford can you look at this again?

2017-09-04 16:49 UTC, ajmaddaford reviewed
If you:
- Start a survey using the code from master
- Change the period dates
- Resume the survey wit the conditional dates
- Choose to keep the default dates

Then all subsequent screens still use the previously provided dates.

2017-09-05 12:46 UTC, shahi645 commented
works for the rsi form types listed on the google doc 👍🏿

2017-09-06 11:05 UTC, ajmaddaford requested changes

2017-09-06 11:05 UTC, ajmaddaford commented on tests/app/templating/test_schema_context.py
> +class TestSchemaContext(AppContextTestCase):  # pylint: disable=too-many-public-methods
I think we need another test for the new evaluation of whether an answer is on the routing path, something like:
- Add 2 answers to the answer store with different locations
- Create a routing path that includes one answer location but not the other
- Verify the first answer in the schema context, and the second isn't

2017-09-06 15:09 UTC, ajmaddaford approved these changes

2017-09-07 08:18 UTC, merged