Update default error messages
ONSdigital/eq-survey-runner pull request #1212
Opened 2017-08-30 10:40 UTC by jonnyshaw89

### What is the context of this PR?
Updated error messages on listed MCI/RSI form types so they match approved error message wording

### How to review 
Check that the error messages meet the Specs defined in https://trello.com/c/1sA9qHlv/1279-update-survey-default-error-messages-m

2017-08-30 12:43 UTC, dwyeradam requested changes

2017-08-30 12:43 UTC, dwyeradam commented on app/validation/validators.py
> +                error_message = self.messages.get('OUT_OF_RANGE', self.messages['NUMBER_TOO_SMALL']) % dict(min=self.minimum, max=self.maximum)
Do we really need to cover both format methods? We could remove the % dict from this line and line 80 and put it back in on line 83 where the error is raised.

2017-08-30 13:25 UTC, yoganandkunche commented
@charlottehirst1 @sarahbrooks6 @donnapalmer3 I have done a quick review of this card on the branch and I have come across conflicting validation error messages which I think has to be finalised before signing off this card (Example: When a negative value '-2' is entered in a £'s field the spec's and confluence pages give different msgs: 1) Enter a positive number. & 2) Enter a number more than 0 (where '0' is also a valid answer).

2017-09-07 14:55 UTC, ajmaddaford requested changes

2017-09-07 14:55 UTC, ajmaddaford commented on tests/new_functional/spec/numbers.spec.js
> +          .getText('ul > li:nth-child(4) > a').should.eventually.contain("Enter a number less than %(max)s.".replace("%(max)s", "100"));
I don't think we need the string replacement here

2017-09-07 14:55 UTC, ajmaddaford commented on tests/new_functional/spec/numbers.spec.js
> +          .getText('ul > li:nth-child(2) > a').should.eventually.contain("Enter a number rounded to %(max)d decimal places.".replace("%(max)d", "2"));
I don't think we need the string replacement here

2017-09-07 15:08 UTC, ajmaddaford approved these changes

2017-09-08 09:13 UTC, dwyeradam requested changes
Two tests in test_number_range_validator.py should now fail. However they do not as they are currently not working as they should. Lines 239 and 290 are tabbed and therefore are not being evaluated but are using the no longer existing 'OUT_OF_RANGE' error message. Line 167 in test_number_validator.py is also tabbed when it shouldn't be but other than the tab removed needs no further changes.

2017-09-08 09:59 UTC, dwyeradam approved these changes

2017-09-12 12:39 UTC, yoganandkunche commented
@jonnyshaw89 error message needs updating 
Expected: 
Enter a number more than or equal to {min}.

Actual: Enter a number more than 0.

2017-09-12 15:14 UTC, yoganandkunche requested changes
Percentage validation error message needs updating ass discussed.

2017-09-12 15:40 UTC, yoganandkunche approved these changes

2017-09-12 16:22 UTC, merged