Eq data converting to strings
ONSdigital/eq-survey-runner pull request #1215
Opened 2017-09-01 13:32 UTC by yoganandkunche

### What is the context of this PR?
Converts all data types entered into a string and pushes it to SDX

### How to review 
Launch any survey with dumper
enter different data type values into fields
and verify the dump

Expected: All the values entered must be displayed as strings on the dump

2017-09-04 14:45 UTC, ajmaddaford approved these changes

2017-09-04 15:52 UTC, dwyeradam requested changes
This only works for schemas with "data_version": "0.0.1". I'm not sure if this was the intention but if we start to use data version 2 at some point then the conversion will not take place.

2017-09-04 17:11 UTC, ajmaddaford commented
@dwyeradam That was the intention. The stringifcation of values is only required for surveys that use Q codes.

2017-09-05 08:15 UTC, dwyeradam approved these changes

2017-09-06 11:10 UTC, ajmaddaford requested changes
The commit message needs changing, it's currently `resolved merge conflicts`.

The full commit message should also include why this is being changed.

2017-09-06 12:50 UTC, ajmaddaford approved these changes

2017-09-06 12:50 UTC, merged