fixes-eg-defect-1216
ONSdigital/eq-survey-runner pull request #1217
Opened 2017-09-04 11:14 UTC by yoganandkunche

### What is the context of this PR?
fixed #1216 

### How to review 
Retest #1216

2017-09-04 14:33 UTC, ajmaddaford approved these changes

2017-09-04 15:54 UTC, dwyeradam approved these changes

2017-09-04 16:55 UTC, ajmaddaford requested changes
The commit message needs to be improved:
- It shouldn't be hyphenated
- It should be more descriptive e.g. `Fix landing page punctuation`
- References to the issue fixed should use a `#` so it becomes linked in GitHub e.g. `Fix landing page punctuation; fixes #1216`

2017-09-05 09:00 UTC, ajmaddaford approved these changes

2017-09-05 09:00 UTC, merged