Added population of path finder in g
ONSdigital/eq-survey-runner pull request #1221
Opened 2017-09-06 09:17 UTC by adoublebarrel

### What is the context of this PR?
Before this the helper always returned a new path finder object which
made most of the code in the helper pointless.

### How to review 
All functional behaviour should be the same as before. If you set a breakpoint within the `if` you should find that you only hit it once per request to the questionnaire blueprint.

2017-09-06 09:18 UTC, jonnyshaw89 commented
@adoublebarrel should this have a test?

2017-09-06 16:20 UTC, jonnyshaw89 commented on tests/app/helpers/test_path_finder_helper.py
> +        self.assertEqual('', mock_path_finder)
This isn't very obvious?
looks like its asserting a mock is an empty string?

2017-09-06 16:20 UTC, jonnyshaw89 requested changes

2017-09-06 16:20 UTC, jonnyshaw89 commented on tests/app/helpers/test_path_finder_helper.py
> +        self.assertEqual('', mock_path_finder)
We should also test that calling it a 2nd time returns the same value and doesn't generate a new one?

2017-09-07 10:31 UTC, adoublebarrel commented
Sorry, I should of marked it as "in progress". This was a broken push so that I had everything tee'd up for being back in the office.

2017-09-12 10:54 UTC, jonnyshaw89 approved these changes

2017-09-12 10:57 UTC, ajmaddaford approved these changes

2017-09-12 10:58 UTC, merged