EQ-1325 Inline feedback form
ONSdigital/eq-survey-runner pull request #1234
Opened 2017-09-12 16:29 UTC by adoublebarrel

### What is the context of this PR?
[Trello Card](https://trello.com/c/loROoVWw/1325-in-service-feedback-inline-js-s)

### How to review 
The feedback link now opens the inline form when JS is enabled, the non-JS experience still opens the standalone form in a new tab.

A new JS module has been added and updates made to the feedback scss.

2017-09-12 17:03 UTC, yoganandkunche commented
@adoublebarrel looks like there is an issue. error 500 on every scheme. 
TemplateNotFound(template)

2017-09-13 08:15 UTC, jonnyshaw89 commented
@adoublebarrel did you forget to commit a file ?
`jinja2.exceptions.TemplateNotFound: partials/feedback/expandable_inline.html`

2017-09-13 09:25 UTC, jonnyshaw89 commented on app/templates/layouts/_base.html
> +      <script id="__bs_script__">//<![CDATA[
Don't forget to take this out again.

2017-09-13 09:27 UTC, jonnyshaw89 commented
I think there should be a way to close the feedback form if i change my mind?

2017-09-13 09:29 UTC, jonnyshaw89 commented
After posting the feedback form i get a 302 and the browser performs a GET request in the background to `http://localhost:5000/feedback/thank-you` for this form i think it should just return a 200 status code

2017-09-13 09:30 UTC, jonnyshaw89 requested changes
Comments above

2017-09-13 10:58 UTC, yoganandkunche submitted a review, later dismissed
The top previous link stops working after submitting a feedback.

2017-09-13 14:29 UTC, adoublebarrel commented
@jonnyshaw89 
The XHR request no longer gets redirected.

I agree with your comment re. being able to collapse the form but having implemented this now I think the general UX should be re-thought ("modal" overlay rather than expanding content FWIW).

We need to get better with engaging with these designs earlier before they get to this point in the process. As it stands the current behaviour is to the agreed spec when this card was accepted for development.

2017-09-14 11:02 UTC, jonnyshaw89 commented
@adoublebarrel I think we should log the POST request out as we do with `questionnaire request`

2017-09-15 12:58 UTC, jonnyshaw89 approved these changes

2017-09-18 18:07 UTC, jcox-dev commented
Echoing what @jonnyshaw89 was saying about being able to close the inline feedback form, perhaps we can keep the "beta" line, instead of hiding it, and clicking the "Help us improve it" with the form visible hides it again.

2017-09-19 12:08 UTC, jcox-dev commented
Missed the import for the helpers in the inline template.

2017-09-20 09:12 UTC, shahi645 approved these changes
New changes look good to me an work fine

2017-09-20 10:31 UTC, charlotte-hirst commented
works fine in chrome but cant submit in Safari. Havent got IE to test it with

2017-09-20 11:04 UTC, jcox-dev requested changes

2017-09-20 11:04 UTC, jcox-dev commented on app/assets/js/app/modules/inline-feedback.js
> +    formData.set('redirect', 'false')
The advanced interface for FormData is not implemented across all browsers. Need to polyfill or handle redirect in another way other than manipulating the form.

2017-09-20 17:54 UTC, armstrongb commented
### The textarea focus state is displaying incorrectly in Chrome.

Both edges are cropped by 1px each when focussed. Both edges should display the same thickness as the top and bottom edges. If the text area is dragged inwards from the right-hand edge the `box-shadow` shows fully on the rh side.

### When at default width:
![ons-screenshot-feedback-textarea-focus](https://user-images.githubusercontent.com/22910336/30658858-01f4eb30-9e34-11e7-99ec-36c41e85dbcc.png)

### When dragged inwards:
![ons-screenshot-feedback-textarea-focus-infromright](https://user-images.githubusercontent.com/22910336/30659182-0220ba0c-9e35-11e7-850e-8414debd2209.png)

2017-09-20 17:58 UTC, armstrongb commented
This also happens to the input fields (lefthand `box-shadow`):

![ons-screenshot-feedback-input-focus](https://user-images.githubusercontent.com/22910336/30659422-a8a9e2d6-9e35-11e7-8895-f607a28d0c65.png)

2017-09-20 18:06 UTC, armstrongb commented
I think that the feedback 'Cancel' link should have `title="Cancel sending your feedback"` added to the link so that its purpose is stated. Alternatively the 'sending your feedback' could be: `<span class="u-vh"> sending your feedback</span>`

@hamishtaplin which is our preferred option for this?

2017-09-20 18:22 UTC, armstrongb requested changes
Can the visual defects and 'Cancel' link attributes be resolved before proceeding please?

2017-09-21 07:20 UTC, jcox-dev approved these changes

2017-09-21 09:16 UTC, jcox-dev commented
Spotted a visible gap (between the feedback CTA and header) introduced with these changes but currently unable to determine how. @armstrongb mentioned an old "previous" link might be the culprit (also in screenshot).

![ons-screenshot-feedback-gap](https://user-images.githubusercontent.com/28348457/30688353-d13f8b4e-9eb5-11e7-95d3-dc07c210dd5c.png)
![ons-screenshot-previous-link](https://user-images.githubusercontent.com/28348457/30688354-d14d31fe-9eb5-11e7-9b47-03d41a9f3c26.png)

2017-09-21 14:39 UTC, bennpearson commented
`overflow: hidden` just needs removing from `.feedback__inline` to fix the border issue.

2017-09-22 09:14 UTC, hamishtaplin requested changes

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/js/app/modules/inline-feedback.js
> +export const classCallToAction = 'feedback__action'
Don't use CSS classes as selectors (as changing them will break the JS)

Instead add `js-` prefixed hooks.

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/js/app/modules/inline-feedback.js
> +  const elFeedback = document.getElementsByClassName(classInlineForm)[0]
use `document.querySelector` which will return the first matched element.

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/styles/partials/components/_feedback.scss
> +  margin-bottom: 0 !important;
Don't use `!important`. We should fix the [greedy selector](https://github.com/ONSdigital/eq-survey-runner/blame/eq-1325-inline-feedback-js/app/assets/styles/partials/objects/_page.scss#L27) that's making this necessary.

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/styles/partials/components/_feedback.scss
> +    margin-top: 1rem !important;
Again with `!important` 😲

This transition looks weird because of the `margin-top`—better to handle the whitespace with an internal `div` with padding than override margins and then attempt to transition them.

2017-09-22 09:14 UTC, hamishtaplin commented on app/templates/partials/feedback/expandable_inline.html
> +        <p class="mars feedback__cancel"><a href="" data-qa="a-feedback-close" {{helpers.track('click', 'Feedback', 'Cancel feedback link click')}}>Cancel</a></p>
Why is this a `p`? Don't use semantic tags for layout—it's not a paragraph of text :)

The `a` has no `href`—use a `button`. I guess it is a link because it's designed to look like one, but it isn't actually a link because it doesn't take you to a new page (or a page fragment). It should look like and _be_ a `button`.

2017-09-22 09:14 UTC, hamishtaplin commented on app/templates/partials/feedback_form.html
> +            <a class="feedback__close" href="#close">Close</a>
Not sure how to test this but it's a link to a page fragment (`#close`) that doesn't seem to exist anywhere?

2017-09-22 09:14 UTC, hamishtaplin commented on tests/new_functional/spec/textarea.spec.js
> +  const textarea_limit = '[data-qa="textarea-with-limit"]';
Much better than using CSS classes 👍

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/js/app/modules/inline-feedback.js
> +    let elSubmit = element.getElementsByClassName(classSubmit)[0]
This never gets reassigned so should be `const`.

2017-09-22 09:14 UTC, hamishtaplin commented on app/assets/js/app/modules/inline-feedback.js
> +    const form = this.form.getElementsByTagName('form')[0]
`this.form.querySelector("form")`

2017-09-22 09:16 UTC, hamishtaplin commented
![screenshot 2017-09-22 10 00 50](https://user-images.githubusercontent.com/930398/30737593-1e3a72a0-9f7f-11e7-8010-602567bb69e2.png)

Looks like this now 😲

2017-09-22 09:22 UTC, hamishtaplin commented
@armstrongb I don't think it should be a link in the first place? It doesn't go anywhere—it should be a button. Using a `title` just gets you a tooltip, [screenreaders don't read them](https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/).

2017-09-22 09:31 UTC, hamishtaplin commented
I don't know if this is intentional, but putting the form on the top of the page but hiding it without `display: none` means it's still in the tab index—meaning that tabbing through the page takes you through the "hidden" form. Confusing for anyone who uses a keyboard but also bad for accessibility as users of things like Dragon will receive announcements for elements they can't see.

Personally, I would have tested this with DAC _before_ implementing it.

2017-09-22 09:40 UTC, hamishtaplin commented
@jcox-dev click the "Help us improve it" link again feels a bit weird for closing the form? Maybe toggle it to "Don't help us improve it"?

2017-09-22 10:05 UTC, armstrongb commented on app/assets/styles/partials/components/_feedback.scss
> +  margin-bottom: 0 !important;
@hamishtaplin Is there not a `u-mb-0` utility class too?

2017-09-22 10:59 UTC, hamishtaplin commented on app/assets/styles/partials/components/_feedback.scss
> +  margin-bottom: 0 !important;
@armstrongb yeah that would also work 👍

2017-09-22 14:44 UTC, jcox-dev commented
@armstrongb @hamishtaplin changes pushed.

2017-09-25 12:05 UTC, armstrongb commented
The 'Previous' link is too close to the border of the feedback form.
`.page__subheader .container>*` bottom margin in `_page.scss` is preventing the addition of a bottom margin (e.g. `.u-mb-l`)
![image](https://user-images.githubusercontent.com/22910336/30807473-e0c45a10-a1f1-11e7-8c78-24771aa7b8f7.png)

2017-09-25 12:21 UTC, armstrongb commented
Can we remove the `.btn--lg` from the 'Send feedback' button as the type is untidily stepped at present. The resolved layout is shown below:

![image](https://user-images.githubusercontent.com/22910336/30807875-9eb41028-a1f3-11e7-8fd3-8c7db1fc114e.png)

2017-09-25 12:36 UTC, armstrongb commented
I don't think that `.feedback__border` needs the padding-top applied to it.

2017-09-25 13:29 UTC, jcox-dev commented
@armstrongb amendments made.

2017-09-25 15:28 UTC, hamishtaplin approved these changes

2017-09-26 12:50 UTC, jcox-dev commented
There was a discussion today which covered:

- moving the link to the bottom of page (above footer), similar to other .gov sites
- whether "Cancel" should be a link or a button (split on agreement)
- display: none should be default for the form (even without JS) to avoid tabbing through hidden form fields and issues with screenreader
- moving implementation to modal rather than expandable inline form

@hamishtaplin @armstrongb @bennpearson

2017-09-26 16:13 UTC, armstrongb commented
@jcox-dev apologies - the button should have been `.btn--link` so still a button but one styled as a link.

If we are to proceed with this version I think that we should change 
> Cancel

to

> I don't want to provide feedback

which would also not require any visually hidden content.

2017-09-29 10:07 UTC, armstrongb commented
Can we amend the 
> I don't want to provide feedback

to 

> I don’t want to provide feedback
(change = use of apostrophe not straight single quote - use `alt+shift+]` on Mac)

,also:
> Please include your name and email address if you're interested in taking part in further research to improve this survey

change
> ... you're ... 
to
> ... you’re ...

?

Thanks.

2017-09-29 10:26 UTC, jcox-dev commented
@armstrongb amendments pushed. 👍

2017-10-02 09:28 UTC, armstrongb approved these changes

2017-10-02 10:28 UTC, merged