Migrate additional functional tests
ONSdigital/eq-survey-runner pull request #1271
Opened 2017-09-28 10:44 UTC by dwyeradam

Migrate remaining tests not related to Census or UKIS
Remove no longer used functional tests specs and pages

2017-09-28 13:57 UTC, jonnyshaw89 requested changes

2017-09-28 13:57 UTC, jonnyshaw89 commented on tests/new_functional/pages/surveys/question.page.js
> +  saveSignOut() { return '[data-ga-action="Save and complete later click"]'; }
We should probably add a `data-qa` attribute to this button and use that instead of hooking on the the GA attribute?

2017-09-28 15:37 UTC, jonnyshaw89 approved these changes

2017-09-29 13:51 UTC, yoganandkunche approved these changes

2017-09-29 15:16 UTC, merged