remove numbering from MWSS
ONSdigital/eq-survey-runner pull request #1304
Opened 2017-10-18 12:09 UTC by MIslam92

### What is the context of this PR?
Removed section numbering & removed question numbering
As this does not provide user value and is incorrect when routed

### How to review 
- Run survey runner and run though 1_0005(MWSS) to check that no numbers in questions/sections are displayed.

2017-10-18 13:45 UTC, dwyeradam requested changes
I believe this request should also include removal of the section numbers: e.g. "section_number": "2",

2017-10-19 08:51 UTC, dwyeradam approved these changes

2017-10-20 13:10 UTC, shahi645 approved these changes

2017-10-20 13:10 UTC, shahi645 commented
squishy squashy

2017-10-20 13:17 UTC, ajmaddaford submitted a review, later dismissed
Leaving a blocking review until we get confirmation this is ok for release

2017-10-23 16:30 UTC, merged