Eq 1447 add hours worked question
ONSdigital/eq-survey-runner pull request #1319
Opened 2017-10-30 08:01 UTC by MIslam92

### What is the context of this PR?
Add new questions to census surveys
    
    - new questions added to census individual and household
    
    - related functional and integration tests modified to include new questions

### How to review 
Run census household/individual survey and tests to see new questions included and tests pass.

2017-10-30 11:30 UTC, shahi645 commented on data/en/census_individual.json
> +
Remove these empty spaces throughout

2017-10-30 11:39 UTC, shahi645 commented on data/en/census_household.json
> +                    "id": "work",
block_id is kinda vague, should be 'hours-worked'

2017-10-30 11:40 UTC, shahi645 commented on data/en/census_household.json
> +                    "id": "work",
this also then matches up with the answer-id

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_household.json
> +                    "id": "work",
I think we should change this block-id to `hours-worked`

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_household.json
> +                    "id": "travel",
this also should change to `work-travel`

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_household.json
> +                                    "value": "Underground, Metro, Light Rail or Tram"
only capitalise first word

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_household.json
> +                                    "value": "Bus, Minibus or Coach "
same as above ^^^

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_individual.json
> +                "id": "work",
same as i mentioned in the census_household

2017-10-30 11:52 UTC, shahi645 commented on data/en/census_individual.json
> +                                "value": "Underground, Metro, Light Rail or Tram"
Same as i mentioned in household, only capitalise first word

2017-10-30 13:11 UTC, shahi645 requested changes

2017-10-30 13:11 UTC, shahi645 commented on data/en/census_household.json
> +                    "id": "travel",
This should be `work-travel` for the block-id?

2017-10-30 13:11 UTC, shahi645 commented on data/en/census_individual.json
> +                "id": "travel",
same as above

2017-10-30 14:20 UTC, shahi645 approved these changes
LGTM

2017-10-30 15:32 UTC, jonnyshaw89 requested changes

2017-10-30 15:32 UTC, jonnyshaw89 commented on data/en/census_household.json
> +                                        "description": "For example, you travel by bus and by car. Your bus journey is 5 miles, and the train journey is 8 miles. You should select train as your answe
This content looks wrong. Car or Train??

2017-10-31 09:59 UTC, MIslam92 commented on data/en/census_household.json
> +                                        "description": "For example, you travel by bus and by car. Your bus journey is 5 miles, and the train journey is 8 miles. You should select train as your answe
Seems so as thats whats on the card I'll just update it and double check with content lot

2017-10-31 13:26 UTC, jonnyshaw89 commented on data/en/census_household.json
> +                                        "description": "For example, you travel by bus and by car. Your bus journey is 5 miles, and the train journey is 8 miles. You should select train as your answe
@MIslam92 was this content confirmed? also you have only updated Household

2017-11-01 09:42 UTC, MIslam92 commented on data/en/census_household.json
> +                                        "description": "For example, you travel by bus and by car. Your bus journey is 5 miles, and the train journey is 8 miles. You should select train as your answe
@jonnyshaw89 yep all confirmed and made change so that it actually makes sense now

2017-11-02 09:20 UTC, jonnyshaw89 requested changes

2017-11-02 09:20 UTC, jonnyshaw89 commented on data/en/census_individual.json
> +                                    "description": "For example, you travel by bus and by car. Your bus journey is 5 miles, and the train journey is 8 miles. You should select train as your answer"
@MIslam92 same issue with this description. bus, car, train?
this should be consistent with household

2017-11-02 10:47 UTC, jonnyshaw89 approved these changes

2017-11-02 11:37 UTC, merged