Removed census household section titles
ONSdigital/eq-survey-runner pull request #1326
Opened 2017-10-31 09:55 UTC by MIslam92

## **Context of this PR**

Removing section headings from census household
Except for summary pages and printing answers after submission

## **How to review**

Run SR and look though Census Household to check that all section headings are removed and run tests

2017-10-31 13:37 UTC, jonnyshaw89 commented
@MIslam92 Did you look at just removing it from the theme?

2017-10-31 13:39 UTC, MIslam92 commented
@jonnyshaw89 I did however if I removed it from the census theme it would remove it from household, communal & individual? While the card only requests it to be removed from household?

2017-11-01 08:00 UTC, shahi645 commented on data/en/census_household.json
> +                    "title": "",
Get rid of these titles, to match rest of schema changes?

2017-11-01 09:36 UTC, shahi645 requested changes
Section headings still remain for individual sections but not on all questions. So need to remove of keep all. 
Also ` def complete_individual_section_person_1` failing in `test_census_household_submission_data`

2017-11-02 09:22 UTC, jonnyshaw89 requested changes

2017-11-02 09:22 UTC, jonnyshaw89 commented on tests/functional/spec/census-household.spec.js
> + /* it('Given a census household survey, When one person in household, Then persons name should appear on member details pages.', function () {
If we remove this then this needs to be deleted now commented

2017-11-02 09:22 UTC, jonnyshaw89 commented on data/schema/schema_v1.json
> -                      "title",
You also need to add validation to say that if it is specified then it can't be empty.

2017-11-02 09:29 UTC, shahi645 approved these changes
LGTM, all section titles gone and tests pass 👍🏿

2017-11-02 14:47 UTC, jonnyshaw89 approved these changes

2017-11-02 14:47 UTC, jonnyshaw89 commented
@MIslam92 Squashy Squishy

2017-11-02 16:06 UTC, merged