Update do you stay at another address question
ONSdigital/eq-survey-runner pull request #1343
Opened 2017-11-07 08:53 UTC by MIslam92

### What is the context of this PR?
Now pipes persons name into question, added validation on date that is entered and updated corresponding functional/integration tests

Card: https://trello.com/c/zDzD5q6S/1479-update-do-you-stay-at-another-address-s

### How to review 
Open SR and get to that question and enter a invalid date to check if validation works.
Run tests as well.

2017-11-08 15:44 UTC, jonnyshaw89 requested changes

2017-11-08 15:44 UTC, jonnyshaw89 commented on data/en/census_household.json
> +                        "title": "When did {{[answers.first_name[group_instance], answers.last_name[group_instance]] | format_household_name_possessive }} most recently arrive to live in the United K
I don't think this should be possessive?

2017-11-09 09:29 UTC, jonnyshaw89 commented
@MIslam92 is this PR title wrong?

2017-11-10 15:00 UTC, jonnyshaw89 commented
@MIslam92 Is the wrong Trello card attached?

2017-11-10 17:08 UTC, MIslam92 commented
@jonnyshaw89 potentially 🙃 but amended now

2017-11-10 17:17 UTC, jonnyshaw89 requested changes

2017-11-10 17:17 UTC, jonnyshaw89 commented on data/en/census_household.json
>                                  "description": "Exclude short visits away from the UK"
The guidance structure doesn't match the design

2017-11-15 16:17 UTC, jonnyshaw89 commented
@MIslam92 is this "in-progress"?

2017-11-15 16:20 UTC, jonnyshaw89 requested changes

2017-11-15 16:20 UTC, jonnyshaw89 commented on data/en/census_household.json
> +                                "description": "<strong>Exclude</strong> <br /> <br />short visits away from the UK"
Pretty sure this isn't how we do this.

2017-11-15 16:20 UTC, jonnyshaw89 commented on data/en/census_household.json
> +                                "description": "<strong>Exclude</strong> <br /> <br />short visits away from the UK"
It should be more like this.
```
{
    "description": "Exclude",
    "list": [
        "short visits away from the UK"
    ]
}
```

2017-11-22 10:05 UTC, closed without merging