census updated language questions
ONSdigital/eq-survey-runner pull request #1346
Opened 2017-11-07 15:33 UTC by yoganandkunche

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.
Content update

Card: https://trello.com/c/XvGRSBlV/1491-update-language-questions-s

###How to review

Run Survey Runner & check content updated and tests pass

2017-11-08 10:26 UTC, shahi645 approved these changes

2017-11-08 10:40 UTC, dwyeradam requested changes
We need to update "language-welsh-question" as well.

2017-11-08 16:39 UTC, dwyeradam approved these changes

2017-11-08 21:55 UTC, charlotte-hirst requested changes

2017-11-08 21:55 UTC, charlotte-hirst commented on data/en/census_household.json
> +                            "title": "What is <em>{{ [answers.first_name[group_instance], answers.last_name[group_instance]] | format_household_name_possessive }}</em> main language?",
Doesnt quite match content - other option needs "(please specify)" removing

2017-11-09 16:33 UTC, charlotte-hirst approved these changes

2017-11-10 08:38 UTC, merged