Fix issue in ethnicity and another address question
ONSdigital/eq-survey-runner pull request #1356
Opened 2017-11-10 08:01 UTC by MIslam92

### What is the context of this PR?

- moved guidance to above question for ethnicity question

- removed please specify from label in another address question

Card: https://trello.com/c/tEyntfnt/1511-issue-in-ethnicity-and-another-address-questions

fixes: #1355

### How to review 
The usual check run Census Household and verify changes made.

2017-11-10 09:59 UTC, shahi645 approved these changes
LGTM

2017-11-10 14:59 UTC, charlotte-hirst requested changes

2017-11-10 14:59 UTC, charlotte-hirst commented on data/en/census_household.json
> +                                        "description": "Please select the answer you think is most appropriate."
this line should not be there as per card

2017-11-10 14:59 UTC, charlotte-hirst commented on data/en/census_household.json
> +                                        "description": "If you don’t feel the options apply to you, select ‘Other ethnic group’. You will then be able to write in the ethnic group you prefer to ident
this line should not be there as per card

2017-11-14 08:15 UTC, charlotte-hirst requested changes
guidance shouldnt be in a panel unless its an include or exclude

2017-11-15 08:21 UTC, MIslam92 commented
@charlotte-hirst can you have a approve this so I can get this merged?

2017-11-15 13:03 UTC, charlotte-hirst approved these changes

2017-11-15 14:41 UTC, merged