Updated sexual identity question
ONSdigital/eq-survey-runner pull request #1365
Opened 2017-11-13 11:32 UTC by MIslam92

### What is the context of this PR?
Census Household content changes: 
- pipes name into question
- updated current functional and integration tests

Card: https://trello.com/c/QmxMUypz/1490-update-sex-identity

### How to review 
Usual

2017-11-13 13:45 UTC, shahi645 requested changes

2017-11-13 13:45 UTC, shahi645 commented on data/en/census_household.json
>                          "type": "General",
need to use format_household_name and first name and surname is required

2017-11-14 08:12 UTC, shahi645 approved these changes

2017-11-14 10:47 UTC, jonnyshaw89 commented
@MIslam92 i think you may have edited the wrong question?
You have edited the sex question and not the sexual identity question
https://github.com/ONSdigital/eq-survey-runner/blob/master/data/en/census_household.json#L2616

2017-11-14 13:53 UTC, closed without merging