Update sexual identity question
ONSdigital/eq-survey-runner pull request #1369
Opened 2017-11-14 13:53 UTC by MIslam92

### What is the context of this PR?

- content updated and pipe name into question

- updated tests functional and integration

Card: https://trello.com/c/QmxMUypz/1490-update-sex-identity

### How to review
 
The usual

2017-11-15 16:19 UTC, shahi645 requested changes

2017-11-15 16:19 UTC, shahi645 commented on data/en/census_household.json
> +                        "title": "Which of the following options best describes how <em>{{[answers.first_name[group_instance]] | format_household_name }}</em> thinks of themselves?",
Doesn't match the question in design exactly

2017-11-15 16:48 UTC, charlotte-hirst approved these changes
Although Shahi is right it doesnt match the design, I think it sounds better and for now is consistent with other questions where we use the phrase 'best describes'.

2017-11-16 08:56 UTC, shahi645 approved these changes
squishy-squashy

2017-11-16 10:50 UTC, shahi645 commented
@jonnyshaw89 to look at and merge when the travis build passes 😉

2017-11-16 11:49 UTC, merged