Attempting to fix Travis pipenv performance issue
ONSdigital/eq-survey-runner pull request #1416
Opened 2017-12-28 13:54 UTC by jonnyshaw89

2017-12-29 09:38 UTC, shahi645 submitted a review, later dismissed

2018-01-03 10:29 UTC, MIslam92 approved these changes

2018-01-03 11:13 UTC, ajmaddaford requested changes
Before we merge this I think we need to understand how this works when we remove dependencies from the app, or downgrade the version of a dependency.

2018-01-03 17:01 UTC, ajmaddaford commented
When I remove a dependency locally from the Pipfile, it remains in the virtualenv. Only when I run the `pipenv uninstall` command is it removed from the virtualenv.

2018-01-08 12:24 UTC, jonnyshaw89 commented
@ajmaddaford that isn't any different to how the pip cache used to work

2018-01-08 16:58 UTC, ajmaddaford approved these changes
Happy for this to merge on the basis it's the same thing that was happening previously when travis was caching the pip dependencies. This has highlighted the possible issue of the Python environment on Travis having dependencies that have been removed. To counter this we've raised a card to run the functional tests against the Docker container that gets built. This container is built cleanly on every build.

2018-01-08 17:31 UTC, merged