Move thank-you page back to original URL
ONSdigital/eq-survey-runner pull request #1424
Opened 2018-01-12 16:08 UTC by jonnyshaw89

### What is the context of this PR?
The thank-you page was moved recently to `/questionnaire/thank-you` (https://github.com/ONSdigital/eq-survey-runner/pull/1391), but this breaks the analytics for survey completion. It needs to be moved back to `/questionnaire/<eq_id>/<form_type>/<ce_id>/thank-you`.

### How to review 
Has the `thank-you` URL changed back?

2018-01-12 17:05 UTC, dwyeradam requested changes

2018-01-12 17:05 UTC, dwyeradam commented on app/views/questionnaire.py
> +                                      url_prefix='/questionnaire/<eq_id>/<form_type>/<collection_id>/')
We don't need the Collection Exercise ID for analytics so should be removed. And therefore doesn't need to be added to session_data.

2018-01-15 09:54 UTC, shahi645 commented on app/views/questionnaire.py
> +    _check_same_survey(values['eq_id'], values['form_type'], values['collection_id'],
👍

2018-01-15 11:19 UTC, ajmaddaford requested changes

2018-01-15 11:19 UTC, ajmaddaford commented on app/views/questionnaire.py
> +                       metadata['eq_id'], metadata['form_type'], metadata['collection_exercise_sid'])
We should use named parameters here

2018-01-15 11:19 UTC, ajmaddaford commented on app/views/questionnaire.py
> +def _check_same_survey(current_eq_id, current_form_type, current_collection_id, stored_eq_id, stored_form_type, stored_collection_id):
I think it would be clearer if we named the values with url instead of current e.g.`url_eq_id` and session instead of stored e.g. `session_eq_id`

2018-01-15 11:44 UTC, dwyeradam approved these changes

2018-01-15 12:13 UTC, ajmaddaford approved these changes

2018-01-15 12:38 UTC, merged