Store the minimum required context for answers in the answer store
ONSdigital/eq-survey-runner pull request #1428
Opened 2018-01-19 10:13 UTC by jonnyshaw89

### What is the context of this PR?
Only answer_id, group_instance and answer_instance should be needed.

Allows question to be moved between sections without breaking the existing answer store.

### How to review 
Would need to load previous version somehow (backwards compatible)

2018-01-22 10:38 UTC, shahi645 commented on app/data_model/answer_store.py
>          :param answer_id: The answer id to filter results to remove
remove/rename parameter

2018-01-26 10:41 UTC, shahi645 approved these changes
Tested and verified. Can't see any problems with code, and removal of lines of code massively outweigh added lines...big 👍

2018-01-30 09:45 UTC, ajmaddaford requested changes

2018-01-30 09:45 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +            assert not group_instance, \
I think we should drop `location` now as we'd only be using it for the `group_instance` and that can be passed as a separate parameter.

2018-01-30 09:45 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +        valid = (answer_id or value) is not None
I don't think this makes sense, shouldn't we always expect an answer_id and value?

2018-01-30 09:45 UTC, ajmaddaford commented on app/templating/schema_context.py
> +def _get_answers_in_path(schema, path):
This method is used in two places, I think it would make sense to add it to path_finder. Something like `get_answer_ids_on_routing_path`.

2018-01-30 09:45 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +    def filter_by_location(self, schema, location):
I think we should consider dropping this method and just using `filter`

2018-01-30 09:45 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +    def filter(self, answer_ids=None, group_instance=None, answer_instance=None,
Should answer_ids now be required? It doesn't make much sense to delete all answers for a given group or answer instance.

2018-02-05 08:54 UTC, ajmaddaford requested changes

2018-02-05 08:54 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +    def __init__(self, answer_id=None, value=None, group_instance=0, answer_instance=0):
We should drop the `None` default for `answer_id` and `value` to make it clear from the method signature that they aren't optional.

2018-02-05 08:54 UTC, ajmaddaford commented on app/data_model/answer_store.py
>          :param answer_id: The answer id to filter results by
answer_id is now answer_ids

2018-02-05 08:54 UTC, ajmaddaford commented on app/questionnaire/navigation.py
> +        answer_on_path = PathFinder.get_answer_ids_on_routing_path(self.schema, self.routing_path)
This variable name isn't very clear, it sounds singular and possibly boolean. It would be much clearer named something like `answer_ids_on_path`

2018-02-05 08:54 UTC, ajmaddaford commented on app/questionnaire/path_finder.py
> +            answer_on_path = self.get_answer_ids_on_routing_path(self.schema, path)
Same as previous comment.

2018-02-05 08:54 UTC, ajmaddaford commented on app/questionnaire/path_finder.py
> +        return answer_ids_in_path
For consistency we should use either `on` or `in`, not both.

2018-02-05 08:54 UTC, ajmaddaford commented on app/questionnaire/rules.py
> +def evaluate_repeat(repeat_rule, answer_store, answer_on_path):
Related to comment above, it would be clearer if `answer_on_path` was renamed `answer_ids_on_path`

2018-02-05 08:54 UTC, ajmaddaford commented on app/templating/schema_context.py
> +            if answer['answer_id'] in PathFinder.get_answer_ids_on_routing_path(schema, routing_path):
`get_answer_ids_on_routing_path` could be called outside of both loops? Or the answer_ids on the routing path could be passed in to build_schema_context removing the dependency on both schema and PathFinder.

2018-02-05 09:00 UTC, ajmaddaford commented
I couldn't test starting a survey on master and continuing on this branch as this branch doesn't have the session encryption changes from master.

2018-02-05 09:22 UTC, jonnyshaw89 commented
@ajmaddaford ill rebase it so it has those changes

2018-02-05 12:51 UTC, ajmaddaford approved these changes

2018-02-06 09:44 UTC, merged