Testing Database Reconnect
ONSdigital/eq-survey-runner pull request #1448
Opened 2018-02-07 12:36 UTC by jonnyshaw89

In Progress

2018-02-09 16:17 UTC, MIslam92 approved these changes

2018-02-12 08:37 UTC, ajmaddaford approved these changes
The Docker changes don't look related to the database changes. If they're not they should be removed from this pull request.

We should look to get the database changes in and run through the OAT scenarios in pre-prod.

2018-02-12 08:37 UTC, ajmaddaford requested changes
The Docker changes don't look related to the database changes. If they're not they should be removed from this pull request.

We should look to get the database changes in and run through the OAT scenarios in pre-prod.

2018-02-13 12:03 UTC, ajmaddaford approved these changes

2018-02-13 14:56 UTC, merged