SessionData to ignore new attributes
ONSdigital/eq-survey-runner pull request #1468
Opened 2018-02-19 15:36 UTC by jonnyshaw89

- SessionData should now be forward compatible

### What is the context of this PR?
When new variables are added to session data during deployment if a session is created with the new code but then later accessed by the old code then an error is thrown.

### How to review 
Create a session on a version of the code with new session data (https://github.com/ONSdigital/eq-survey-runner/pull/1467) then return to this branch and you should be able to resume.

2018-02-19 15:47 UTC, dwyeradam requested changes

2018-02-19 15:47 UTC, dwyeradam commented on app/data_model/session_data.py
> +    def __init__(self, tx_id, eq_id, form_type, period_str, language_code=None, survey_url=None, ru_name=None, ru_ref=None, submitted_time=None, **kwargs):
For everything other than **submitted_time** we should really remove the None defaults now. These were only needed for backward compatibility.

2018-02-19 15:47 UTC, dwyeradam commented on tests/app/data_model/test_session_store.py
> +            additional_value='some cool new value you dont know about yet'
I'll be the pedant `do not` rather than `dont`.

2018-02-19 16:19 UTC, dwyeradam requested changes

2018-02-19 16:19 UTC, dwyeradam commented on tests/app/data_model/test_session_store.py
> +            additional_value='some cool new value you do not know about yet'
We should test with multiple additional variables.

2018-02-19 16:23 UTC, dwyeradam commented on app/data_model/session_data.py
> +    def __init__(self, tx_id, eq_id, form_type, period_str, language_code, survey_url, ru_name, ru_ref, submitted_time=None, **kwargs):
`**kwargs` is failing linting. I believe `*_` is a valid alternative.

2018-02-19 16:46 UTC, dwyeradam approved these changes
Checked switching between this and **ras-integration-changes** branch and worked as expected.

2018-02-20 13:13 UTC, nealedj approved these changes

2018-02-20 13:39 UTC, merged