Improved test coverage of converter.py
ONSdigital/eq-survey-runner pull request #1477
Opened 2018-02-27 11:26 UTC by MebinAbraham

### What is the context of this PR?
#1466 removed a schema-specific test. In an effort to make sure we don't lose any test coverage, more convert tests have been added.

- Added test conversion for the following answer types:
   - radio
   - number
   - percentage
   - textarea
   - currency
   - dropdown
   - date
   - unit
   - relationship

### How to review 
1. Run `pipenv run scripts/run_tests_unit.sh`
2. Ensure that all units tests pass.
3. Ensure all the new tests in `converter.py` are correct and the structure is valid.

2018-02-27 12:09 UTC, MIslam92 approved these changes

2018-02-27 12:09 UTC, MIslam92 commented on tests/app/submitter/test_converter.py
> +                                         block_id='radio-block')]
Minor nitpick why the new line? You can keep them on the same line in the same style as the rest of the file.

2018-02-27 12:09 UTC, MIslam92 requested changes
Misclick

2018-02-27 14:25 UTC, jonnyshaw89 requested changes

2018-02-27 14:25 UTC, jonnyshaw89 commented on tests/app/submitter/test_converter.py
> +class TestConverter(AppContextTestCase):  # pylint: disable=too-many-public-methods, too-many-lines
I would potentially split this into 2 tests?
one for each data version.

2018-03-01 13:30 UTC, MebinAbraham commented
Test against master.

2018-03-02 09:21 UTC, MIslam92 approved these changes

2018-03-05 08:16 UTC, jonnyshaw89 commented
@yoganandkunche you should test that this PR doesn't change the downstream data.

2018-03-05 08:16 UTC, jonnyshaw89 approved these changes

2018-03-05 15:20 UTC, yoganandkunche approved these changes
LGTM 👍

2018-03-05 16:45 UTC, merged