Removed logic from templates
ONSdigital/eq-survey-runner pull request #1480
Opened 2018-03-05 14:37 UTC by jonnyshaw89

Constucted a view model will all information required to render the page

### What is the context of this PR?
The model passed to the templates is now a dict and contains all of the information required to render the page.
Also implemented is the ability to get to json back from any questionnaire endpoint, by only specifying in the request that the the client accepts json

### How to review 
Does everything continue to work.
When adding the accepts `application/json` header then all of the context is returned as json

2018-03-05 16:01 UTC, nealedj approved these changes
Nicely done. `request_wants_json` is a good addition - plus it made it easier to verify the context.

2018-03-06 16:50 UTC, dwyeradam requested changes

2018-03-06 16:50 UTC, dwyeradam commented on app/helpers/form_helper.py
> +        return generate_household_composition_form(schema, block_json, data), {}
Can we remove the return of the empty dict here. Also the same on line 65. Only line 46 returns values and should be made part of the form.

2018-03-08 11:11 UTC, dwyeradam approved these changes

2018-03-08 11:28 UTC, merged