Remove edit links from Answers after submission
ONSdigital/eq-survey-runner pull request #1493
Opened 2018-03-13 16:11 UTC by jonnyshaw89

### What is the context of this PR?
The edit links were appearing on the answers after submission screen

### How to review 
Do the edit links appear on the answers after submission screen? They shouldn't.

2018-03-13 16:17 UTC, dwyeradam requested changes
Change works but could we just add a line to one of the current tests to ensure there are no edit links on the view-submission page.

2018-03-13 16:24 UTC, dwyeradam commented
How about adding the following line into test_view_submission.py (line 74 perhaps)
`self.assertNotInPage('data-ga-action="Edit click"')`

2018-03-13 16:37 UTC, dwyeradam approved these changes

2018-03-14 08:28 UTC, nealedj approved these changes

2018-03-14 08:28 UTC, nealedj commented
@jonnyshaw89 okay to rebase please?

2018-03-14 10:10 UTC, merged