Empty Total Routing RSI/MCI
ONSdigital/eq-survey-runner pull request #1511
Opened 2018-03-19 11:24 UTC by dwyeradam

Zero or empty routing for schemas:
1_0102, 1_0112, 1_0203, 1_0205, 1_0213 and 1_0215

2018-03-19 11:36 UTC, jonnyshaw89 approved these changes

2018-03-19 11:40 UTC, jonnyshaw89 requested changes

2018-03-19 11:40 UTC, jonnyshaw89 commented on data/en/1_0112.json
> +                                "block": "changes-in-employees"
This should route to `employees-breakdown`

2018-03-19 11:42 UTC, jonnyshaw89 commented on data/en/1_0112.json
> +                                "block": "changes-in-employees"
Im wrong. Ignore me

2018-03-19 11:42 UTC, jonnyshaw89 approved these changes

2018-03-20 07:52 UTC, shahi645 requested changes

2018-03-20 07:52 UTC, shahi645 commented on tests/functional/spec/features/default_value/default_value.spec.js
> +describe('@watch Feature: Default Value', function() {
Remove `@watch`. Also small nit pick, but for our functional specs don't we use hyphens not underscores.

2018-03-20 07:55 UTC, shahi645 commented
We shouldn't merge this until SDX changes are merged in, otherwise they will just get transactions nacking. 
https://github.com/ONSdigital/sdx-transform-cs/pull/147

2018-03-20 08:57 UTC, jonnyshaw89 commented
@shahi645 not our problem.

2018-03-20 08:59 UTC, shahi645 commented
yeah but SDC is our service for the sake of not causing them an issue im sure we can hold off merging for like a day

2018-03-20 09:22 UTC, jonnyshaw89 commented
@shahi645 if we were going down that road then we shouldn't have merged this PR
https://github.com/ONSdigital/eq-survey-runner/pull/1512

If we are going to get these deployed for tomorrow then we need to get them in and tested asap

2018-03-20 09:26 UTC, shahi645 commented
i completely agree, but we cant test e2e without SDX changes, we can still test locally

2018-03-20 10:11 UTC, shahi645 approved these changes

2018-03-20 10:40 UTC, merged