Eq 1945 social alpha
ONSdigital/eq-survey-runner pull request #1531
Opened 2018-04-03 13:00 UTC by davecharles

### What is the context of this PR?
Author a first cut survey schema for Labour Force Survey.  This PR adds a new schema for LFS to `data/en`, there are no code changes.

Only the first path of the LFM design has been implemented (Socio Demographic), the remainder (Labour Market) will be implemented in a subsequent iteration.  Issues and omissions have been documented on the related [Trello card](https://trello.com/c/eBUSUODf).

### How to review 
- Check schema is valid using the schema validator i.e:
   `pipenv run ./scripts/test_schemas.sh data/en/labour_force.json`
- Run the survey [with this url](https://preprod-surveys-launch.eq.ons.digital/quick-launch?url=https://raw.githubusercontent.com/ONSdigital/eq-survey-runner/eq-1945-social-alpha/data/en/labour_force.json).

2018-04-03 16:14 UTC, dwyeradam commented
A `yarn format` should fix your linting issue.

2018-04-05 13:29 UTC, MIslam92 requested changes
Just some observations in the comments

2018-04-05 13:29 UTC, MIslam92 commented on data/en/labour_force.json
> +                                            "label": "Don&apos;t know",
Should we be allowing the respondent to give a date then answer "I don't know"/"Prefer not to say " at this point? I know these are essentially two different answers and the mutually exclusive answers might overcome this.

2018-04-05 13:29 UTC, MIslam92 commented on data/en/labour_force.json
> +                        "id": "household-relationships",
Should this not route to asking the relationship question when the household members are equal to two as well? It takes this into consideration in the JSON but doesn't match what the docs are saying in the card?

2018-04-06 14:00 UTC, davecharles commented on data/en/labour_force.json
> +                                            "label": "Don&apos;t know",
Agreed with @charlotte-hirst to remove the DK/PNTS radios for now.

2018-04-06 14:03 UTC, davecharles commented on data/en/labour_force.json
> +                        "id": "household-relationships",
The routing design is based on a separate "first page" to get info on first two household occupants and their relationship.  We couldn't do this with the existing household-composition mechanics from census so @charlotte-hirst agreed we could duck this in the alpha.

2018-04-10 12:13 UTC, MebinAbraham reviewed
Shouldn't this section be selected in the navigation?
![image](https://user-images.githubusercontent.com/35296336/38557062-ba0677e2-3cc3-11e8-9f10-5e98e0e3ac48.png)

2018-04-10 13:58 UTC, MebinAbraham requested changes
If I click `Continue` on the proxy check question. I get the following.
![image](https://user-images.githubusercontent.com/35296336/38561225-606ad3b6-3ccf-11e8-9114-55c95b2e20ce.png)

2018-04-10 14:11 UTC, MebinAbraham requested changes
Ignore this. :point_down:

2018-04-10 14:14 UTC, shahi645 commented
@MebinAbraham The above is because there is piping in the answer value

2018-04-11 07:13 UTC, davecharles commented
I can get around this by rephrasing the option labels but it seems to be an issue with functionality (i.e. this should work). @shahi645's sounds like this is a known issue?

2018-04-11 08:21 UTC, MebinAbraham approved these changes
Need to raise a card for the issue above, but apart from that, looks good.

2018-04-11 08:33 UTC, nealedj commented
Note that https://github.com/ONSdigital/eq-survey-runner/pull/1533 changes the way that values are referenced when piping. If it gets merged first then this PR will need updating -> or vice versa.

2018-04-11 09:07 UTC, davecharles commented
@MebinAbraham raised #1538 [trello card here](https://trello.com/c/Eka2Udyd)

2018-04-11 10:33 UTC, MIslam92 approved these changes

2018-04-11 12:24 UTC, shahi645 commented
@davecharles Rebase and Squash and we can merge this one?

2018-04-11 15:29 UTC, merged