added new survey mbs 0106
ONSdigital/eq-survey-runner pull request #1569
Opened 2018-04-27 14:31 UTC by nealedj

### What is the context of this PR?
New survey on for MBS 0106 added to SR

### How to review 
Check content on slides match: 
https://trello.com/c/VGKHp3ZQ/2026-turnover-mbs-form-0106-m

2018-04-30 09:00 UTC, shahi645 requested changes
only a couple of minor content changes

2018-04-30 09:00 UTC, shahi645 commented on data/en/mbs_0106.json
> +                                    "question": "Turnover",
Should be `Total turnover`

2018-04-30 09:00 UTC, shahi645 commented on data/en/mbs_0106.json
> +                                                "payment for work in progress",
`payments`

2018-04-30 09:00 UTC, shahi645 commented on data/en/mbs_0106.json
> +                                            "payment for work in progress",
payments

2018-04-30 13:37 UTC, shahi645 approved these changes

2018-05-01 11:46 UTC, dwyeradam requested changes
Just little niggles.

2018-05-01 11:46 UTC, dwyeradam commented on data/en/mbs_0106.json
> +                                    "question": "Changes in turnover",
Changes in `total` turnover
Slides incorrect.

2018-05-01 11:46 UTC, dwyeradam commented on data/en/mbs_0106.json
> +                                "label": "Turnover excluding VAT",
`Total` turnover excluding VAT

2018-05-01 12:01 UTC, dwyeradam approved these changes

2018-05-01 12:05 UTC, dwyeradam commented
@MIslam92 Squishy squashy.

2018-05-01 13:53 UTC, merged