NI theme modification
ONSdigital/eq-survey-runner pull request #1573
Opened 2018-05-02 16:13 UTC by MebinAbraham

Increased the NI logo dimensions as it was a bit too small.
Also added the ONS logo to the footer.

### How to review?
- Test with `mbs_0204` schema.
- You may need to run `yarn compile`

NI theme looks correct:
1. Header logo should be `280px`
2. ONS logo should be present in the footer.

2018-05-03 09:27 UTC, AndrewTorrance approved these changes
Difficult to review as there is no definitive acceptance criteria . All I can say is that the images are present , and in the correct position. Footer needs updating later, move images to a cdn comes later

2018-05-03 09:33 UTC, armstrongb commented
The alt text on the logo in the header should be amended. It should have the following alt attribute value: **"Department of Finance | An Roinn Airgeadais"**

2018-05-03 09:34 UTC, armstrongb requested changes
Header logo alt text amend required.

2018-05-03 09:44 UTC, MebinAbraham commented
@armstrongb Sorted alt tag

2018-05-03 14:54 UTC, armstrongb approved these changes

2018-05-04 10:01 UTC, bennpearson requested changes

2018-05-04 10:01 UTC, bennpearson commented on app/assets/styles/themes/northernireland/theme.scss
> +}
Move this to ` app/assets/styles/themes/northernireland/components/_footer.scss` then imported here with `@import "components/footer"`

2018-05-04 10:01 UTC, bennpearson commented on app/assets/styles/themes/northernireland/theme.scss
> +}
Move this to ` app/assets/styles/themes/northernireland/components/_logo.scss` then imported here with `@import "components/logo"`

2018-05-04 10:22 UTC, bennpearson approved these changes

2018-05-04 12:45 UTC, merged