Add min and max jinja filters
ONSdigital/eq-survey-runner pull request #1599
Opened 2018-05-17 22:48 UTC by davecharles

### What is the context of this PR?
Social Demographic require a page in LFS to render the most recent of two date responses.  This PR implements two general purpose filters `max_value` and `min_value` that fulfil the SD requirement as well as providing a useful feature for other use cases.  Currently blocking #1581.

### How to review 
- Review code in `app/jinja_filters.py` and `app/templating/template_renderer.py`.
- Review and run related tests in `tests/app/templating/test_template_renderer.py` and `tests/app/test_jinja_filters.py`.
- Apply the following patch to `labour_force.json` in `master` and run the survey (rename to `.diff`):
    [lfs.diff](https://github.com/ONSdigital/eq-survey-runner/files/2014939/lfs.diff.txt)

2018-05-18 06:42 UTC, shahi645 requested changes
Again i think this would definitely benefit if it was in a test_schema of sought accompanied by some functional tests, @nealedj what would your thinking be here?

2018-05-18 06:53 UTC, shahi645 commented on app/jinja_filters.py
> +        raise Exception(msg)
@davecharles Can we pass in the min or max here then have this all in same method, as the code is very similar

2018-05-18 08:20 UTC, nealedj commented on app/jinja_filters.py
> +        raise Exception(msg)
In this case I'd leave them separate for readability.

2018-05-18 08:24 UTC, nealedj commented
@shahi645 In this case I don't think that functional tests provide any value above what unit tests provide.

A functional test could test the combination of the filter and the jinja renderer. But the unit test for `TemplateRenderer` already covers that. Beyond that I can't see what extra scenarios are added.

I don't want to start adding functional tests for every change.

Martin Fowler puts it better:

> I always argue that high-level tests are there as a second line of test defence. If you get a failure in a high level test, not just do you have a bug in your functional code, you also have a missing or incorrect unit test. Thus I advise that before fixing a bug exposed by a high level test, you should replicate the bug with a unit test. Then the unit test ensures the bug stays dead.

https://martinfowler.com/bliki/TestPyramid.html

2018-05-18 08:38 UTC, nealedj approved these changes

2018-05-18 09:16 UTC, dwyeradam commented
@nealedj a date for the diary as I agree with @shahi645. I agree we may don't want to add a load of functional test but I would like to see an implementation in a test schema otherwise we're not testing the implementation of this filter. Also our test schemas make it simpler to see how we would implement this when needed in a real survey. Maybe just add to an existing test_dates.json etc.

2018-05-18 09:20 UTC, nealedj commented
Yep just chatted about this a little more. There's value in exposing the new filters in at least one test schema. Otherwise there's no way to test it (even manually) - and we don't want to rely on live surveys to be the sole consumer of functionality.

@davecharles would you mind adding a use of the filter to the test_dates, test_numbers and test_textfield schemas?

2018-05-21 06:45 UTC, shahi645 approved these changes
LGTM. Quick comment for line: https://github.com/ONSdigital/eq-survey-runner/pull/1599/commits/6150e4e4d49126f892af8441f492bed3dc84f429#diff-ed4511c7a48d60265a6bfa720e219c00R15
Unrelated to this work, but as we are editing should probably add some guidance like; 'Please enter a minimum value between 0 and 1000 and a maximum greater than 1001'.

2018-05-21 06:50 UTC, davecharles commented
@shahi645 good point - will add to backlog

2018-05-21 07:05 UTC, shahi645 commented
@davecharles was thinking as its just a line to a schema adding it here, but i dont mind either way, just a suggestion. Can merge this in now and come back to it later, add a ticket that covers all test schemas?

2018-05-21 07:29 UTC, merged