Renaming LFS survey to LMS survey
ONSdigital/eq-survey-runner pull request #1609
Opened 2018-05-30 14:31 UTC by warrenbailey

### What is the context of this PR?
Renaming LFS survey to LMS and updating EQ ids and form types to match SDX

### How to review 
1. Run the survey via go launch a survey

2018-05-30 16:24 UTC, davecharles requested changes

2018-05-30 16:24 UTC, davecharles commented on data/en/lms_1.json
> -}
Need to apply a `yarn format`

2018-05-30 16:24 UTC, davecharles commented on data/en/lms_1.json
> -}
The rest LGTM but need to make sure we also update go-launcher.

2018-05-31 10:47 UTC, warrenbailey commented
https://github.com/ONSdigital/go-launch-a-survey/pull/87

2018-05-31 10:50 UTC, nealedj approved these changes

2018-05-31 11:47 UTC, davecharles approved these changes

2018-05-31 12:55 UTC, merged