Fix validation for trad_as or ru_name
ONSdigital/eq-survey-runner pull request #1614
Opened 2018-06-04 12:14 UTC by MebinAbraham

### What is the context of this PR?
Fixes [1613](https://github.com/ONSdigital/eq-survey-runner/issues/1613)

2018-06-04 12:49 UTC, shahi645 approved these changes

2018-06-04 14:22 UTC, dwyeradam requested changes

2018-06-04 14:22 UTC, dwyeradam commented on app/storage/metadata_parser.py
> +            valid = bool(metadata.get('trad_as') or metadata.get('ru_name'))
Looks good but we should probably have a test that returns false.

2018-06-04 14:24 UTC, shahi645 commented on app/storage/metadata_parser.py
> +            valid = bool(metadata.get('trad_as') or metadata.get('ru_name'))
good point

2018-06-04 15:25 UTC, MebinAbraham commented on app/storage/metadata_parser.py
> +            valid = bool(metadata.get('trad_as') or metadata.get('ru_name'))
Sorted 👍

2018-06-05 08:58 UTC, dwyeradam approved these changes

2018-06-05 08:58 UTC, merged