RU Name mandatory in metadata for Default/NI Themes
ONSdigital/eq-survey-runner pull request #1615
Opened 2018-06-04 15:36 UTC by dwyeradam

### What is the context of this PR?
The introduction page expects RU Name to be present for `default` and `northernireland` themes. 

This PR adds ru_name as required metadata in the required schemas.

2018-06-04 15:56 UTC, dwyeradam commented on scripts/test_schemas.sh
> -    validator="$(docker run -d -p 5001:5000 onsdigital/eq-schema-validator)"
Will need reverting once [validator PR](https://github.com/ONSdigital/eq-schema-validator/pull/55) has been approved. Both should go in together.

2018-06-05 08:10 UTC, MebinAbraham requested changes
Shouldn't need this [line](https://github.com/ONSdigital/eq-survey-runner/blob/eq-2164-mandatory-metadata-based-on-theme/app/templating/schema_context.py#L58) anymore. As it would be created on line 51 for the schemas that require it.

2018-06-05 10:06 UTC, MebinAbraham approved these changes
👍

2018-06-05 10:21 UTC, shahi645 approved these changes

2018-06-05 15:09 UTC, merged