Fix displaying of submitted response copy on summary page
ONSdigital/eq-survey-runner pull request #1656
Opened 2018-06-28 15:19 UTC by kierenbeckett

### What is the context of this PR?
When viewing the summary page of a schema with submitted responses, there's supposed to be a bit of copy telling the user they can print/copy their answers

### How to review 
In `dev_settings.sh` set `EQ_DYNAMODB_ENABLED=True`. Run `test_view_submitted_response.json` and go through to the summary, at the bottom you should see the copy 'You will have the opportunity...'.  Try a different survey and see that the copy isn't there.

2018-06-28 16:40 UTC, dwyeradam approved these changes

2018-06-29 13:00 UTC, nealedj requested changes
Could we add an assertion to the "Submitted Responses" functional test to make sure this content is getting rendered?

2018-07-02 09:39 UTC, nealedj approved these changes

2018-07-02 10:18 UTC, dwyeradam commented
@kierenbeckett once the conflicts are resolved this can be squashed and merged.

2018-07-02 11:35 UTC, merged