Transformed MCI changes
ONSdigital/eq-survey-runner pull request #1659
Opened 2018-07-02 11:57 UTC by nealedj

### What is the context of this PR?
Content changes to transformed MCI survey prototype as per slides.

### How to review 
Launch survey and compare against slides.

2018-07-02 14:17 UTC, dwyeradam commented on data/en/mci_transformation.json
> +                        "title": "Of the {{answers['retail-sales-answer']|format_currency}} retail sales, how much were your <em>food sales, drink and tobacco sales</em>?",
Should be just food. Not food `sales`.

2018-07-02 14:17 UTC, dwyeradam commented on data/en/mci_transformation.json
> +                                        "tobacco products and smokers’ requisites (including e-cigarettes)"
These changes must also be matched on the Introduction page.

2018-07-02 14:32 UTC, kierenbeckett approved these changes
Besides Adam's comments LGTM

2018-07-02 14:34 UTC, dwyeradam requested changes
The include/exclude changes must also be matched on the Introduction page's Information you need. See slide 4.

2018-07-02 14:36 UTC, nealedj commented
Thanks @dwyeradam - ready for re-review

2018-07-02 14:46 UTC, dwyeradam commented
@nealedj, i'll review now. I'm guessing it's correct so do you want to squash now and save 20 mins.

2018-07-02 15:00 UTC, dwyeradam submitted a review, later dismissed
Missed one. Also just my OCD but it should be a lower case T for Turnover in Total turnover on the Information you need. I wouldn't have said if it wasn't for the other change. I also think it should be lower case S for Retail Sales but inconsistent.

2018-07-02 15:00 UTC, dwyeradam commented on data/en/mci_transformation.json
> +                                        "travel cases and luggage"
Talked too soon. Missing `Exclude` list from Clothing and footwear sales.

2018-07-02 15:01 UTC, dwyeradam requested changes
See above.

2018-07-03 10:34 UTC, MebinAbraham reviewed
Even though it isn't mentioned on the card, to match the slides, `retail sales` should have `em` tags for the following. More of a while you are here...

https://github.com/ONSdigital/eq-survey-runner/blob/d1be5e9c8df7daad5b619c106124b2e467adeffc/data/en/mci_transformation.json#L760

https://github.com/ONSdigital/eq-survey-runner/blob/d1be5e9c8df7daad5b619c106124b2e467adeffc/data/en/mci_transformation.json#L814

https://github.com/ONSdigital/eq-survey-runner/blob/d1be5e9c8df7daad5b619c106124b2e467adeffc/data/en/mci_transformation.json#L865

2018-07-03 11:19 UTC, nealedj commented
@dwyeradam @MebinAbraham good catches. Should all be addressed now.

2018-07-03 11:57 UTC, MebinAbraham commented
@nealedj Needs a `yarn format`

2018-07-03 12:06 UTC, dwyeradam approved these changes
Ready to squash and merge. I think you now need to add a line for linting.

2018-07-03 12:10 UTC, MebinAbraham approved these changes
👍

2018-07-03 12:33 UTC, merged