Add set condition and unit test
ONSdigital/eq-survey-runner pull request #1663
Opened 2018-07-03 15:39 UTC by insacuri

### What is the context of this PR?
The inverse to 'not set' didn't exist so this creates it so that future routing can check 'did you put anything in the box'.

### How to review 
There aren't any schemas that use this currently so it's just a code quality and unit test check

2018-07-04 08:46 UTC, nealedj approved these changes

2018-07-04 08:59 UTC, nealedj requested changes
I think we're missing a test schema here.

We have test schemas for various routing rules but nothing for `not set` (it's used in other schemas but they aren't explicitly testing that).

Since this is a feature we need to have it in at least one test schema to verify the functionality.

Could you add `test_routing_set.json` and `test_routing_not_set.json` schemas along with basic functional tests for them?

2018-07-04 10:52 UTC, MebinAbraham commented
Apart from David's comment, looks good 👍

2018-07-04 11:01 UTC, MebinAbraham requested changes
You will also need to make a validator change to allow `set` as one of the options for `condition` before this can be merged.

https://github.com/ONSdigital/eq-schema-validator/blob/e25aa3a06a693374e1a5a2d37c9d7fd5b8468786/schemas/common_definitions.json#L120

2018-07-05 15:23 UTC, MebinAbraham approved these changes
Validator PR merged.

2018-07-10 15:19 UTC, dwyeradam commented on README.md
> +
👍

2018-07-11 09:15 UTC, nealedj approved these changes
Nicely done. Helpful README addition in there too 👍

2018-07-11 09:47 UTC, merged