Refactor metadata structure
ONSdigital/eq-survey-runner pull request #1697
Opened 2018-07-25 14:33 UTC by jonnyshaw89

### What is the context of this PR?
Changes the allowed structure of metadata to 
```
"metadata": [
    {
        "name": "period_id",
        "validator": "string"
    },
```
from
```
"metadata": {
    "period_id": {
        "validator": "string"
    },
```

### How to review 
This branch points to validator change in https://github.com/ONSdigital/eq-schema-validator/pull/70

2018-07-25 15:40 UTC, benhowes commented
@jonnyshaw89 do all the tests pass locally for you? When I checkout this branch locally I see a lot of test fails relating to `sdc.crypto.exceptions.InvalidTokenException: Missing key/value for tx_id`

2018-07-25 15:45 UTC, jonnyshaw89 commented
@benhowes they did last time i ran them

2018-07-25 15:53 UTC, jonnyshaw89 commented
@benhowes its because i removed the `tx_id` generator.
i'm updating them now

2018-07-26 08:11 UTC, MebinAbraham reviewed
Personal opinion but I think these should have been 2 PRs, one to change the metadata structure and one to change the JSON structure.

Also FYI some schema still using the old metadata format.

2018-07-26 08:17 UTC, jonnyshaw89 commented
@MebinAbraham it would take me hours and hours to go through each schema and only change the metadata.

2018-07-26 08:22 UTC, MebinAbraham commented
@jonnyshaw89 Fair enough, didn't use a script/validator?

2018-07-26 10:01 UTC, kierenbeckett requested changes
Perhaps rather than attempt to review the changes to the schemas, you could paste the script you used to reformat them?

2018-07-26 10:01 UTC, kierenbeckett commented on data/cy/test_language.json
> -    "mime_type": "application/json/ons/eq",
Ideally we'd keep these at the top of each schema

2018-07-26 10:03 UTC, kierenbeckett commented
You could change the JSON structure first, then change the metadata?

2018-07-26 10:10 UTC, jonnyshaw89 commented
@kierenbeckett the script to format is here https://github.com/ONSdigital/eq-survey-runner/pull/1697/files#diff-ba210a9157252cc983268fdc3aa3ed52R194

2018-07-26 10:14 UTC, kierenbeckett submitted a review, later dismissed

2018-07-26 10:14 UTC, kierenbeckett commented on gulpfile.babel.js
> +    .pipe(sortJSON({ space: 2 }))
Can we update `.editorconfig` to match

2018-07-26 10:16 UTC, kierenbeckett commented
How did you reformat the metadata?

2018-07-26 10:32 UTC, jonnyshaw89 commented
@kierenbeckett i knocked together a script. does that need to be part of this PR?

2018-07-26 10:33 UTC, MebinAbraham reviewed
Validator is only checking `data/en` atm, we should change sometime.

`data/cy/test_language.json`
```
"metadata": {
        "period_id": {
            "validator": "string"
        },
        "ru_name": {
            "validator": "string"
        },
        "user_id": {
            "validator": "string"
        }
    },
```

2018-07-26 10:39 UTC, kierenbeckett commented
Doesn't need to be in the PR, could you paste it in a comment/gist?  I can't realistically review the schema diffs but I could at least check the method used to rewrite them.

2018-07-26 10:53 UTC, jonnyshaw89 commented
@kierenbeckett here is the script used
https://gist.github.com/jonnyshaw89/803b9a95c48a94468ca9f10a5b45cba5

2018-07-26 15:48 UTC, kierenbeckett requested changes
Would be good if you can find a way to specify the ordering or the fields in the JSON or failing that at least preserve the existing ordering.  Otherwise LGTM.

2018-07-30 08:25 UTC, kierenbeckett approved these changes

2018-07-30 10:58 UTC, insacuri approved these changes
Code changes look reasonable, linting and tests pass to LGTM

2018-07-30 14:19 UTC, merged