Header/Footer - Pattern Library V1.5.0
ONSdigital/eq-survey-runner pull request #1710
Opened 2018-07-31 16:09 UTC by boxadesign

### What is the context of this PR?

####Header
* Updated to the latest design from Pattern Library release v1.5.0.
* Updated NI and Census theme files
* Removed header2.html file and references and updated to use just header.html

####Footer
* Updated to the latest design from Pattern Library release v1.5.0.
* NI and Census theme footer2.html file has not been updated with latest markup. On `master` both themes use the main/standard footer and not the footer2.html files in their respective theme folders so this has remained the same.

####Icons
* Guidance and details components have been updated so that they reference the new icon approach and display correctly.

### How to review 
Check the above components across business, social, census and NI surveys. 

### Checklist

* [ ] Header displays correctly across all themes/survey types.
* [ ] Footer displays correctly across all themes/survey types.
* [ ] Guidance and details components display and function correctly.
* [ ] Code clean up has removed the correct files/code.

2018-08-06 15:19 UTC, insacuri requested changes
random spaces in templates needs removing

2018-08-06 15:19 UTC, insacuri commented on app/templates/introduction.html
> +{% block subheader %}
Need to remove all the random space from all the re-added feedback sections

2018-08-06 15:20 UTC, insacuri commented on app/templates/layouts/_base.html
> +  <body>
extra space here

2018-08-07 09:29 UTC, insacuri commented on app/assets/styles/themes/northernireland/components/_logo.scss
> +
very minor, but does that extra line need to be there?

2018-08-07 09:29 UTC, insacuri commented on app/templates/layouts/_questionnaire.html
> +
same with this, does it need to be added?

2018-08-07 09:31 UTC, insacuri approved these changes
Other then those 2 minor comments (that aren't critical) looks good

2018-08-07 11:30 UTC, MebinAbraham reviewed
We shouldn't merge this until all breaking changes relating to runner are addressed (accordians/radio buttons etc) and ready to go in.

Also padding issue:
<img width="253" alt="screen shot 2018-08-07 at 12 28 23" src="https://user-images.githubusercontent.com/35296336/43773407-87329954-9a3d-11e8-84ef-85234d0df04f.png">

2018-08-07 12:37 UTC, insacuri requested changes
Didn't notice the padding change, needs to be fixed first!

2018-08-07 12:44 UTC, boxadesign commented
@MebinAbraham @insacuri Fair enough. This is fixed on another branch but I'll add in the necessary classes here.

2018-08-07 14:21 UTC, MebinAbraham commented
For other's reference, it was summary pages.
👍

2018-08-07 14:37 UTC, benhowes commented
I see this on questions with radio button answers with the latest commit (since we're on buttons in this thread): 

![screenshot from 2018-08-07 15-34-46](https://user-images.githubusercontent.com/471170/43782556-8aec4882-9a57-11e8-933e-88aa5e4639ae.png)

2018-08-07 15:24 UTC, boxadesign commented
@benhowes As discussed, unable to replicate locally.

2018-08-07 15:35 UTC, benhowes commented
@boxadesign Seems that it was caching - I've not been able to see it again after force refreshing!

2018-08-08 08:45 UTC, benhowes commented
Looks great! I haven't found anything to compare the census headers against though

2018-08-08 10:32 UTC, benhowes commented
Appears to resolve https://github.com/ONSdigital/eq-survey-runner/issues/1505 too, so that's a bonus :)

2018-08-08 11:21 UTC, boxadesign commented
@benhowes I have a PR for #1103 which will be approved after lunch. I'll push a new release of the patter library (v1.5.1) and update runner.

2018-08-09 08:34 UTC, boxadesign commented
I have updated with v1.5.1 of the pattern library which fixes the text rendering issue of FF.

2018-08-10 12:36 UTC, insacuri commented
Did anyone else have any trouble with the javascript on the page?  I'm running it using eq-compose and the accordion bits on the introduction pages aren't working and throwing:
`bundle.min.js:10266 Uncaught TypeError: Cannot read property 'getAttribute' of undefined` when I click on the link.

2018-08-10 12:47 UTC, boxadesign commented
@insacuri This is because the mark up for the accordion is incorrect for the latest pattern library release. The correct mark up has been added for this branch - > https://github.com/ONSdigital/eq-survey-runner/pull/1720

2018-08-10 13:04 UTC, insacuri approved these changes
Tested 5 different surveys and everything looks as I would expect

2018-08-13 06:54 UTC, dcdarrell9 approved these changes

2018-08-13 07:31 UTC, insacuri commented
Just added do not merge label until the matching work in RAS has been completed.

2018-08-22 09:49 UTC, MebinAbraham requested changes
No padding bottom for button?

***Before:***
<img width="592" alt="screen shot 2018-08-22 at 10 44 34" src="https://user-images.githubusercontent.com/35296336/44456444-72b90280-a5f8-11e8-9a91-0f40e3311aec.png">
***After:***
<img width="596" alt="screen shot 2018-08-22 at 10 44 24" src="https://user-images.githubusercontent.com/35296336/44456445-72b90280-a5f8-11e8-9b36-df0ee9572bd9.png">

This is on the screen after submission.

2018-08-22 10:36 UTC, MebinAbraham commented on app/templates/partials/questions/repeatinganswer.html
>        <span class="u-vh">. Selecting this will add a new set of fields to enter another person</span>
Not related to this PR. We need to mark all static content like this for translation. Feel free mark like the above or leave it.

2018-08-30 11:43 UTC, jonnyshaw89 commented
@MebinAbraham are you still blocking this?

2018-08-30 11:52 UTC, MebinAbraham approved these changes

2018-08-30 12:11 UTC, MebinAbraham requested changes
Actually, it turns out the `Print this page` buttons on view submission no longer works as expected.

2018-08-30 12:38 UTC, MebinAbraham commented
I've added the change to make the print button. Check it does work in fact work.

2018-08-30 12:46 UTC, MebinAbraham commented
Also updated the translation file.

2018-08-30 13:04 UTC, MebinAbraham commented
@boxadesign Just seen you haven't updated the NI theme files. I am pretty sure that you do need to update this. They ***are*** using the footer files within the respective theme files, not the main directory.

2018-09-04 08:29 UTC, MebinAbraham commented on app/templates/layouts/_base.html
> +        {% endblock %}
This empty line can be removed.

2018-09-04 13:03 UTC, boxadesign commented on app/templates/layouts/_base.html
> +        {% endblock %}
Done

2018-09-04 13:03 UTC, boxadesign commented
@MebinAbraham I have added in the theme footers and also added the transactional variant of the footer across all themes.

2018-09-04 14:17 UTC, MebinAbraham commented
@boxadesign I can't see the new changes?

2018-09-04 14:49 UTC, boxadesign commented
@MebinAbraham Should be good to go now.

2018-09-04 14:59 UTC, MebinAbraham approved these changes
https://github.com/ONSdigital/eq-survey-runner/blob/3652978f03dbbbe7589f8fd42d6fe7eaccb4eedb/app/assets/styles/partials/components/_footer2.scss

Is everything from file above still needed?. It references `footer2`?

The translations `messages.pot` needs updating also.

2018-09-04 15:14 UTC, MebinAbraham commented on app/templates/layouts/_base.html
> +        {% endblock %}
Still there.

2018-09-04 15:24 UTC, boxadesign commented
@MebinAbraham I have removed that file at it wasn't being used anywhere.

2018-09-05 07:33 UTC, MebinAbraham reviewed
@boxadesign Quick change. Not sure if you are aware but the Star Wars theme doesn't display correctly, we do not care much for this theme but it seems to be just because of reference error.

For Star Wars, the `header.html` is actually called `topbar.html` hence the broken layout. Can you rename this to `header.html` which fixes the issue.

2018-09-05 07:41 UTC, MebinAbraham commented on app/templates/partials/question-definition.html
> +            data-ga-category="Help">{{ definition.title }} <span class="u-vh js-details-label">Click to expand.</span></a>
`Click to expand` needs to be marked for translation like before. Need to update `messages.pot` after.

2018-09-05 07:46 UTC, MebinAbraham requested changes
Just those 2 changes to make. Can also squash this when you push as everything seems to be as expected 👍

2018-09-05 09:41 UTC, boxadesign commented
@MebinAbraham Those changes are now in to check

2018-09-05 09:48 UTC, MebinAbraham commented on app/templates/partials/question-definition.html
> +            data-ga-category="Help">{{ definition.title }} <span class="u-vh js-details-label">{{ _("Click to expand") }}</span></a>
Very small but need the full stop?

2018-09-05 10:19 UTC, MebinAbraham commented on app/themes/starwars/templates/layouts/_base.html
> +
Sorry to be a pain, can we remove these empty lines.
Also if you add `<!-- Theme selected: Star Wars -->` then the failing test will pass.

2018-09-05 11:20 UTC, MebinAbraham approved these changes

2018-09-05 15:16 UTC, merged