Remove mandatory variant_flags
ONSdigital/eq-survey-runner pull request #1715
Opened 2018-08-02 09:56 UTC by benhowes

### What is the context of this PR?
Related to https://github.com/ONSdigital/ons-schema-definitions/pull/32#discussion_r207161581

`variant_flags` is being checked for in the metadata parser, but it's never used in the code.

### How to review 
Nothing should break. Run some surveys from the launcher.

2018-08-02 10:03 UTC, jonnyshaw89 commented
Its used in `census_household.json` `variant_flags.sexual_identity` which should be changed to just `sexual_identity`

2018-08-02 10:18 UTC, benhowes commented
@jonnyshaw89 It's used in 2 other surveys too, however I this was intended to be a change which just means that it's no longer mandatory metadata? `variant_flags` does appear in the `metadata` key for each survey it's used in.

2018-08-02 10:47 UTC, MebinAbraham commented
If any `variant_flags` are used, it should be defined, ie https://github.com/ONSdigital/eq-survey-runner/blob/06cf7215f9a6799a6ffb20a9e9611e1fc0e0194d/data/en/census_household.json#L13-L25

2018-08-02 15:04 UTC, jonnyshaw89 requested changes

2018-08-02 15:04 UTC, jonnyshaw89 commented on app/storage/metadata_parser.py
> +                VALIDATORS[metadata_field['validator']](claim)
👍

2018-08-02 15:04 UTC, jonnyshaw89 commented on app/storage/metadata_parser.py
> +        logger.error('Unable to parse metadata for key `{}`'.format(name), exc_info=error)
We should maintain structured logging format
`logger.error('Unable to parse metadata', key=name, exc_info=error)`

2018-08-02 15:04 UTC, jonnyshaw89 commented on data/en/census_household.json
> +        "validator": "boolean"
👍

2018-08-02 15:04 UTC, jonnyshaw89 commented on scripts/test_schemas.sh
> +    validator="$(docker run -d -p 5001:5000 onsdigital/eq-schema-validator:eq-2224-update-metadata-requirements)"
remember to switch back

2018-08-03 08:50 UTC, dcdarrell9 commented
Launching census_household / census_individual breaks for me...
@jonnyshaw89 is working on refactoring the go-launch, but this is where it's being set
https://github.com/ONSdigital/go-launch-a-survey/blob/1914c3d4d6c61b5346c2510018ed2f303d759746/authentication/auth.go#L136

2018-08-03 11:51 UTC, jonnyshaw89 approved these changes

2018-08-03 12:18 UTC, dcdarrell9 approved these changes

2018-08-03 12:20 UTC, dwyeradam approved these changes
Worthwhile PR with recent metadata changes. Ready to squash. I'd be happy to merge even though current Census schemas are affected.

2018-08-03 14:02 UTC, merged