Support group_instance_id on skip conditions for groups
ONSdigital/eq-survey-runner pull request #1750
Opened 2018-08-28 15:22 UTC by jonnyshaw89

### What is the context of this PR?
Skip conditions are now supported in repeating groups to conditionally not show one of the repeats.

### How to review 
launch schema `test_routing_on_answer_from_driving_repeating_group.json` and observe that when answering that you do not live here then you are not included in the repeating group being asked their gender.

2018-08-30 09:43 UTC, dcdarrell9 commented
![screen shot 2018-08-30 at 10 40 01](https://user-images.githubusercontent.com/16637283/44843848-3a8d7180-ac41-11e8-8a66-ed616a88eec4.png)
I answered for 5 people and looks like it's cutting off past 2 and not displaying name correctly in the `What is 's sex?` question

2018-08-30 12:33 UTC, insacuri commented on app/questionnaire/group_dependencies.py
> +                    # Only when the group is a repeat
I don't think the comment is helpful as there isn't a conditional around the next line.  Either expand this comment to give more information or remove it.

2018-08-30 12:39 UTC, insacuri commented on app/questionnaire/rules.py
> +        repeat_indexex = []
Is this name intentional?

2018-08-30 14:27 UTC, insacuri requested changes
Other than my 2 fairly small comments, looks good to me

2018-08-30 14:38 UTC, jonnyshaw89 commented
@dcdarrell9 that is another piece of work that @dwyeradam is working on.

2018-08-30 14:39 UTC, jonnyshaw89 commented on app/questionnaire/rules.py
> +        repeat_indexex = []
I just cant spell

2018-08-30 14:56 UTC, insacuri approved these changes

2018-08-31 10:10 UTC, bitdivision approved these changes
Minor pedantic docstring comments. Code looks good.

Will need to remove validator branch before merging.

2018-08-31 10:10 UTC, bitdivision commented on app/questionnaire/rules.py
> +def evaluate_goto(goto_rule, schema, metadata, answer_store, group_instance, group_instance_id=None):
Pedantic: Add group_instance_id to docstring.

2018-08-31 10:10 UTC, bitdivision commented on app/questionnaire/rules.py
> +def evaluate_skip_conditions(skip_conditions, schema, metadata, answer_store, group_instance=0, group_instance_id=None):
Pedantic: docstring.

2018-08-31 10:10 UTC, bitdivision commented on app/questionnaire/rules.py
> +def evaluate_when_rules(when_rules, schema, metadata, answer_store, group_instance, group_instance_id):
Pedantic: docstring.

2018-08-31 10:24 UTC, jonnyshaw89 commented
@bitdivision cant remove validator branch until https://github.com/ONSdigital/eq-schema-validator/pull/80 is merged

2018-08-31 15:13 UTC, merged