Allow for missing keys in answer matching
ONSdigital/eq-survey-runner pull request #1777
Opened 2018-09-11 16:42 UTC by dwyeradam

### What is the context of this PR?
When matching answers it relied on all keys being present
Allowing for keys to be missing allows easier forward compatibility

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-09-11 17:38 UTC, jonnyshaw89 requested changes

2018-09-11 17:38 UTC, jonnyshaw89 commented on tests/app/data_model/test_answer_store.py
> +        answer_2 = {
Shouldn't this include a `group_instance_id`? or another test with one?

2018-09-12 07:48 UTC, dcdarrell9 commented
So, I run off v2.55, answered a few question and `group_instance_id` wasn't present. Then switched to v2.57.2 after trying `census_household` and `test_repeating_household` and they both worked for me (both had `group_instance_id` and saving worked.

2018-09-12 09:21 UTC, bitdivision commented
Reproduced and fixed with latest version. Tested 2.55 -> this branch :+1:

There are a few other instances of `['group_instance_id']` in the code base:
```
$ rg "'group_instance_id'\]"
app/forms/household_relationship_form.py
28:                'answers': _build_answers(answer_store, answer['group_instance_id']),

app/data_model/answer_store.py
286:        answer['group_instance_id'] = get_group_instance_id(schema, answer_store, location, answer['answer_instance'])

app/helpers/schema_helpers.py
53:        return existing_answers[0]['group_instance_id']
85:            group_instance_ids.append(answers[0]['group_instance_id'])
100:            group_instance_ids.append(answers[0]['group_instance_id'])
```

But I don't think any of these will cause a problem

2018-09-12 09:41 UTC, jonnyshaw89 approved these changes

2018-09-12 09:45 UTC, bitdivision approved these changes
:+1:

2018-09-12 10:22 UTC, merged