Add address fields to lms schema
ONSdigital/eq-survey-runner pull request #1787
Opened 2018-09-13 15:12 UTC by insacuri

### What is the context of this PR?
https://trello.com/c/iugfWgRR/2392-add-address-fields-to-lms-schema

The individual address fields needed to be passed in, but addresses being what they are, can have empty fields.  This PR adds those fields and allows metadata to be labelled as optional also.

### How to review 
Open the lms_2.json schema in launcher.  Remove the value of any of the 5 individual address fields.  It should launch the survey fine.  Every other field not labelled with optional: true should still fail validation if it's empty.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-09-14 08:16 UTC, bitdivision requested changes
I don't think it's strictly necessary, but I think adding some optional fields to an integration test would be nice.

Additionally, this will need a change to validator.

2018-09-17 09:55 UTC, jonnyshaw89 requested changes

2018-09-17 09:55 UTC, jonnyshaw89 commented on app/storage/metadata_parser.py
>      for metadata_field in required_metadata:
technically this is not correctly named now as its no longer a list of `required_metadata`

2018-09-17 09:55 UTC, jonnyshaw89 commented on data/en/lms_2.json
> +            "name": "address_line1",
Im confused as to why we are defining these in metadata if we are not using them?

2018-09-25 09:19 UTC, bitdivision commented
Closing until further work as discussed.

2018-09-25 09:19 UTC, closed without merging