Fix safe_content regex for jinja filters in titles
ONSdigital/eq-survey-runner pull request #1788
Opened 2018-09-14 11:20 UTC by bitdivision

### What is the context of this PR?
@dcdarrell9 noticed that some titles on LMS2 were including jinja filters.

The regex was not matching anything that contained curly braces (which we use for date offsets).

### How to review 
Test LMS2 and make sure reference date filters etc. are not shown in titles.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-09-14 12:21 UTC, dcdarrell9 approved these changes

2018-09-17 09:59 UTC, jonnyshaw89 requested changes

2018-09-17 09:59 UTC, jonnyshaw89 commented on app/templating/template_renderer.py
> +            content = re.sub(r'{{.*?}}', '…', content)
Testy McTest Face?

2018-09-17 10:27 UTC, bitdivision commented on app/templating/template_renderer.py
> +            content = re.sub(r'{{.*?}}', '…', content)
Donezy McDone Face.

2018-09-17 10:37 UTC, bitdivision commented
I guess the only thing this won't handle currently is nested dictionaries in a filter argument e.g.

`{{ some_jinja_filter(arg, {'a': 'test', 'b': {1:1}}) }}`

I can't really see how to handle that without building a stack, which I don't think we can do in a regex.

2018-09-17 10:44 UTC, jonnyshaw89 approved these changes

2018-09-17 12:33 UTC, merged