Added AnswerSummary
ONSdigital/eq-survey-runner pull request #1793
Opened 2018-09-21 10:27 UTC by jonnyshaw89

### What is the context of this PR?
Provides a summary of an answer group, eg a household member

### How to review 
Test schema `test_answer_summary.json` has been created as a test case.
You can add multiple people and you are presented with a summary with a schema configured label.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-09-24 10:58 UTC, insacuri approved these changes
LGTM

2018-09-24 15:09 UTC, dcdarrell9 approved these changes
Just some things left in there - but works well 👍

2018-09-24 15:09 UTC, dcdarrell9 commented on tests/functional/spec/features/summary/answer_summary.spec.js
> +describe('@watch Answer Summary', function () {
watch

2018-09-24 15:09 UTC, dcdarrell9 commented on scripts/test_schemas.sh
> +    validator="$(docker run -d -p 5001:5000 onsdigital/eq-schema-validator:support-answer-summary)"
Just a reminder

2018-09-24 15:09 UTC, dcdarrell9 commented on tests/functional/spec/features/summary/answer_summary.spec.js
> +
extra space

2018-09-25 09:41 UTC, MebinAbraham requested changes
The summary layout doesn't seem to be responsive.
<img width="364" alt="screen shot 2018-09-25 at 10 40 37" src="https://user-images.githubusercontent.com/35296336/46006453-7afcd580-c0af-11e8-9e7d-e2b92e860e63.png">


Changing: `<div class="grid__col col-12@xs mars col-10@m">` to 
`<div class="grid__col col-8@xs mars col-10@m">` seems to resolves it.

2018-09-26 08:12 UTC, MebinAbraham requested changes
The responsive issue addressed. 👍 

But another problem, the routing path is not letting me go past the `AnswerSummary` page. If you click `Continue`, you are loaded back to the summary page. (Temporary redirect - 302 status)

2018-09-26 10:19 UTC, jonnyshaw89 commented
@MebinAbraham that issue is now fixed.

2018-09-26 12:57 UTC, MebinAbraham reviewed
@jonnyshaw89 Previous issue solved 👍 

However, since this is a new summary type, we should add the same check we do with `SectionSummary` to make sure you are allowed to access the page?. I am able to access the summary directly otherwise.

<img width="617" alt="screen shot 2018-09-26 at 13 54 53" src="https://user-images.githubusercontent.com/35296336/46081256-f8017b00-c193-11e8-9c45-dbed1173d472.png">

2018-09-26 13:15 UTC, jonnyshaw89 commented
@MebinAbraham that will then enforce that this block needs to be at the end of a section? Im not sure if this should have the same behaviour as `SectionSummary` it currently behaves the same as `CalculatedSummary`

2018-09-26 13:53 UTC, MebinAbraham commented
@jonnyshaw89 Should something be done so that it isn't empty?. Ie `CalculatedSummary` will show `No answer provided`. So should this do the same for person 1?

2018-09-27 09:50 UTC, MebinAbraham commented
Should add a test for this new behaviour.

2018-09-27 09:55 UTC, MebinAbraham reviewed
Curious. So `test_repeat_until.json` shows `Does anyone else live here?` on the Summary, hence you can change your answer. But on `test_answer_summary.json`, it doesn't on the answer summary, is this intended?. How will a user add a new person?. Are we having a link at the bottom `Missing someone?`, something like that?.

2018-09-27 10:00 UTC, jonnyshaw89 commented
It doesn't show on summary as its a `ConfirmationQuestion`

2018-09-27 10:02 UTC, MebinAbraham reviewed
So in the prototype, there is a link `Add someone to the household`, will the implementation of that be a separate card?

2018-09-27 10:49 UTC, jonnyshaw89 commented
@MebinAbraham agreed with @charlotte-hirst that the add link will be a new card

2018-09-27 13:01 UTC, MebinAbraham commented on app/templates/partials/summary/answer-summary.html
> +                            {{ answer.label|striptags }}
Spoke with @ajmaddaford and he confirmed that we should use this style for translation:
https://github.com/ONSdigital/eq-survey-runner/blob/1cc1406becda068f3519bd34d36ee4bd7cbbb800/app/templates/partials/summary/edit-link.html#L7-L9

2018-09-27 14:50 UTC, MebinAbraham approved these changes
👍

2018-09-27 14:51 UTC, MebinAbraham commented
Merge once validator branch merged and `test_schemas.sh` reverted.

2018-09-27 15:44 UTC, merged