Repeat rule check if answer instance is on path
ONSdigital/eq-survey-runner pull request #1798
Opened 2018-09-25 14:24 UTC by jonnyshaw89

### What is the context of this PR?
Previously it was only checking if an answer id was on the routing path. Now we check if that instance of an answer is on the path

### How to review 
run `test_routing_repeat_until.json` add 2 additional people then press the browser back and say no additional people to essentially orphan the last person in the answer store.
In the next group it should not ask the sex of the orphaned person.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-09-26 09:46 UTC, insacuri commented on app/questionnaire/rules.py
> +        # is block_id / group_instance on routing path?
This block of comments still needed?  If so, putting them above the line that does the action would be more useful

2018-09-26 09:59 UTC, insacuri approved these changes
Tested it and works as expected.  Code looks fine 👍

2018-09-27 09:37 UTC, MebinAbraham requested changes
As discussed, if you add multiple people, ie 4, then you navigate back using the browser and answer `No` to the driver question for the eg 2nd person, it repeats the `driver` question for the other people you added and keeps their instances in the submission. Hope this makes sense.

2018-09-28 11:10 UTC, jonnyshaw89 commented
@MebinAbraham i believe that issue is fixed now.
It was a similar case of repeats on the number of answers and not checking those answers are still on the path

2018-09-28 13:23 UTC, MebinAbraham approved these changes
Seem to be working as expected. 👍

2018-09-28 15:02 UTC, merged