Eq 2113 create a social theme small
ONSdigital/eq-survey-runner pull request #1807
Opened 2018-10-02 10:41 UTC by jonnyshaw89

### What is the context of this PR?
Updated content for Social theme

### How to review 
Compare against slides

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-10-02 13:21 UTC, bitdivision approved these changes
Matches the slides.

2018-10-02 13:59 UTC, insacuri requested changes

2018-10-02 13:59 UTC, insacuri commented on app/themes/social/templates/static/contact-us.html
> +                                        <p>{{helpers.email_address(email="surveyfeedback@ons.giv.uk")}}</p>
:%s/ons.giv.uk/ons.gov.uk/

2018-10-02 14:07 UTC, dcdarrell9 commented on app/themes/social/templates/thank-you.html
> +        <p class="u-mb-s mars">{{ _("Your answers will only be available for <b>%(duration)s</b> to keep them secure.",
Translation tag needs to be after secure?

2018-10-02 14:09 UTC, MebinAbraham requested changes

2018-10-02 14:09 UTC, MebinAbraham commented on app/themes/social/templates/static/contact-us.html
> +{% set survey_title  = _("ONS Business Surveys") %}
This content doesn't suit.

2018-10-02 14:22 UTC, insacuri approved these changes

2018-10-02 14:28 UTC, MebinAbraham reviewed
Trello card has cookies and privacy page content attachment?

2018-10-03 09:21 UTC, jonnyshaw89 commented
@MebinAbraham cookies and privacy is out of scope of this card now

2018-10-03 09:29 UTC, MebinAbraham approved these changes

2018-10-03 10:14 UTC, merged