Social theme cookies and privacy page
ONSdigital/eq-survey-runner pull request #1811
Opened 2018-10-04 10:52 UTC by MebinAbraham

### What is the context of this PR?
Added cookies and privacy page for the Social theme.
Also made some slight modification to existing cookies and privacy page for consistency.

### How to review 
Ensure layout and content matches whats on [Trello](https://trello.com/c/0HZdt4MN/2448-cookies-and-privacy-for-social-theme)

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-10-04 12:59 UTC, dcdarrell9 commented
![screen shot 2018-10-04 at 13 40 31](https://user-images.githubusercontent.com/16637283/46475455-7afe8300-c7dd-11e8-8b4d-f5b3ed2f5cff.png)
Doesn't look like it matches the card

2018-10-04 12:59 UTC, dcdarrell9 commented
![screen shot 2018-10-04 at 13 42 13](https://user-images.githubusercontent.com/16637283/46475543-b39e5c80-c7dd-11e8-993c-d7522406db00.png)
Same here, should there be a 'purpose' and 'description'?

2018-10-04 14:06 UTC, jonnyshaw89 requested changes

2018-10-04 14:06 UTC, jonnyshaw89 commented on app/translations/messages.pot
> -#: app/templates/partials/answers/date.html:5
Why are these removed?

2018-10-04 14:31 UTC, MebinAbraham commented
> ![screen shot 2018-10-04 at 13 40 31](https://user-images.githubusercontent.com/16637283/46475455-7afe8300-c7dd-11e8-8b4d-f5b3ed2f5cff.png)
> Doesn't look like it matches the card

Updated.

2018-10-04 14:38 UTC, MebinAbraham commented
> ![screen shot 2018-10-04 at 13 42 13](https://user-images.githubusercontent.com/16637283/46475543-b39e5c80-c7dd-11e8-993c-d7522406db00.png)
> Same here, should there be a 'purpose' and 'description'?

@dcdarrell9 This was being hidden purposely?, not sure, I removed the class that hid it from both default and social theme.

2018-10-04 21:31 UTC, MebinAbraham commented on app/translations/messages.pot
> -#: app/templates/partials/answers/date.html:5
Babel was being a **#@&%^!**. Fixed now.

2018-10-05 08:16 UTC, jonnyshaw89 requested changes

2018-10-05 08:16 UTC, jonnyshaw89 commented on app/templates/static/cookies-privacy.html
> +                                        {{ _("Wycliffe House") }}<br>
Do we want to translate addresses? this is an english address?

2018-10-05 08:16 UTC, jonnyshaw89 commented on app/themes/social/templates/static/cookies-privacy.html
> +                                        {{ _("Government Buildings") }}<br>
Same here re translating addresses

2018-10-05 08:16 UTC, jonnyshaw89 commented on app/themes/social/templates/static/cookies-privacy.html
> +                                        {{ _("Wycliffe House") }}<br>
another address

2018-10-05 13:43 UTC, insacuri approved these changes
👍 LGTM (after the address translation issue gets sorted out)

2018-10-08 07:30 UTC, MebinAbraham commented
@jonnyshaw89 I'm not sure whether we should be marking addresses for translation. We have some addresses marked for translation and some not, so I was just trying to make 1 consistent. And the contact us page for the social theme you did recently have address marked for translation so thought maybe there was a reason you kept it. I'll ask Simon what we should do.

2018-10-08 09:27 UTC, jonnyshaw89 commented
@MebinAbraham @charlotte-hirst has clarified that Addresses should not be translated

2018-10-08 10:12 UTC, MebinAbraham commented
@jonnyshaw89 Ready for re-review.

2018-10-08 10:19 UTC, jonnyshaw89 approved these changes

2018-10-08 13:50 UTC, merged