LMS - Who lives here section
ONSdigital/eq-survey-runner pull request #1812
Opened 2018-10-04 15:34 UTC by jonnyshaw89

Have updated the Who lives here section to meet the slides

Currently the names do not work in the navigation but everything else should work as expected.

2018-10-04 16:32 UTC, bitdivision reviewed
Obviously address piping and navigation aren't in yet. 

I've done a little bit of testing on the routing and flow and it all seems to be as expected.

2018-10-04 16:32 UTC, bitdivision commented on data/en/lms_2.json
> +                                            "description": "For examples it is my old address, second home, holiday home, business address or is not familiar to me"
For example

2018-10-04 16:32 UTC, bitdivision commented on data/en/lms_2.json
> +                                            "description": "For examples it is my old address, second home, holiday home, business address or is not familiar to me"
I've commented on the spec, Donna will need to change it.

2018-10-04 16:32 UTC, bitdivision commented on data/en/lms_2.json
> -                                    "block": "unpaid-overtime-w10",
This is just a bad diff I think?

2018-10-09 06:50 UTC, MebinAbraham reviewed
Person icon needs to be added instead of bullets for listing peoples names?

2018-10-09 06:52 UTC, MebinAbraham commented on data/en/lms_2.json
> +                                "title": "Is this address your main residence",
Needs the `?`?

2018-10-09 07:29 UTC, MebinAbraham commented on data/en/lms_2.json
> +                            "description": "{{metadata['ru_name']}}",
Bad merge?. Not meant to be using `ru_name` anymore?

2018-10-09 07:48 UTC, MebinAbraham reviewed
Question:
Do we require the driver questions to be mandatory?:
`/other-household-member-group/0/other-household-member-anyone-else-block`
and
`/student-household-member-group/0/student-household-member-anyone-else-block`
are both mandatory in schema but not in the spec. Is this a requirement for `repeat_until` cause we don't treat no answer the same way?

2018-10-09 07:49 UTC, MebinAbraham requested changes
Questions for slide 10 and 11 are mandatory in the schema but not according to spec.

2018-10-09 07:54 UTC, dcdarrell9 commented on data/en/lms_2.json
> +                                    "value": "Is <em>{{[group_instances[group_instance_id]['primary-household-member-first-name'], group_instances[group_instance_id]['primary-household-member-last-na
Same here with `ru_name`

2018-10-09 10:17 UTC, jonnyshaw89 commented
@MebinAbraham can you re-review?

2018-10-09 10:32 UTC, dcdarrell9 commented
Sooo, when you navigate back to `About Household` If you change the name then it works fine, but then if you try to 'add' any more members to the household, it will overwrite the next in the list. 

For example: 
- If you had added -> 'darrell cox' / 'jon shaw' / 'mebin abraham'
- Return to About Household and be asked about 'darrell cox' name -> change to 'Darrell Cox' -> save
- On the next screen it will ask if you want to add another member -> add another member 'Andrew MadDog' -> save -> 'jon shaw' will have been overwritten

Not sure what the expected functionality is, or what we should be doing with this

2018-10-09 13:06 UTC, bitdivision approved these changes

2018-10-09 13:06 UTC, bitdivision commented on app/questionnaire/navigation.py
> +        group_instance_id = get_group_instance_id(self.schema, self.answer_store, location)
👍

2018-10-09 14:10 UTC, MebinAbraham reviewed
Some routing on slide 5 (Hholdchk) seems to be missing.
```If no and answer to ineligbletype = ‘student accommodation rented from a private landlord’ then go to sharecooking```

Routing goes to `Addppl` instead of `sharecooking`

So:
- Person 1 `(/primary-household-member-group/0/primary-household-member-block)`
- No, the above address is not my main residence `(/primary-household-member-group/0/address-check-block)`
- Student accommodation rented through a private landlord `(/address-type-group/0/address-type-block)`
- No, this is not the main residence of any other adults, children or babies `(/other-household-member-group/0/other-household-member-anyone-else-block)`

Goes to: `/student-household-member-group/0/student-household-member-anyone-else-block`
but should go to: `/share-group/0/share-cooking-block`?

2018-10-09 14:23 UTC, jonnyshaw89 commented
@MebinAbraham can you check again?

2018-10-09 14:33 UTC, MebinAbraham commented
@jonnyshaw89 No sure if it was the recent change that @boxadesign or because of the groups/block structure, but some blocks don't have `Previous` links such as the sharecooking.

Also the mandatoriness doesn't match the spec.

2018-10-09 14:42 UTC, jonnyshaw89 commented
@MebinAbraham any block at the beginning of a group doesnt gave a Previous link.
can you be more specific about missing mandatory?

2018-10-09 16:02 UTC, MebinAbraham commented
@jonnyshaw89 sharecooking

2018-10-09 16:17 UTC, MebinAbraham approved these changes

2018-10-09 16:38 UTC, merged