Remove Flask login which adds user_id to cookie
ONSdigital/eq-survey-runner pull request #1877
Opened 2018-11-01 16:20 UTC by dwyeradam

### What is the context of this PR?
PR #1657 causes the user_id to get stored in the session cookie.

EQ's current encryption model for questionnaire state intends for the user_id to not be exposed to the user, only the user_ik.

This [line](https://github.com/ONSdigital/eq-survey-runner/commit/92f54df0160c2f15aa2afcc1024847de769a2fc8#diff-38d589711ca2d8ef50e47c9f2cf2ae0fR116) was only added as an optimisation to save an extra DB hit and therefore I have removed it.

### How to review 
The cookie can be verified by copying the value of a session cookie to https://www.kirsle.net/wizards/flask-session.cgi and decoding it).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-11-01 16:25 UTC, dwyeradam commented on tests/integration/integration_test_case.py
> +    """Decode a Flask cookie."""
This function seems like overkill to me. Can I do it more simply, ideally with existing EQ code or inbuilt Flask functions?

2018-11-01 17:26 UTC, bitdivision commented
No idea what's happened with codecov there...

2018-11-02 08:57 UTC, jonnyshaw89 requested changes

2018-11-02 08:57 UTC, jonnyshaw89 commented on tests/integration/integration_test_case.py
> +from itsdangerous import base64_decode
What is `itsdangerous`? we could use..
```
import base64
base64.b64decode(data)
```

2018-11-02 08:59 UTC, jonnyshaw89 commented
This is obviously not needed anymore then either.
https://github.com/ONSdigital/eq-survey-runner/pull/1657/files#diff-4d5ff7e65b71e6875dfead2645e34354R12

2018-11-02 09:13 UTC, jonnyshaw89 requested changes

2018-11-02 09:13 UTC, jonnyshaw89 commented on tests/integration/integration_test_case.py
> +    if compressed:
If our cookie is always compressed then we should always try and decompress, therefore we can tell if we suddenly stop compressign it

2018-11-02 09:23 UTC, dwyeradam commented on tests/integration/integration_test_case.py
> +from itsdangerous import base64_decode
My understanding is that Flask, by default, uses the URL-safe signed serializer "itsdangerous" to encode its client-side session cookies and therefore so did I.

2018-11-02 09:33 UTC, bitdivision commented on tests/integration/integration_test_case.py
> +    """Decode a Flask cookie."""
I don't think so, the flask code is all wrapped up. You have to override a bunch of stuff and I don't think it's really worth the effort.

2018-11-02 09:42 UTC, dwyeradam commented on tests/integration/integration_test_case.py
> +    """Decode a Flask cookie."""
That's the conclusion I came to so happy if I didn't miss something.

2018-11-02 10:41 UTC, bitdivision approved these changes

2018-11-02 10:42 UTC, jonnyshaw89 approved these changes

2018-11-02 13:10 UTC, merged