Add signout and 'save and sign out' buttons
ONSdigital/eq-survey-runner pull request #1881
Opened 2018-11-02 11:26 UTC by insacuri

### What is the context of this PR?
https://trello.com/c/39EwmSSe/2385-sign-out-of-eq-and-ras

Adds a 'sign out' or 'save and sign out' button to blue banner and removed it from the submit button on the page.

### How to review 
Open a survey and sure that for the introduction page and thank you page, the button in the blue banner reads 'Sign out' and every other page should have 'Save and Sign out' as the button in the blue banner.

Additionally, make the browser smaller to trigger the mobile version of the site and it should appear in the dropdown menu also.
### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-11-02 12:02 UTC, insacuri commented
Adding in progress label because I forgot to run the tests and a bunch of the broke

2018-11-05 12:24 UTC, MebinAbraham commented on app/templates/partials/header.html
> +                    <div class="u-fr u-d-no--@xs@s"><button class="btn btn--ghost print__hidden" data-qa="btn-save-sign-out" type="submit" name="action[save_sign_out]">{{ _("Sign out") }}</button></d
`data-qa` and `action` needs updating?. Also worth adding event for analytics?.

2018-11-05 12:38 UTC, MebinAbraham requested changes
Layout issue:
<img width="360" alt="screenshot 2018-11-05 at 12 37 05" src="https://user-images.githubusercontent.com/35296336/47998539-910ea480-e0f7-11e8-9b28-6657d2b62bbd.png">

2018-11-05 12:42 UTC, MebinAbraham requested changes
Something odd is happening, when you hover over an answer and hit the `Enter` button, it invokes the save and signout button?
Seems to be doing it for like every answer type.


<img width="583" alt="screenshot 2018-11-05 at 12 40 54" src="https://user-images.githubusercontent.com/35296336/47998692-290c8e00-e0f8-11e8-81cb-e27b7735761c.png">


Form Data:
```
action[save_sign_out]: 
csrf_token: IjBiNTY1NzVhMjE3MjQ3ZWRmMmM5OGM1NTRjOTI1YjdmZGRhNjhiYWMi.DsHNkw.6Vcxidf0ErDOsTjphli1RduIInU
weekly-pay-paid-employees-answer: 9
```

2018-11-05 12:43 UTC, MebinAbraham reviewed
Does this not need to apply for our other themes?

2018-11-05 13:11 UTC, MebinAbraham commented on app/templates/partials/header.html
> +                    {% if not content or content.block and content.block.type == 'Introduction' %}
I found this kinda confusing, can we use parentheses?.
`{% if not content or (content.block and content.block.type == 'Introduction') %}`

2018-11-05 13:55 UTC, MebinAbraham reviewed
The layout column seems to slightly off?
<img width="505" alt="screenshot 2018-11-05 at 13 52 25" src="https://user-images.githubusercontent.com/35296336/48002026-3a5a9800-e102-11e8-8989-10b80538bb0f.png">
According to pattern lib, it should be like this?
<img width="505" alt="screenshot 2018-11-05 at 13 54 32" src="https://user-images.githubusercontent.com/35296336/48002064-59f1c080-e102-11e8-91aa-e8336a898efc.png">

2018-11-05 15:26 UTC, insacuri commented on app/templates/partials/header.html
> +                    <div class="u-fr u-d-no--@xs@s"><button class="btn btn--ghost print__hidden" data-qa="btn-save-sign-out" type="submit" name="action[save_sign_out]">{{ _("Sign out") }}</button></d
Agreed, I did all 3 bits in the end

2018-11-05 15:27 UTC, insacuri commented on app/templates/partials/header.html
> +                    {% if not content or content.block and content.block.type == 'Introduction' %}
Yea agreed, I added brackets

2018-11-05 15:50 UTC, insacuri commented
@MebinAbraham I've fixed the column layout (didn't realise the header had a few new classes against it).
I also sorted out the alignment issue too.
I've spoken to Matt about pressing enter logging you out and he's going to look into it.

2018-11-06 09:59 UTC, MebinAbraham commented
My last comment is still an issue when the width is between 500-575px

2018-11-06 10:43 UTC, MebinAbraham reviewed
I get a 500 error when I click `Sign out` after submission?
```
File "/Users/abrahm/.virtualenvs/eq-survey-runner-TQNVnq61/lib/python3.6/site-packages/werkzeug/routing.py", line 1580, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
127.0.0.1 - - [06/Nov/2018 10:42:30] "POST /questionnaire/test/view_submitted_response/thank-you HTTP/1.1" 500 -
```

2018-11-09 10:28 UTC, dwyeradam commented
Lewis has confirmed now 👍 so ignore below.

@insacuri can you please chase up RAS/RH regarding https://github.com/ONSdigital/ons-schema-definitions/pull/39. Until we confirm that they are going to pass the `account_service_log_out_url` we shouldn't really merge this. That said i'll still review this on the assumption that the above PR is fine.

2018-11-09 10:36 UTC, insacuri commented
@dwyeradam done, Lewis said it's all good.  Is that enough or do we need another from that team looking at it?

2018-11-09 14:00 UTC, dwyeradam submitted a review, later dismissed
At the moment if `account_service_log_out_url` isn't passed we don't have a save and sign out button. Shouldn't we still have the button but if the `account_service_log_out_url` isn't available we go to the current signed-out.html page? It seems to do this for social. Otherwise we're stopping respondents from saving and signing out part way through.

2018-11-09 14:37 UTC, insacuri commented
@dwyeradam This was a tricky one.  For business surveys we 'should' always have it.  This field is a weird one as it's optional but expected for certain surveys.  Is the correct thing here to have a better fallback option? or can we make that field mandatory for surveys we **know** will have an account service driving the whole thing?

2018-11-09 15:37 UTC, insacuri commented
@dwyeradam Removed the conditional 'save and sign out' and it works fine.  Should be good to review now

2018-11-12 10:17 UTC, bitdivision submitted a review, later dismissed

2018-11-12 10:17 UTC, bitdivision commented on tests/functional/base_pages/theme/northernireland/introduction-page.page.js
> +const QuestionPage = require('../../question.page');
Don't think these pages should be here?

2018-11-12 10:42 UTC, insacuri commented on tests/functional/base_pages/theme/northernireland/introduction-page.page.js
> +const QuestionPage = require('../../question.page');
Removed them now

2018-11-12 12:21 UTC, MebinAbraham commented
Any update from Matt?. Sign out on `Enter` still occurs.

2018-11-12 12:52 UTC, MebinAbraham requested changes
If I go to the feedback page (`/feedback`) then click 'Save and sign out`, instead of signing out, it actually submits the form and displays:
```
Submission successful
Thank you for your feedback.

It is now safe to close this window.
```

---

Also if you then click `Sign out`, you get a 500 error.
```
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
127.0.0.1 - - [12/Nov/2018 12:50:55] "POST /feedback/thank-you HTTP/1.1" 500 -
```

2018-11-28 17:05 UTC, ajmaddaford commented
@MebinAbraham @dwyeradam @bitdivision this is ready for re-review.

The changes I've made are:
- Introduced a new top level variable to the templates - `save_on_signout` - this is used to determine if the page is saveable before signing out.
- Refactored the sign out button logic into its own template and added macros for the buttons.
- The CSRF tokens are injected directly in the template rather than via the view context. There was a lot of duplication here previously.
- Added additional functional tests to cover the sign out buttons available on the feedback screen and view submission.

I've raised some issues for further refactoring that I felt would have bloated this pull request - https://github.com/ONSdigital/eq-survey-runner/issues/1918 and https://github.com/ONSdigital/eq-survey-runner/issues/1919.

2018-11-29 09:55 UTC, MebinAbraham requested changes

2018-11-29 09:55 UTC, MebinAbraham commented on data/en/test_theme_northernireland.json
> +    "theme": "social",
This should be `northernireland`

2018-11-29 09:55 UTC, MebinAbraham commented on data/en/test_theme_northernireland.json
> +            "title": "Norther Ireland Theme Test"
An `n` was lost in transition...

2018-11-29 10:23 UTC, MebinAbraham requested changes
`Sign out` button on the`/feedback` page is submitting the form.

2018-11-29 12:23 UTC, MebinAbraham reviewed
@ajmaddaford You should also update the message.pot

2018-11-29 16:16 UTC, MebinAbraham commented on app/templates/layouts/_base.html
> +          <button class="u-vh" tabindex="-1" type="submit" name="action[save_continue]">Save and continue</button>
Needs to be marked for translation.

2018-11-29 16:23 UTC, MebinAbraham commented on app/themes/census/templates/introduction.html
> +  <button class="btn qa-btn-get-started" type="submit" name="action[start_questionnaire]">Start survey</button>
Needs marking for translation.

2018-11-29 16:23 UTC, MebinAbraham commented on app/themes/census/templates/introduction.html
>      <div class="venus lock__text"><p>Important: Your response is legally required</p></div>
This was never marked for translation?

2018-11-29 16:24 UTC, MebinAbraham commented on app/themes/census/templates/introduction.html
> +  <button class="btn qa-btn-get-started" type="submit" name="action[start_questionnaire]">Start survey</button>
ah its census...

2018-11-29 16:25 UTC, MebinAbraham commented on tests/functional/spec/checkbox.spec.js
> +  it('Given I have previously added text in other textfield and saved, when I uncheck other options and select a different checkbox as answer, then the text entered in other field must be wiped.', fu
👍

2018-11-29 16:27 UTC, MebinAbraham reviewed
Code changes looks good, just that translation comment to fix. Will approve tomorrow morning after a final check.

2018-11-30 09:18 UTC, MebinAbraham commented on app/templates/signed-out.html
> + {% if account_service_url %}
Dodgy indentation.

2018-11-30 09:22 UTC, MebinAbraham commented on app/views/session.py
> +        cookie_session['account_service_log_out_url'] = claims.get('account_service_log_out_url')
I know the existing is done like this but can it not just be:
```
 if claims.get('account_service_log_out_url'):
        cookie_session['account_service_log_out_url'] = claims.get('account_service_log_out_url')

2018-11-30 09:26 UTC, MebinAbraham commented on tests/functional/spec/save_sign_out.spec.js
> +  it('@watch  Given I load the feedback page and I sign out, then I should be on the account service logged out page', function() {
`@watch`

2018-11-30 09:27 UTC, MebinAbraham commented on tests/functional/spec/save_sign_out.spec.js
> +  it('Given I am returning to the questionnaire, then I am returned to the page I was on and can then complete the survey', function() {
Subjective I guess, but we should be doing `Given, When, Then`?

2018-11-30 12:31 UTC, ajmaddaford commented on tests/functional/spec/save_sign_out.spec.js
> +  it('Given I am returning to the questionnaire, then I am returned to the page I was on and can then complete the survey', function() {
Fair point, I've updated all scenarios to be Given, When, Then

2018-11-30 13:52 UTC, MebinAbraham approved these changes
Nice 👍

2018-11-30 16:58 UTC, bitdivision reviewed
I've looked through all the code :+1:

I've done some testing, but will finish testing and have a last look on Monday morning.

2018-11-30 16:58 UTC, bitdivision commented on tests/functional/helpers.js
> +function openQuestionnaire(schema, { userId = getRandomString(10), collectionId = getRandomString(10), periodId = '201605', periodStr = 'May 2016', region = 'GB-ENG', language = 'en', sexualIdentity
:+1:

2018-12-03 11:51 UTC, bitdivision commented
@ajmaddaford 	Not a big deal, but:

![how frequently are employees paid - monthly wages and salaries survey](https://user-images.githubusercontent.com/205209/49372167-b04a2300-f6f1-11e8-812a-024bc3744c66.png)

The save and signout button is not on the same row as the title.

2018-12-03 12:28 UTC, bitdivision approved these changes

2018-12-05 09:26 UTC, MebinAbraham reviewed
@ajmaddaford To fix the header issue you just need to edit:
https://github.com/ONSdigital/eq-survey-runner/blob/1bbb7ea0fef9361d0e0982f9f752a10770e2c489/app/themes/northernireland/templates/partials/header.html#L21
https://github.com/ONSdigital/eq-survey-runner/blob/1bbb7ea0fef9361d0e0982f9f752a10770e2c489/app/templates/partials/header.html#L24

Class is missing: `col-6@s`
So should be: 
``` HTML
<div class="grid__col {{ 'col-10@xs col-6@s col-8@m' if account_service_url }}">
```

2018-12-05 15:25 UTC, merged