Remove functional test pages and generate each time
ONSdigital/eq-survey-runner pull request #1896
Opened 2018-11-08 09:22 UTC by bitdivision

### What is the context of this PR?
The functional test pages of selectors were meant to be auto generated but were often manually modified. Changes to generate_pages.py often broke previous pages, but the pages weren't regenerated so this wasn't noticed until later.

To fix this, generate_pages.py has been modified to generate the pages before each test run. The run_tests_functional.sh script now deletes and recreates the generated_pages directory.

Originally I had planned to refactor generate_pages.py. I think that should probably be done as a seperate PR it likely needs to be rethought quite a bit.

### How to review 
Run all the scripts locally and make sure they make sense.
Check that I haven't broken any functionality in the tests.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-11-08 13:44 UTC, dwyeradam approved these changes
Tedious to check but good positive change. I also like the splitting of some of the larger spec files into their component parts. 
My favourite change by far is `.click(RadioButtonsPage.newMethodsOfOrganisingExternalRelationshipsWithOtherFirmsOrPublicInstitutions())`
to `.click(RadioButtonsPage.maybe())`

2018-11-08 15:11 UTC, dwyeradam commented on README.md
> +`./generate_pages.py ../../data/en/test_multiple_piping.json ./temp_directory -r "../../base_pages" -s specs/test_multiple_piping.spec.js
missing ` from end of line.

2018-11-08 15:22 UTC, MebinAbraham requested changes
We should update this in the readme:
`Runs the functional tests through ChimpJS (requires app running on localhost:5000)`

Need to also generate the pages. This is only mentioned further down the readme so we should either explain it here as well or only have 1 reference for running tests etc.

2018-11-08 17:05 UTC, bitdivision commented on README.md
> +`./generate_pages.py ../../data/en/test_multiple_piping.json ./temp_directory -r "../../base_pages" -s specs/test_multiple_piping.spec.js
Sorry about that! Both fixed now.

2018-11-09 08:48 UTC, MebinAbraham commented on README.md
> +`./generate_pages.py ../../data/en/test_multiple_piping.json ./temp_directory -r "../../base_pages" -s specs/test_multiple_piping.spec.js`
This should be `spec/` not `specs/`

2018-11-09 08:57 UTC, MebinAbraham requested changes
☝️

2018-11-09 09:08 UTC, MebinAbraham reviewed
Ignore - Wasn't worth it

2018-11-09 10:31 UTC, MebinAbraham approved these changes

2018-11-09 10:52 UTC, bitdivision commented
@dwyeradam I've changed the scripts a little, but it's not a significant change so I haven't dismissed your review

2018-11-09 12:11 UTC, merged