Update to pattern library v1.8.4
ONSdigital/eq-survey-runner pull request #1903
Opened 2018-11-14 15:08 UTC by boxadesign

### What is the context of this PR?

Primary reason to update is to fix a bug with mutually exclusive checkboxes in Safari (Override checkbox would not clear when selecting a `checkbox` from the group).

The release brought with it a breaking change with `textarea` char limit component. This is now capable of handling translations for both singular and plural characters. 

### How to review
 
Check that the new strings are able to be translated for the mutually exclusive char limit.

Check mutually exclusive checkboxes work as expected in Safari (this has been tested in the PL).

2018-11-27 16:21 UTC, bameyrick approved these changes

2018-11-28 10:49 UTC, bitdivision requested changes
You'll need to regenerate the messages.pot file, it doesn't have the new strings in it at the moment.

2018-11-28 11:00 UTC, bitdivision commented
I've tested a few surveys and not seen any issues. Happy once messages.pot is regenerated.

2018-11-28 11:41 UTC, boxadesign commented
@bitdivision Just pushed up the regenerated messages.pot file

2018-11-28 11:41 UTC, bitdivision approved these changes
:+1: Ready to squash @boxadesign

2018-11-28 13:01 UTC, MebinAbraham submitted a review, later dismissed
@boxadesign Bad rebase? `+9,447 -6,244` lines.

2018-11-28 13:03 UTC, boxadesign commented
@MebinAbraham Seems to have a load of other commits in there. Will sort now.

2018-11-28 13:08 UTC, boxadesign commented
@MebinAbraham Looking healthier now!

2018-11-28 13:45 UTC, boxadesign commented
@MebinAbraham Merge when you're ready!

2018-11-28 14:02 UTC, merged