2575 issue piping incorrect date
ONSdigital/eq-survey-runner pull request #1910
Opened 2018-11-21 14:59 UTC by bitdivision

### What is the context of this PR?
The original issue stems from: [trello](https://trello.com/c/Fy8nWytY/2575-issue-piping-incorrect-date). If a date was passed to format_date before December 14 1901 then format_date would change the hour by -1, meaning that 1902 would become 1901 when piped into another question.

I originally thought we needed to set `rebase=False` on `flask_babel.format_date`, this did fix the issue, but we were not converting dates to BST anymore, breaking a test. 

Investigating further, I found that 1901 coincides with the earliest possible unix timestamp, e.g. minimum value of a signed 32 bit integer. If you run `zdump -v Europe/London` you can actually see a couple of BST transitions in 1901, which shouldn't really be there, since it was introduced in 1916. I found a few vague references to similar problems on stack overflow which suggested issues with the Olsen database (used by `pytz`).

One fix for the issue was to fork flask-babel (fork [here](https://github.com/ONSdigital/flask-babel/tree/replace-pytz-with-pendulum)) and replace their [use of pytz](https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L23) with [pendulum](https://github.com/sdispater/pendulum). Pendulum fixes the issue found in `pytz` with dates before 1902 (and potentially a few others). This solution is problematic because flask-babel isn't well maintained and we are unlikely to be able to merge any changes upstream. The issue would probably need to be fixed upstream in `pytz`, which lives on sourceforge and has a mailing list. 

An alternate fix is to skirt the issue in flask babel by avoiding the [`to_user_timezone`](https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L360) function in flask_babel, which is where the issue comes into play. I did this by calling `flask_babel.format_datetime` with a `date` object rather than a `datetime` object. This fixes our use of format_date and doesn't rely on maintaining a fork of flask_babel. I think it's the better solution in the short term.

As a part of this, I did have a look at replacing our use of datetime with pendulum, which on the face of it looks like it would fix some common datetime issues we have. I found that the `now()` method is a local time object and there is no `utcnow()` method, additionally, the datetime.strptime() function is not replicated exactly (different format strings etc.). Having investigated a little, I don't think there are any major advantages *for us* switching at the moment. Though it could become useful in future if we start doing complex manipulations of timezones etc.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-11-21 16:53 UTC, ajmaddaford requested changes
LGTM, just a small docstring issue.

2018-11-21 16:53 UTC, ajmaddaford commented on tests/app/test_jinja_filters.py
> +        pendulum.
This docstring is now out of date

2018-11-21 16:57 UTC, bitdivision commented on tests/app/test_jinja_filters.py
> +        pendulum.
Good spot. Fixed.

2018-11-21 16:59 UTC, ajmaddaford approved these changes

2018-11-21 17:20 UTC, dwyeradam approved these changes

2018-11-22 12:50 UTC, bitdivision commented
Should probably ensure that Codacy works before this is merged. Not sure how to trigger it though...

2018-11-23 08:43 UTC, bitdivision commented
Codacy finally seems to have run @ajmaddaford. Should be ready to merge.

2018-11-23 13:36 UTC, merged