Fix mobile navigation when no account url set
ONSdigital/eq-survey-runner pull request #1935
Opened 2018-12-07 15:50 UTC by ajmaddaford

### What is the context of this PR?
Fixes #1934

### How to review 
- Launch a survey with no account url set
- Verify the sign navigation button is displayed when the viewport is resized
- Check variations of account url and account logout url
- Also check a `northernireland` theme survey

2018-12-10 11:22 UTC, MebinAbraham requested changes
On mobile for the social theme, once you click `Save & complete later` you get an empty mobile navigation which shouldn't be displayed.
<img width="322" alt="screenshot 2018-12-10 at 11 16 45" src="https://user-images.githubusercontent.com/35296336/49729500-98cce600-fc6d-11e8-8715-74b3e016c16f.png">

This is when the account service/logout URL is not set.

2018-12-11 14:08 UTC, MebinAbraham commented
@ajmaddaford Still an issue on the social theme if I have account service URL but not sign out URL.

2018-12-11 16:14 UTC, MebinAbraham approved these changes
As discussed, separate task to look at how we handle account service URLs and languages in a more meaningful and managable way.

2018-12-11 16:28 UTC, dwyeradam approved these changes

2018-12-11 16:29 UTC, dwyeradam commented
@ajmaddaford squishy squashy

2018-12-12 15:53 UTC, merged