Use new totaliser pattern
ONSdigital/eq-survey-runner pull request #1938
Opened 2018-12-11 15:04 UTC by insacuri

### What is the context of this PR?
https://trello.com/c/ZBUzk4tb/763-new-totaliser-pattern

Needed to use the new totaliser pattern

### How to review 
Test the validation on the questions in the e-commerce and ukis forms.

Note: To test the UKIS one, first answer the 'Goods and services innovation' section (saying yes to every question), followed by Turnover and exports.  Failing to do this won't cause the percentage totaliser question on ukis to appear as it's dependant on a question from the first section.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2018-12-12 16:15 UTC, jonnyshaw89 approved these changes

2018-12-13 09:58 UTC, dwyeradam approved these changes

2018-12-13 10:31 UTC, dwyeradam requested changes

2018-12-13 10:31 UTC, dwyeradam commented on data/en/ukis_0001.json
> +                            }],
You could previously leave this answer blank (in fact it only validated that the total was less than 100). If no answer is still a requirement then this should actually be:

```
"calculations": [{
    "calculation_type": "sum",
    "value": 0,
    "answers_to_calculate": ["answer3207", "answer3208", "answer3209", "answer3211"],
    "conditions": ["equals"]
},{
    "calculation_type": "sum",
    "value": 100,
    "answers_to_calculate": ["answer3207", "answer3208", "answer3209", "answer3211"],
    "conditions": ["equals"]
}],
```

2018-12-13 17:02 UTC, dwyeradam approved these changes

2018-12-13 17:31 UTC, merged