UKIS content changes
ONSdigital/eq-survey-runner pull request #1943
Opened 2018-12-17 12:47 UTC by jonnyshaw89

### What is the context of this PR?
Changes described in https://trello.com/c/i4bB9SEk/768-ukis-content-changes

### How to review 
Are the changes correct?

2018-12-19 11:56 UTC, hamishtaplin requested changes

2018-12-19 11:56 UTC, hamishtaplin commented on app/themes/ukis/templates/partials/header.html
> +                <div class="grid__col col-6@s">
Make logo smaller.

```suggestion
                <div class="grid__col col-7@xs col-6@s">
```

2018-12-20 14:35 UTC, hamishtaplin approved these changes

2018-12-20 14:36 UTC, tgandrews approved these changes
I haven't run it but the changes LGTM

2018-12-20 14:40 UTC, jonnyshaw89 commented
:man_facepalming:

2018-12-20 16:52 UTC, samiwel approved these changes
LGTM

2018-12-21 08:44 UTC, merged