Update readme to include sqlite3
ONSdigital/eq-survey-runner pull request #1959
Opened 2019-01-11 10:51 UTC by bitdivision

### What is the context of this PR?
People were having issues running this repo because sqlite3 wasn't installed before python. This PR updates the readme to include installing sqlite3 and simplifies the install commands.

### How to review 

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2019-01-11 11:38 UTC, jonnyshaw89 requested changes

2019-01-11 11:38 UTC, jonnyshaw89 commented on README.md
>  PostgreSQL
This title doesn't make sense now

2019-01-11 11:41 UTC, bitdivision commented on README.md
>  PostgreSQL
🤦‍♂️ I've updated and squashed

2019-01-11 11:52 UTC, jonnyshaw89 approved these changes

2019-01-14 12:50 UTC, dwyeradam approved these changes

2019-01-14 17:08 UTC, merged