Implement new url structure
ONSdigital/eq-survey-runner pull request #2017
Opened 2019-03-12 20:58 UTC by ajmaddaford

### What is the context of this PR?
Implements the URL structure as proposed in https://github.com/ONSdigital/eq-survey-runner/blob/v3/doc/architecture/decisions/0005-simplify-urls-and-extend-to-support-repeating-effectively.md. 

In doing this a large amount of code has been removed:
- Anything to do with repeats
- Household composition and household relationships
- Completeness and dependencies
- Answer summaries (they weren't being used)
- Multiple surveys checking (to be replaced by something appropriate at a later date)

This code has been removed to enable the upcoming feature work for [lists](https://github.com/ONSdigital/eq-survey-runner/blob/v3/doc/architecture/decisions/0006-make-named-lists-a-first-class-construct.md) and hub and spoke navigation.

### How to review 
- Does everything work as expected?
- Has enough been removed?
- Should anything be put back?

2019-03-13 09:49 UTC, bitdivision commented on app/data_model/answer_store.py
> -    2: upgrade_to_2_add_group_instance_id,
I think we should remove upgrades entirely. We talked about rewriting the interface previously, and these upgrades aren't really relevant on v3.

2019-03-13 10:00 UTC, jonnyshaw89 requested changes
Looking good

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +        return len(list(self.answer_map.values()))
pretty sure you can just do `len(self.answer_map)`
as key:value is a 121 mapping

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +        filtered_map = {k: v for k, v in self.answer_map.items() if k in answer_ids}
Can we skip a step with this and do the following?
`answers = [v for k, v in self.answer_map.items() if k in answer_ids]`

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/questionnaire/path_finder.py
> +        return next((index for (index, b) in enumerate(blocks) if b['id'] == location.block_id), None)
this is me just being annoying but can we change `b` to `block`?

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/questionnaire/path_finder.py
> +        return next((index for (index, b) in enumerate(blocks) if b['id'] == location.block_id), None)
#HatesAbbreviations

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/questionnaire/path_finder.py
> +                blocks.append(block)
`blocks.extend(group['blocks'])`

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/submitter/convert_payload_0_0_1.py
> -def convert_answers_to_payload_0_0_1(answer_store, schema, routing_path):
Why have we removed this in this PR?

2019-03-13 10:00 UTC, jonnyshaw89 commented on app/templating/summary_context.py
> +        # if (group['id'] in group_ids_on_path and schema.group_has_questions(group['id'])):
remove comments?

2019-03-13 17:25 UTC, bitdivision reviewed
I've looked through all the changes I think. 

Can't see any big issues, all looks good. Happy to approve.

2019-03-13 17:25 UTC, bitdivision commented on app/helpers/form_helper.py
>      Maps the answers in an answer store to a dictionary of key, value answers. Keys include instance
There's a reference to instance id in the docstring here.

2019-03-14 11:20 UTC, ajmaddaford commented on app/submitter/convert_payload_0_0_1.py
> -def convert_answers_to_payload_0_0_1(answer_store, schema, routing_path):
I got a bit carried away 🙄

2019-03-14 12:26 UTC, jonnyshaw89 approved these changes

2019-03-14 12:26 UTC, jonnyshaw89 commented
Im happy, you just need to please the Travis / Codecov gods

2019-03-14 12:56 UTC, bitdivision approved these changes
👍

🤞 for the tests

2019-03-14 15:05 UTC, merged