Add Opencensus Tracing
ONSdigital/eq-survey-runner pull request #2036
Opened 2019-04-02 15:00 UTC by iwootten

### What is the context of this PR?

In order to better understand where most time is spent within runner add support for opencensus tracing to capture traces to stackdriver. This uses the opencensus flask middleware to initially setup a overall trace and provides a decorator capture_trace which can be added to methods of interest.

### How to review 

Manually create a stackdriver project, add the environment vars:

EQ_STACKDRIVER_PROJECT_ID=$YOUR_PROJECT_ID

Then step through a survey and look through the trace list captured to stackdriver.

2019-04-02 15:04 UTC, jonnyshaw89 requested changes

2019-04-02 15:04 UTC, jonnyshaw89 commented on app/decorators/opencensus_decorators.py
> +        with tracer.span(name=f.__name__) as span:  # noqa: F841
```suggestion
        with tracer.span(name=f.__name__):
```

2019-04-02 15:04 UTC, jonnyshaw89 commented on app/settings.py
> +EQ_OPENCENSUS_ENABLED = os.getenv('EQ_OPENCENSUS_ENABLED')
Is this used?

2019-04-03 08:01 UTC, iwootten commented on app/settings.py
> +EQ_OPENCENSUS_ENABLED = os.getenv('EQ_OPENCENSUS_ENABLED')
Nope, removed

2019-04-03 08:04 UTC, jonnyshaw89 commented on app/decorators/opencensus_decorators.py
> +            return f(*args, **kwargs)
this is really petty but can we make `f` `function` or something like that? I have a real aversion to abbreviations in code

2019-04-03 09:53 UTC, jonnyshaw89 commented
This doesn't seem to work when deployed to GCP. The requests take ages and the logs show...
![Screenshot 2019-04-03 at 10 53 03](https://user-images.githubusercontent.com/7594012/55470043-bf3cd580-55fe-11e9-87d0-a9d6a9c36be3.png)

2019-04-03 10:10 UTC, jonnyshaw89 commented
I am able to replicate the above issue using docker-compose and setting `EQ_STACKDRIVER_PROJECT_ID`

2019-04-03 11:36 UTC, jonnyshaw89 requested changes
`/session` isn't being traced

2019-04-03 11:46 UTC, jonnyshaw89 commented
You need to add permission for the cluster to push traces.
add `"https://www.googleapis.com/auth/trace.append",` to the `oauth_scopes` in
https://github.com/ONSdigital/census-eq-terraform/blob/master/main.tf#L201

2019-04-03 14:09 UTC, jonnyshaw89 commented on tests/integration/test_app_create.py
> +        with context:
Why not just `with application.test_request_context(path='/'):

2019-04-04 15:03 UTC, jonnyshaw89 commented
@iwootten These changes look good but the issue with not being able to run it in the container is a bit of a show stopper at the moment.

2019-04-05 07:54 UTC, MebinAbraham commented on k8s/helm/values.yaml
> +stackdriverProject: ""
You should add this to
https://github.com/ONSdigital/eq-survey-runner/blob/v3/k8s/deploy_app.sh
and update the README.

2019-04-11 15:02 UTC, iwootten commented
@jonnyshaw89 Has done a fair amount of performance investigation here and it looks like that currently runner can cope with around 475 requests/sec in our default terraform setup. This tracing branch takes that down to around 200 due to the use of a custom gevent worker which doesn't patch threading. Gevent replaces the behaviour of a lot of libraries to make use of libev (In particular threading which opencensus also uses).

Without tracing enabled, but still using the custom tracing worker class in this branch drops performance to 320 requests/sec.

As decided by the team in planning, this work therefore is going to be archived until such a point as we've investigated whether it is possible to improve the performance of runner by looking at making some of it run asynchronously.

2019-04-11 15:02 UTC, closed without merging