Combined routing rules
ONSdigital/eq-survey-runner pull request #2041
Opened 2019-04-08 09:00 UTC by MebinAbraham

### What is the context of this PR?
Added the ability to define multiple response options to route to the same location, in a single routing rule.

Reduced routing rule from:
```
{
    "goto": {
      "block": "current-marriage-status",
      "when": [
        {
          "id": "confirm-marriage-type-answer",
          "condition": "equals",
          "value": "Married"
        }
      ]
    }
  },
  {
    "goto": {
      "block": "current-marriage-status",
      "when": [
        {
          "id": "confirm-marriage-type-answer",
          "condition": "equals",
          "value": "Separated, but still legally married"
        }
      ]
    }
  }
```
To:
```
{
    "goto": {
      "block": "current-marriage-status",
      "when": [
        {
          "value": [
            "Married",
            "Separated, but still legally married"
          ],
          "condition": "contains",
          "id": "confirm-marriage-type-answer"
        }
      ]
    }
  }
```

### How to review 
Ensure:
- You can route to same location based on multiple response options in a single routing rule.

Our current implementation has the notion that the answer value is the left hand side operand and the match value is the right hand side operand. With this notion, the condition name `contains` doesn't really read well for this scenario. Is it worth having an operator called `intersects`/`in` etc. Thoughts?

2019-04-08 13:00 UTC, jonnyshaw89 submitted a review, later dismissed

2019-04-08 13:00 UTC, jonnyshaw89 commented on app/questionnaire/rules.py
> +        'equals': lambda lhs, rhs: lhs == rhs,
🤢 abbreviation hell

2019-04-08 13:00 UTC, jonnyshaw89 commented on data/en/test_conditional_combined_routing.json
> +                            "value": ["yes", "sometimes"]
I wonder if we can make this more explicit and make this `"values": ["yes", "sometimes"]`

2019-04-08 14:50 UTC, MebinAbraham commented on app/questionnaire/rules.py
> +        'equals': lambda lhs, rhs: lhs == rhs,
👀 hell is worse.

2019-04-09 06:05 UTC, MebinAbraham commented on data/en/test_conditional_combined_routing.json
> +                            "value": ["yes", "sometimes"]
Possibly?. I thought about it but wasn't sure if to go ahead with it. Just an extra property in JSON schema and an extra `if` in runner. Also wasn't sure if additional checks would be appropriate, such as values to be only used with this kind of comparison.

2019-04-09 08:13 UTC, jonnyshaw89 commented on data/en/test_conditional_combined_routing.json
> +                            "value": ["yes", "sometimes"]
Yeh, I can see why, it makes the code simpler

2019-04-10 10:18 UTC, ajmaddaford commented
- I don't think using contains on a singular answer - "does this singular answer value contain this list of values" - reads very well . What we're trying to express is "does this singular answer value equal one of these values".
- The current approach only allows for OR logic, we should take this opportunity to add AND logic (or at least leave it open for this in the future). This would allow us to route multiple checkbox options that must be selected together in a single routing rule.

After discussing this with @bitdivision and @MebinAbraham we've come up with `equals any`, `contains any` and `contains all` - which reads more clearly and allows for AND logic. The example above becomes:

```
{
  "goto": {
    "block": "current-marriage-status",
    "when": [
      {
        "id": "confirm-marriage-type-answer"
        "condition": "equals any",
        "values": [
          "Married",
          "Separated, but still legally married"
        ],
        
      }
    ]
  }
}
```

If we implement this we could remove the contains rule as you should be able to use either `contains any` or `contains all`. We should also add validation in eq-schema-validator that checkbox answers only can use contains comparisons, and all other answer types can't.

2019-04-12 08:01 UTC, MebinAbraham commented
@ajmaddaford @jonnyshaw89
Introduced these new conditions:
1. `equals any`
2. `not equals any`
3. `contains any`
4. `contains all`

2019-04-18 08:05 UTC, ajmaddaford requested changes
Looks good 👍 

We need to review how we write rules in schema as it's not very clear. I've raised a card in the backlog to discuss this.

2019-04-18 08:05 UTC, ajmaddaford commented on data/en/test_conditional_combined_routing.json
> +                            "value": "no hot drinks"
The values for these should match the labels, as we do for any real schemas. It's confusing to see the different variations of text in the routing rules.

2019-04-18 08:47 UTC, MebinAbraham commented on data/en/test_conditional_combined_routing.json
> +                            "value": "no hot drinks"
Done

2019-04-18 09:52 UTC, ajmaddaford approved these changes

2019-04-23 09:24 UTC, jonnyshaw89 approved these changes

2019-04-23 09:24 UTC, jonnyshaw89 commented on scripts/test_schemas.sh
> +    docker pull onsdigital/eq-schema-validator:eq-2917-combined-routing-rules
This needs changing once merged

2019-04-24 08:32 UTC, merged