V3 templating upgrade
ONSdigital/eq-survey-runner pull request #2045
Opened 2019-04-11 13:19 UTC by bameyrick

### What is the context of this PR?
Updated runner to use the new design system macros to render templates. I had to create quite a lot of (poorly written) jinja filters to format the configs for some of the macros / add extra attributes for functional/intergration tests to use so I don't know if it would be a separate task to refactor these and make them not so terrible.

### How to review 
1. clone: `https://github.com/ONSdigital/design-system`
2. change to `update-npm-package-for-flask` branch
3. run `yarn` to install dependencies
4. run `yarn start` to boot dev server
6. symlink `design-system/src/styles/page-templates` to `eq-survey-runner/app/templates/layouts2`
7. symlink `design-system/src/components` to `eq-survey-runner/app/templates/components`
8. boot local runner

### Skipped tests
I have skipped some of the functional tests for now as I'm unsure how to fix them:
1. `save_sign_out.spec.js`: I'm not sure if this is a schema error, but the save and sign out button doesn't seem to be appearing when it should. This also seems to be the issue in the `v3` branch.
2. `static-feedback.spec.js` and `test_feedback.py`: I'm not sure if we're actually going to be using the standalone feedback page rather than the footer one yet so didn't dig into why this was failing too much.
3. `total-breakdown.spec.js`: I don't think we use this functionality anymore, so will check with charlotte if thats true so I can remove this test schema, and any code related.

### Failing tests

1. `test_app_create.py => test_enforces_secure_headers`: This is because i've added localhost:3030 to the security headers temporarily so I could pull the design system css/js from a local branch.
2. `test_render_percentage_widget.py => test_percentage_widget_has_icon` couldn't figure out how to update the regex on this one... is there a better way of selecting DOM element's contents using BeautifulSoup?
3. `test_questionnaire_language.py => test_load_non_existant_lang_fallback`: Doesn't seem to be putting `language_code` back to 'en' when a non existent language_code parameter is added, causing the language switcher macro to fail.

### Checklist
* [ ] Check templates are rendering correctly (there may be some minor spacing issues to address so if you spot anything funky looking let me know)
* [ ] Check performance isn't adversely affected.

### Still to do
* [ ] Deploy built CSS/JS/Images/fonts etc to CDN
* [ ] Figure out a way to import macros to the project as a dependency

2019-04-12 14:45 UTC, saedwards commented
Good effort Ben, looks like a hefty piece of work and can't have been easy. This is definitely a step in the right direction. Removing more presentational concerns from EQ will decrease coupling of this problem from the application and promote code reuse across the service, potentially further.

This is a first visit of integrating externalised templates into EQ, but catching problems early on will save a lot of time and money, some observations;

- A lot of conditional config mappings in templates/base-templates to meet macro preconditions, this will be unavoidable to a certain extent but could we organise/arrange this better? _base.html has a bit too much logic in one file. It’ll probably be the case that the application would have to adjust to supply the correct view-model mappings for the templates.

- There’s a lot of great reuse with low level components but it would be great to see more structural level components used where you can inject arbitrary content inside a structural node. Good examples of these would be: header, body, footer (for example, this is currently used with the onsPanel component using caller()).

- Not too sure about using the parameters “classes” and “attributes” for some of the macros and probably should be a last resort. It means the calling context knows too much about the inner workings of exact markup/styles/behaviours that are imported from the design system for each component causing tight coupling. You wouldn’t be able to change the name of classes/attributes in the design system without changing all applications that integrate with it.

- Would be good to see less hard-coded HTML removed to completely abstract presentation markup in future, kind of a given.

2019-04-15 10:18 UTC, bameyrick commented
> Good effort Ben, looks like a hefty piece of work and can't have been easy. This is definitely a step in the right direction. Removing more presentational concerns from EQ will decrease coupling of this problem from the application and promote code reuse across the service, potentially further.
> 
> This is a first visit of integrating externalised templates into EQ, but catching problems early on will save a lot of time and money, some observations;
> 
> * A lot of conditional config mappings in templates/base-templates to meet macro preconditions, this will be unavoidable to a certain extent but could we organise/arrange this better? _base.html has a bit too much logic in one file. It’ll probably be the case that the application would have to adjust to supply the correct view-model mappings for the templates.
> * There’s a lot of great reuse with low level components but it would be great to see more structural level components used where you can inject arbitrary content inside a structural node. Good examples of these would be: header, body, footer (the onsPanel component using caller()).
> * Not too sure about using the parameters “classes” and “attributes” for some of the macros and probably should be a last resort. It means the calling context knows too much about the inner workings of exact markup/styles/behaviours that are imported from the design system for each component causing tight coupling. You wouldn’t be able to change the name of classes/attributes in the design system without changing all applications that integrate with it.
> * Would be good to see less hard-coded HTML removed to completely abstract presentation markup in future, kind of a given.

I think you've raised valid points, definitely worth us discussing in a tech session or design meeting.

 * I agree about the conditional mappings, I think the amount of mapping in templates should be minimal, and most of the mapping be done in python to create a view model for the templates. There are a lot of jinja filters I created to map things for components, but these should be run before the view is hit, rather that from the view. This is quite a big thing to fix and will likely need to be a separate piece of work.

* Structural components are something we're quite weak on in the design system, as really we've only really been working with components as units, and not actually any page structure (the anatomy of a question for example), so I think we can definitely improve this by creating more macros that are purely for structure. It's something we should discuss in a design meeting.

* You're right about classes and attribute only being a last resort. I think a lot of components rely on you manually applying a class such as `btn--secondary` to change it's presentation rather than that being abstracted to some other parameter that sets the correct classes to change the presentation of that component. Those parameters should only be used to add stuff like `data-ga` attributes etc, and utility classes. If you spot examples of those attributes being misused though, if you could let me know or place a comment against the relevant component in the [design system forum](https://github.com/ONSdigital/design-system/issues?q=is%3Aissue+is%3Aopen+label%3A%22Design+System+forum%22) we can get on top of those issues.

* I think we can reduce the amount of `HTML` hand coded in templates by creating more macros dedicated to structure, but considering a lot of content in runner is hard coded rather than populated from a CMS WYSIWYG, there will always be a small amount knocking around.

2019-04-26 09:20 UTC, bitdivision commented on scripts/load_templates.sh
> +#!/usr/bin/env bash
We need to add a call to this in all our scripts and also in the readme as a setup step if you're running anything manually

2019-04-26 10:03 UTC, bitdivision commented
I'm hitting a few errors when running the integration tests:
`jinja2.exceptions.TemplateNotFound: _themes/default/sectionsummary.html`

Looks like there's still some setup code referencing themes. Do we need to remove all of this?

2019-04-26 10:11 UTC, bameyrick commented
> I'm hitting a few errors when running the integration tests:
> `jinja2.exceptions.TemplateNotFound: _themes/default/sectionsummary.html`
> 
> Looks like there's still some setup code referencing themes. Do we need to remove all of this?

I think so, removing all theming for now.

2019-05-01 10:32 UTC, bameyrick commented on tests/functional/spec/components/checkbox/mutually_exclusive/mutually_exclusive_dropdown.spec.js
> +        .click(DropdownPage.dropdownExclusiveIPreferNotToSayLabel())
By clicking the label you may be effectively clicking the checkbox so this might not be the correct fix

2019-05-01 10:34 UTC, bameyrick commented on tests/functional/spec/components/checkbox/mutually_exclusive/mutually_exclusive_dropdown.spec.js
> +        .click(DropdownPage.dropdownExclusiveIPreferNotToSayLabel())
By clicking the label you may be effectively clicking the checkbox so this isn't a safe way of fixing this. I think `selectByValue` may need to be modified to trigger a change event.

2019-05-01 11:37 UTC, ajmaddaford requested changes
- We should move the templates directory to the top level i.e. at the same level as the app directory. They're currently the only non-Python content in the app folder.
- The design system dependencies should be brought in to the same folder to easily isolate and identify them from the other templates - something like /templates/design-system.

I think we should get this merged as is. We can look at generating the required view data before rendering the templates (rather than via Jinja filters called from the templates) after it's merged.

2019-05-01 11:37 UTC, ajmaddaford commented on scripts/load_templates.sh
> +unzip /tmp/templates.zip -d /tmp/templates
This should unzip to a randomly generated directory name as we're forcefully removing it and there is always a chance that another app/service is using a directory of the same name. It looks like the `mktemp` command would be a good option - https://stackoverflow.com/questions/4632028/how-to-create-a-temporary-directory

2019-05-10 09:57 UTC, bitdivision commented
When clicking the Contact Us link while viewing in Welsh, I'm running into a 500, looks like it's related to the brackets around ru_ref?

```  File "/Users/forter/Code/eq-survey-runner/app/../templates/static/contact-us.html", line 16, in block "main"
    <p>{{ _("Please quote the reference <b>%(ru_ref)s</b> when contacting ONS about this survey.", ru_ref=session.ru_ref) }}</p>
  File "/Users/forter/virtualenvs/eq-survey-runner-mBP_POI1/lib/python3.7/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/Users/forter/virtualenvs/eq-survey-runner-mBP_POI1/lib/python3.7/site-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
ValueError: unsupported format character '(' (0x28) at index 27```

2019-05-10 10:03 UTC, MebinAbraham requested changes

2019-05-10 10:03 UTC, MebinAbraham commented on README.md
> +export EQ_DATASTORE_EMULATOR_CREDENTIALS="True"
I know it was just an addition but these should go in env var section?
https://github.com/ONSdigital/eq-survey-runner/blob/347ec4f0ca2907a60682a59fca125ffce2249844/README.md#environment-variables

2019-05-10 10:03 UTC, bitdivision commented
![padding_guidance](https://user-images.githubusercontent.com/205209/57519443-2c850a00-7313-11e9-99bc-02b5e5326bdb.png)

The padding around guidance doesn't look quite right to me.

2019-05-10 10:05 UTC, bitdivision commented
![padding](https://user-images.githubusercontent.com/205209/57519573-8554a280-7313-11e9-9eea-699704a08f30.png)
Another padding issue.

2019-05-10 10:06 UTC, MebinAbraham requested changes
A lot of text is in bold for me in Chrome/Firefox on this page only. This is on the first page of the census individual schema.
<img width="691" alt="Screenshot 2019-05-10 at 11 01 54" src="https://user-images.githubusercontent.com/35296336/57519606-99000900-7313-11e9-81a9-1002340504bb.png">
And footer on same page:
<img width="891" alt="Screenshot 2019-05-10 at 11 07 36" src="https://user-images.githubusercontent.com/35296336/57519715-dcf30e00-7313-11e9-9485-faabb62c082b.png">

2019-05-10 10:08 UTC, bitdivision commented
![twisty](https://user-images.githubusercontent.com/205209/57519691-d2387900-7313-11e9-84f1-b71a71e5d5b0.png)

The main text on the twisty here isn't showing up:

![twisty-open](https://user-images.githubusercontent.com/205209/57519747-f300ce80-7313-11e9-8a00-05b1ced46811.png)

2019-05-10 10:09 UTC, MebinAbraham reviewed
Since all the static file compiling has gone, the readme needs to be updated. It still outlines things like yarn and compile etc.

2019-05-10 10:12 UTC, bitdivision commented
I'm not sure about this, but the thank you page looks a little more condensed than it used to.

![thanks](https://user-images.githubusercontent.com/205209/57519993-83d7aa00-7314-11e9-9324-df3e23739ba8.png)

2019-05-10 10:20 UTC, bitdivision commented
On test_final_confirmation.json, the submit button is showing inline:
![submit-answers](https://user-images.githubusercontent.com/205209/57520451-9a323580-7315-11e9-86fd-c3827b25fc92.png)

2019-05-10 10:21 UTC, MebinAbraham submitted a review, later dismissed
Answer option description alignment issue?
#### Before:

<img width="379" alt="Screenshot 2019-05-10 at 11 19 34" src="https://user-images.githubusercontent.com/35296336/57520445-97cfdb80-7315-11e9-9876-79459faebfca.png">

#### After:
<img width="377" alt="Screenshot 2019-05-10 at 11 20 40" src="https://user-images.githubusercontent.com/35296336/57520489-b2a25000-7315-11e9-886d-cb6a9fbf5a10.png">

2019-05-10 10:24 UTC, MebinAbraham reviewed
The summary seems very padded. Also the Change link is missing as well as the Previous link?

#### Before:
<img width="615" alt="Screenshot 2019-05-10 at 11 22 45" src="https://user-images.githubusercontent.com/35296336/57520631-090f8e80-7316-11e9-9d31-e2c2f420ea6c.png">

#### After:
<img width="680" alt="Screenshot 2019-05-10 at 11 24 07" src="https://user-images.githubusercontent.com/35296336/57520678-29d7e400-7316-11e9-9e4e-7c656e5a6b44.png">

2019-05-10 10:28 UTC, MebinAbraham reviewed
The print button not looking so good today :P
<img width="194" alt="Screenshot 2019-05-10 at 11 27 51" src="https://user-images.githubusercontent.com/35296336/57520874-b2ef1b00-7316-11e9-85c0-9cae8f6e34c7.png">

2019-05-10 10:39 UTC, MebinAbraham commented
Not sure how to explain it but every time you load the definitions, you can see/notice the transition (flicker) from non-js to js version when the js scripts are loaded. Give me a shout if it doesn't make sense and ill explain in person.
<img width="400" alt="Screenshot 2019-05-10 at 11 37 20" src="https://user-images.githubusercontent.com/35296336/57521412-1e85b800-7318-11e9-8089-e9158ff63b18.png">

2019-05-10 10:43 UTC, MebinAbraham commented
For the summary and pages after summary ie, submission etc, the page content width has been increased, is that intentional?

2019-05-10 11:18 UTC, bameyrick commented
> Answer option description alignment issue?
> 
> #### Before:
> <img alt="Screenshot 2019-05-10 at 11 19 34" width="379" src="https://user-images.githubusercontent.com/35296336/57520445-97cfdb80-7315-11e9-9876-79459faebfca.png">
> 
> #### After:
> <img alt="Screenshot 2019-05-10 at 11 20 40" width="377" src="https://user-images.githubusercontent.com/35296336/57520489-b2a25000-7315-11e9-886d-cb6a9fbf5a10.png">

@will-madebymoon asked for this to be changed here: https://github.com/ONSdigital/design-system/issues/56#issuecomment-456444482

2019-05-10 11:19 UTC, bameyrick commented
> The summary seems very padded. Also the Change link is missing as well as the Previous link?
> 
> #### Before:
> <img alt="Screenshot 2019-05-10 at 11 22 45" width="615" src="https://user-images.githubusercontent.com/35296336/57520631-090f8e80-7316-11e9-9d31-e2c2f420ea6c.png">
> 
> #### After:
> <img alt="Screenshot 2019-05-10 at 11 24 07" width="680" src="https://user-images.githubusercontent.com/35296336/57520678-29d7e400-7316-11e9-9e4e-7c656e5a6b44.png">

I've fixed the missing change links, but I'm not sure what the padding on that summary should be... will have to ask @will-madebymoon

2019-05-10 11:20 UTC, bameyrick commented
> The print button not looking so good today :P
> <img alt="Screenshot 2019-05-10 at 11 27 51" width="194" src="https://user-images.githubusercontent.com/35296336/57520874-b2ef1b00-7316-11e9-85c0-9cae8f6e34c7.png">

This will be fixed once this pr is merged and released: https://github.com/ONSdigital/design-system/pull/362

2019-05-10 11:24 UTC, bameyrick commented
> eady rendered in. Give me a shout if it doesn't make sense and I'll explain in person. Doesn't happen with the current version of v3.

Will need to take a look when we're both in, it shouldn't be slow enough to see the flicker... we can raise a bug against that component in the design system.

2019-05-10 11:24 UTC, bameyrick commented
> For the summary and pages after summary ie, submission etc, the page content width has been increased, is that intentional?

All pages should be using 8 columns now rather than 7

2019-05-10 11:27 UTC, bameyrick commented
> On test_final_confirmation.json, the submit button is showing inline:
> ![submit-answers](https://user-images.githubusercontent.com/205209/57520451-9a323580-7315-11e9-86fd-c3827b25fc92.png)

I'll fix this

2019-05-10 12:29 UTC, MebinAbraham commented on templates/feedback.html
> +  <form id="feedback-form" method="POST">
There is no closing tag for `form` in this file.

2019-05-10 12:30 UTC, MebinAbraham commented on templates/feedback.html
> +  <form id="feedback-form" method="POST">
There is no closing tag for `<form>` in this file.

2019-05-10 14:21 UTC, ajmaddaford approved these changes

2019-05-10 14:27 UTC, bitdivision approved these changes

2019-05-10 15:16 UTC, bitdivision commented
🎉 👏

2019-05-10 15:39 UTC, merged

2019-05-10 15:58 UTC, bameyrick commented
![WholeNarrowAmurratsnake-size_restricted](https://user-images.githubusercontent.com/8447446/57540534-d761ec00-7344-11e9-855f-28bb1f1807a1.gif)