Dont update session expiry too much
ONSdigital/eq-survey-runner pull request #2046
Opened 2019-04-12 11:50 UTC by jonnyshaw89

### What is the context of this PR?
We are making a lot of writes to the session table that we potentially don't need to make.
When we create a new session from the `/session` login page, we create the session and then we make a request to update the expiry milliseconds later.
Also when we do a POST and redirect to a GET, we update the expiry on the POST and then again on the GET immediately after.

This PR introduces a change to not update the session expiry if it has been updated in the last 60 seconds

### How to review 
Does Session expiry continue to work as expected?

2019-04-16 07:05 UTC, MebinAbraham requested changes
Apart from the minor comments, have tested and seems to be working as expected. Should save a bunch of writes to db.  👍

2019-04-16 07:05 UTC, MebinAbraham commented on tests/app/authentication/test_authenticator.py
> +    def test_valid_user_does_not_extend_session_expiry_when_time_close(self):
```suggestion
    def test_valid_user_does_not_extend_session_expiry_when_expiry_less_than_60_seconds_different(self):
```
I don't think this really makes sense. Maybe like your other one?. I guess its less than or equal to though.

Or maybe
``` python
def test_valid_user_does_not_extend_session_expiry_when_expiry_not_greater_than_60_seconds_different(self):
```
Or even change the code to `>= 60`. 🤷‍♂️ 
Up to you.

2019-04-16 07:09 UTC, MebinAbraham commented on tests/app/authentication/test_authenticator.py
> +    def test_valid_user_extends_session_expiry_when_expiry_greater_then_60_seconds_different(self):
```suggestion
    def test_valid_user_extends_session_expiry_when_expiry_greater_than_60_seconds_different(self):
```

2019-04-17 06:02 UTC, MebinAbraham approved these changes

2019-04-25 11:32 UTC, bitdivision approved these changes
:+1:

2019-04-25 12:25 UTC, merged