Update jsonnet census schema
ONSdigital/eq-survey-runner pull request #2053
Opened 2019-04-23 14:25 UTC by bambrp

### What is the context of this PR?
This PR integrates requested changes to the schema into the Jsonnet scripts that are processed to form the individual census JSON.

### How to review 
Compile the Jsonnet to JSON by running scripts/build_schema.sh.
Check out and locally run the v3 branch of the eq-schema-validator.
Using a REST client of your choice (e.g. Insomnia), send the census-individual.json to the service's /validate endpoint.
Observe a 200 HTTP status code, and an empty JSON response, confirming it is compliant.

2019-04-29 10:39 UTC, charlotte-hirst commented on data-source/blocks/individual/employment/main_employment_block.jsonnet
> +            text: '<em>{person_name_possessive}</em> main job',
This can be changed to just "Main job" so its the same across proxy and self complete

2019-04-29 10:39 UTC, charlotte-hirst commented on data-source/blocks/individual/employment/main_employment_block.jsonnet
> +          title: 'Your last main job',
Can be changed to just "Last main job" for both proxy and self complete

2019-04-29 10:39 UTC, charlotte-hirst commented on data-source/blocks/individual/qualifications/gcse.jsonnet
>    routing_rules: [
The when condition for appreticeship-answer needs to be removed from this block as its not part of the routing rules

2019-04-29 10:49 UTC, bambrp commented on data-source/blocks/individual/qualifications/gcse.jsonnet
>    routing_rules: [
Done :thumbsup:

2019-04-29 10:49 UTC, bambrp commented on data-source/blocks/individual/employment/main_employment_block.jsonnet
> +          title: 'Your last main job',
done :thumbsup:

2019-04-29 10:49 UTC, bambrp commented on data-source/blocks/individual/employment/main_employment_block.jsonnet
> +            text: '<em>{person_name_possessive}</em> main job',
done :thumbsup:

2019-05-01 14:15 UTC, ajmaddaford requested changes

2019-05-01 14:15 UTC, ajmaddaford commented on data-source/blocks/individual/employment/jobseeker.jsonnet
> +    hide_guidance: 'Why do I need to answer if I am retired or long term sick or disabled',
I don't think these lines of text should be different. If not, it might be clearer to go back to having a separate variables for title and guidance text. So we'd have:
```
nonProxyGuidance = 'Why do I need to answer if I am retired or long term sick or disabled?';
proxyGuidance = 'Why do I need to answer if they have retired or are long term sick or disabled?';
```

2019-05-01 14:15 UTC, ajmaddaford commented on data-source/blocks/individual/identity-and-health/disability_limitation.jsonnet
> +};
I think we're losing some clarity by creating an object with both title and definitions. It's also not clear as we use options elsewhere to refer to answer options. This could be achieved by having `nonProxyTitle` and `nonProxyDefinition` etc.

2019-05-01 14:15 UTC, ajmaddaford commented on data-source/blocks/individual/qualifications/apprenticeship.jsonnet
> +};
I don't think the nesting in the variable is unnecessary - the guidance and content structure could be in `question` as it's common to both?

2019-05-02 12:26 UTC, bambrp commented on data-source/blocks/individual/qualifications/apprenticeship.jsonnet
> +};
Fixed, just a simple string now (or most minimal structure depending on situation)

2019-05-02 12:27 UTC, bambrp commented on data-source/blocks/individual/identity-and-health/disability_limitation.jsonnet
> +};
All examples I could find now broken apart and disassociated.

2019-05-02 12:28 UTC, bambrp commented on data-source/blocks/individual/employment/jobseeker.jsonnet
> +    hide_guidance: 'Why do I need to answer if I am retired or long term sick or disabled',
Fixed, broken apart wherever possible, and identical strings dried up.

2019-05-02 15:24 UTC, ajmaddaford requested changes

2019-05-02 15:24 UTC, ajmaddaford commented on data-source/blocks/individual/identity-and-health/language.jsonnet
> +local question(title, definitionContent, regionOptions) = {
Minor, `regionOptions` is only ever one item, so should be `regionOption` (or possibly `regionalOption`).

2019-05-02 15:24 UTC, ajmaddaford commented on data-source/blocks/individual/identity-and-health/language.jsonnet
> +  title: 'What do we mean by “main language”?',
This is duplicated in the proxy and non-proxy version, it could be simplified to just having the content description as a variable.

2019-05-02 15:43 UTC, bitdivision approved these changes
Looks good to me. The content seems to pretty much match the document, but I haven't been through it in detail. The jsonnet makes sense.

2019-05-02 16:15 UTC, ajmaddaford approved these changes

2019-05-02 17:04 UTC, closed without merging