Generate user_id and user_ik using the response_id
ONSdigital/eq-survey-runner pull request #2069
Opened 2019-05-08 12:48 UTC by bitdivision

### What is the context of this PR?
See [trello](https://trello.com/c/RPDhFERZ/2981-jwt-claims-generate-userid-userik-from-responseid).

Previously we used a combination of `collection_exercise_sid, eq_id, form_type, ru_ref` to create the `user_id` and `user_ik`. Upstream will now be sending a `response_id` which is to replace the above fields during generation of `user_id` / `user_ik`.

I have made the `response_id` field mandatory on the assumption that upstream are currently sending it.

### How to review 

This PR can be tested in combination with the [go-launcher PR](https://github.com/ONSdigital/go-launch-a-survey/pull/134) and [benchmark PR](https://github.com/ONSdigital/eq-survey-runner-benchmark/pull/4/files).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2019-05-08 13:39 UTC, MebinAbraham approved these changes
Since this is mandatory, we should add it to?
https://github.com/ONSdigital/eq-survey-runner/blob/v3/app/storage/metadata_parser.py#L52-L77

We should also add a validator for it?.

2019-05-08 13:39 UTC, MebinAbraham requested changes
Wrong button ☝️

2019-05-09 07:59 UTC, bitdivision commented
I have added a validator for numeric strings, with a length parameter.

2019-05-09 08:44 UTC, MebinAbraham commented on app/storage/metadata_parser.py
> +def numeric_string_parser(to_parse, length=None):
To keep it consistent with the other method?
`to_parse` > `string_value`?, or `string_to_parse`.

2019-05-09 09:26 UTC, ajmaddaford requested changes
I think we should be more flexible in what we allow in response id. The current requirements are for a numeric string, but other clients may want to use something like a uuid. The main concern is ensuring it is long enough as we use it to generate the user id and ik. For this, the length validation is appropriate, but I'd consider deferring that work into another card for replacing the current implementation with something like Marshmallow.

2019-05-09 09:26 UTC, ajmaddaford commented on app/authentication/user_id_generator.py
> +        token_data = UserIDGenerator._get_token_data(metadata)
Now that `response_id` is the only field we're using from the metadata, we should change the `generate_id` and `generate_ik` methods to accept that as a parameter rather than all of the metadata.

2019-05-09 09:26 UTC, ajmaddaford commented on app/authentication/user_id_generator.py
> +            raise InvalidTokenException('Missing value for response_id in JWT token')
Does this ever happen given the claims are validated in `metadata_parser.py`?

2019-05-09 09:26 UTC, ajmaddaford commented on app/utilities/strings.py
> +def generate_numeric_string(length=16):
I don't think this needs to be factored out into it's own method in another file as this is only used in one place.

2019-05-09 09:26 UTC, ajmaddaford commented on tests/app/authentication/test_user_id_generator.py
> +        user_id_3 = id_generator.generate_id(self.create_token('0000000000000000'))
The `create_token` method could be removed if `generate_id` was refactored as previously mentioned.

2019-05-10 06:22 UTC, MebinAbraham reviewed
The `response_id` should be in the submission payload?

2019-05-10 10:10 UTC, ajmaddaford approved these changes

2019-05-10 11:44 UTC, MebinAbraham approved these changes

2019-05-10 12:46 UTC, merged