Add proposal for lookups
ONSdigital/eq-survey-runner pull request #2070
Opened 2019-05-08 15:30 UTC by iwootten

### What is the context of this PR?

This proposes how lookups might be represented in a survey schema. 

### How to review 

See if you think the proposal makes sense.
Is there anything I've missed?

2019-05-08 15:31 UTC, iwootten commented
I had pondered whether including a limit for the number of results to display might be appropriate?

2019-05-09 08:17 UTC, bitdivision commented
I think when this was initially discussed, we talked about having the ability to avoid using a lookup api for simple lookups, i.e. where there are not many options. Obviously there are some disadvantages to this, so I assume this was ruled out?

2019-05-09 08:59 UTC, iwootten commented
@bitdivision - don't remember that conversation, but I guess that's still an option if we set a flag to indicate the query_path will come from runner host itself?

2019-05-09 09:41 UTC, ajmaddaford commented
@bitdivision I think the intent of the lookup has changed as it's gone through user testing. The current design/prototype is for the suggestions from the lookup to behave more like a search than an autocomplete. If we weren't using the api we'd end up having to have two implementations of that, one client side and another in the api.

2019-05-09 09:50 UTC, ajmaddaford commented on doc/architecture/decisions/0008-lookups.md
> +The answer behaves as a Textfield when JavaScript is disabled and specifies a query_path for the frontend component to retrieve suggestions from when enabled.
I think it behaves as a Textfield regardless of Javascript. The Javascript will add the suggestions list below the textfield.

![image](https://user-images.githubusercontent.com/1754822/57444375-ef077a80-7247-11e9-8188-3d5afaad8cba.png)

2019-05-09 10:02 UTC, pricem14pc commented
> I think when this was initially discussed, we talked about having the ability to avoid using a lookup api for simple lookups, i.e. where there are not many options. Obviously there are some disadvantages to this, so I assume this was ruled out?

Presumably all the look ups need to behave the same regardless of the number of entries in the datasets? Unless a simple lookup could replicate the behaviour of an elasticsearch api (e.g. partial tokenized matches etc) then it might impact the user experience.

2019-05-09 14:31 UTC, ajmaddaford approved these changes

2019-05-09 14:38 UTC, bitdivision approved these changes

2019-05-10 06:54 UTC, MebinAbraham requested changes
>I had pondered whether including a limit for the number of results to display might be appropriate?

Do we not want to do add an option for this, instead of leaving it to the front end to determine a hard limit on all look ups?.

Is the only reason we may not want it to be configurable in the schema is that it's researched and the current hard limit just works and wouldn't need changing?

@iwootten @ajmaddaford @bitdivision

2019-05-10 06:56 UTC, MebinAbraham commented on doc/architecture/decisions/0008-lookups.md
> +The answer behaves as a Textfield and specifies a query_path for the frontend component to retrieve suggestions from when JavaScript is enabled.
🤷‍♂ Personally prefer if variables in sentences are highlighted in some way.
```suggestion
The answer behaves as a Textfield and specifies a `query_path` for the frontend component to retrieve suggestions from when JavaScript is enabled.
```

2019-05-10 06:56 UTC, MebinAbraham commented on doc/architecture/decisions/0008-lookups.md
> +The hostname would be combined with the query_path attribute at runtime to determine the full api url.
```suggestion
The hostname would be combined with the `query_path` attribute at runtime to determine the full api url.
```

2019-05-10 07:08 UTC, MebinAbraham commented
Does `path_to_query` need to live in the schema?. Have we considered a `lookup_type` option instead?

2019-05-10 08:00 UTC, bitdivision commented
@MebinAbraham Regarding the number of items shown, we discussed this briefly yesterday and I think the conclusion was that there should be one number which makes sense for all devices and that number can be chosen by the product owner. There shouldn't ever be a need to modify it on a per schema basis.

2019-05-10 11:56 UTC, MebinAbraham approved these changes

2019-05-10 12:44 UTC, bitdivision approved these changes

2019-05-10 13:42 UTC, merged