Use .env file for environment variables
ONSdigital/eq-survey-runner pull request #2089
Opened 2019-05-20 11:20 UTC by ajmaddaford

### What is the context of this PR?

Adds a .development.env file with developer defaults. This provides one
common place to set defaults (used both locally and in Docker) and
should stop people having environment issues when new variables are
added to runner. It should also mean less configuration for code editors.

Also introduces a Makefile for running the various commands - less typing
and tab completion on compatible shells.

The jwt-test-secrets and jwt-test-keys have been removed as we default to using the built dev-secrets.yml and dev-keys.yml.

### How to review 
- Try following the updated Readme to run locally and in Docker
- Try all the commands in the Makefile
- Try your integrating with your code editor of choice

2019-05-20 11:33 UTC, jonnyshaw89 reviewed
👍 Lots of deletes

2019-05-20 11:33 UTC, jonnyshaw89 commented on .development.env
> +EQ_RABBITMQ_ENABLED=False
this is an old var. I cant find it used anywhere

2019-05-21 07:03 UTC, MebinAbraham commented
Makefile finally 👍

2019-05-21 07:42 UTC, jonnyshaw89 requested changes
Also as spoken about IRL the keys are missing for the integration tests to launch

2019-05-21 07:42 UTC, jonnyshaw89 commented on Makefile
> +	docker-compose -f docker-compose-dev.yml up -d
You need to change references to `go-launch-a-survey` to `eq-questionnaire-launcher` in both compose files.
@bitdivision must have missed them when forking the launcher repo

2019-05-21 14:49 UTC, jonnyshaw89 commented
`EQ_PROFILING` is left behind in `settings.py`

2019-05-21 14:50 UTC, jonnyshaw89 commented on README.md
> +## Profiling
This section needs updating

2019-05-22 07:41 UTC, jonnyshaw89 approved these changes

2019-05-22 08:53 UTC, MebinAbraham approved these changes
👍

2019-05-22 12:53 UTC, merged