Add a linux compatible compose file
ONSdigital/eq-survey-runner pull request #2099
Opened 2019-05-23 13:16 UTC by JamesGardiner

### What is the context of this PR?
Adds a Linux specific compose file and supporting Makefile targets.

### How to review 
Using a Linux host, run `make dev-compose-up-linux`, once everything successfully starts, run `make dev-compose-down-linux`.

2019-05-23 14:08 UTC, jonnyshaw89 commented
How do I test this? 😆

2019-05-23 14:10 UTC, JamesGardiner commented
@jonnyshaw89 🍓🥧

2019-05-23 14:11 UTC, JamesGardiner commented
*raspberry pi???

2019-05-23 14:11 UTC, JamesGardiner commented
Linux VM...

2019-05-24 13:09 UTC, bitdivision approved these changes
Works for me

2019-05-31 08:52 UTC, ajmaddaford requested changes

2019-05-31 08:52 UTC, ajmaddaford commented on docker-compose-dev-linux.yml
> +  go-launch-a-survey:
This should be `eq-questionnaire-launcher` rather than `go-launch-a-survey`

2019-05-31 09:42 UTC, ajmaddaford approved these changes

2019-06-03 08:10 UTC, merged