Updating the default path for unanswered voluntary questions
ONSdigital/eq-survey-runner pull request #2127
Opened 2019-06-14 12:45 UTC by berroar

### What is the context of this PR?
We need to change the validation and build the default path for unanswered voluntary questions (currently for England and Wales only).

### How to review 
Build and Test the schema changes.

Check that unanswered voluntary questions route correctly through the survey. 
The correct path for unanswered questions is described in column E of the spreadsheet attached to the Trello Card [(here)](https://trello.com/c/qG5xkN0j/3033-voluntary-questions-and-default-path-eng-wls-m).

2019-06-17 09:54 UTC, bambrp commented
term-time-location: routing leaps you to comments block if answering anything other than household address

2019-06-18 12:41 UTC, MebinAbraham requested changes
On what is your name, (Position in establishment and proxy question not answered)
**Expected:** go to DOB
**Actual:** Got asked 'Position in establishment'

---

If you answer `No` to `Does M A stay at another address for more than 30 days a year?` then selecting `Another address` on `During term time, where does M A usually live?` shows you `Is this address in the UK?` but this question isn't shown if you answered `Yes, an address within the UK` for 
`Does M A stay at another address for more than 30 days a year?` even if you chose `Another address` in later question. Is that expected?

---

I was not able to view: `Did you arrive in the UK on, or after 12 June 2019?` and related question even though I believed I answered as needed. Not clear from google sheets what I need to do to view that question.

2019-06-19 11:15 UTC, berroar commented
> On what is your name, (Position in establishment and proxy question not answered)
> **Expected:** go to DOB
> **Actual:** Got asked 'Position in establishment'
> 
> If you answer `No` to `Does M A stay at another address for more than 30 days a year?` then selecting `Another address` on `During term time, where does M A usually live?` shows you `Is this address in the UK?` but this question isn't shown if you answered `Yes, an address within the UK` for
> `Does M A stay at another address for more than 30 days a year?` even if you chose `Another address` in later question. Is that expected?
> 
> I was not able to view: `Did you arrive in the UK on, or after 12 June 2019?` and related question even though I believed I answered as needed. Not clear from google sheets what I need to do to view that question.

Have fixed the issue with the routing from the name question.

For the third issue, It looks like the recent change to the census date (which is now mid-month) has broken the current routing rule. This will need to be fixed.

2019-06-20 06:46 UTC, MebinAbraham approved these changes

2019-06-20 09:51 UTC, JamesGardiner approved these changes

2019-06-20 11:05 UTC, merged