Fix Google Tag Manager 403 Error
ONSdigital/eq-survey-runner pull request #2131
Opened 2019-06-18 12:34 UTC by rmccar

### What is the context of this PR?
This PR is to fix the 403 error on Google Tag Manager. The fix was to change the order the variables are passed in. The ID of the GTM container is now passed in before the environment.

### How to review 
Run locally and see that the GTM preview mode displays on Runner

2019-06-18 12:44 UTC, samiwel requested changes
Looks good to me just turn off your auto formatter 👍

2019-06-18 12:44 UTC, samiwel commented on app/templates/layouts/_base.html
> +    <meta name="theme-color" content="#ffffff" />
Can you revert these changes ☝️ I think they were introduced by your auto-formatting settings, but it just makes it more difficult to see what the actual change was.

2019-06-18 14:59 UTC, samiwel approved these changes

2019-06-19 07:35 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Turn on tag manager/GA for Runner (1)](https://trello.com/c/Bc2H7IbD/1021-turn-on-tag-manager-ga-for-runner-1)

2019-06-19 08:22 UTC, tgandrews approved these changes

2019-06-19 08:25 UTC, merged