Fix error skip links
ONSdigital/eq-survey-runner pull request #2202
Opened 2019-07-15 10:22 UTC by bameyrick

### What is the context of this PR?
Fix the skip links for errors which autofocus the related field.

Affected answer types:
- Date input (fixed by design system update in previous PR)
- Durations

2019-07-15 10:22 UTC, bameyrick commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue ID: DAC_Broken_Skip_Link_Issue1](https://trello.com/c/kvgKpncJ/3116-issue-id-dacbrokenskiplinkissue1)

2019-07-16 06:48 UTC, MebinAbraham commented on app/jinja_filters.py
> +        answer['type'] == 'Date' or answer['type'] == 'Duration' for answer in answers
```suggestion
        answer['type'] in ['Date', Duration'] for answer in answers
```
Are there other types that need to be considered such as MonthYear date types etc?

2019-07-16 06:48 UTC, MebinAbraham reviewed
How do I test this?. It seems to focus on the field on v3?

2019-07-16 08:35 UTC, MebinAbraham commented on app/jinja_filters.py
> +        answer['type'] in ['Date', 'MonthYearDate', 'Duration'] for answer in answers
We also have `YearDsate` type. Also since Duration type is checked here, are `Unit` types special?

2019-07-16 08:56 UTC, JamesGardiner requested changes

2019-07-16 08:56 UTC, JamesGardiner commented on app/jinja_filters.py
> +        answer['type'] in ['Date', 'MonthYearDate', 'Duration'] for answer in answers
```suggestion
        answer['type'] in {'Date', 'MonthYearDate', 'Duration'} for answer in answers
```

Set lookup is far quicker than list lookup

2019-07-16 09:12 UTC, bameyrick commented on app/jinja_filters.py
> +        answer['type'] in ['Date', 'MonthYearDate', 'Duration'] for answer in answers
Year only renders one field so it doesn't wrap itself in a fieldset, so if there were multiple year answers this would be valid. Units are also considered as an answer each so this should still cater for that

2019-07-16 09:39 UTC, MebinAbraham approved these changes

2019-07-16 13:07 UTC, JamesGardiner approved these changes

2019-07-16 13:50 UTC, merged