Update to to design system 13.1.3
ONSdigital/eq-survey-runner pull request #2206
Opened 2019-07-16 10:24 UTC by bameyrick

- Updated how field errors are rendered – Error object is now passed to input but only one error is accepted. This will require a refactor of how field errors are handled as they currently pass an array.
- Updated 500 error page to match what's documented in the design system: https://ons-design-system.netlify.com/patterns/error-status-pages/#500-server-errors
- Updated durations answer to use new duration component: https://ons-design-system.netlify.com/patterns/durations/

2019-07-16 10:28 UTC, bameyrick commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update to design-system 13.1.0](https://trello.com/c/bMrbC4r6/3147-update-to-design-system-1310)

2019-07-25 12:20 UTC, iwootten commented
I've added a couple of changes here that move the title handling to the back end and gives the ability to set a default error page. It's likely that this will be handled better as part of the view refactor work coming in here https://github.com/ONSdigital/eq-survey-runner/pull/2228

2019-07-30 08:16 UTC, ajmaddaford requested changes

2019-07-30 08:16 UTC, ajmaddaford commented on templates/layouts/_error.html
> +  {% include 'partials/errors/' ~ status_partial ~ '.html' %}
Why have the include? The relevant template is known by the handling code in `errors.py`.

2019-07-30 09:26 UTC, ajmaddaford commented on templates/errors/401.html
> +{% endblock %}
I don't think this template is used, as 401 errors seem to use the `session-expired` template?

2019-07-31 10:20 UTC, ajmaddaford commented on app/routes/errors.py
> +
We could remove the error map and move the strings to the templates, setting `page_title` as we do for example in `signed-out.html`.

2019-07-31 11:52 UTC, ajmaddaford commented on app/routes/errors.py
> +    template = template or status_template
```suggestion
    template = template or status_code
```

2019-07-31 12:35 UTC, ajmaddaford approved these changes

2019-07-31 15:09 UTC, bitdivision commented on app/routes/errors.py
> +    return _render_error_page(500)
Why has this been changed to 500? And should it log a 500 too?

2019-07-31 15:23 UTC, bitdivision approved these changes
Changes all seem reasonable. 

As discussed with @ajmaddaford and @iwootten we should remove all references to 503 (in logs) and check whether displaying a normal 500 is okay on a failed submission.

2019-08-01 08:41 UTC, bitdivision approved these changes

2019-08-01 10:47 UTC, merged