Schema changes for HH accomodation type Eng & Wal
ONSdigital/eq-survey-runner pull request #2280
Opened 2019-08-14 11:53 UTC by JamesGardiner

### What is the context of this PR?
Schema changes for Household England and Wales Survey accommodation section.

### How to review 
Build the new schema changes. Test that the house hold accommodation flow is as specified in  https://trello.com/c/s3FsJSyh/3209-household-accommodation-eng-wls

2019-08-14 12:59 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Household accommodation Eng/Wls](https://trello.com/c/s3FsJSyh/3209-household-accommodation-eng-wls)

2019-08-14 13:18 UTC, berroar reviewed
The default routing looks good and I am able to skip through the non mandatory questions

2019-08-15 08:01 UTC, MebinAbraham requested changes
Routing/Validation is fine.

Translation POT files need to be updated.

Also:

2019-08-15 08:01 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/lib/rules.libsonnet
> +  accomodationNotAnswered: {
This doesn't seem to be used.

2019-08-15 09:17 UTC, MebinAbraham approved these changes

2019-08-15 09:21 UTC, berroar approved these changes

2019-08-15 12:26 UTC, merged