Add lists to section summary
ONSdigital/eq-survey-runner pull request #2293
Opened 2019-08-19 08:40 UTC by iwootten

### What is the context of this PR?

Section summary now includes a summary of list collectors within a section. It is assumed traditional questions won't be mixed with list collector sections, so list collector summaries appear beneath a usual section summary to reduce the complexity of mixing different content types on templates. This also means all summaries can continue to share the same template.

### How to review 

See if you agree with the keys that have been added, the way additional context has been introduced for views.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2019-08-21 07:18 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add lists to section summary (L)](https://trello.com/c/7ld7bDvO/3134-add-lists-to-section-summary-l)

2019-08-21 07:40 UTC, iwootten commented on scripts/test_schemas.sh
> +    branch="eq-3134-add-lists-to-section-summary"
Reminder to be changed back once the validator PR is merged

2019-08-21 08:50 UTC, LJBabbage reviewed
Not sure this is working for me, using test_list_collector_section_summary.json I get a grey button on the last screen that doesn't seem to do anything
<img width="1280" alt="Screen Shot 2019-08-21 at 09 49 30" src="https://user-images.githubusercontent.com/14179817/63417396-15b57f80-c3f9-11e9-96f9-ecf26ff16bf9.png">

2019-08-21 08:56 UTC, iwootten commented
> Not sure this is working for me, using test_list_collector_section_summary.json I get a grey button on the last screen that doesn't seem to do anything

Yes, that's the final summary as it stands - included here only because validator requires it.

2019-08-21 10:00 UTC, ajmaddaford requested changes
Looks good. The assumptions made about when lists will appear on section summaries makes sense. 

When choosing add/edit/remove from the section summary and then submitting the add/edit/remove screen, the user should be returned to the section summary rather than the list collector.

2019-08-21 10:00 UTC, ajmaddaford commented on app/views/contexts/summary_context.py
> +        list_item_summaries.append(list_item_summary)
I think when referring to the summary of a list we should not include the word `item` i.e. `list_item_summary` should be shortened to `list_summary` and `list_item_summaries` to `list_summaries`.

2019-08-21 10:00 UTC, ajmaddaford commented on tests/app/views/contexts/conftest.py
> +    return ListStore([{'items': ['PlwgoG', 'UHPLbX', 'FnoDHP'], 'name': 'people'}])
Where does `FnoDHP` come from?

2019-08-21 10:14 UTC, iwootten commented on tests/app/views/contexts/conftest.py
> +    return ListStore([{'items': ['PlwgoG', 'UHPLbX', 'FnoDHP'], 'name': 'people'}])
This is an old item that is no longer in the tests

2019-08-21 10:21 UTC, iwootten commented
> When choosing add/edit/remove from the section summary and then submitting the add/edit/remove screen, the user should be returned to the section summary rather than the list collector.

We had a couple of discussions around this in your absence, we decided the collector confirmation step and then return to summary was good enough. As discussed offline, given as this behaviour has been added as part of @MebinAbraham's work, we should create a card to return to the summary immediately using it once merged.

2019-08-21 10:39 UTC, iwootten commented
Added a card to cover returning to summary here: https://trello.com/c/yq5GWXVc/3231-add-returnto-parameter-to-list-summaries

2019-08-21 13:32 UTC, ajmaddaford commented on app/views/contexts/list_collector.py
> +        for answer in list_collector_block['add_block']['question']['answers']
This breaks if there are variants in the `add_block`. I've had a look and I don't think `list_answer_ids` is needed as it's only used to add an `answers` key to the list item, which is not used now that `item_title` exists.

2019-08-21 14:24 UTC, ajmaddaford approved these changes

2019-08-22 09:00 UTC, MebinAbraham requested changes

2019-08-22 09:00 UTC, MebinAbraham commented on app/views/contexts/summary_context.py
> +            'title': list_collector_block['summary']['title'],
We need to add support to placeholder rendering for `title` as on census it pipes in the census date.

2019-08-22 12:34 UTC, MebinAbraham approved these changes

2019-08-22 13:16 UTC, merged