Simplify Summary Context
ONSdigital/eq-survey-runner pull request #2313
Opened 2019-08-27 08:36 UTC by iwootten

### What is the context of this PR?

As part of the work done in https://github.com/ONSdigital/eq-survey-runner/pull/2293 it was very difficult to understand how summaries were constructed due to the nesting of multiple classes to construct the final summary dictionary. 

The summary context class also has a large number of similarly named methods which operate on the same arguments, all called by different handlers. Most of these arguments are passed in order to construct other objects and evaluate when rules deeper down through multiple method calls. 

This change seeks to remove some of the classes used only to serialise a summary, whilst using the a child class structure within handlers to share behaviour amongst each of the different Summary types. The summary tests have also been broken apart and are testing against appropriate handlers.

### How to review 

See if you agree with the design/approach. Overall, it's up for debate whether handlers should be returning context or calling matching classes to return it. In the case of summaries, there is nothing to each handler, so context can easily be created there without confusion.

2019-08-28 12:41 UTC, JamesGardiner requested changes
This looks like a positive change to me, but I do have some issues with the current changes:

1. The code slips too easily into heavily nested block of loops and if statements. Where it makes sense code should be flat not nested.
2. There are a number of functions and methods which are unacceptably large and obtuse, and should be refactored if they are going to be part of the pr

2019-08-28 12:41 UTC, JamesGardiner commented on app/routes/questionnaire.py
> +            submitted_path_finder = PathFinder(schema, answer_store, metadata=metadata)
```suggestion
            path_finder = PathFinder(schema, answer_store, metadata=metadata)
```

2019-08-28 12:41 UTC, JamesGardiner commented on app/routes/questionnaire.py
> +                schema=schema, path_finder=submitted_path_finder
```suggestion
                schema=schema, path_finder=path_finder
```

2019-08-28 12:41 UTC, JamesGardiner commented on app/routes/questionnaire.py
> +            for group in context.get('summary').get('groups'):
```suggestion
            for group in context['summary']['groups']:
```

2019-08-28 12:41 UTC, JamesGardiner commented on app/routes/questionnaire.py
> +                for this_block in group.get('blocks'):
This could be flattened:

```Python
args = (answer_store, list_store, metadata, schema, None)
this_block['question'] = Block.get_question(this_block['id'], *args)
```

2019-08-28 12:41 UTC, JamesGardiner commented on app/routes/questionnaire.py
> +                for this_block in group.get('blocks'):
With the args tuple defined outside of the loop

2019-08-28 12:41 UTC, JamesGardiner commented on app/views/handlers/calculated_summary.py
> +def _get_formatted_total(
These huge functions need refactoring.

2019-09-03 07:27 UTC, iwootten commented on app/routes/questionnaire.py
> +            submitted_path_finder = PathFinder(schema, answer_store, metadata=metadata)
This conflicts with the global already imported in the file.

2019-09-04 08:30 UTC, closed without merging