fixed wording
ONSdigital/eq-survey-runner pull request #2334
Opened 2019-09-01 15:25 UTC by rmccar

### What is the context of this PR?
PR raised for content changes

### How to review 
Go through survey until you hit a summary page then make sure that the wording has changed

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2019-09-01 16:59 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Summary screen template change (xs)](https://trello.com/c/79kEkzX0/3266-summary-screen-template-change-xs)

2019-09-02 14:24 UTC, JamesGardiner requested changes

2019-09-02 14:24 UTC, JamesGardiner commented on app/translations/cy/LC_MESSAGES/messages.po
> +msgid "You can check your answers below"
As discussed, po files don't need to be manually updated.

2019-09-02 14:24 UTC, JamesGardiner commented on app/translations/ga/LC_MESSAGES/messages.po
> +msgid "You can check your answers below"
This can be reverted as well

2019-09-02 15:05 UTC, MebinAbraham approved these changes

2019-09-03 06:34 UTC, JamesGardiner approved these changes

2019-09-03 06:35 UTC, merged