Ensure summary context is rendered using current language code
ONSdigital/eq-survey-runner pull request #2343
Opened 2019-09-03 12:04 UTC by MebinAbraham

### What is the context of this PR?
The summary was not rendering context with `language_code` in mind. This PR ensures that the current `language_code` is used when rendering the context on the summary.

### How to review 
Ensure:
- When switching languages on the summary, context is rendered as expected.

2019-09-03 12:04 UTC, MebinAbraham commented
![](https://github.trello.services/images/mini-trello-icon.png) [Welsh language issues](https://trello.com/c/eDqVO3Mc/3268-welsh-language-issues)

2019-09-03 13:39 UTC, JamesGardiner approved these changes

2019-09-03 14:42 UTC, MebinAbraham commented on tests/integration/questionnaire/test_questionnaire_placeholders.py
> +    def test_title_placeholders_rendered_in_summary_using_correct_language_en(self):
```suggestion
    def test_title_placeholders_rendered_in_summary_using_correct_language(self):
```

2019-09-04 09:37 UTC, rmccar approved these changes

2019-09-04 09:59 UTC, merged

2019-09-04 11:16 UTC, ajmaddaford requested changes

2019-09-04 11:16 UTC, ajmaddaford commented on tests/app/questionnaire/test_placeholder_renderer.py
> +                'second_date': {'value': '2019-02-01'},
Is this just changing the `second_date` value? If so it would be much clearer if it just changed that value 
```python
json_to_render['answers'][0]['options'][0]['label']['placeholders'][1]['transforms'][0]['arguments']['second_date']['value'] = '2019-02-01'
```

Although it would be better if we replaced the question json with a method that took the date as a parameter and returned the json.

Actually, can the date just be changed in the question json?

2019-09-04 11:32 UTC, MebinAbraham commented on tests/app/questionnaire/test_placeholder_renderer.py
> +                'second_date': {'value': '2019-02-01'},
Too slow 😄 . Good shout, yes it can just be changed in the question JSON. Can address in a future PR.