Fix relaunch after adding visitor
ONSdigital/eq-survey-runner pull request #2361
Opened 2019-09-09 15:57 UTC by JamesGardiner

### What is the context of this PR?
Fixes a bug where, after signing out once completing the any visitors question, users would enter an infinite redirects situation.

### How to review 
Follow these steps:

1. Launch the census household survey
2. Add three people to the household
3. Add a visitor to the household
4. Sign out
5. Launch the survey with the same response id
6. Ensure you are redirected to the who lives here section summary page.

2019-09-09 15:57 UTC, JamesGardiner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Relaunch after adding visitor error](https://trello.com/c/tm8Budnx/3294-relaunch-after-adding-visitor-error)

2019-09-10 11:11 UTC, berroar approved these changes
Tested the change - all looks OK

2019-09-11 08:03 UTC, MebinAbraham requested changes
Very minor comment otherwise looks good 👍

2019-09-11 08:03 UTC, MebinAbraham commented on tests/integration/questionnaire/test_questionnaire_save_sign_out.py
> +        self.post({'visitor-answer': 'No, I do not need to add anyone'})
Can you add an assertion here to assert that you are on the Section Summary, since this change is based on that condition?
```py
self.assertInUrl('/who-lives-here-section-summary')
```

2019-09-11 08:03 UTC, MebinAbraham commented on app/questionnaire/path_finder.py
> +        if not location:
Up to you.
```python
        if not location or (
            location == path[-1]
            and self.schema.get_block(location.block_id)['type'] == 'SectionSummary'
        ):
            return True

        return False
```

2019-09-11 08:13 UTC, rmccar approved these changes
Mebin makes a good point but other than that looks good

2019-09-11 11:37 UTC, MebinAbraham approved these changes

2019-09-11 12:50 UTC, merged