Update WLH to use ListCollectorDrivingQuestion
ONSdigital/eq-survey-runner pull request #2367
Opened 2019-09-11 15:36 UTC by iwootten

Due to the complexity of the scenarios for the household composition, we can't have a driving question when there are multiple list collectors for the same list. 

To fully resolve links on the summary for the household list, the current household schema should be modified to use variants over a driving question.

Additionally, we should update the visitors list to use a driving question single list collector.

### What is the context of this PR?

https://github.com/ONSdigital/eq-survey-runner/pull/2348

### How to review 

Go through WLH within census for eng/nir. You should see different variants whether you have entered anyone to the household or not. Answering either no/yes to each additional person within each household/visitor list collector.

There shouldn't be any broken links on the summary.

2019-09-11 15:36 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add person to household on section summary doesn't work when "No, no one usually lives here" is selected](https://trello.com/c/o0W9MfTh/3304-add-person-to-household-on-section-summary-doesnt-work-when-no-no-one-usually-lives-here-is-selected)

2019-09-12 09:35 UTC, JamesGardiner approved these changes

2019-09-12 12:48 UTC, ajmaddaford requested changes

2019-09-12 12:48 UTC, ajmaddaford commented on data-source/jsonnet/england-wales/household/lib/rules.libsonnet
> +};
This condition is used in `central_heating.jsonnet` and `renewables.jsonnet`, we should replace  them with `listIsEmpty`.

2019-09-12 13:18 UTC, ajmaddaford approved these changes

2019-09-12 16:31 UTC, ajmaddaford requested changes
The visitors fix hasn't been applied to the NIR survey.

2019-09-13 06:38 UTC, ajmaddaford approved these changes
👍

2019-09-16 06:24 UTC, merged