Adding Gaelic translations for NI Household, Individual and static content
ONSdigital/eq-survey-runner pull request #2369
Opened 2019-09-12 13:51 UTC by berroar

### What is the context of this PR?
I have downloaded the latest Gaelic .po files for NI from Crowdin and have added them to the repo. I have also updated the translate scripts so that the NI Gaelic schemas are being generated during the build process.

### How to review 
Build the the new schemas and then check that the NI household and individual census surveys have been translated.

**Note**

There are some issues with the translations in Crowdin that need to be resolved. I have made the following amendments in the .po files that will now need to be done in Crowdin in order for the build process to run without error if the .po files are downloaded again:
- Removed translations for single letter strings. (census_household)
- Removed the 'num' placeholder from the translation for the string 'This page has an error'.  (messages)

There are other instances where translations will need to be updated in Crowdin as it appears that placeholders are being used in translated strings where they are not in the original.

2019-09-12 13:52 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Download Irish PO files (S)](https://trello.com/c/w7aDW5A4/3307-download-irish-po-files-s)

2019-09-13 06:28 UTC, JamesGardiner requested changes
As far as I can see the changes look good - you have a formatting error though so need to run Black against the repo :+1:

2019-09-13 07:55 UTC, ajmaddaford requested changes

2019-09-13 07:55 UTC, ajmaddaford commented on app/translations/ga/LC_MESSAGES/messages.po
> +msgstr[4] "Caithfear<strong>seo a cheartú</strong>le leanstan ar aghaidh"
There is a space missing before `<strong>`

2019-09-13 11:36 UTC, ajmaddaford approved these changes

2019-09-13 11:53 UTC, JamesGardiner approved these changes

2019-09-13 12:08 UTC, merged