Updated Gaelic and Ulster Scots translations
ONSdigital/eq-survey-runner pull request #2377
Opened 2019-09-16 12:21 UTC by berroar

### What is the context of this PR?
Updated the Gaelic and Ulster Scots Household and Individual census translations.

### How to review 
Check that the updated translations look OK.

2019-09-16 12:21 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Download Irish and US (HH & Ind)](https://trello.com/c/An562uJp/3321-download-irish-and-us-hh-ind)

2019-09-16 13:28 UTC, JamesGardiner approved these changes

2019-09-16 16:53 UTC, ajmaddaford requested changes

2019-09-16 16:53 UTC, ajmaddaford commented on app/translations/eo/LC_MESSAGES/messages.po
> +msgstr "Tha laa gies lave 'at wittins hauden fur nummerin ettlins alane, tha like o wittins frae yer spierin foarm, micht be hauden fur langer tacks. We'll jist haud tae hingin oan tae wittins anent
The href in this text is missing a closing quote, when rendered:
![image](https://user-images.githubusercontent.com/1754822/64977130-b8eb9e80-d8aa-11e9-9e98-c97315f74812.png)

2019-09-17 08:10 UTC, ajmaddaford approved these changes

2019-09-17 08:45 UTC, merged