Stopping names from appearing in Question Titles
ONSdigital/eq-survey-runner pull request #2382
Opened 2019-09-17 15:42 UTC by berroar

### What is the context of this PR?
This PR was raised to stop names from appearing in question page titles. 

It also includes a fix for content pages - they now use the content title where they used to use the group title within the page title.

### How to review 
Run a schema and check that:
- 'Question' Page titles no longer contain names.
- 'Content' pages now use the content title in the page title.
- Other page titles are correct
- Tests pass

2019-09-17 15:42 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Names are appearing in page titles in question](https://trello.com/c/z5qR48eU/3316-names-are-appearing-in-page-titles-in-question)

2019-09-18 06:34 UTC, MebinAbraham requested changes
Apart from my 1 minor comment, all looks good to me. 👍

2019-09-18 06:34 UTC, MebinAbraham commented on app/views/handlers/content.py
> +            if type(transformed_block['content']['title']) is str:
Can we use `isinstance` for consistency?
``` py
    def _get_page_title(self, transformed_block):
        content = transformed_block.get('content')
        if content:
            if isinstance(content['title'], str):
                content_title = content['title']
            else:
                content_title = content['title']['text']

            page_title = f'{content_title} - {self._schema.json["title"]}'

            return safe_content(page_title)
```

2019-09-18 07:25 UTC, JamesGardiner approved these changes
LGTM once @MebinAbraham 's changes have been addressed

2019-09-18 08:30 UTC, JamesGardiner requested changes
case_id needs to be added to the metadata in the failing test schema

2019-09-18 09:21 UTC, MebinAbraham approved these changes

2019-09-18 09:22 UTC, JamesGardiner commented on data-source/json/test_interstitial_page_title.json
> +        }
You can add this here:

```JSON
{
    "name": "case_id",
    "type": "string"
}
```

2019-09-18 10:44 UTC, JamesGardiner approved these changes

2019-09-18 11:13 UTC, merged