Update footer and feedback
ONSdigital/eq-survey-runner pull request #2384
Opened 2019-09-18 07:35 UTC by rmccar

### What is the context of this PR?
This PR is to update to the new footer and feedback design and also make some content changes

### How to review 
Check the footer and feedback is now the new design (some links may still not work as the pages for them are not live yet.

2019-09-18 16:21 UTC, MebinAbraham commented on templates/layouts/configs/_feedback.html
> +            "subject": _("Census%202021%20feedback%3A%20"),
```jinja
            "subject": _("Census 2021 feedback: "),
            "body": ("\n\n\n---\n" ~ _("This email is for feedback on the census rehearsal, which will help us to improve Census 2021. We are unable to respond to these emails.\nIf you need help with your census, visit https://www.census.gov.uk/contact-us.")) | urlencode,
```

2019-09-18 16:21 UTC, MebinAbraham commented on templates/layouts/configs/_feedback.html
> +            "body": _("%0D%0A%0D%0A%0D%0A%2D%2D%2D%0D%0AThis%20email%20is%20for%20feedback%20on%20the%20census%20rehearsal%2C%20which%20will%20help%20us%20to%20improve%20Census%202021.%20We%20are%20u
```jinja
            "subject": _("Census 2021 feedback: "),
            "body": ("\n\n\n---\n" ~ _("This email is for feedback on the census rehearsal, which will help us to improve Census 2021. We are unable to respond to these emails.\nIf you need help with your census, visit https://www.census.gov.uk/contact-us.")) | urlencode,
```

2019-09-18 17:51 UTC, MebinAbraham submitted a review, later dismissed
Has the colours been changed in the design system?. This is on click.
<img width="241" alt="Screenshot 2019-09-18 at 18 51 07" src="https://user-images.githubusercontent.com/35296336/65172669-55e23f00-da45-11e9-9712-4997ecfa784d.png">

2019-09-18 19:15 UTC, rmccar commented
> Has the colours been changed in the design system?. This is on click.
> <img alt="Screenshot 2019-09-18 at 18 51 07" width="241" src="https://user-images.githubusercontent.com/35296336/65172669-55e23f00-da45-11e9-9712-4997ecfa784d.png">

Yeah that was part of a PR to address an issue pulled up in the DAC report. It's to do with the contrast on focus not being enough before.

https://github.com/ONSdigital/design-system/pull/593

2019-09-19 09:36 UTC, ajmaddaford requested changes
I get an extra twisty character above the feedback link:
![image](https://user-images.githubusercontent.com/1754822/65232596-53c1c400-dac9-11e9-8dc5-77cee5322cf2.png)

2019-09-19 09:39 UTC, ajmaddaford requested changes
When I clicked the mailto link it opened gmail in the same tab, it should probably match the other links in the footer and open a new tab.

2019-09-19 09:41 UTC, MebinAbraham requested changes

2019-09-19 09:41 UTC, MebinAbraham commented on templates/layouts/_base.html
> +      var a = /^(.*)?\s*'usage':true\s*[^;]+(.*)?$/;
Can not have a more meaningful variable name and add a comment about what this does?

2019-09-19 09:54 UTC, iwootten commented on templates/layouts/configs/_feedback.html
> +        "title": _("Give us feedback and help us improve this service"),
The indentation in this file is a bit wonky.

2019-09-19 09:58 UTC, ajmaddaford commented on templates/layouts/_base.html
> +      if (document.cookie.match(gtmCookieSettings)) {
We shouldn't need to do this. The cookie could be read by flask and the `google_tag_manager_*` template variables not set if not enabled.

2019-09-19 09:58 UTC, iwootten commented on templates/static/accessibility.html
> +{% else %}
The indentation on these if statements is incorrect. Can't we set the url outside the if to the default and drop one of the switches?

Wouldn't it make more sense to set this url in the backend?

2019-09-19 10:46 UTC, MebinAbraham commented on tests/functional/spec/question_definitions.spec.js
> +        // // Then
```suggestion
        // Then
```

2019-09-19 10:54 UTC, MebinAbraham approved these changes

2019-09-19 10:56 UTC, ajmaddaford approved these changes

2019-09-19 11:49 UTC, MebinAbraham commented on tests/integration/test_application_variables.py
> +        self._client.set_cookie(
Need to rework in future to not use the private method.

2019-09-19 12:43 UTC, merged