Set dynamic limits on replicas
ONSdigital/eq-survey-runner pull request #2407
Opened 2019-09-24 13:35 UTC by LJBabbage

### What is the context of this PR?
We need to dynamical set the min and max of the replicas for multiple environments.

### How to review 
Go to the concourse PR and use this as your branch for eq-survey-runner

2019-09-24 16:19 UTC, ajmaddaford commented on k8s/helm/values.yaml
>      targetCPUUtilizationPercentage: 50
It would be useful to make this configurable as well.

2019-09-25 07:37 UTC, ajmaddaford requested changes

2019-09-25 07:37 UTC, ajmaddaford commented on k8s/deploy_app.sh
> +MAX_SURGE="${MAX_SURGE:-1}"
It's not clear these are for rolling updates, it would be better to prefix the two with `ROLLING_UPDATE_`.

2019-09-25 13:11 UTC, ajmaddaford approved these changes

2019-09-25 13:30 UTC, pricem14pc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cluster min/max size](https://trello.com/c/RHIG9Sto/3369-cluster-min-max-size)

2019-09-25 14:28 UTC, pricem14pc approved these changes

2019-09-25 14:28 UTC, pricem14pc commented on k8s/helm/values.yaml
>      targetCPUUtilizationPercentage: 50
We thought that too but maybe in another PR.

2019-09-25 15:03 UTC, merged