Show list summaries on questions
ONSdigital/eq-survey-runner pull request #2422
Opened 2019-10-03 11:00 UTC by iwootten

### What is the context of this PR?

Added a new schema 'test_list_on_question.json' to demonstrate reusing existing list summary definition on a question block.

### How to review 

High level review of the schema design *only*, if we're happy with the design I can spend additional time refactoring the current approach.

2019-10-03 11:06 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [Able to display list on non list collector questions](https://trello.com/c/JAmvSheb/3372-able-to-display-list-on-non-list-collector-questions)

2019-10-07 10:29 UTC, ajmaddaford requested changes

2019-10-07 10:29 UTC, ajmaddaford commented on app/jinja_filters.py
> +            row['rowItems'][0]['actions'].append(
This will fail if there was no `edit_link_text` as the array won't have been initialised.

2019-10-07 10:29 UTC, ajmaddaford commented on app/views/contexts/list_collector.py
> +        return []
Where can the `KeyError` get raised?

2019-10-07 10:29 UTC, ajmaddaford commented on app/views/contexts/list_collector.py
>          'add_link': url_for(
As discussed, I don't think `add_link` is used for list collectors.

2019-10-07 11:10 UTC, iwootten commented on app/views/contexts/list_collector.py
> +        return []
It can't as far as I can see - this was just as per the original method.

2019-10-09 07:59 UTC, ajmaddaford approved these changes

2019-10-09 09:26 UTC, MebinAbraham commented on data-source/json/test_list_on_question.json
> +{
Sorry to be picky but can we make this `test_list_summary_on_question.json`

2019-10-09 09:42 UTC, MebinAbraham commented on app/jinja_filters.py
> +    remove_link_aria_label=None,
Let me know if I am mistaken but I cannot see a test where these are None?

2019-10-09 13:15 UTC, MebinAbraham approved these changes

2019-10-09 13:16 UTC, merged