Remove dumb quotes from the census schema
ONSdigital/eq-survey-runner pull request #2435
Opened 2019-10-10 09:43 UTC by berroar

### What is the context of this PR?
Removing dumb quotes in the census schema.

### How to review 
Build and check that dumb quotes have been removed from the census schemas. We should now only be using smart quotes.

2019-10-10 09:44 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Inconsistent quotes used in Welsh translations](https://trello.com/c/6LEeu41c/3228-inconsistent-quotes-used-in-welsh-translations)

2019-10-14 11:07 UTC, ajmaddaford requested changes

2019-10-14 11:07 UTC, ajmaddaford commented on data-source/jsonnet/england-wales/individual/blocks/personal-details/address_type.jsonnet
> +          value: "Partner‘s address",
These are using an opening quote (‘) rather than a closing quote (’)

2019-10-14 11:07 UTC, ajmaddaford commented on data-source/jsonnet/england-wales/individual/blocks/personal-details/another_address.jsonnet
> +          description: "We mean a different address to the one at the start of this survey. This might be another parent or guardian’s address, a term-time address, a partner‘s address or a holiday h
Same issue with opening vs closing quote.

2019-10-15 09:20 UTC, LJBabbage approved these changes

2019-10-15 12:15 UTC, berroar commented on data-source/jsonnet/england-wales/individual/blocks/personal-details/address_type.jsonnet
> +          value: "Partner‘s address",
Fixed

2019-10-15 14:39 UTC, JamesGardiner approved these changes

2019-10-15 14:40 UTC, JamesGardiner commented
Needs a format of the json

2019-10-16 08:22 UTC, ajmaddaford approved these changes

2019-10-16 10:20 UTC, merged