Allow POST requests to the /session endpoint
ONSdigital/eq-survey-runner pull request #2437
Opened 2019-10-10 13:01 UTC by MebinAbraham

### What is the context of this PR?
This change allows `POST` requests to the `/session` endpoint to be treated the same as the existing `GET` request. Trello card has the details to why this has be done.

### How to review 
- Make `POST` requests to the `session` endpoint and ensure it works as expected. Test with a both valid/invalid token.

2019-10-10 13:01 UTC, MebinAbraham commented
![](https://github.trello.services/images/mini-trello-icon.png) [Understand POST to /session as method not allowed](https://trello.com/c/DN10djio/3394-understand-post-to-session-as-method-not-allowed)

2019-10-11 10:12 UTC, LJBabbage requested changes
Thorough tests, just a little bit of reworking unrelated to this story which perhaps shouldn't be in this PR

2019-10-11 10:12 UTC, LJBabbage commented on tests/integration/routes/test_errors.py
> +        self.launchSurvey('test_percentage')
Is this part of this story? Just seems more like an unrelated tidy up unless I am wrong

2019-10-11 10:12 UTC, LJBabbage commented on tests/integration/session/test_login.py
> +    def test_http_head_request_to_login_returns_successfully_and_get_still_works(self):
How do you know get still works?

2019-10-11 10:19 UTC, MebinAbraham commented on tests/integration/routes/test_errors.py
> +        self.launchSurvey('test_percentage')
This test fails because of my change.

2019-10-11 10:26 UTC, MebinAbraham commented on tests/integration/session/test_login.py
> +    def test_http_head_request_to_login_returns_successfully_and_get_still_works(self):
This should be `post`, have changed.

2019-10-11 15:03 UTC, JamesGardiner approved these changes

2019-10-11 15:03 UTC, JamesGardiner commented
I won't block on this point, but I think some of these tests could be parameterized

2019-10-15 09:16 UTC, LJBabbage approved these changes

2019-10-15 10:05 UTC, merged