Building CCS Version 3
ONSdigital/eq-survey-runner pull request #2445
Opened 2019-10-15 10:26 UTC by berroar

### What is the context of this PR?
We have updated the CCS branch with the requested changes listed on [Trello](https://trello.com/c/iRQgpyVC/3419-ccs-v3).

### How to review 
Build the schema and check that the the requested changes have been implemented for this version of CCS.

2019-10-15 12:54 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [CCS v3](https://trello.com/c/iRQgpyVC/3419-ccs-v3)

2019-10-16 11:09 UTC, donnap573 approved these changes
Content reviewed

2019-10-16 12:35 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/accommodation/other_living_accommodation.jsonnet
> +    description: '<em>If "Yes" ensure this accommodation is recorded on the Fieldwork Management Tool and interview household separately</em>',
This should be using smart quotes?

2019-10-16 12:35 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/individual/proxy.jsonnet
> +    title: "<em>Interviewer Note: Are they answering the questions for themselves or on someone else's behalf?</em>",
Need to use smart quotes. Worth check all content.

2019-10-16 12:35 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_temp_away_list_collector.jsonnet
> +      description: '<em>Enter a full stop (.) if the respondent does not know a person\'s "First name" or "Last name"</em>',
Need to be a smart quote, instead of escaping.

2019-10-16 12:35 UTC, LJBabbage approved these changes
This PR is too BIG and nearly impossible to review and should be broken up. The schema works and I have checked the content, but I am only 49% sure its correct. Orange approve tick

2019-10-16 12:36 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_list_collector.jsonnet
> +      description: '<em>Enter a full stop (.) if the respondent does not know a person\'s "First name" or "Last name"</em>',
Shouldn't be escaping. Should use smart quotes.

2019-10-16 12:54 UTC, MebinAbraham requested changes
individual_interstitial and visitor_interstitial still have em tags for piped named. Should be removed according to the Trello card.

2019-10-16 12:57 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/individual/confirm_dob.jsonnet
> +  text: 'Yes',
Placeholder is no longer used so this variable can be removed and just added to the structure directly.

2019-10-16 12:58 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/individual/confirm_dob.jsonnet
> +local nonProxyNoLabel = 'No';
This variable can be removed and just added to the structure directly.

2019-10-16 12:58 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/individual/confirm_dob.jsonnet
> +  text: 'Yes',
Placeholder is no longer used so this variable can be removed and just added to the structure directly.

2019-10-16 12:59 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/individual/confirm_dob.jsonnet
> +local proxyNoLabel = 'No';
This variable can be removed and just added to the structure directly.

2019-10-16 14:35 UTC, MebinAbraham commented on data-source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_list_collector.jsonnet
> +      description: '<em>Enter a full stop (.) if the respondent does not know a person’s ”First name” or ”Last name”</em>',
```suggestion
      description: '<em>Enter a full stop (.) if the respondent does not know a person’s “First name” or “Last name”</em>',
```

2019-10-16 14:37 UTC, MebinAbraham approved these changes
Need to review quote usage after.

2019-10-16 15:27 UTC, merged