3457 ccs issues
ONSdigital/eq-survey-runner pull request #2449
Opened 2019-10-18 12:47 UTC by petechd

### What is the context of this PR?
This adds latest fixes and changes to CCS schema.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2019-10-18 13:09 UTC, petechd commented
![](https://github.trello.services/images/mini-trello-icon.png) [CCS Issues](https://trello.com/c/kBEBUp9b/3457-ccs-issues)

2019-10-18 13:53 UTC, donnap573 approved these changes

2019-10-21 06:45 UTC, petechd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update CCS with new instruction pattern](https://trello.com/c/t67BKLuo/3448-update-ccs-with-new-instruction-pattern)

2019-10-21 08:04 UTC, ajmaddaford requested changes
Contents look good 👍 
Leaving a blocking review so it doesn't get merged until the validator change is merged.

2019-10-22 10:28 UTC, ajmaddaford approved these changes

2019-10-22 10:53 UTC, merged