Merging the Census Rehearsal branch into v3
ONSdigital/eq-survey-runner pull request #2469
Opened 2019-10-30 12:52 UTC by berroar

### What is the context of this PR?
We now need to merge the changes from the Census Rehearsal into the v3 branch.

The census-rehearsal-to-v3 branch incorporates the latest changes from the census-rehearsal branch.

### How to review 
Check that nothing is broken by this change.

2019-10-31 10:19 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Merge census-rehearsal branch into v3](https://trello.com/c/ChNcY5gE/3479-merge-census-rehearsal-branch-into-v3)

2019-10-31 11:21 UTC, ajmaddaford requested changes
Looks good. When we merge this we should clean up the commits and do a rebase and merge rather than a squash and merge. Blocking so the commits can be reviewed before merging.

2019-11-04 08:22 UTC, MebinAbraham approved these changes

2019-11-04 09:49 UTC, ajmaddaford approved these changes

2019-11-04 09:53 UTC, merged