1375 e commerce ecom 187
ONSdigital/eq-survey-runner pull request #2490
Opened 2019-11-12 13:13 UTC by MattElcock

### What is the context of this PR?
Added q_codes, form types for NI and GB, negative playbacks, changed title and survey ID from ecommerce draft to ecommerce and added a link to the survey introduction page

### How to review 
Ensure the above is correct and the survey works

https://trello.com/c/9eZ5fVhD

2019-11-14 11:30 UTC, zimboflyman commented
Found a few instances where the negatives are not correlating to the question
Seem to go wrong in the same places in both surveys (001 and 002)
Give me a shout if you need any clarification

**Use of computers**

_Which of the following features does sdvsdv's website have?_
Select ‘Links or references to this business's social media profiles’
Save and continue
The list of non selected items includes both above - but shouldn’t

**Use of cloud computing services**

_Which of the following cloud computing services does tester buy?_
Select both ‘Hosting the business databases’ and ‘Computing capacity to run the business's own software’
Save and continue
The list of non selected items includes both above - but shouldn’t

**Big data**

_During May 2017, did tester use any of the following sources to analyse big data?_
Select ‘The business's own data from smart devices or sensors’
Save and continue
The list of non selected items includes both above - but shouldn’t

**Use of 3D printing**

_During May 2017, did tester use 3D printing for any of the following activities?_
Select ‘Goods to be used in the business's production process, excluding prototypes or models’
 The list of non selected items includes both above - but shouldn’t

2019-11-15 09:53 UTC, heofs requested changes
Looks good to me. Survey runs and q_codes looks good, except for one.

2019-11-15 09:53 UTC, heofs commented on data/en/ecommerce_0001.json
> +                                            "title": "What is an e-commerce market
I think this q_code should be 521 if I am interpreting the document correctly. 512 is also used in another place. Same for both files.

2019-11-15 14:58 UTC, heofs approved these changes
Looks good to me!

2019-11-19 12:04 UTC, zimboflyman commented
all looks good now!

2019-11-19 12:06 UTC, zimboflyman approved these changes

2019-11-20 10:39 UTC, merged