Conditionally render and set cookies/cookiesbanner
ONSdigital/eq-survey-runner pull request #2632
Opened 2020-09-03 20:43 UTC by tjamesmac

### What is the context of this PR?

Currently in progress but using this to track the diff

### How to review 
TBC

2020-09-22 09:46 UTC, MattElcock requested changes
Hi Tom,

Functionally, it looks like there's some problems but it could just be the way Martyn and I are testing. Could you go through this with us when you're back in, please?

As for the code, it all looks pretty neat and tidy. There's a few refactoring things that I've noticed could be done, but nothing major. I've put some notes on those below. There's a bit about logging, too. We should have a chat about this, too, when you're back in, to decide on a way forward.

Reg. the code:

- You can use template strings on Runner's version of Node; I didn't think you could either but I tried it in my console on version 8 and it works.
- You're right to be logging things out, especially the errors. However, `console.*` should ideally only be used whilst deving as the output isn't amazing in production environments. Dedicated loggers are usually better. I'll hit you up about this when you're next in to go over how we do it in Author.

Reg. the feature:

When you're back in can we go through this with you? A lot seems to be broken so I'm not sure if we're doing something wrong.

- When I click 'Accept all cookies', visually nothing happens.
- On the preference page, my selection doesn't stay when I navigate away and come back, or after clicking an option and the page refreshes.
- The buttons in the banner are different sizes
- I don't think the padding or margins on the banner are quite right as the title text is really close to the top of the screen.
- The buttons on the preferences page are really spaced out
- The buttons on the preference page don't have the borders around it

Here's a screenshot of how it looks my end.

![image](https://user-images.githubusercontent.com/15129656/93866054-1a64fb00-fcbf-11ea-9791-ffc4f9a12944.png)

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +  let approvedConsent = {
```suggestion
  const approvedConsent = {
```

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +            const cookieString = cookies + '=; expires=' + new Date() + '; domain=' + domain + '; path=/'
```suggestion
            const cookieString = `${cookies}=; expires=${new Date()}; domain=${domain}; path=/`
```

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +            console.log('remove cookie:', cookieString)
```suggestion

```

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +    console.error(e)
```suggestion
```

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +    let cookieString = name + '=' + value + setDomain + '; path=/'
Could swap this to be a template string.

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +      cookieString = cookieString + '; expires=' + date.toGMTString()
Could swap this to be a template string.

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +    document.cookie = s + '=' + s + ';domain=' + domainName + ';'
Could swap this to be a template string.

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiesfunctions.js
> +  document.cookie = s + '=;expires=Thu, 01 Jan 1970 00:00:01 GMT;domain=' + domainName + ';'
Could swap this to be a template string.

2020-09-22 09:46 UTC, MattElcock commented on app/assets/js/app/modules/cookies/cookiessettings.js
> +      console.error(e)
```suggestion
```

2020-09-22 15:21 UTC, MattElcock commented
Spoken with Tom and Martyn, managed to get the visual stuff sorted so that's all good. Agreed that the `console.*` statements will just be removed for now. Template literals can be ignored also.

2020-09-24 08:38 UTC, MattElcock approved these changes

2020-09-29 11:06 UTC, farres1 approved these changes

2020-09-29 13:03 UTC, merged