Implement UKIS_0001 and UKIS_0002 changes
ONSdigital/eq-survey-runner pull request #2712
Opened 2020-12-14 16:02 UTC by farres1

### What is the context of this PR?
Updated UKIS content.

### How to review 
Check that the ukis_0001 and ukis_0002 surveys work as expected.

### Checklist

* [ ] Open ukis_0001
* [ ] Check that this survey is working as intended
* [ ] Open ukis_0002
* [ ] Check that this survey is working as intended
* [ ] Check that the values from the Jira ticket are correct in the ukis_0001 and ukis_0002 JSON files

2020-12-16 10:25 UTC, MattElcock requested changes

2020-12-16 10:25 UTC, MattElcock commented on data/en/ukis_0001.json
> +    "eq_id": "ukis_0001",
Hi Sam. I see why this has changed; normally you're not incorrect - the eq_id is of that format. However, to avoid unpredicted errors, if the existing eq_id is different within the schema when we go to change it we normally leave it alone. Just in case.

```suggestion
    "eq_id": "ukis",
```

2020-12-16 10:25 UTC, MattElcock commented on data/en/ukis_0001.json
> +            "validator": "date"
Double checked with the business via Jordan, we don't need these two bits of metadata in here.

2020-12-16 10:34 UTC, MattElcock requested changes

2020-12-16 10:34 UTC, MattElcock commented on data/en/ukis_0002.json
> +            "validator": "date"
The same as above reg metadata

2020-12-16 10:34 UTC, MattElcock commented on data/en/ukis_0002.json
> +    "eq_id": "ukis_0002",
The same as above reg eq_id

2020-12-16 11:07 UTC, MattElcock approved these changes

2020-12-22 08:25 UTC, tbaggaley approved these changes

2020-12-22 08:58 UTC, merged