EAR-1244 Update Summary and Thank You page wording
ONSdigital/eq-survey-runner pull request #2750
Opened 2021-04-14 09:02 UTC by jchapman68

### What is the context of this PR?
Update wording to show respondants can save and print to pdf

### How to review 
Check wording on surveys match the ACs and supplied document

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2021-04-14 09:06 UTC, tjamesmac commented on app/themes/covid/templates/thank-you.html
> +            data-ga-label="Goto covid survey view-submission page">{{ _("VView, save or print a copy of your answers") }}</a>
```suggestion
            data-ga-label="Goto covid survey view-submission page">{{ _("View, save or print a copy of your answers") }}</a>
```
Spelling mistake here

2021-04-14 09:07 UTC, tbaggaley requested changes

2021-04-14 09:07 UTC, tbaggaley commented on app/themes/covid/templates/thank-you.html
> +            data-ga-label="Goto covid survey view-submission page">{{ _("VView, save or print a copy of your answers") }}</a>
```suggestion
            data-ga-label="Goto covid survey view-submission page">{{ _("View, save or print a copy of your answers") }}</a>
```

2021-04-14 09:09 UTC, tbaggaley commented on app/themes/covid/templates/thank-you.html
> +            data-ga-label="Goto covid survey view-submission page">{{ _("VView, save or print a copy of your answers") }}</a>
Jinx!!

2021-04-14 09:09 UTC, tjamesmac commented on app/themes/covid/templates/thank-you.html
> +            data-ga-label="Goto covid survey view-submission page">{{ _("VView, save or print a copy of your answers") }}</a>
Damn

2021-04-14 09:09 UTC, tjamesmac commented on app/themes/covid/templates/thank-you.html
> +            data-ga-label="Goto covid survey view-submission page">{{ _("VView, save or print a copy of your answers") }}</a>
Got me

2021-04-14 09:21 UTC, tbaggaley approved these changes

2021-04-15 10:44 UTC, MattElcock approved these changes
Hi Josh, nice work here. Thanks for doing this!

2021-04-15 10:50 UTC, merged