EQ-525 Summary page improvements
ONSdigital/eq-survey-runner pull request #426
Opened 2016-09-13 08:05 UTC by LJBabbage

### What is the context of this PR?
Include links on the summary page and introduce a registry for formatting rules

### How to review 
Using star wars, complete the questionnaire and make sure everything works and the summary page displays all the questions asked and answer, also that the links work. 

(n.b. It is known that you must complete the survey again if using a link, e.g. you can't return to the summary page, this will be picked up in another story)

- [ ] Do all commits have sensible commit messages?
- [ ] Is all new code unit tested?
- [ ] Are there integration tests if needed?
- [ ] Is there sufficient logging?
- [ ] Is there documentation or is the code self-describing?

### Who worked on the PR
@LJBabbage

2016-09-13 10:36 UTC, iwootten commented on app/templating/summary/formatters/abstract_formater.py
> +class AbstractFormater(metaclass=ABCMeta):
Typo here.

2016-09-13 12:00 UTC, LJBabbage commented
Is the rest ok then?

2016-09-13 15:24 UTC, iwootten commented
@LJBabbage think there may be a couple of styling issues here that haven't yet made it across from the other branch. Here's what I get on the summary page at the mo after a compile of the frontend. 

Been through with @hamishtaplin and he's happy to jump in if necessary.

<img width="544" alt="screen shot 2016-09-13 at 16 23 02" src="https://cloud.githubusercontent.com/assets/3598161/18479835/61999846-79ce-11e6-8130-8df495847d3b.png">

2016-09-13 15:42 UTC, iwootten commented on app/templating/summary/summary_item.py
> +            else:
Could lose the else here

2016-09-13 15:49 UTC, LJBabbage commented
Star wars theme is good, but the default one is not

2016-09-13 15:50 UTC, iwootten commented on app/templating/summary/formatters/check_box.py
> +        for option in schema.answers[0].options:
We only seem to be using answers here

2016-09-13 15:53 UTC, iwootten commented on app/templating/summary/formatters/date_range.py
> +    def format(schema, state, user_answer):
We only seem to be using the answers from both schema, state.

2016-09-13 15:54 UTC, iwootten commented on app/templating/summary/formatters/radio_button.py
> +    def format(schema, state, user_answer):
Again, we only seem to be using an answer from both schema

2016-09-13 16:12 UTC, LJBabbage commented on app/templating/summary/formatters/check_box.py
> +        for option in schema.answers[0].options:
We use schema in schema.answers[0].options, but we can tighten up as suggested on the other comments to just pass schema.answers.

2016-09-13 16:19 UTC, iwootten commented on app/templating/summary/formatters/check_box.py
> +        for option in schema.answers[0].options:
Ah, yes my mistake.

2016-09-14 09:34 UTC, hamishtaplin commented
@LJBabbage this should be ok now

2016-09-16 10:13 UTC, hamishtaplin commented on app/templates/summary.html
> +              {{item.answer|nl2br or not_answered}}
I'm getting a string "None" here instead of a falsy value when the comments aren't entered.

2016-09-16 13:17 UTC, hamishtaplin commented on app/templates/summary.html
> +              {{item.answer|nl2br or not_answered}}
Turns out this was caused by the filter, have fixed.

2016-09-16 14:01 UTC, bennpearson commented on app/templates/confirmation.html
> +  <h1 class="header__title h1">Confirmation</h1>
Should be planet name

2016-09-16 14:01 UTC, bennpearson commented on app/templates/confirmation.html
> +  <h2 class="header__subtitle">Thank you for your answers, do you wish to submit</h2>
Should contain planet class

2016-09-16 14:03 UTC, bennpearson commented on app/assets/styles/partials/components/_summary.scss
> +    background-color: #efefef;
Should be a var?

2016-09-16 14:05 UTC, bennpearson commented on app/templates/submission.html
> +{% extends 'layouts/_survey.html' -%}
Note: Should this be theme()

2016-09-16 14:56 UTC, yoganandkunche commented
@hamishtaplin @LJBabbage  as discussed can you please change the 'Not answered' to 'No answer provided' to match requirements in acceptance criteria.

2016-09-19 13:10 UTC, iwootten commented on app/templating/summary/formatter_registry.py
> +    "GENERAL": {
These formatters all appear to apply to single answer fields, whilst daterange is comprised of multiple. Would it be better to name these keys 'SINGLE"/"MULTIPLE" or similar and change the subkey "DATE" to "DATERANGE"? 'GENERAL' could cover everything.

2016-09-19 13:12 UTC, iwootten commented on app/templating/summary/formatters/abstract_formater.py
> +    def format(schema_answers, state_answers, user_answer):
Are we able to make use of keyword arguments here in order to allow child classes to omit variables that aren't used in formatting?

2016-09-19 13:13 UTC, iwootten commented on tests/app/templating/test_question_formatters.py
> +    def test_general_Radio(self):
Seems to be some weird camelcasing of method names throughout this file.

2016-09-19 13:14 UTC, iwootten commented on tests/integration/routing/test_routing.py
> +    def test_routing_paths(self):
This is a boatload easier to understand than what we had previously!

2016-09-19 13:17 UTC, iwootten requested changes
In addition to my comments, have yogi's concerns been addressed - do we need to change the content of no_answers?

2016-09-19 13:32 UTC, LJBabbage commented on app/templating/summary/formatter_registry.py
> +    "GENERAL": {
It matches the JSON format, so possibly something for the future

2016-09-19 13:34 UTC, hamishtaplin commented
@iwootten Wording was changed here, as per Yogi's comment: https://github.com/ONSdigital/eq-survey-runner/pull/426/files#diff-9877ee549e610942cbd6fa832b7411b7R5

2016-09-19 13:39 UTC, iwootten commented
@hamishtaplin cheers!

2016-09-19 13:57 UTC, LJBabbage commented on app/templating/summary/formatters/abstract_formater.py
> +    def format(schema_answers, state_answers, user_answer):
As discussed, this doesn't really lend itself at the moment, with the updated questionnaire state model this should improve

2016-09-19 15:06 UTC, ajmaddaford commented on app/templating/summary/summary_item.py
> +            answer_type = self.schema.answers[0].type.upper()
I think this should be uppercased in the `get_formatter` method as it's only being uppercased to do the lookup against the dictionary in the `FormatterRegistry`.

2016-09-19 15:08 UTC, ajmaddaford commented on app/templating/summary/summary_item.py
> +                formatter_rule = formatter_class()
Not sure where rule comes from, would be better to go with `formatter = formatter_class()`

2016-09-19 15:12 UTC, ajmaddaford commented on app/templating/summary/section_summary.py
> +class SectionSummary(object):
This should be called `SummarySection` to be consistent with `SummaryItem`

2016-09-19 15:14 UTC, ajmaddaford commented on app/templating/summary_template_preprocessor.py
> +                    summary_section.append(section_summary)
If `SectionSummary` is renamed `SummarySection`, `summary_section` should be renamed `summary_sections`

2016-09-19 15:18 UTC, ajmaddaford commented on app/templating/summary/formatter_registry.py
> +    def get_formatter(answer_type, question_type):
Minor, `question_type` should be the first argument as it's the more significant parameter (the logic of the method uses it first and doesn't carry on if it doesn't match)

2016-09-19 15:24 UTC, ajmaddaford approved these changes

2016-09-19 15:27 UTC, iwootten approved these changes

2016-09-20 08:39 UTC, merged

2020-05-04 13:46 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update to Python 3.8](https://trello.com/c/5pBfWFfU/3849-update-to-python-38)