Driving functional tests using page models
ONSdigital/eq-survey-runner pull request #467
Opened 2016-09-30 12:41 UTC by benjefferies

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

The functional tests were going down a path where it would have started
to get harder to manage if changes to survey schema occured because we
would potentially have to make changes in multiple places. We have
introduced page models which should be an abstraction on top of a
webpage e.g. the landing page.

Also renamed the wdio test folder to reflect the type of tests rather
than the technology implementing them

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

The changes can be tested by running the functional tests with the command `npm run test_functional -- --spec=mci` once the survey-runner is running

2016-09-30 14:39 UTC, hamishtaplin commented on tests/functional/pages/surveys/monthly-business-survey.page.js
> +    browser.setValue('[id = "6fd644b0-798e-4a58-a393-a438b32fe637-day"]', day)
Minor quibble: no spaces these selectors

2016-09-30 14:40 UTC, hamishtaplin commented on tests/functional/pages/surveys/monthly-business-survey.page.js
> +    browser.setValue('.input-type--currency .input', amount)
It would be good to sort these selectors out so they aren't using CSS hooks.

2016-09-30 14:44 UTC, hamishtaplin commented on tests/functional/pages/dev.page.js
> +module.exports = new DevPage()
Prefer es6 export syntax: `export default new DevPage()`

2016-10-05 10:34 UTC, jonnyshaw89 commented on tests/functional/pages/surveys/monthly-business-survey.page.js
> +    browser.setValue('.input-type--currency .input', amount)
yeh i agree, I've seen this before and styling changes make the tests brittle.

2016-10-05 12:15 UTC, hamishtaplin requested changes
Minor quibble regarding the `export` syntax but apart from that, looks brilliant.

2016-10-05 12:15 UTC, hamishtaplin commented on tests/functional/pages/surveys/question.page.js
> +module.exports = QuestionPage
prefer es6 `export`:

``` javascript
export default QuestionPage
```

2016-10-05 12:15 UTC, hamishtaplin commented on tests/functional/pages/surveys/rsi/0102/changes-in-retail-turnover.page.js
> +module.exports = new ChangesInRetailTurnoverPage()
As per other `export` comment.

2016-10-05 12:15 UTC, hamishtaplin commented on tests/functional/pages/surveys/rsi/0102/changes-in-retail-turnover.page.js
> +module.exports = new ChangesInRetailTurnoverPage()
(do this for all of them)

2016-10-05 12:30 UTC, benjefferies commented on tests/functional/pages/surveys/rsi/0102/changes-in-retail-turnover.page.js
> +module.exports = new ChangesInRetailTurnoverPage()
Oh yeah not sure how this sneaked in. Fixed

2016-10-05 14:01 UTC, benjefferies commented on tests/functional/pages/surveys/question.page.js
> +module.exports = QuestionPage
Done

2016-10-05 14:26 UTC, hamishtaplin approved these changes

2016-10-05 14:27 UTC, merged