eq-616 Radio button helper text
ONSdigital/eq-survey-runner pull request #471
Opened 2016-10-03 10:58 UTC by hamishtaplin

### What is the context of this PR?

More context is sometimes needed for radio button and checkbox answers. This adds the concept of "helper" text to site in the schema alongside the `label`. For example:

```json

{
    "question": {
        "answers": [
            {
                "guidance": "",
                "id": "ca3ce3a3-ae44-4e30-8f85-5b6a7a2fb23c",
                "label": "Choose a side",
                "mandatory": true,
                "options": [
                    {
                        "label": "Light Side",
                        "value": "Light Side",
                        "helper": "I am some helper text and I might be a bit <strong>bold in places</strong>."
                    },
                    {
                        "label": "Dark Side",
                        "value": "Dark Side",
                        "helper": "Vestibulum id ligula porta felis euismod semper."
                    },
                    {
                        "label": "I prefer Star Trek",
                        "value": "I prefer Star Trek",
                        "helper": "Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit."
                    }
                ],
                "q_code": "20",
                "type": "Radio",
            }
        ]
    }
}
```

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2016-10-03 11:02 UTC, hamishtaplin commented
This needs wiring up from the schema, the templates have the basic implementation in place.

I wonder if this is a good opportunity to simplify the widget rendering? There's a bit too much work happening in the templates still where it takes the model it is exposed and then remodels it according to what the `include` needs, for example:

```jinja
{% set label = {
  'for': answer.id,
  'text': answer.label
} %}
{% include 'partials/forms/label.html' %}

{% set textarea = {
  'value': (answer.value or "")|e,
  'name': answer.name,
  'id': answer.id,
  'placeholder': answer.placeholder,
  'aria-describedby': "description-" ~ question.id ~ " guidance-" ~ answer.id ~ "-trigger",
  'maxChars': answer.maxChars or 2000
} %}

{% include 'partials/forms/textarea.html' %}
```

Much of this should be done in the python, perhaps?

2016-10-06 13:37 UTC, bennpearson requested changes
Tags are coming through in radio description

2016-10-06 15:29 UTC, hamishtaplin commented
@bennpearson Sorted now

2016-10-07 09:54 UTC, bennpearson approved these changes

2016-10-07 10:06 UTC, merged