Eq 553 change of details
ONSdigital/eq-survey-runner pull request #496
Opened 2016-10-17 11:43 UTC by iwootten

### What is the context of this PR?
Add a change of details box to allow respondents to update their details.

### How to review 
Check against acceptance criteria:

- Respondent is presented a phone number and e-mail address to update their contact details.
Phone number is accessible (screen readers)
- Wording will be: 'Have there been any changes to your business name, address or structure? Telephone 0300 1234 931 or alternatively email EDCAdmin@ons.gov.uk' (Confirmed this should be changed due to large title wrapping around)

2016-10-17 11:56 UTC, hamishtaplin commented on app/templates/landing-page.html
> +            <dd class="dl__data mars">Telephone <a href="tel:0300 1234 931" aria-describedby="survey-help">0300 1234 931</a> or alternatively email <a href="mailto:EDCAdmin@ons.gov.uk" aria-described
There's a rogue `aria-describedby` attribute on here.

2016-10-17 11:57 UTC, hamishtaplin requested changes
Need to remove the rogue `aria` attributes.

2016-10-17 12:43 UTC, hamishtaplin approved these changes

2016-10-19 14:08 UTC, yoganandkunche commented
Passed QA in Local.

Tested with a lengthy real time Business Name and Trading  as Name on all the Browsers for all eQ Schemas 

Call 0300 1234 931 or email surveys@ons.gov.uk if there have been any changes to your business name, address or structure

2016-10-20 14:36 UTC, merged