Split out end points
ONSdigital/eq-survey-runner pull request #497
Opened 2016-10-17 12:56 UTC by benjefferies

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

* Split questionnaire submit and get requests
* Pull out thank-you page
* Pull out previous
* Remove first end point
  * first end point only ever appeared to be used in integration test
* Delete unused methods

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

- [ ]  Run tests

2016-10-17 13:12 UTC, iwootten commented on app/main/views/questionnaire.py
> +    logger.debug("Post location : /questionnaire/%s/%s/%s/%s/%s", eq_id, form_type, period_id, collection_id, location)
Isn't flask (werkzeug) logging the url visited by default?

2016-10-17 13:14 UTC, benjefferies commented on app/main/views/questionnaire.py
> +    logger.debug("Post location : /questionnaire/%s/%s/%s/%s/%s", eq_id, form_type, period_id, collection_id, location)
From the look of my logs yes. Will remove them.

2016-10-17 16:12 UTC, iwootten commented on app/main/views/questionnaire.py
> +    questionnaire_manager.delete_user_data()
I feel that it may be good to move the questionnaire manager behaviour behind into this main route? It's only ever called here.

2016-10-17 16:18 UTC, benjefferies commented on app/main/views/questionnaire.py
> +    questionnaire_manager.delete_user_data()
Certainly, didn't catch that it was only used here.

2016-10-17 16:22 UTC, iwootten commented on app/main/views/questionnaire.py
> +    session_manager.clear()
Think you've missed a line here- need's to call delete on the questionnaire store once it's retrieved it.

2016-10-17 16:28 UTC, iwootten commented on app/main/views/questionnaire.py
> +    session_manager.clear()
Oh I see!

2016-10-18 08:04 UTC, iwootten commented
I think this change highlights how much questionnaire_manager is trying to do - for me I feel that it possibly should be tackled as part of this work?

2016-10-18 10:02 UTC, benjefferies commented
I am happy with this to be merged given the merge conflicts are resolved

2016-10-19 09:30 UTC, iwootten commented on app/questionnaire/questionnaire_manager.py
>      def get_rendering_context(self, location):
If we're going to be splitting these into two methods, it probably makes sense that if the location is unknown within a call to get_rendering_context it should be capable of handling a location which is 'summary'. Maybe it should therefore check on the first line and return get_summary_rendering_context() if so?

2016-10-19 14:09 UTC, benjefferies commented on app/questionnaire/questionnaire_manager.py
>      def get_rendering_context(self, location):
done

2016-10-19 14:49 UTC, benjefferies commented on tests/integration/mci/test_change_answers.py
> -
This exact test live in test_errors.py

2016-10-20 14:51 UTC, benjefferies commented on tests/app/views/test_health_check.py
> -def test_errors_404(survey_runner):
This exact test live in test_errors.py

2016-10-21 09:19 UTC, ajmaddaford requested changes

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/questionnaire.py
> +def get_page(questionnaire_manager, location, is_valid):
get_page is confusing, I think render_page would be clearer

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/questionnaire.py
> +    return TemplateRegistry.get_template_name(location)
Any reason not to use this directly rather than via the `get_rendering_template` method?

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/questionnaire.py
> +    return decorated_function
I think we should re-implement this using the `url_value_preprocessor` blueprint decorator function (see http://exploreflask.com/en/latest/blueprints.html#using-a-dynamic-url-prefix). We should also set the questionnaire_manager on the global application (request) context so that the routes that use this function don't need to re-instantiate the manager.

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/questionnaire.py
>      return redirect('/questionnaire/' + eq_id + '/' + form_type + '/' + period_id + '/' + collection_id + '/' + location)
We should be using the Flask url_for method for generating URLs for known routes. Also, is there a way to get the current route rather than keep having to pass all of the parameters to this method?

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/questionnaire.py
> +def go_to_page(collection_id, eq_id, form_type, period_id, location, is_valid=True):
This method go's to a page **and** renders it. I think we should either rename the method or move the rendering out to be called independently.

2016-10-21 09:19 UTC, ajmaddaford commented on app/main/views/errors.py
> +errors_blueprint = Blueprint('errors', __name__)
Should the errors blueprint be setting the cache headers like the root and questionnaire blueprints?

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/errors.py
> +errors_blueprint = Blueprint('errors', __name__)
What is the reason we are indicating to the browser not to cache? I can add it just to blanket cover this too anyway

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/questionnaire.py
> +    return decorated_function
Done

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/questionnaire.py
>      return redirect('/questionnaire/' + eq_id + '/' + form_type + '/' + period_id + '/' + collection_id + '/' + location)
Done

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/questionnaire.py
> +    return TemplateRegistry.get_template_name(location)
Nope, copy and paste initially and then forgot to remove

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/questionnaire.py
> +def get_page(questionnaire_manager, location, is_valid):
Good call

2016-10-21 12:16 UTC, benjefferies commented on app/main/views/questionnaire.py
> +def go_to_page(collection_id, eq_id, form_type, period_id, location, is_valid=True):
Not a great fan of methods with `and` suggests it's doing too much which could be right in this case so I've pulled out

2016-10-21 14:46 UTC, benjefferies commented
Superseded by https://github.com/ONSdigital/eq-survey-runner/pull/512

2016-10-21 14:46 UTC, closed without merging