eq-518 Census survey cannot be completed
ONSdigital/eq-survey-runner pull request #519
Opened 2016-10-24 15:07 UTC by hamishtaplin

### What is the context of this PR?
Fixes #518 by adding a single question to the schema. Also makes sure that the whole user journey to "thankyou" page is using the correct theme.

### How to review 

1. Select `census_theme` schema.
2. Complete survey through to "thankyou" page, ensuring that the journey is themed appropriately.

2016-10-25 10:10 UTC, jonnyshaw89 requested changes

2016-10-25 10:10 UTC, jonnyshaw89 commented on app/data/census_theme.json
> +            "blocks": [
This fails for me when i run it complaining that this block has no id

2016-10-25 12:50 UTC, hamishtaplin commented on app/data/census_theme.json
> +            "blocks": [
@jonnyshaw89 There is an `id` on line 25 though?

2016-10-25 16:44 UTC, ajmaddaford commented on app/data/census_theme.json
> +            "blocks": [
I just ran the tests and they all passed

2016-10-25 16:45 UTC, ajmaddaford approved these changes

2016-10-26 08:29 UTC, jonnyshaw89 commented on app/data/census_theme.json
> +            "blocks": [
Seems this was an issue on my machine where is was loading the wrong schema.

2016-10-26 08:32 UTC, jonnyshaw89 approved these changes

2016-10-26 08:32 UTC, merged