Eq 650 Implement Previous + Next from Schema
ONSdigital/eq-survey-runner pull request #523
Opened 2016-10-25 12:24 UTC by iwootten

### What is the context of this PR?

Moved to using the schema for navigation, rather than methods on the questionnaire manager. Added a new class Navigator, which deals with finding block and location paths through a survey from a schema. Refactored all the previous routing behaviour to use new navigator and removed redundant dependencies. 

It's been necessary to modify the way a schema is loaded, so it returns a tuple of the parsed schema and original json, so the navigator is able to use the json.

### How to review 
Review the approach, confirm that tests pass and test coverage is appropriate.

2016-10-26 08:46 UTC, iwootten commented
Codecov's patch is complaining as I've refactored a number of method names in preexisting files. I've managed to bump them quite a lot by mocking out boto, but not enough to get our current target of 90.3%. 

I think the patch blocking a PR isn't helpful, given it's difficult to know what the coverage of a patch will be before letting codecov run, so we're forever making updates to a PR to get it to increase.

2016-10-26 09:28 UTC, collisdigital commented
This is the coverage report: https://codecov.io/gh/ONSdigital/eq-survey-runner/compare/b9b82d14406a662b6c8bede15bc3ee72e18347c4...9f5190fde5b3680b688116dffcf12997fe2a8240

We can either disable blocking the PR or change the codecov setting (i.e. just fix it at 85% rather than always the same or higher than the parent branch...

2016-10-26 10:13 UTC, jonnyshaw89 commented on app/questionnaire/questionnaire_manager.py
> +                rule['when'] = rule['when'].__dict__
I get the following error from this line when completing the star wars survey
`File "/Users/jonshaw/code/eq-survey-runner/app/questionnaire/questionnaire_manager.py", line 332, in _conditional_display
    rule['when'] = rule['when'].__dict__
AttributeError: 'dict' object has no attribute '__dict__'`

2016-10-26 15:07 UTC, LJBabbage commented on app/questionnaire/questionnaire_manager.py
> +                rule['when'] = rule['when'].__dict__
It works for me oddly, and I can see all whens in rules are dicts

2016-10-26 15:09 UTC, jonnyshaw89 commented on app/questionnaire/questionnaire_manager.py
> +                rule['when'] = rule['when'].__dict__
It also no longer breaks for me. Worth investigating? or ignoring and putting it down to switching between branches etc?

2016-10-26 15:25 UTC, LJBabbage commented
If I click on the first page I prefer Star Trek, it gives me a 500
block_id_index = next(index for (index, b) in enumerate(blocks) if b["id"] == block_id)
StopIteration

2016-10-26 15:35 UTC, LJBabbage commented on app/globals.py
> +def get_schema(eq_id, form_type):
Is this function being called? questionnaire_factory still seems to be pointed at the old get_schema in schema.py

2016-10-26 16:03 UTC, LJBabbage commented on app/globals.py
> +    schemas = g.get('_schemas')
This is for request scope, not sure why we would load every schema is we lose it after the request

2016-10-26 16:08 UTC, LJBabbage commented on app/globals.py
> +    schemas = g.get('_schemas')
Won't this allows be None as its requests scope, also why are we loading all schemas in request scope

2016-10-26 21:28 UTC, iwootten commented on app/globals.py
> +def get_schema(eq_id, form_type):
Good spot - I was using flask globals but ended up ditching the approach given the questionnaire manager is tested outside of a flask request.

2016-10-26 21:29 UTC, iwootten commented on app/globals.py
> +    schemas = g.get('_schemas')
No, worked the same as the other get globals. Have removed this all for now, given it's not used.

2016-10-26 21:31 UTC, iwootten commented
@LJBabbage - The recursive visit_block method was only working with block ids and had no idea interstitial pages could be jumped to. Have added a test to catch it and handled the case.

2016-10-27 07:28 UTC, collisdigital commented on app/questionnaire/navigator.py
> +    def get_block_ids(self):
There's no test coverage on this function; which is suspicious, would have thought other tests would have hit it indirectly, is this function redundant ?

https://codecov.io/gh/ONSdigital/eq-survey-runner/compare/b9b82d14406a662b6c8bede15bc3ee72e18347c4...333b0e5b685e2fab03a8eb7ad9cdaeac72c01c1a#6170702F7175657374696F6E6E616972652F6E6176696761746F722E7079-108

2016-10-27 13:24 UTC, ajmaddaford requested changes

2016-10-27 13:24 UTC, ajmaddaford commented on app/questionnaire/navigator.py
> +def visit_block(blocks, block_id, answers, path):
I think this function name should more clearly reflect what is does, something like `build_path` (which it does by visiting blocks)

2016-10-27 13:24 UTC, ajmaddaford commented on app/questionnaire/navigator.py
> +    PROCEEDING_INTERSTITIAL_PATH = ['introduction']
I think this should be preceding rather than proceeding?

2016-10-27 13:24 UTC, ajmaddaford commented on app/questionnaire/navigator.py
> +    def get_location_path(self, answers=None):
I think `get_locations_visited` would be a better name

2016-10-27 13:24 UTC, ajmaddaford commented on app/questionnaire/navigator.py
> +    def get_next_block_id(self, answers=None, current_block_id=None):
I can only see this method used in the tests - has this been superseded by `get_next_location`?

2016-10-27 13:24 UTC, ajmaddaford commented on app/schema_loader/schema_loader.py
> +def load_all_schemas():
Unused method?

2016-10-27 15:56 UTC, iwootten commented on app/questionnaire/navigator.py
> +    def get_location_path(self, answers=None):
I'm not sure, given the list of locations haven't yet been visited, at least from a respondents point of view.

2016-10-27 21:08 UTC, iwootten commented on app/questionnaire/navigator.py
> +def visit_block(blocks, block_id, answers, path):
Sure thing.

2016-10-27 21:09 UTC, iwootten commented on app/schema_loader/schema_loader.py
> +def load_all_schemas():
Yup

2016-10-27 21:13 UTC, iwootten commented on app/questionnaire/navigator.py
> +    PROCEEDING_INTERSTITIAL_PATH = ['introduction']
Yes, you're right.

2016-10-27 21:13 UTC, iwootten commented on app/questionnaire/navigator.py
> +    def get_next_block_id(self, answers=None, current_block_id=None):
Yes.

2016-10-27 21:13 UTC, iwootten commented on app/questionnaire/navigator.py
> +    def get_block_ids(self):
Yes.

2016-10-27 21:15 UTC, iwootten commented on app/questionnaire/questionnaire_manager.py
> +                rule['when'] = rule['when'].__dict__
Unless this can be replicated (I've never hit this issue and don't on this branch), then I can't see how we would pursue it.

2016-10-31 10:18 UTC, benjefferies requested changes

2016-10-31 10:18 UTC, benjefferies commented on app/main/errors.py
> +import logging
Think this can be removed as it's superseded by app/main/view/errors.py

2016-10-31 10:18 UTC, benjefferies commented on app/questionnaire/navigator.py
> +        self.location_path = ['introduction']
Is this making the assumption there will always be a introduction, is that the case now?

2016-10-31 10:18 UTC, benjefferies commented on app/questionnaire/navigator.py
> +        location_path.extend(['summary', 'thank-you'])
Is this making the assumption there will always be a summary and thank you page, is that the case now?

2016-10-31 10:18 UTC, benjefferies commented on app/questionnaire/questionnaire_manager.py
>              self._valid_locations = self._build_valid_locations()
Does build_path() do something similar to this when given no answers? It would be worth using that I guess if it is the case

2016-10-31 10:18 UTC, benjefferies commented on app/utilities/schema.py
>  def load_and_parse_schema(eq_id, form_type):
The docs are missing the other return object

2016-10-31 12:10 UTC, iwootten commented on app/questionnaire/questionnaire_manager.py
>              self._valid_locations = self._build_valid_locations()
Yes, leaving this for @jonnyshaw89's PR branching from this.

2016-10-31 12:42 UTC, ajmaddaford approved these changes

2016-10-31 16:42 UTC, benjefferies approved these changes

2016-10-31 16:42 UTC, benjefferies commented on app/questionnaire/navigator.py
> +        if self.blocks[len(self.blocks) - 1]['id'] == last_routing_block_id:
self.blocks[-1]['id'] could work here I think?

2016-10-31 16:42 UTC, benjefferies commented on app/questionnaire/navigator.py
> +        last_routing_block_id = routing_path[len(routing_path) - 1]
routing_path[-1] could work here I think?

2016-10-31 17:14 UTC, merged