Test schemas organisation and naming for checkboxes and radio
ONSdigital/eq-survey-runner pull request #530
Opened 2016-10-27 13:44 UTC by samiwel

### What is the context of this PR?
This PR is to fix #527 
This is a continuation of the refactoring work to split out the functional tests for the radio and checkbox widgets that was started in another PR.
The schemas have been modified so that there is now one for checkboxes and one for radio.
The schemas each contain one mandatory and one non-mandatory checkbox/radio answer respectfully.
The functional tests have been split out into their own spec files.
Some general renaming and files around for consistency.
Most of the tests right now cover the functionality for the Other input option on both checkboxes and radios, but this can be extended going forward.

### How to review 
All tests should continue to pass.

2016-10-28 13:20 UTC, ajmaddaford requested changes

2016-10-28 13:20 UTC, ajmaddaford commented on tests/app/templating/summary/formatters/test_radio_formatter.py
> +    def test_formatter_outputs_other_if_other_selected_but_no_value_specified(self):
Bit wordy, maybe `test_other_selected_but_no_value_provided`?

2016-10-28 13:20 UTC, ajmaddaford commented on tests/app/templating/summary/formatters/test_radio_formatter.py
> +    def test_formatter_outputs_other_value_when_provided(self):
If the method above is renamed, it would be worth renaming this to `test_other_selected_and_value_provided` for consistentency

2016-10-28 13:20 UTC, ajmaddaford commented on tests/app/templating/summary/formatters/test_radio_formatter.py
> +        self.__user_answers = 'other'
Why the double underscore?

2016-10-28 13:20 UTC, ajmaddaford commented on app/data/0_test_checkbox_with_radio.json
>                                                  {
Do we need this schema now we have separate checkbox and radio schemas?

2016-10-31 11:23 UTC, benjefferies approved these changes

2016-10-31 11:23 UTC, ajmaddaford approved these changes

2016-10-31 12:41 UTC, merged