Add new date type(Month/Year) and update tests
ONSdigital/eq-survey-runner pull request #562
Opened 2016-11-14 12:54 UTC by LJBabbage

### What is the context of this PR?
To add in the month/year answer type "mm/yyyy". A new widget has been introduced to deal with the alternative format and the summary . A test schema has also been set up to handle all dates 

### How to review 
Using dev, open up the test_dates.json and make sure it shows both the date range and the new format above. Add  invalid data into each and make sure the right messages are shown. Correct the errors and make sure the summary page is correct.

(N.B there is a malfunctioning test_date.json file as well and an associated selenium test already in master. This needs removing/fixing, but this is outside the scope of this story and will be done in EQ-718 date of birth)

2016-11-14 13:34 UTC, jonnyshaw89 commented on tests/functional/pages/surveys/dates/dates-answers.page.js
> +  setMonthYearDay(month) {
Is this name correct?

2016-11-14 13:42 UTC, jonnyshaw89 commented on app/schema/widgets/date_widget.py
>              parts = [None, None, '']
Is this correct given that the day is a text box?

2016-11-14 14:58 UTC, LJBabbage commented on tests/functional/pages/surveys/dates/dates-answers.page.js
> +  setMonthYearDay(month) {
Oh yeah, thanks

2016-11-14 15:05 UTC, benjefferies requested changes

2016-11-14 15:05 UTC, benjefferies commented on app/schema/widgets/month_year_date_widget.py
> +        if isinstance(post_vars, dict):
Does this logic have to be complex i.e. Do we need to check if it's a dict or not? Under what circumstance will it not be a dict or will it be the other case?

2016-11-14 15:05 UTC, benjefferies commented on tests/app/validation/test_date_month_year.py
> +        result = month_year_date_type.validate(None)
This feels like 7/8 separate tests to me as we are testing 7/8 different scenarios? The comments are not needed when they are separate tests and it's easier to track broken functionality because it will say test_empty_string will fail in travis?

2016-11-14 15:05 UTC, benjefferies commented on tests/app/validation/test_date_month_year.py
> +if __name__ == '__main__':
I think 

```
if __name__ == '__main__':
    ...
```

is redundant

2016-11-14 15:05 UTC, benjefferies commented on tests/functional/spec/dates.spec.js
> +describe('Checkbox with "other" option', function() {
Describe text is wrong

2016-11-14 15:05 UTC, benjefferies commented on tests/functional/spec/dates.spec.js
> +import chai from 'chai'
Do we need to exercise all of this logic as selenium tests, can the validation logic not be exercised as unit tests?

2016-11-14 15:07 UTC, LJBabbage commented on app/schema/widgets/month_year_date_widget.py
> +        if isinstance(post_vars, dict):
Its the old/current pattern, but it does get them in the different types if memory serves correctly. As discussed, one for technical debt

2016-11-14 15:08 UTC, LJBabbage commented on tests/app/validation/test_date_month_year.py
> +        result = month_year_date_type.validate(None)
No problem will separate them

2016-11-14 15:15 UTC, LJBabbage commented on tests/functional/spec/dates.spec.js
> +import chai from 'chai'
Did both

2016-11-14 15:31 UTC, LJBabbage commented on tests/app/validation/test_date_month_year.py
> +if __name__ == '__main__':
Has been removed

2016-11-14 15:31 UTC, LJBabbage commented on tests/functional/spec/dates.spec.js
> +describe('Checkbox with "other" option', function() {
Updated

2016-11-14 16:02 UTC, benjefferies commented on app/schema/widgets/month_year_date_widget.py
> +        if isinstance(post_vars, dict):
Cool, I have checked and it's still used in both patterns. It's bit nasty and confusing really but not scope of this PR

2016-11-15 10:22 UTC, jonnyshaw89 commented on app/validation/month_year_date_type_check.py
> +            time.strptime(user_answer, "%m/%Y")  # NOQA
Is this just cheating? # NOQA
Maybe if we add this we should also say why?

2016-11-15 10:50 UTC, LJBabbage commented on app/validation/month_year_date_type_check.py
> +            time.strptime(user_answer, "%m/%Y")  # NOQA
Its not needed, and has been removed

2016-11-15 13:50 UTC, hamishtaplin submitted a review, later dismissed

2016-11-15 13:50 UTC, hamishtaplin commented on app/data/test_dates.json
> +{
This adds a `test_dates` schema but we already have `test_date`—should these be combined?

2016-11-15 14:36 UTC, benjefferies commented on app/schema/widgets/date_widget.py
> +        day = {
inline return would be nicer than reassigning day to be something of a totally different type

2016-11-15 14:36 UTC, benjefferies commented on app/schema/widgets/date_widget.py
> +        month = {
inline return would be nicer than reassigning month to be something of a totally different type

2016-11-15 14:36 UTC, benjefferies commented on app/schema/widgets/date_widget.py
> +        year = {
inline return would be nicer than reassigning year to be something of a totally different type

2016-11-15 14:36 UTC, benjefferies commented on app/schema/widgets/date_widget.py
> +        if selected_month:
How will the widget handle it if the selected month isn't selected? Should there always be a selected month?

2016-11-15 15:02 UTC, LJBabbage commented on app/data/test_dates.json
> +{
Yep, but I am doing it in the next story as the note above, just because I need to fix the summary screen for the single date before combining them

2016-11-15 17:03 UTC, LJBabbage commented on app/schema/widgets/date_widget.py
> +        if selected_month:
Its the refilling of pre-existing data, if there is no month then it should not have a selected value and just behave as a normal drop down

2016-11-16 09:40 UTC, benjefferies approved these changes

2016-11-17 09:53 UTC, samiwel commented on app/schema/widgets/month_year_date_widget.py
> +        if isinstance(post_vars, dict):
Just to supplement this discussion, the repeating single answer story and new answer store mechanism should hopefully ensure that only dict will be passed down to the widget going forward.

2016-11-17 11:01 UTC, jonnyshaw89 requested changes
All good once the codacy issues are fixed

2016-11-17 13:50 UTC, jonnyshaw89 approved these changes

2016-11-17 13:50 UTC, merged