added group_id and group_instance to answer store
ONSdigital/eq-survey-runner pull request #567
Opened 2016-11-16 15:01 UTC by jonnyshaw89

### What is the context of this PR?
We need to store answers with the group_id and group_instance so we can develop repeating groups functionality (used by relationship questions and household member personal details)

### How to review 
Check that AnswerStore stores group_id and group_instance for all answers

2016-11-16 15:14 UTC, benjefferies requested changes

2016-11-16 15:14 UTC, benjefferies commented on app/data_model/answer_store.py
> +            self.group_id == answer.group_id and \
Docs need updating

2016-11-16 15:46 UTC, benjefferies approved these changes

2016-11-17 09:41 UTC, samiwel commented on app/data_model/answer_store.py
> +    def __init__(self, answer_id, block_id, group_id, value, answer_instance=0, group_instance=0):
This is only a small point, but semantically, does it make sense to order these in the same order that we'd expect them to appear in the schema e.g. group, block, answer?

2016-11-17 09:56 UTC, iwootten commented on app/data_model/answer_store.py
> +    def __init__(self, answer_id, block_id, group_id, value, answer_instance=0, group_instance=0):
I'd say yes - in my branch I've updated the ones there to be kwargs, because entering a bunch of uuids into an answer makes things really difficult to read where answers are created.

2016-11-17 10:05 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +    def __init__(self, answer_id, block_id, group_id, value, answer_instance=0, group_instance=0):
Done

2016-11-17 10:15 UTC, samiwel approved these changes

2016-11-17 10:21 UTC, ajmaddaford requested changes

2016-11-17 10:21 UTC, ajmaddaford commented on app/questionnaire_state/state_item.py
>          self.instance = 0
We should rename this `answer_instance`, now we have a `group_instance`

2016-11-17 10:21 UTC, ajmaddaford commented on app/questionnaire_state/state_answer.py
>              answer_instance=self.instance,
`instance` -> `answer_instance`

2016-11-17 10:29 UTC, ajmaddaford approved these changes

2016-11-17 10:31 UTC, merged