Add single date type question
ONSdigital/eq-survey-runner pull request #570
Opened 2016-11-17 15:22 UTC by LJBabbage

### What is the context of this PR?
Adding a single date type question; combining all the date tests into one Selenium test and renaming the Jinja templates when formatting date to be more explicit.

### How to review 
Using Dev, use test_dates.json and make sure the survey generates an error message if the date of birth question is either left empty of is an invalid date. Correct the error and then make sure the summary page works and presents the date correct and then submits.

2016-11-17 15:52 UTC, jonnyshaw89 requested changes

2016-11-17 15:52 UTC, jonnyshaw89 commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(format_value, '1 January 2017')
Why does this give full month name and the others are short month names. maybe the filter names should suggest what you will get?

2016-11-17 16:30 UTC, collisdigital commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(format_value, '1 January 2017')
Please check with UX on this; I would assume full month names would be preferable to abbreviations (everywhere)?

2016-11-18 11:01 UTC, LJBabbage commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(format_value, '1 January 2017')
All changed to long months as agreed

2016-11-18 11:06 UTC, jonnyshaw89 approved these changes

2016-11-18 11:15 UTC, benjefferies requested changes

2016-11-18 11:15 UTC, benjefferies commented on app/jinja_filters.py
> +def format_str_as_short_date(value):
Do we need the str_as part?

2016-11-18 11:15 UTC, benjefferies commented on app/templates/partials/summary/date.html
> +{% if question.type == 'DateRange' %}
It would be nice if we could pull the formatting out into different templates so we didn't have this logic in the template

2016-11-18 11:29 UTC, LJBabbage commented on app/jinja_filters.py
> +def format_str_as_short_date(value):
Making it explicit due to the fact we have other Jinja filters formating dates that aren't strings

2016-11-18 11:30 UTC, LJBabbage commented on app/templates/partials/summary/date.html
> +{% if question.type == 'DateRange' %}
Due to a refactor of summary page after Census test, this was the agreed approach for now

2016-11-18 11:37 UTC, benjefferies commented on app/data/test_dates.json
> +                                            "id": "a51b1c7b-3f25-49dd-9275-2ea742eee510",
Shall we give the schema ids more descriptive names?

2016-11-18 11:42 UTC, LJBabbage commented on app/data/test_dates.json
> +                                            "id": "a51b1c7b-3f25-49dd-9275-2ea742eee510",
Agree, but lets agree a format, time and a place to do it and raise a story to cover all the id's just not the odd one in a middle of a story

2016-11-18 11:44 UTC, benjefferies commented on app/data/test_dates.json
> +                                            "id": "a51b1c7b-3f25-49dd-9275-2ea742eee510",
Boy scout rule?

2016-11-18 12:32 UTC, LJBabbage commented on app/data/test_dates.json
> +                                            "id": "a51b1c7b-3f25-49dd-9275-2ea742eee510",
Happy to have a meeting with the team and discuss id structure for answers, blocks, question etc and the process we migrate them from what we have to that new structure and raise a card, but doing it for one answer in one of 20 schemas which all have GUID's seems a little out of scope of this story

2016-11-18 12:36 UTC, benjefferies approved these changes
Can you squash your commits down?

It might be worth setting up a meeting to address how we are going to name things in test schemas. I have just been going by common sense in the past as they are just test schemas and nothing public facing.

2016-11-18 13:26 UTC, merged