Enabled config of werkzeug log level and reduce TRAVIS CI logging
ONSdigital/eq-survey-runner pull request #572
Opened 2016-11-17 21:02 UTC by collisdigital

### What is the context of this PR?
Travis builds logs are full of INFO logging from the app and werkzeug making it hard to see errors and test output. This change enables config of the "werkzeug" logging level (which was logging every GET) and sets both it and the normal app logging to WARNING for TRAVIS builds.

I also moved login init outside of logging setup function as it looks to have been put there by mistake (logging/login??)

### How to review 
- Check Travis build log for this PR and confirm only WARNING/ERROR messages are displayed.
- Confirm if we're happy to not log INFO on TRAVIS before merging.

2016-11-17 22:12 UTC, collisdigital commented on tests/functional/config.js
> +    logLevel: 'silent',
Note that `silent` is the default logLevel for WebDriver.IO http://webdriver.io/guide/getstarted/configuration.html

2016-11-18 08:33 UTC, jonnyshaw89 requested changes

2016-11-18 08:33 UTC, jonnyshaw89 commented on app/settings.py
> +EQ_WERKZEUG_LOG_LEVEL = os.getenv('EQ_WERKZEUG_LOG_LEVEL', 'INFO')
This new environment variable should be added to the Readme

2016-11-18 13:35 UTC, collisdigital commented on app/settings.py
> +EQ_WERKZEUG_LOG_LEVEL = os.getenv('EQ_WERKZEUG_LOG_LEVEL', 'INFO')
Done

2016-11-18 14:50 UTC, jonnyshaw89 approved these changes

2016-11-18 15:29 UTC, merged