Fixed most pylint issues
ONSdigital/eq-survey-runner pull request #576
Opened 2016-11-20 09:11 UTC by collisdigital

### What is the context of this PR?
Worked through most of the issues reported by Pylint in #574 and fixed them. Not all issues are resolved yet.

### How to review 
Review changes, decide if it is worth merging them in now given it will likely cause merge problems for everyone for a period due to number of files touched.

2016-11-20 09:36 UTC, collisdigital commented
Was planning to resolve the `Redefining built-in 'id'` in a later PR

2016-11-21 09:18 UTC, ajmaddaford requested changes

2016-11-21 09:18 UTC, ajmaddaford commented on app/authentication/jwt_decoder.py
> +        header_data, _, _ = token.split('.', maxsplit=2)  # header_data, payload_data, signature_data
For this method and the `_check_payload` method it would be better to split the token before the method calls and only pass `header_data` or `payload_data` to the methods

2016-11-21 09:29 UTC, collisdigital commented on app/authentication/jwt_decoder.py
> +        header_data, _, _ = token.split('.', maxsplit=2)  # header_data, payload_data, signature_data
Although this function also uses the token at the end as well; hmmm...

2016-11-21 16:56 UTC, collisdigital commented
PR Horribly Broken, sorry!

2016-11-21 16:56 UTC, closed without merging