Added basic census schemas.
ONSdigital/eq-survey-runner pull request #580
Opened 2016-11-22 15:12 UTC by jonnyshaw89

### What is the context of this PR?
Added basic census schemas.
Mainly Household survey but includes skeleton schemas for individual and communal establishment.

2016-11-23 20:49 UTC, collisdigital commented on tests/functional/generate_pages.py
> +        radio_check = find_kv(block, 'type', 'Radio')
Does this also need to check for Checkbox types?

2016-11-23 20:49 UTC, collisdigital commented on tests/functional/generate_pages.py
> +    if answer['type'] == 'Date':
can be `elif`

2016-11-23 20:56 UTC, collisdigital commented on tests/functional/generate_pages.py
> +        answer_name = generate_camel_case_from_id(answer['id'])
Worth moving all this to a separate function to keep it clean?

2016-11-23 20:58 UTC, collisdigital commented on tests/functional/generate_pages.py
> +    else:
Could this actually be `elif answer['type'] == 'TextField':` ? possible with a final `else` that throws an Exception so it's obvious when the type isn't handled.

2016-11-25 15:47 UTC, ajmaddaford commented on app/data/schema/schema-v1.json
>  {
The reformatting it should be done in a separate commit, it's not clear what changes (if any) there are.

2016-11-25 15:47 UTC, ajmaddaford commented on app/questionnaire/navigator.py
> +    answer_to_test = answer[0] if (isinstance(answer, list) and len(answer) == 1) else answer
I think this is superseded by the work in #578. Mentioning it here as it won't conflict as it's done in a different place in the other pull request.

2016-11-25 16:23 UTC, ajmaddaford requested changes

2016-11-25 16:23 UTC, ajmaddaford commented on tests/functional/generate_pages.py
> +SPEC_PAGE_IMPORT = r"""import {pageName} from '../pages/surveys/census/household/{pageFile}'
Seems a bit census specific 😛

2016-11-27 14:57 UTC, benjefferies commented on tests/functional/generate_pages.py
> +        muntiple_choice_check = find_kv(block, 'type', ['Radio', 'Checkbox'])
muntiple -> multiple?

2016-11-28 10:27 UTC, benjefferies requested changes

2016-11-28 10:27 UTC, benjefferies commented on app/data/census_household.json
> +                            "id": "else-permanent-or-family-home_section",
_section should be -section I guess?

2016-11-28 10:27 UTC, benjefferies commented on app/data/census_household.json
> +                                            "q_code": "20",
Do we know what these q_codes should be?

2016-11-28 10:27 UTC, benjefferies commented on app/questionnaire/navigator.py
> +    # answer_to_test = answer[0] if (isinstance(answer, list) and len(answer) == 1) else answer
Can we delete the line if not needed?

2016-11-28 10:34 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                                            "q_code": "20",
no not yet.

2016-11-28 10:34 UTC, jonnyshaw89 commented on app/questionnaire/navigator.py
> +    # answer_to_test = answer[0] if (isinstance(answer, list) and len(answer) == 1) else answer
ah yes, that got left after my merge fixes

2016-11-28 14:06 UTC, benjefferies approved these changes

2016-11-28 14:21 UTC, ajmaddaford approved these changes

2016-11-28 14:21 UTC, merged