Adds support for question highlights
ONSdigital/eq-survey-runner pull request #590
Opened 2016-11-27 23:00 UTC by collisdigital

### What is the context of this PR?
Adding support for highlights within questions as per the latest tested design prototypes
- See http://onsdigital.github.io/eq-prototypes/ukis/v3/section-11/ for example
- Or http://onsdigital.github.io/eq-prototypes/census-lite/v7/section-4/

<img width="620" alt="screen shot 2016-11-27 at 22 47 14" src="https://cloud.githubusercontent.com/assets/14041600/20652561/7a44c018-b4f3-11e6-8db4-e18f937d2dd2.png">

<img width="655" alt="screen shot 2016-11-27 at 22 46 58" src="https://cloud.githubusercontent.com/assets/14041600/20652563/7df69164-b4f3-11e6-9eaf-15cdbf9c8128.png">

Highlights are attached to questions and can contain optional titles, descriptions and bullet lists of items to show. Multiple highlights are allowed per question (they stack below each other).

Here's an example of the JSON to add a highlight to a question object:

```Javascript
"highlights": [
    {
        "title": "Include",
        "description": "<p>Highlight <b>include</b> description text</p>",
        "list": [
            "Item Include 1",
            "Item Include 2",
            "Item Include 3",
            "Item Include 4"
        ]
    },
    {
        "title": "Exclude",
        "description": "<p>Highlight <b>exclude</b> description text</p>",
        "list": [
            "Item Exclude 1",
            "Item Exclude 2",
            "Item Exclude 3",
            "Item Exclude 4"
        ]
    }
```

The general approach (in the schema) was agreed with @ajmaddaford and @hamishtaplin.

### Help needed
This PR needs help on the selenium test, see the strawman approach, is this the right way to go? Should we be checking raw HTML in the test like this?

The frontend changes and SCSS need a FEer to review; noting that the existing alert style used a 90% hint to handle the background, which didn't match the actual approach to the design, so I've added a default to use 90% and the ability to override the alert background if needed (and used that here).

The Census theme hasn't been updated to include the highlight style; it's not clear how best to do this looking at the existing theme (maybe wait for Census Header, Footer & Landing Page Design (8) card?), discuss with @hamishtaplin.

Finally the schemas in #580 will need updating (after that merges) to break out the include/exclude lists etc.

### How to review 
- Run the `test_question_highlights.json` schema to see various examples of highlights.
- Run each of the existing business surveys schemas (0102, 0112, 0215 etc.) and verify the highlights have been applied correctly.
- Review the schema approach taken and names of elements used, are they acceptable?
- Review the frontend changes to the question.html
- Review the SCSS changes

2016-11-28 09:13 UTC, hamishtaplin requested changes

2016-11-28 09:13 UTC, hamishtaplin commented on app/templates/partials/question.html
> +                <li class="mars">{{item|safe}}</li>
We don't need to explicitly use the `mars` class as it's the default body text style (ignore how the prototypes approach this)

2016-11-28 09:13 UTC, hamishtaplin commented on app/assets/styles/partials/vars/_colors.scss
> +$color-highlight: #003d59;
I'm not sure we need to store this colour as a variable as it won't be used again elsewhere. Need to check why it's not just the brand shade of blue as it's very close. 

In fact, there's already a style for an alert using the brand colour of the theme here: https://onsdigital.github.io/eq-survey-runner-patterns/components/detail/alert--default.html

2016-11-28 09:13 UTC, hamishtaplin commented on app/data/1_0102.json
> +                                    "description": "Round your figures to the nearest whole pound (£). Even if your figures are zero, please still complete.",
I realise this isn't a change we introduced here but we should be consistent with how we apply the paragraphs in the description as this doesn't have a wrapping `<p>` tag but others do.

2016-11-28 15:58 UTC, hamishtaplin approved these changes

2016-11-28 16:06 UTC, jonnyshaw89 requested changes
Should be be updating the current Census schemas with these changes?

2016-11-28 16:55 UTC, collisdigital commented
Will make the changes to the household schema as part of this PR

2016-11-29 09:08 UTC, jonnyshaw89 approved these changes

2016-11-29 09:08 UTC, jonnyshaw89 commented
@collisdigital Are the labels on this PR still relevant?

2016-11-29 09:23 UTC, collisdigital commented
@jonnyshaw89 Yes, whilst @hamishtaplin  and @bennpearson  review the spacing and alignment of the boxes

2016-11-29 13:49 UTC, yoganandkunche commented
QA for this PR is done on the branch.
Cross browser testing is done: Window (IE,Chrome,Firefox) Mac (Safari, Firefox, Chrome) Android (Samsung S7) iOS (Iphone 7s) Ipad.
One minor issue identified for Survey 0102 & 0112. Please find attached screenshot.
![screen shot 2016-11-29 at 11 46 06](https://cloud.githubusercontent.com/assets/21335236/20712104/a71fc8a6-b63a-11e6-8cd5-4d7b7b1ba344.png)

2016-11-29 14:38 UTC, collisdigital commented
@yoganandkunche fixed 0112 and 0102 schemas.

Agreed with @hamishtaplin and @bennpearson that margins and whitespace issues will be resolved as part of https://trello.com/c/PBOnBqqL (vertical rhythm).

2016-11-29 15:10 UTC, merged