Extend schema validation to validate routing rules are valid
ONSdigital/eq-survey-runner pull request #608
Opened 2016-12-01 14:09 UTC by jonnyshaw89

### What is the context of this PR?
Extend the schema validation test to ensure that the routing rules are semantically correct and cover all scenarios. 

Fixes 601 and Fixes 602

### How to review 
Re-test issues.

2016-12-01 15:45 UTC, samiwel commented on app/data/0_star_wars.json
> +                            }
Do we need to specify a `goto` route if it's just going to the next block? Assuming the previous routing rules don't fire, doesn't it just route to the next block anyway?

2016-12-01 15:45 UTC, samiwel commented on tests/app/data/test_schema_validation.py
> +                    is_goto_rule = 'goto' in rule and 'when' in rule['goto'].keys() or 'id' in rule['goto'].keys()
Do we need this check? `'when' in rule['goto'].keys() or ` Isn't it sufficient just to check for existence of `'id'`?

2016-12-01 15:51 UTC, jonnyshaw89 commented on tests/app/data/test_schema_validation.py
> +                    is_goto_rule = 'goto' in rule and 'when' in rule['goto'].keys() or 'id' in rule['goto'].keys()
agree, ill change this

2016-12-01 15:58 UTC, jonnyshaw89 commented on app/data/0_star_wars.json
> +                            }
we need to specify, the way the navigator works if routing_rules are defined then 1 of them needs to match or default

2016-12-01 16:23 UTC, samiwel commented on app/data/0_star_wars.json
> +                            }
Okay, fair enough.

2016-12-01 19:39 UTC, collisdigital commented on tests/app/data/test_schema_validation.py
> +            error = self.validate_schema_contains_valid_routing_rules(file, json_to_validate)
Each time error is set is overriding the last before the list is extended finally below (will only lost last error found if there were multiple); maybe extend errors immediately? Or alternatively only call later checks of previous check had no errors?

2016-12-01 19:41 UTC, collisdigital commented on tests/app/data/test_schema_validation.py
> +            error = self.validate_schema_contains_valid_routing_rules(file, json_to_validate)
Only **list** ...

2016-12-02 08:44 UTC, jonnyshaw89 commented on tests/app/data/test_schema_validation.py
> +            error = self.validate_schema_contains_valid_routing_rules(file, json_to_validate)
A keen eye you have.

2016-12-02 09:43 UTC, benjefferies requested changes

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +    def validate_schema_containing_routing_rules_has_default_if_nots_all_answers_routed(file, json_to_validate):
validate_schema_containing_routing_rules_has_default_if_nots_all_answers_routed -> validate_schema_containing_routing_rules_has_default_if_not_all_answers_routed

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                        try:
This try except block seems a bit nasty and hard to understand. I think we should create a has_block method in the test file instead

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +    def validate_schema_containing_routing_rules_has_default_if_nots_all_answers_routed(file, json_to_validate):
validate_schema_containing_routing_rules_has_default_if_nots_all_answers_routed -> validate_schema_containing_routing_rules_has_default_if_not_all_answers_routed

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                                    if answer['type'] == 'Radio' or answer['type'] == 'Checkbox':
I think we should refactor this to a method called get_radio_and_checkbox_answers so it is more readable in what it's doing

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                                            options = []
Could do some nice bit of python magic here

```
options = [option['value'] for option in answer['options']]
```

2016-12-02 09:43 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                                            if len(options) > 0 and len(options) != len(answer['options']):
Might be nice to refactor to boolean variable no_routing_or_all_routes for clarity

2016-12-02 10:49 UTC, benjefferies approved these changes

2016-12-02 11:57 UTC, ajmaddaford requested changes

2016-12-02 11:57 UTC, ajmaddaford commented on tests/app/data/test_schema_validation.py
> +                for section in block['sections']:
Can we remove some of the nesting by doing something like this for each loop:
```
for section in (s for s in block['sections'] if 'sections' in block)
```

2016-12-02 11:57 UTC, ajmaddaford commented on tests/app/data/test_schema_validation.py
> +    def validate_schema_containing_routing_rules_has_default_if_not_all_answers_routed(file, json_to_validate):
I think `validate_routing_rules_has_default_if_not_all_answers_routed` says the same in a few less words

2016-12-02 11:57 UTC, ajmaddaford commented on tests/app/data/test_schema_validation.py
> +                    if is_goto_rule:
Can this not just be `if 'goto' in rule and 'id' in rule['goto'].keys():`?

2016-12-02 11:57 UTC, ajmaddaford commented on tests/app/data/test_schema_validation.py
> +                        if not cls.has_block(json_to_validate, rule['goto']['id']):
I think this method would be clearer as `schema_has_block`

2016-12-02 11:57 UTC, ajmaddaford commented on tests/app/data/test_schema_validation.py
> +                        if rule['goto']['id'] == 'summary':
`rule['goto']['id']` is used three times, might be neater using a variable e.g. `block_id`

2016-12-02 13:43 UTC, ajmaddaford approved these changes

2016-12-02 14:21 UTC, merged