WIP Household composition real time changes
ONSdigital/eq-survey-runner pull request #610
Opened 2016-12-01 18:19 UTC by ajmaddaford

### What is the context of this PR?

This PR has the backend changes required for the household composition real time changes to work
(removing all person related answers on POST of household composition)

2016-12-06 14:12 UTC, yoganandkunche commented
QA passed on Branch. Created a new trello card following discussion with Louise M

https://trello.com/c/frP99GYd/778-census-must-not-wipe-data-if-responded-does-not-make-any-changes-on-household-who-live-here-page

2016-12-06 14:41 UTC, benjefferies requested changes

2016-12-06 14:41 UTC, benjefferies commented on app/data_model/answer_store.py
> +            answer_store_answer = Answer(group_id=answer['group_id'],
Seems a bit overkill to find the answer create an answer find the answer index and then remove via index when we can just do self.answers.remove(answer)

2016-12-06 14:59 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +            answer_store_answer = Answer(group_id=answer['group_id'],
Good point!

2016-12-06 16:45 UTC, benjefferies requested changes

2016-12-06 16:45 UTC, benjefferies commented on app/data_model/answer_store.py
> +        for answer in answers:
Not sure if we can modify the list if we are iterating over it when user_filter == False. Worth a test to confirm

2016-12-06 16:45 UTC, benjefferies commented on tests/app/data_model/test_answer_store.py
> +        self.assertEqual(self.store.map(), expected_answers)
At this point can't we make the assumption that they have been added?

2016-12-06 17:32 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +        for answer in answers:
Good spot! Fixed the code and added a unit test

2016-12-06 17:33 UTC, ajmaddaford commented on tests/app/data_model/test_answer_store.py
> +        self.assertEqual(self.store.map(), expected_answers)
Yeah, it was copied and pasted from another test. I've removed it from this one now.

2016-12-07 12:24 UTC, collisdigital commented
Waiting on unit/int tests from @ajmaddaford before merging

2016-12-07 16:45 UTC, benjefferies commented on tests/app/data_model/test_answer_store.py
> +    def test_remove_all_answers(self):
Should we have more tests to cover each filter param?

2016-12-07 16:46 UTC, benjefferies commented on tests/integration/household_composition/test_repeating_household.py
> +class TestRepeatingHousehold(IntegrationTestCase):
Definitely made sense to make these integration tests

2016-12-07 16:51 UTC, benjefferies approved these changes

2016-12-07 16:54 UTC, ajmaddaford commented on tests/app/data_model/test_answer_store.py
> +    def test_remove_all_answers(self):
Possibly, my thinking was it uses filter and that has tests for each param.

2016-12-07 16:54 UTC, samiwel commented on app/templates/partials/questions/repeatinganswer.html
> +    <h2 class="question)__title neptune">{{question_title}}</h2>
Is the `)` a typo in the class name?

2016-12-07 16:55 UTC, samiwel commented on app/assets/js/app/modules/household.js
> +    this.removeBtn.innerHTML = 'Remove'
Is this string translatable for the Welsh version of census?

2016-12-07 17:02 UTC, jonnyshaw89 requested changes

2016-12-07 17:02 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +        use_filter = (group_id or block_id or answer_id or group_instance or answer_instance) is not None
could the use_filter logic potentially go into the filter function as its duplicated in a couple of places in this file. e.g. if you pass no filter arguments in then it doesn't filter?

2016-12-08 09:23 UTC, ajmaddaford commented on app/templates/partials/questions/repeatinganswer.html
> +    <h2 class="question)__title neptune">{{question_title}}</h2>
Good spot. Fixed.

2016-12-08 09:23 UTC, ajmaddaford commented on app/assets/js/app/modules/household.js
> +    this.removeBtn.innerHTML = 'Remove'
Good spot. I'll speak to @hamishtaplin tomorrow about what we can do for this

2016-12-08 09:23 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +        use_filter = (group_id or block_id or answer_id or group_instance or answer_instance) is not None
Good point. I've moved the `use_filter` logic out of the `remove` and `map` methods. I think we should consider making the `filter` method something we can chain in the future, so we could have something like `answer_store.filter(group_id='group1').remove()`

2016-12-08 09:27 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +        If no filter parameters are passed it returns a copy of the list of all answers.
Oh, so it already worked like that?

2016-12-08 10:28 UTC, ajmaddaford commented on app/data_model/answer_store.py
> +        If no filter parameters are passed it returns a copy of the list of all answers.
Yeah

2016-12-08 10:47 UTC, jonnyshaw89 approved these changes

2016-12-08 10:48 UTC, jonnyshaw89 commented
👍 Lets squash this one.

2016-12-08 10:53 UTC, ajmaddaford commented
There is still a small change to make to sort out the 'Remove' text in the Javascript

2016-12-08 11:05 UTC, jonnyshaw89 commented
@ajmaddaford Is that currently being worked on or can it be follow up?

2016-12-08 13:59 UTC, ajmaddaford commented
@bennpearson is working on it

2016-12-08 15:27 UTC, samiwel approved these changes
Looking good. There'll be some work to do merging this PR with the multiple repeating answers PR though.

2016-12-09 09:31 UTC, ajmaddaford commented
Merge waiting on #613

2016-12-10 09:55 UTC, benjefferies commented
Once #631 is merged I can squash this one and it's ready to go?

2016-12-10 10:46 UTC, ajmaddaford commented
@benjefferies yes

2016-12-10 11:10 UTC, benjefferies commented
I will have to resolve all conflicts for each rebase although any merge conflicts have been resolved previously. For that reason to get the same result I will just copy the repo and create a new commit

2016-12-10 13:48 UTC, benjefferies commented on tests/integration/household_composition/test_household_question.py
> -        form_data = MultiDict()
The add logic has been tested in another test, we don't need to test it again

2016-12-12 11:40 UTC, ajmaddaford commented
Closing this pull request, changes raised in new pull request #696

2016-12-12 11:40 UTC, closed without merging