Census individual are these details correct
ONSdigital/eq-survey-runner pull request #627
Opened 2016-12-05 12:26 UTC by jonnyshaw89

### What is the context of this PR?
Fixes https://github.com/ONSdigital/eq-survey-runner/issues/625

2016-12-05 18:15 UTC, ajmaddaford approved these changes

2016-12-06 09:54 UTC, iwootten requested changes

2016-12-06 09:54 UTC, iwootten commented on tests/functional/spec/census/issues/individual-Q1-are-these-details-correct.spec.js
> +import PermanentOrFamilyHome from '../../../pages/surveys/census/household/permanent-or-family-home.page.js'
It looks like many of these imports aren't actually used. I count 17 pages in the tests, with 71 imports. Can they be tidied up?

2016-12-06 09:55 UTC, iwootten requested changes

2016-12-06 09:55 UTC, iwootten commented on tests/functional/spec/census/issues/household-member-details-q1-are-these-details-correct.spec.js
> +import PermanentOrFamilyHome from '../../../pages/surveys/census/household/permanent-or-family-home.page.js'
It looks like many of these imports aren't actually used. I count 17 pages in the tests, with 71 imports. Can they be tidied up?

2016-12-06 09:57 UTC, jonnyshaw89 commented on tests/functional/spec/census/issues/household-member-details-q1-are-these-details-correct.spec.js
> +import PermanentOrFamilyHome from '../../../pages/surveys/census/household/permanent-or-family-home.page.js'
Yeh i guess so, they are auto generated with the page models. Have we excluded tests from any code checking? as those things normally go nuts over this.

2016-12-06 10:23 UTC, jonnyshaw89 commented on tests/functional/spec/census/issues/household-member-details-q1-are-these-details-correct.spec.js
> +import PermanentOrFamilyHome from '../../../pages/surveys/census/household/permanent-or-family-home.page.js'
Have removed unused

2016-12-06 13:28 UTC, iwootten approved these changes

2016-12-06 14:45 UTC, merged