Implementing Census Communal Establishment schema with selenium tests
ONSdigital/eq-survey-runner pull request #630
Opened 2016-12-05 15:27 UTC by jonnyshaw89

### What is the context of this PR?
Implementing Census Communal Establishment schema with selenium tests

### How to review 
Load schema census_communal.json and confirm it matches slides.

2016-12-06 13:44 UTC, benjefferies requested changes

2016-12-06 13:44 UTC, benjefferies commented on app/data/census_communal.json
> +                                    "type": "General",
Does this need guidance for "Count double rooms as 2 guest bed spaces"

2016-12-06 13:44 UTC, benjefferies commented on app/data/census_communal.json
> +                                    "description": "For the 2021 Census all hotels, B&B, guest houses etc. will be expected to complete a questionnaire about their establishment. All usual residents
Should this appear as guidance or something as it looks in the wrong order

2016-12-06 13:51 UTC, jonnyshaw89 commented on app/data/census_communal.json
> +                                    "type": "General",
will add as description.

2016-12-06 13:54 UTC, jonnyshaw89 commented on app/data/census_communal.json
> +                                    "description": "For the 2021 Census all hotels, B&B, guest houses etc. will be expected to complete a questionnaire about their establishment. All usual residents
I don't think we actually have anything that displays in that order?

2016-12-07 08:21 UTC, benjefferies commented on app/data/census_communal.json
> +                                    "description": "For the 2021 Census all hotels, B&B, guest houses etc. will be expected to complete a questionnaire about their establishment. All usual residents
This is the only thing that looked really wrong against the slides anyway

2016-12-07 09:14 UTC, jonnyshaw89 commented on app/data/census_communal.json
> +                                    "description": "For the 2021 Census all hotels, B&B, guest houses etc. will be expected to complete a questionnaire about their establishment. All usual residents
This has been resolved now with the section description

2016-12-07 10:30 UTC, benjefferies approved these changes

2016-12-07 16:01 UTC, samiwel approved these changes

2016-12-07 16:03 UTC, ajmaddaford approved these changes

2016-12-07 17:02 UTC, merged