Add conditional routing to a previous group location
ONSdigital/eq-survey-runner pull request #631
Opened 2016-12-05 15:35 UTC by iwootten

### What is the context of this PR?
Adds conditional routing to a previous location. Allows us to support the routing of users to the household composition screen in census, based on the answer to a question. This is handled by adding a route to the routing path and removing the users current answer to this question (which would otherwise prevent the location path being calculated by navigator).

Additionally, I've added a pluralize jinja filter to support person/people is/are based pluralization of text, which will need some work in another story to evaluate a more appropriate approach.

### How to review 
There are unit tests in navigator and integration tests to cover new behaviour. I've had to update current composition selenium tests to work with the new block.

========================================

2016-12-07 15:32 UTC, benjefferies requested changes

2016-12-07 15:32 UTC, benjefferies commented on app/data/test_household_question.json
> +                                  "description": "",
Can description/display be removed?

2016-12-07 15:32 UTC, benjefferies commented on app/data/test_household_question.json
> +                            "display": {
Can display be removed?

2016-12-07 15:32 UTC, benjefferies commented on app/jinja_filters.py
> +def pluralize(number, singular='', plural='s'):
Should we not be able to get this functionality from flask babel?

2016-12-07 15:32 UTC, benjefferies commented on app/main/views/questionnaire.py
> -def _go_to_next_block(location, eq_id, form_type, collection_id):
Nice tidy up

2016-12-07 15:32 UTC, benjefferies commented on app/questionnaire/navigator.py
> +        self.first_location = self.location_path[0]
Aren't first_block_location and first_location the same?

2016-12-07 15:32 UTC, benjefferies commented on app/questionnaire/navigator.py
> +                        answer = Answer(answer_id=rule['goto']['when']['id'],
Do we need another check here incase it's a metadata rule?

2016-12-07 15:32 UTC, benjefferies commented on tests/functional/pages/surveys/household_composition/summary.page.js
> +    return browser.element('.box--entity__person').getText() === name
I think the preference to to use id/name/attribute hook over classes

2016-12-07 15:35 UTC, jonnyshaw89 requested changes

2016-12-07 15:35 UTC, jonnyshaw89 commented on app/data/test_household_question.json
> +                            "description": "<h3>There {{answers.person_full_name|length|pluralize('is', 'are')}} <strong class='strong-census'>{{answers.person_full_name|length}} {{answers.person_ful
We need to also integrate this into the census household schema.

2016-12-07 15:35 UTC, jonnyshaw89 commented on app/main/views/questionnaire.py
> +    return redirect(location_url(eq_id, form_type, collection_id, next_location))
👍

2016-12-07 15:39 UTC, iwootten commented on app/questionnaire/navigator.py
> +        self.first_location = self.location_path[0]
Nope, not always. First_location points to everything, including interstital. Block location only includes blocks.

2016-12-07 15:46 UTC, iwootten commented on tests/functional/pages/surveys/household_composition/summary.page.js
> +    return browser.element('.box--entity__person').getText() === name
Yeah, this is subject to whatever we decide the template we're rendering is going to end up.

2016-12-07 15:52 UTC, benjefferies commented on app/questionnaire/navigator.py
>          self.first_block_id = SchemaHelper.get_first_block_id(self.survey_json)
We don't use this first_block_id other than below to create the first_block_location, maybe we should get rid as we have lots of first location related fields

2016-12-07 16:39 UTC, benjefferies commented
Can you cherry pick issue selenium test onto branch https://github.com/ONSdigital/eq-survey-runner/commit/ecabc7f571970d17d5ebaf0f4bc203c8325f6925

2016-12-08 16:20 UTC, iwootten commented
@benjefferies - the scenarios are covered in the current census/routing/census-routing-scenarios.spec.js routing file and commented out, I've just uncommented everything from there.

2016-12-09 10:21 UTC, iwootten commented
I've reverted the changes I made to repeating answers and left with guidance displaying incorrectly. 

![screen shot 2016-12-09 at 10 16 05](https://cloud.githubusercontent.com/assets/3598161/21045535/bbe69876-bdf8-11e6-9de1-113edbecc7c9.png)

2016-12-09 11:22 UTC, benjefferies commented on tests/functional/spec/census/routing/census-routing-scenarios.spec.js
> -    it('Given I am answering question 1 in the individual detail section, When I select -yes- as respone, Then I am routed to What is you sex question 2 ', function () {
How come we are deleting these tests?

2016-12-09 11:24 UTC, jonnyshaw89 approved these changes

2016-12-09 11:25 UTC, benjefferies approved these changes

2016-12-09 11:26 UTC, benjefferies commented
Has anyone front-end reviewed? @hamishtaplin @bennpearson

2016-12-10 08:00 UTC, benjefferies commented
If someone okays the last commit I'll squash down and someone can merge

2016-12-10 08:12 UTC, collisdigital commented on app/data/test_household_question.json
> +                                    "id": "summary",
Is this right in terms of where to go next?

2016-12-10 08:15 UTC, benjefferies commented on app/data/test_household_question.json
> +                                    "id": "summary",
In the test schema does it matter much?

2016-12-10 08:16 UTC, benjefferies commented on app/data/test_household_question.json
> +                                    "id": "summary",
I think it makes sense in the context of the question, if you have entered everyone go to the next section which in the test schema is the summary

2016-12-10 08:26 UTC, collisdigital commented on app/data/test_household_question.json
> +                                    "id": "summary",
Sorry thought it was the HH schema, ignore me 😆

2016-12-10 09:49 UTC, jonnyshaw89 commented
👍 LGTM

2016-12-10 09:54 UTC, benjefferies commented
Squashed and ready to go once all is green

2016-12-10 10:14 UTC, merged