Eq 781 mandatory first name
ONSdigital/eq-survey-runner pull request #660
Opened 2016-12-08 17:10 UTC by benjefferies

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2016-12-09 10:42 UTC, jonnyshaw89 requested changes

2016-12-09 10:42 UTC, jonnyshaw89 commented on app/data/census_individual.json
>                                              "mandatory": false,
Should this one also be mandatory?

2016-12-09 10:42 UTC, jonnyshaw89 commented on tests/functional/generate_pages.py
> +            answer_name = generate_camel_case_from_id(answer['id'])
define this outside of the if so you don't also have to define it in the else

2016-12-09 10:42 UTC, jonnyshaw89 commented on tests/functional/spec/census-household.spec.js
> +        HouseholdComposition.setFirstName(0, 'John').submit()
do we have any scenario where we enter middle and last name?

2016-12-09 10:45 UTC, benjefferies commented on tests/functional/spec/census-household.spec.js
> +        HouseholdComposition.setFirstName(0, 'John').submit()
Don't think we need to. We need to test the scenario that the middle/last is optional. Maybe that would be good as an explicit test. As for the second test I am going to delete, it's not really a selenium test, it is unit tested

2016-12-09 12:10 UTC, jonnyshaw89 commented on tests/functional/pages/surveys/census/household/address-type.page.js
> +  isOpen() {
Can this not move up the the question page class and then just provide the blockId in each file?

2016-12-09 14:03 UTC, samiwel commented on tests/functional/spec/census-household.spec.js
> +        HouseholdComposition.setFirstName(0, 'John').submit()
The Jina filter I created should display middle and last names appropriately if only middle and/or last were provided. But the fact that we've added mandatory validation here will help to ensure that we always have something, which is good.

2016-12-09 15:38 UTC, samiwel commented
I noticed that the validation messages appears correctly when the Save and continue button is pressed, but when I the add new person button is pressed the error was not displayed yet I was prevented from adding additional household members (presumably due to failed validation).

Does it make sense to ignore the validation check when adding new people? So that users can add as many new people as they like, but fail the validation as soon as they hit save and continue? From a UX point of view, I guess that is more consistent with the way that screen behaves when JS is enabled on that page.

2016-12-10 09:19 UTC, benjefferies commented
I think your right Sam, from a UX views they should act the same. I have removed validation on the add/remove action

2016-12-10 09:43 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_household_composition.py
> +        self.assertNotIn('This field is mandatory.', resp.get_data(True))
If we returned a status code of 400 for invalid answers we wouldn't need to check the body making testing end points nicer. I know in REST apis status codes are ubiquitous but not sure how it fits in outside them

2016-12-12 14:38 UTC, jonnyshaw89 commented
@benjefferies @samiwel i think the removing of validation isn't a good thing. if i click add lots of times, when go previous and say no one lives here, then go forward i get repeated around lots of groups of people with empty names.

2016-12-12 15:19 UTC, jonnyshaw89 requested changes

2016-12-12 15:19 UTC, jonnyshaw89 commented on app/main/views/questionnaire.py
> +        questionnaire_manager.build_state(this_block, request.form)
if my request.form contained answers for other blocks would they be applied without being validated. I'm a little worried that we have exposed our answer store to be open to abuse by not validating.

2016-12-12 15:19 UTC, jonnyshaw89 commented on tests/functional/generate_pages.py
> +ANSWER_SELECT = r"""  set{answerName}(value) {
ANSWER_SELECT -> ANSWER_SELECTOR?

2016-12-12 15:53 UTC, jonnyshaw89 commented
If you add a person with no name, click previous then go forwards again. you can then not ever remove them.

2016-12-13 16:41 UTC, jonnyshaw89 commented on tests/functional/pages/surveys/question.page.js
> +        throw new Error(`Expected to be on ${this.pageName} page but was on ${browser.getUrl()}`)
Kudos

2016-12-14 11:11 UTC, jonnyshaw89 commented
I have created an issue (https://github.com/ONSdigital/eq-survey-runner/issues/727) for the scenario i found above. But given that that existed before this PR I'm happy.

2016-12-14 11:12 UTC, jonnyshaw89 approved these changes

2016-12-14 11:16 UTC, samiwel approved these changes
Looks good to me 👍

2016-12-14 11:38 UTC, ajmaddaford requested changes

2016-12-14 11:38 UTC, ajmaddaford commented on tests/functional/spec/census-household.spec.js
> +    it('Given I enter a first name but no middle or surname, When I save and continue, Then I should see errors that first name is mandatory.', function () {
Should this say no errors?

2016-12-14 11:39 UTC, benjefferies commented on tests/functional/spec/census-household.spec.js
> +    it('Given I enter a first name but no middle or surname, When I save and continue, Then I should see errors that first name is mandatory.', function () {
Your sharp-eyed, always catching me out on these!

2016-12-14 11:45 UTC, ajmaddaford approved these changes

2016-12-14 14:10 UTC, merged