Updated census household schema to match slides
ONSdigital/eq-survey-runner pull request #683
Opened 2016-12-09 17:19 UTC by jonnyshaw89

### What is the context of this PR?
Updating the census schemas to match the defined content in the slides

### How to review 
Check that content match slides

2016-12-09 18:03 UTC, iwootten requested changes

2016-12-09 18:03 UTC, iwootten commented on app/templates/partials/questions/repeatinganswer.html
> +  {%- if question.schema_item.guidance -%}
I don't think this is necessary...there's updates to display guidance in my summary branch.

2016-12-10 07:16 UTC, benjefferies commented on app/templates/partials/questions/repeatinganswer.html
> +  {%- if question.schema_item.guidance -%}
It will get sorted out in one of the merges anyway?

2016-12-10 12:51 UTC, jonnyshaw89 commented on app/templates/partials/questions/repeatinganswer.html
> +  {%- if question.schema_item.guidance -%}
resolved this conflict

2016-12-11 01:07 UTC, iwootten commented on app/templates/partials/questions/relationship.html
> +      {{question_title}}
Should we be piping the question title through safe as we do elsewhere to?

2016-12-11 18:50 UTC, collisdigital commented
@jonnyshaw89 I've pushed some changes up based on a review today. I had to add another routing rule that goes to `household-member-completed` block (which doesn't exist yet).

Most importantly I had to remove the group_id check from navigator.py to allow you to navigate to a block in another group (i.e. the confirmation screen or the start of the visitors section). @iwootten may want to comment on that. Discussing with @ajmaddaford we probably need a way to jump to a group_id which takes you to the first block in the group (thus avoiding the above change). He's going to look at that as part of the Navigation branch but probably merge that first then work on a refractor as part of Ian's location refactor work (which also relates to #693)

In short, I think careful planning tomorrow of what to do is needed!

2016-12-12 09:29 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                            "title": "Visitors",
@collisdigital have we changed our minds on having the visitors name?

2016-12-12 09:37 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                                "id": "household-member-completed"
where is this page coming from?

2016-12-12 10:39 UTC, iwootten requested changes

2016-12-12 10:39 UTC, iwootten commented on app/data/census_household.json
> +                                "id": "household-member-completed"
Yeah, don't see the point of adding a routing rule that is going to break, especially if we're modifying navigator in order to make it jump outside of a group.

2016-12-12 10:45 UTC, iwootten commented on app/questionnaire/navigator.py
> +            return next(index for (index, b) in enumerate(blocks) if
This seems dangerous to me. A lot of the repeat logic is based around being within the same group/instance. It's not clear what impact removing the group id check has. Seems like routing rules should be able to specify both group/block_id.

2016-12-12 11:50 UTC, benjefferies commented on app/data/census_household.json
>                              "id": "disability-section",
Should there be routing on this to skip to 27. Thinking of the last 12 months... if the person is under 16?

2016-12-12 12:31 UTC, iwootten commented
The formatting on this pages looks pretty bad:
![screen shot 2016-12-12 at 12 29 58](https://cloud.githubusercontent.com/assets/3598161/21099580/daad6990-c066-11e6-8b7f-cde64b743a02.png)

2016-12-12 12:38 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                                "id": "household-member-completed"
sorted

2016-12-12 12:48 UTC, jonnyshaw89 commented on app/data/census_household.json
>                              "id": "disability-section",
done

2016-12-12 12:54 UTC, iwootten commented
There's issues with this household page:

The section title and the question title is shown, where there isn't a section title in the schema.
The question content is different in the slides (should be 'Is there anyone else for whom this address is their permanent or family home?') to how it is asked in the schema, which will impact on the routing rules:

![screen shot 2016-12-12 at 12 50 46](https://cloud.githubusercontent.com/assets/3598161/21100068/e96f7100-c069-11e6-8d5a-cb1f0244126f.png)

2016-12-12 13:08 UTC, iwootten commented
There's an issue on the completed page, where the title in the slides is different to the schema
![screen shot 2016-12-12 at 13 06 33](https://cloud.githubusercontent.com/assets/3598161/21100462/1270149a-c06c-11e6-9c92-e92e16896844.png)
![screen shot 2016-12-12 at 13 06 41](https://cloud.githubusercontent.com/assets/3598161/21100467/15206b86-c06c-11e6-946b-a8aca0b19250.png)

2016-12-12 14:27 UTC, benjefferies commented on app/data/census_household.json
> +                            "title": "You have successfully completed the 'Who lives here?' section"
Wording in slides are `You have successfully completed this section`

2016-12-12 15:01 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                            "title": "You have successfully completed the 'Who lives here?' section"
It is, but this has changed since.

2016-12-12 15:28 UTC, benjefferies commented on app/data/census_household.json
>                                      "title": "What is your main language",
Missing question mark

2016-12-12 15:28 UTC, benjefferies commented on app/data/census_household.json
>                                      "title": "What is your main language",
Missing question mark

2016-12-12 15:30 UTC, benjefferies commented on app/data/census_household.json
> +                                            "id": "other-passports-answer",
Needs Passports held label

2016-12-12 15:32 UTC, benjefferies commented on app/data/census_household.json
>                                              "description": "Exclude any Court ordered activities"
Exclude should be in bold

2016-12-12 15:33 UTC, benjefferies commented on app/data/census_household.json
>                                          {
Should include be in bold too?

2016-12-12 15:37 UTC, benjefferies commented on app/data/census_household.json
> +                                                    "label": "Yes, usually lives in the United Kingdom",
These answers differ from the slides

2016-12-12 15:38 UTC, benjefferies commented on app/templates/confirmation.html
> +    <h1 class="header__title saturn">Confirmation</h1>		 +  <h1 class="header__title saturn">You’ve completed the 2017 Census Test</h1>
There looks to me some merging issues here

2016-12-12 16:05 UTC, jonnyshaw89 commented on app/data/census_household.json
> +                                            "id": "other-passports-answer",
Im not sure thats supported? wasn't that on the original list?

2016-12-12 16:44 UTC, collisdigital commented on app/templates/partials/questions/relationship.html
> +    {{question_guidance|safe}}
Note, @hamishtaplin is going to look at presenting this differently (added a card: https://trello.com/c/Oc4yln5z)

2016-12-12 17:53 UTC, iwootten approved these changes

2016-12-12 22:18 UTC, jonnyshaw89 commented on tests/functional/generate_pages.py
> +DROP_DOWN_SETTER = r"""  set{answerName}(value) {
I think these changes have been made in another branch by ben

2016-12-12 22:48 UTC, collisdigital commented on tests/functional/generate_pages.py
> +DROP_DOWN_SETTER = r"""  set{answerName}(value) {
Ah yes #660; this is enough to get this PR in, we can merge the two afterwards; Ben's also include the relationship question stuff

2016-12-12 22:49 UTC, collisdigital commented on tests/functional/generate_pages.py
> +DROP_DOWN_SETTER = r"""  set{answerName}(value) {
Andrew has had to make some similar changes too; the joys of parallel working 😀

2016-12-12 23:59 UTC, collisdigital commented on app/data/census_household.json
> +                                            "id": "other-passports-answer",
Done

2016-12-12 23:59 UTC, collisdigital commented on app/data/census_household.json
> +                            "title": "You have successfully completed the 'Who lives here?' section"
Matches latest slides

2016-12-13 00:00 UTC, collisdigital commented on app/data/census_household.json
> +                                "id": "household-member-completed"
Done

2016-12-13 08:30 UTC, ajmaddaford approved these changes

2016-12-13 08:41 UTC, benjefferies commented on tests/functional/generate_pages.py
> +HEADER = r"""// >>> WARNING THIS PAGE WAS AUTO-GENERATED ON {generated} - DO NOT EDIT!!! <<<
Should we be checking these files into the repository? They are compiled so fast it could be part of the build process

2016-12-13 08:58 UTC, merged