Routing on one of multiple selected checkbox answers
ONSdigital/eq-survey-runner pull request #687
Opened 2016-12-10 12:47 UTC by jonnyshaw89

### What is the context of this PR?
Added a contains condition to routing rules.
When a routing rule is specified on a checkbox, the routing rule checks if a value is one of the selected answers.

### How to review 
On the census-household questionnaire test the routing of the employment-type question

2016-12-10 13:22 UTC, collisdigital commented
Also needed on the which passport screen I think

2016-12-10 13:22 UTC, collisdigital commented
This also fixes some issues reported by yogi, can we add them to the description?

2016-12-10 13:23 UTC, collisdigital commented
https://github.com/ONSdigital/eq-survey-runner/issues/684

2016-12-10 13:50 UTC, jonnyshaw89 commented
@collisdigital i can't add this to the passports question as the question it routes to is added in here https://github.com/ONSdigital/eq-survey-runner/pull/683 so need this to go in then i can merge into the other branch

2016-12-10 15:34 UTC, yoganandkunche commented
@jonnyshaw89 Re-tested the issue #684 one scenarios seems to be not working. Lets discuss on Monday

2016-12-10 16:26 UTC, jonnyshaw89 commented
@yoganandkunche i have corrected the routing on the none of the above option

2016-12-10 16:26 UTC, yoganandkunche commented
@jonnyshaw89 As discussed selecting the 7 option along with any/all the 1-6 options must skip the next questions

2016-12-12 09:23 UTC, yoganandkunche commented
Not merged into master yet. So will be testing it in pre-prod tomorrow as I will be busy with e2e testing today

2016-12-13 10:38 UTC, iwootten requested changes

2016-12-13 10:38 UTC, iwootten commented on app/questionnaire/rules.py
> +    answer_to_test = str(answer_value) if 'equals' in condition else answer_value
'equals' in condition 
or

    condition == 'equals'?

2016-12-13 10:43 UTC, iwootten requested changes

2016-12-13 10:43 UTC, iwootten commented on app/questionnaire/rules.py
> +    answer_to_test = str(answer_value) if 'equals' in condition else answer_value
Ah is this converting everything with 'equals' in the title to a string? If so, then you probably should be explicit about it:

     if condition in ['equals', 'not equals']

2016-12-13 11:10 UTC, samiwel commented on app/questionnaire/rules.py
> +    answer_to_test = str(answer_value) if 'equals' in condition else answer_value
I agree with Ian's comment here. It's wasn't immediately obvious that you're matching `equals` and `not equals` conditions. Probably better to make that explicit.

2016-12-13 11:22 UTC, samiwel reviewed
Looks good to me.
Do any of the census schemas have `contains` routing where an input field is displayed upon selecting Other?  I didn't see any examples of that in this PR. Are these all the cases?

2016-12-13 11:32 UTC, samiwel approved these changes

2016-12-13 11:59 UTC, iwootten approved these changes

2016-12-13 15:25 UTC, merged