798 census individual schema final content update
ONSdigital/eq-survey-runner pull request #689
Opened 2016-12-10 15:05 UTC by benjefferies

### What is the context of this PR?
Review/Update individual schema
Half way review of individual schema. Managed to get up to What is your
ethnic group? line 910. Any questions or points I have made so far are
under the trello card
https://trello.com/c/PrZli0nM/798-census-individual-schema-final-content-update
Slides https://docs.google.com/presentation/d/1eD3btr06jWJA8bwo6lBoes2IQMkrgYY5_saUd4aALPs/edit#slide=id.g1763972a4f_1_377

### How to review
Open sides in one screen and individual survey in the other and check slides

2016-12-12 10:59 UTC, ajmaddaford requested changes

2016-12-12 10:59 UTC, ajmaddaford commented on app/data/census_household.json
> +                                    "title": "In your main job, What is (was) the name of the organisation or business you work (worked) for?",
Should this be 'what' rather that 'What'?

2016-12-12 10:59 UTC, ajmaddaford commented on app/templates/partials/questions/general.html
> +            </span>
There are `question_titles` and `question_guidance` jinja variables that we should use if possible

2016-12-12 11:07 UTC, iwootten commented
Is there any reason I'd be getting a confirmation screen with a list with a single item on it in this branch?

![screen shot 2016-12-12 at 11 05 49](https://cloud.githubusercontent.com/assets/3598161/21097147/143038c0-c05b-11e6-9ef7-1ead1eb335ad.png)

2016-12-12 11:12 UTC, collisdigital commented
@benjefferies Can you update the Date of Birth example to 1980 instead of 2014 - Discussed with Louise.

2016-12-12 11:18 UTC, iwootten submitted a review, later dismissed

2016-12-12 11:18 UTC, iwootten commented on app/templates/confirmation.html
> +    <ul>
Is this really meant to be here? Seems like the confirmation page is being updated in this PR: https://github.com/ONSdigital/eq-survey-runner/pull/688/files, and that's different to this?

2016-12-12 12:42 UTC, benjefferies commented on app/data/census_household.json
> +                                    "title": "In your main job, What is (was) the name of the organisation or business you work (worked) for?",
Done

2016-12-12 12:43 UTC, benjefferies commented on app/templates/partials/questions/general.html
> +            </span>
Pulled in from https://github.com/ONSdigital/eq-survey-runner/pull/683/files

2016-12-12 12:52 UTC, benjefferies commented
@collisdigital Changed the date of birth examples
@iwootten this has been fixed in https://github.com/ONSdigital/eq-survey-runner/pull/688/files

2016-12-12 12:58 UTC, samiwel requested changes

2016-12-12 12:58 UTC, samiwel commented on app/data/census_individual.json
> +                                                    "label": "Northern Iri1sh",
Typo?

2016-12-12 13:02 UTC, samiwel commented on app/data/census_individual.json
> +                                                    "value": "None"
See https://github.com/ONSdigital/eq-survey-runner/pull/691#issuecomment-266376207 I think these need to be swapped so Other is last.

2016-12-12 13:10 UTC, benjefferies commented on app/data/census_individual.json
> +                                                    "label": "Northern Iri1sh",
Done

2016-12-12 14:17 UTC, benjefferies commented on app/data/census_individual.json
> +                                                    "value": "None"
Spoken to @LJBabbage and this doesn't seem to be an issue

2016-12-12 14:19 UTC, samiwel commented on app/data/census_individual.json
> +                                                    "value": "None"
Okay, fair enough, just highlighting it may need to be tested to ensure it works correctly. 👍

2016-12-12 14:33 UTC, LJBabbage commented
Referencing Trello card
3. What is date of birth? Example of date done in census_household.json, rather than census_individual.json, probably should be both.
22a. Last year address, seeing 22
23. Other isn't type 'Other' so this doesn't need changing, additional this won't be a problem anyway

2016-12-12 14:37 UTC, samiwel commented on app/data/census_individual.json
> +                                            "description": "<strong>Exclude</strong> any Court ordered activities"
Court should be court

2016-12-12 14:40 UTC, samiwel commented on app/data/census_individual.json
> +                                            "description": "<strong>Include</strong> any paid work, including casual or temporary work, even if only for one hour"
From the google doc it looks like the whole thing should be bold. But there's inconsistency here across questions so, pinch of salt..

2016-12-12 14:50 UTC, samiwel commented on app/data/census_individual.json
> +                                    ],
The google doc does not have a label for the TextArea field.

2016-12-12 14:52 UTC, samiwel commented on app/data/census_individual.json
> +                                    "number": "37",
The google doc does not have a label for the TextArea answer.

2016-12-12 14:53 UTC, samiwel commented on app/data/census_individual.json
> +                                    ],
Google doc does not have a label for the TextArea answer.

2016-12-12 15:05 UTC, benjefferies commented
3. What is date of birth? Example of date done in census_household.json, rather than census_individual.json, probably should be both. - Fixed
22a. Last year address, seeing 22 - Fixed on census household branch
23. Other isn't type 'Other' so this doesn't need changing, additional this won't be a problem anyway Thanks for confirming

2016-12-12 15:09 UTC, benjefferies commented on app/data/census_individual.json
> +                                    "number": "37",
I think we agreed to keep this on the census household so I have sync'd with what that defines in the label is that correct @jonnyshaw89?

2016-12-12 15:09 UTC, benjefferies commented on app/data/census_individual.json
> +                                    ],
See other comment about label

2016-12-12 15:09 UTC, benjefferies commented on app/data/census_individual.json
> +                                            "description": "<strong>Exclude</strong> any Court ordered activities"
Done

2016-12-12 15:10 UTC, benjefferies commented on app/data/census_individual.json
> +                                            "description": "<strong>Include</strong> any paid work, including casual or temporary work, even if only for one hour"
Think it might be an error in the slide

2016-12-12 17:21 UTC, samiwel approved these changes

2016-12-12 22:39 UTC, ajmaddaford commented
Tested against latest slides. Found:
- Some guidance text gets cut off on the right hand side:
![screen shot 2016-12-12 at 21 43 57](https://cloud.githubusercontent.com/assets/1754822/21119672/8a5d6530-c0bb-11e6-88cb-df55412fcc5c.png)
- Question numbers aren't being output for all questions.
- Routing issue on question '23. What passports do you hold?' - If other selected with other options, 23a is not displayed. This needs #687 merged before it can work

2016-12-13 01:21 UTC, collisdigital commented
@ajmaddaford  Question numbers being output on questions with multiple answers is fixed in #683 see https://github.com/ONSdigital/eq-survey-runner/pull/683/files#diff-e80db9608eb2273765145ab36a20454eR23

2016-12-13 08:31 UTC, ajmaddaford approved these changes

2016-12-13 09:19 UTC, merged