Fixes #667 other value not retained throughout census survey.
ONSdigital/eq-survey-runner pull request #691
Opened 2016-12-11 10:40 UTC by samiwel

### What is the context of this PR?
Fixes #667 other value not retained throughout census survey.

Turns out there were two issues:

1. Case sensitive match for 'other'. In the census schemas the value to be matched is 'Other'. I changed this to perform a case insensitive match when checking to see if an other value was posted.

2. When restoring the Other value an assumption was being made that the other option in the radio had the label 'Other'. This has now been changed to get the label from the schema option.

### How to review 
Re-test the issue #667.
Observe that the text entered in the 'other' text field in radio options is retained.
All tests should pass.

2016-12-12 08:37 UTC, samiwel commented
I'm going to add a `not-ready-to-merge` label to this PR. Feel free to start reviewing because it should fix the raised defect. But there's a few additional scenarios I want to test, namely:

1. Other field for checkbox questions, and
2. When the Other option is not the last option.

Both of these scenarios are found in various census test questions. So if there's any additional fixes to be made in these areas, it makes sense to fix them under this PR.

2016-12-12 09:05 UTC, collisdigital commented
@samiwel we agreed with Census that 'Other' with please specify will always be the last option for the test as we don't support it anywhere else. What Q's is this on?

2016-12-12 09:13 UTC, samiwel commented
As I was going through the individual questionnaire yesterday, I noticed it. I made a note of it on the Trello card. So it may just be a case of swapping the options around in the schema then.

2016-12-12 09:52 UTC, LJBabbage commented
There is code in checkbox_answer.py which already has the capacity to find the right 'other' value, regardless of each position, however as @collisdigital mentioned above it was decided to also put it last meaning it descoped itself

2016-12-12 14:09 UTC, samiwel commented
I tested checkboxes with other fields in the individual census schema on this branch and it seemed to behave correctly. Removing the `not-ready-to-merge` label.

2016-12-12 15:11 UTC, LJBabbage requested changes

2016-12-12 15:11 UTC, LJBabbage commented on app/questionnaire_state/state_answer.py
> +    def restore_other_value(self, user_input):
Why has this been changed to public?

2016-12-12 15:11 UTC, LJBabbage commented on app/schema/widgets/multiple_choice_widget.py
> +            for answer in filter(None, [value.strip() for value in posted_data]):
Not a fan of this double for loop filter to just get rid of spaces, prefer the other way

2016-12-12 15:14 UTC, LJBabbage requested changes

2016-12-12 15:14 UTC, LJBabbage commented on app/schema/widgets/multiple_choice_widget.py
> +        if posted_data and 'other' in (value.lower() for value in posted_data):
Doesn't quite seem right to make everything lower case to just check the other value isn't Other

2016-12-12 15:16 UTC, samiwel commented on app/schema/widgets/multiple_choice_widget.py
> +        if posted_data and 'other' in (value.lower() for value in posted_data):
Is there a better way to perform a case insensitive match?

2016-12-12 15:18 UTC, samiwel commented on app/questionnaire_state/state_answer.py
> +    def restore_other_value(self, user_input):
It was changed so that I could unit test its behaviour, but you're right, it doesn't need to be public. I'll revert this change.

2016-12-12 16:20 UTC, samiwel commented on app/schema/widgets/multiple_choice_widget.py
> +            for answer in filter(None, [value.strip() for value in posted_data]):
The other way doesn't get rid of the spaces. Maybe that's valid, but even if not it should arguably be done in `get_other_value` in the widget instead. I'll put this back the way it was for now.

2016-12-13 11:00 UTC, jonnyshaw89 commented
@samiwel The only issue i can find with this is that if you enter a value in the text box which is the same as one of the options to click then the value is not retained? Im not sure how that sits in terms of requirements though?

2016-12-13 14:42 UTC, samiwel commented
@jonnyshaw89 Thanks for letting me know about that. Should be fixed by my latest commit.

2016-12-13 14:56 UTC, jonnyshaw89 requested changes

2016-12-13 14:56 UTC, jonnyshaw89 commented on app/questionnaire_state/state_answer.py
> +                elif self.input == other_option['value'] and hasattr(user_input, 'getlist'):
is the hasattr checking if its a MultiDict?

2016-12-13 15:04 UTC, jonnyshaw89 commented
@samiwel Just re-tested. it now selects the value i typed, which i guess is acceptable behaviour

2016-12-13 15:07 UTC, samiwel commented on app/questionnaire_state/state_answer.py
> +                elif self.input == other_option['value'] and hasattr(user_input, 'getlist'):
Yeah, unfortunately the logic gets called on GET and POST. When POST-ing an `ImmutableMultiDict` gets passed in. This whole `other` solution needs to be re-visited, I feel.
At the moment we're sort of storing an answer inside an answer and that causes quite a lot of unnecessary complexity - perhaps we can change this when we bring in the WTF-Forms solution.

2016-12-13 15:13 UTC, jonnyshaw89 approved these changes

2016-12-13 15:30 UTC, LJBabbage approved these changes

2016-12-13 15:31 UTC, jonnyshaw89 commented
👍 @samiwel rebase and squash?

2016-12-13 16:15 UTC, merged

2016-12-14 13:45 UTC, yoganandkunche commented
Defect passed re-test. This defect is tested across all the census schemas and works as expected.