Fixes #686 Previous Link on the first question gives error.
ONSdigital/eq-survey-runner pull request #694
Opened 2016-12-11 12:35 UTC by samiwel

### What is the context of this PR?
Fixes #686 by not displaying the Previous link if it's the first block in the survey.

### How to review 
Observe that the Previous link is not displayed on the first block of any survey.
All existing tests should pass.

2016-12-11 12:37 UTC, collisdigital commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
why the `state.group_instance > 0` ?

2016-12-11 12:38 UTC, samiwel commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
For repeating groups the block will still be the first in the schema so we need this check to allow going backwards in repeating groups.

2016-12-11 12:48 UTC, collisdigital commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
Except the navigation PR hides the previous link for the first block in a group; so I guess this will conflict (or merge out) when that lands?

2016-12-11 13:47 UTC, samiwel commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
There may be some overlap here, not sure I'll need to check with Lewis/Hamish tomorrow.
If the navigation PR fixes this defect already then it should reference the issue.

2016-12-11 14:13 UTC, collisdigital commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
Doh! Suspect that is the case...

2016-12-11 23:42 UTC, iwootten requested changes

2016-12-11 23:42 UTC, iwootten commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
I don't think adding this sort of logic to the schemas is the way to go for resolving this issue. The previous location is calculated before rendering the template and presumably should be none for the first pages on census schemas, so isn't it easier just to check it isn't None?

2016-12-12 09:06 UTC, samiwel commented on app/templates/questionnaire.html
> +      {% if state.group_instance > 0 or not block.first_in_schema() %}
Hi Ian, I think this defect is already fixed by PR #628 so there's probably no need to make this change after all.

2016-12-12 09:47 UTC, LJBabbage commented
Hold fire on this one, the navigation branch will indeed fix this. Its done in the backend so there is no logic in the front end

2016-12-12 10:33 UTC, iwootten commented
Closing this given seems like nav is going to fix original issue #686.

2016-12-12 10:33 UTC, closed without merging