Fix repeating group bug for census
ONSdigital/eq-survey-runner pull request #735
Opened 2016-12-15 11:19 UTC by benjefferies

### What is the context of this PR?

Repeating answers will repeat if the answer which determines the repeat
was originally answered but if the user then changes their mind to go
down a path where the answer which determines the repeat will no longer
appear on. The expected result is for those repeating answers to not be
repeated.

The scenario this occurs under is:
Given I have added a person in my household, When I change my mind and
they should be visitors, Then I do not have to answer household member
details

The short term fix for this is to remove the answer which determines the
repeat when the user goes down the other path which is consistent with
what we do when a user changes their answer which determines the number
of repeats.

The ideal fix going forward would be to check if the answer which
determines the repeating answers is on the path that the user is being
followed.

[trello](https://trello.com/c/vnjf9dR9/813-eq-survey-runner-727-when-clicking-previous-after-adding-household-members-the-reporting-groups-still-repeat-issue)
[trello for the real fix](https://trello.com/c/QXkI2J6i/298-repeating-groups-should-only-be-evaluated-if-the-answer-which-determines-the-repeating-groups-in-on-the-path)

### How to review 
All selenium tests should still pass and also the BDD test `Given I have added a person in my household, When I change my mind they should be visitors, Then I do not have to answer household details`

2016-12-15 11:30 UTC, jonnyshaw89 requested changes

2016-12-15 11:30 UTC, jonnyshaw89 commented on app/main/views/questionnaire.py
> +    _remove_repeating_on_household_answers(get_answer_store(current_user), group_id)
Do we only want to do this if the answer is no?
If i navigate backwards and then forwards without changing the answer then the values are deleted.

2016-12-15 11:32 UTC, benjefferies commented on app/main/views/questionnaire.py
> +    _remove_repeating_on_household_answers(get_answer_store(current_user), group_id)
Good point

2016-12-15 12:18 UTC, jonnyshaw89 commented on app/main/views/questionnaire.py
> +        get_questionnaire_manager(g.schema, g.schema_json).update_questionnaire_store(this_block)
why this?

2016-12-15 12:52 UTC, jonnyshaw89 approved these changes

2016-12-15 13:49 UTC, jonnyshaw89 commented
@benjefferies the flaw with selenium tests is that they don't count towards coverage

2016-12-15 14:23 UTC, samiwel commented
But integration tests do ;)

2016-12-16 09:22 UTC, ajmaddaford approved these changes

2016-12-16 09:27 UTC, benjefferies commented
Ready for merge once builds pass

2016-12-16 10:25 UTC, merged