eq-709, eq-737 quesrtion/answer guidance
ONSdigital/eq-survey-runner pull request #739
Opened 2016-12-15 15:15 UTC by hamishtaplin

### What is the context of this PR?

Fixes #709 

- moved answer guidance into it's own `answer-guidance` template
- refactored to use more sensible method of mapping large amounts of attributes on the elements via `xmlattr` filter
- decoupled it from the schema_item
- wired the question guidance for household question into this template

Fixes #747

- wired the guidance for repeatinganswer into `answer-guidance` template
- moved outside answers

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2016-12-15 15:26 UTC, collisdigital commented on app/templates/partials/questions/repeatinganswer.html
> +      'id': composite_answers[0][2].schema_item.id,
Raise a tech debt card about this, we're explicitly dependent on their being 3 fields (last-name) now.

2016-12-16 11:09 UTC, ajmaddaford commented
I've just run this and don't get a 'Show further guidance' link after the Add Person button

2016-12-16 11:10 UTC, ajmaddaford commented
Show further guidance for the relationships does collapse now, but is displayed after all of the answers, I assume that is correct?

2016-12-16 12:39 UTC, ajmaddaford commented on app/templates/partials/questions/repeatinganswer.html
> +      'id': composite_answers[0][2].schema_item.id,
Can we just use `composite_answers[0][-1].schema_item.id`?

2016-12-16 13:37 UTC, hamishtaplin commented
@ajmaddaford RE point #1: which schema did you test with?

point #2: yes that is correct, guidance appears once, at the bottom of the question

2016-12-16 13:39 UTC, ajmaddaford commented
Census household

2016-12-19 14:26 UTC, ajmaddaford approved these changes

2016-12-19 15:03 UTC, iwootten approved these changes

2016-12-19 15:43 UTC, benjefferies requested changes

2016-12-19 15:43 UTC, benjefferies commented on app/templates/partials/questions/repeatinganswer.html
> +            {% with render_guidance = False %}
Do we actually need this boolean flag as it's not reassigned and it's only used in one place?

2016-12-19 16:53 UTC, benjefferies approved these changes

2016-12-19 16:59 UTC, ajmaddaford commented on app/templates/partials/questions/repeatinganswer.html
> +            {% with render_guidance = False %}
The flag is used to not display the guidance in the shared answer template for repeating answers. I think this is good enough to go in as we need to review all of the template handling.

2016-12-19 17:22 UTC, merged

2016-12-20 12:25 UTC, yoganandkunche commented
Defects passed retest following deployment on 20th Dec 2016