Eq 699 bleaching answer store
ONSdigital/eq-survey-runner pull request #742
Opened 2016-12-15 15:46 UTC by jonnyshaw89

### What is the context of this PR?
Move the bleaching of input to when the value is entered into the AnswerStore. This should then catch all input.

Fixes https://github.com/ONSdigital/eq-survey-runner/issues/699

2016-12-15 16:08 UTC, collisdigital commented on app/data_model/answer_store.py
> +            for index, answer_from_list in enumerate(answer.value):
why enumerate? can't you just `answer_from_list in answer.value` ?

2016-12-15 16:10 UTC, samiwel commented
I've just noticed that when entering `<person name>` into the household composition entry screen that when the answer gets piped into the group title it displays the encoded values `&lt;person name&gt;`. Do you think we should be marking group titles as `safe` or should the unescaping happen in the household member name filter?

The behaviour for entering `person<name` is the same as before, but maybe that is correct/expected and bleach is just doing its thing.

2016-12-15 16:12 UTC, jonnyshaw89 commented on app/data_model/answer_store.py
> +            for index, answer_from_list in enumerate(answer.value):
Ah yes i can change to this now. I had a different approach originally.

2016-12-15 16:14 UTC, benjefferies requested changes

2016-12-15 16:14 UTC, benjefferies commented on tests/app/data_model/test_answer_store.py
> +        self.assertFalse('<' in self.store.get(answer_1))
self.assertNotIn would give a better failure message

2016-12-15 16:14 UTC, benjefferies commented on tests/app/data_model/test_answer_store.py
> +    def test_answer_store_bleaches_answers(self):
We should probably have a unit test for bleaching list and ints

2016-12-15 17:26 UTC, iwootten requested changes

2016-12-15 17:26 UTC, iwootten commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
Isn't the fix here not to remove the current bleaching, but to validate all input before storing it? Moving the bleaching to retrieval seems like the wrong way to go, couldn't we have executed something malicious on storing it?

2016-12-16 08:03 UTC, benjefferies commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
Good point it does make sense to sanitise on entering the survey runner

2016-12-16 08:09 UTC, collisdigital commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
Really it should be bleached immediately after being received from the POST before anything else happens; you don't know what effect dirty data can have on any of the system, even validation code etc.

2016-12-16 09:51 UTC, samiwel commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
I think the values are being bleached when they get validated on POST. That's the reason we observe text being cut off in household composition member names if you leave a half open tag in there e.g. 'Pers<on Name' only 'Pers' gets stored.

2016-12-16 09:59 UTC, collisdigital commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
In reality we should probably show an error to the user if they put a `<` in their name (like non-numeric input in numeric fields). I'm thinking WTForms stuff (regex acceptance list for text input?)

2016-12-16 10:14 UTC, ajmaddaford commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
That might be ok for people's names, but if we ever have inputs for something like a company name blocking '<' or '>' probably isn't what we want to do e.g. MORE TH>N.

2016-12-16 11:55 UTC, benjefferies commented on app/schema/answer.py
> -        user_input = bleach.clean(raw_input)
It's interesting that bleach actually removes parts of the answer instead of encoding

2016-12-20 09:11 UTC, jonnyshaw89 commented
We probably need to do a more in depth review of how we handle data within the application. what is allowed ini and what isn't.

2016-12-20 09:11 UTC, closed without merging