Split routing tests
ONSdigital/eq-survey-runner pull request #744
Opened 2016-12-16 09:20 UTC by benjefferies

### What is the context of this PR?
When a test fails it takes a long time to run all of the routing rules
to see what has broken. It is also more difficult to maintain. It will
only get larger and more unmaintainable if we don't split them out

### How to review 
Check that no selenium tests have gone missing in the refactor
All selenium tests should still pass

2016-12-16 09:21 UTC, benjefferies commented on tests/functional/spec/census/routing/private-response.spec.js
> +    function completeHouseholdAndAccommodation() {
I will refactor these to be importable modules

2016-12-16 10:20 UTC, jonnyshaw89 requested changes

2016-12-16 10:20 UTC, jonnyshaw89 commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
If a unit test fails then the other builds will run all of the functional tests? surely this breaks the fail fast rule?

2016-12-16 10:23 UTC, benjefferies commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
I guess you still get the fail fast indication from the other build, the disadvantage is that you don't free up your travis resource I guess. I am just playing at the moment to see how much time it saves us to see if the cost is worth the benefit

2016-12-16 10:34 UTC, benjefferies commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
The results are:

Running all tests on both matrix:
https://travis-ci.org/ONSdigital/eq-survey-runner/builds/184486318
https://travis-ci.org/ONSdigital/eq-survey-runner/builds/184489761

Running all tests on core:
https://travis-ci.org/ONSdigital/eq-survey-runner/builds/184491190

2016-12-16 10:56 UTC, benjefferies commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
We could fail the census branch if the core branch fails to free up resources, that said we can't do that until travis get their act together - https://github.com/travis-ci/travis-ci/issues/2062

2016-12-16 11:11 UTC, jonnyshaw89 commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
i can't see much difference in the build times.

2016-12-16 11:15 UTC, benjefferies commented on scripts/run_tests.sh
> +if [ "$EQ_FUNCTIONAL_TEST_SUITES" = "core" ]; then
I've updated my comment above to include the times

2016-12-16 13:09 UTC, ajmaddaford commented
I think splitting out the routing tests and changing the behaviour of run_tests.sh should be two different pull requests. Splitting the routing tests could go in now, whereas changing the behaviour of the script will involve more discussion.

2016-12-16 13:35 UTC, benjefferies commented
Removed run_tests change. Note that the build time will increase as a consequence of these changes

2016-12-16 13:47 UTC, jonnyshaw89 approved these changes

2016-12-16 17:38 UTC, iwootten commented on tests/functional/spec/census/routing/who-lives-here.spec.js
> +    completeHouseholdDetails()
Is this meant to be filled in twice?

2016-12-16 18:48 UTC, benjefferies commented on tests/functional/spec/census/routing/who-lives-here.spec.js
> +    completeHouseholdDetails()
It's other one of those implicit checks I can change it while I'm the area

2016-12-17 06:20 UTC, benjefferies commented on tests/functional/spec/census/routing/carer.spec.js
> +    TypeOfAccommodation.clickTypeOfAccommodationAnswerWholeHouseOrBungalow().submit()
I think it will be useful to use the helper methods in the complete-sections.js. I won't do it in this PR as it will muddy the water

2016-12-18 12:22 UTC, ajmaddaford approved these changes

2016-12-18 12:45 UTC, merged