Adding skip_conditions for groups
ONSdigital/eq-survey-runner pull request #753
Opened 2016-12-16 13:31 UTC by benjefferies

### What is the context of this PR?
We need to be able to skip the visitors completed interstitial page in
the census household questionnaire. It lives in a separate group to the
visitor questions therefore it won't be skipped by the repeat rule.

This change implements skip_condition on a group to solve that.

Fixes #740 and Fixes
https://trello.com/c/wGkp3T52/291-remove-need-to-update-state-in-navigator

### How to review

2016-12-16 13:51 UTC, jonnyshaw89 requested changes

2016-12-16 13:51 UTC, jonnyshaw89 commented on app/data/test_skip_condition_group.json
> +            "skip_condition": {
do you need to add this to schema-v1.json?

2016-12-16 13:51 UTC, jonnyshaw89 commented on app/questionnaire/navigator.py
> +            if 'skip_condition' in group:
if we are putting this on groups maybe we want to support blocks too? would have made some of the census routing rule a bit simpler?

2016-12-16 13:52 UTC, benjefferies commented on app/data/test_skip_condition_group.json
> +            "skip_condition": {
Yep, still a bit WIP but wanted to get some views on how we are implementing this

2016-12-16 13:54 UTC, benjefferies commented on app/questionnaire/navigator.py
> +            if 'skip_condition' in group:
Might make sense one day but let's do it in a feature driven manor then just add it now. Looks at the S3 bucket stuff, isn't used.

2016-12-16 14:13 UTC, collisdigital commented on app/data/test_skip_condition_group.json
> +      "INTEGER_TOO_LARGE": "Number is too large",
Do we actually support these at the top-level like this, would have saved copy/pasting them against each answer in the Census schema!

2016-12-16 14:14 UTC, collisdigital commented on app/questionnaire/rules.py
> +def evaluate_skip_condition(skip_condition, answer_store):
Pretty sure there is already at least one if not more of these identical blocks of code about parsing/evaluating when rules, can it be consolidated?

2016-12-16 14:16 UTC, benjefferies commented on app/questionnaire/rules.py
> +def evaluate_skip_condition(skip_condition, answer_store):
There are 3, it should be possible to consolidate. I started doing it initially and it was a bit of a can of worms so planned on coming back to it later so thanks for the reminder 👍

2016-12-17 11:39 UTC, benjefferies commented on app/data/test_skip_condition_group.json
> +      "INTEGER_TOO_LARGE": "Number is too large",
Will take a look to see if we can remove, we need to spend some time making sure the schema is correct and introduce validation so we wouldn't have to cross reference against the code

2016-12-17 12:03 UTC, benjefferies commented on app/data/test_skip_condition_group.json
> +      "INTEGER_TOO_LARGE": "Number is too large",
Done

2016-12-17 12:03 UTC, benjefferies commented on app/data/test_skip_condition_group.json
> +            "skip_condition": {
Done

2016-12-19 09:54 UTC, iwootten commented on app/questionnaire/rules.py
> +def evaluate_skip_condition(skip_condition, answer_store):
I think this method name should be more generic. Perhaps something like evaluate_when_list, given it doesn't just apply to skip_conditions, it's equally applicable to the when attribute of any rule.

2016-12-19 10:55 UTC, benjefferies commented on app/questionnaire/rules.py
> +def evaluate_skip_condition(skip_condition, answer_store):
Done

2016-12-19 15:27 UTC, jonnyshaw89 requested changes

2016-12-19 15:27 UTC, jonnyshaw89 commented on app/data/schema/schema-v1.json
>                              "skip_condition": {
is this correct? arn't skip conditions on sections?

2016-12-19 15:27 UTC, jonnyshaw89 commented on tests/functional/pages/surveys/skip_condition_group/do-you-want-to-skip.page.js
> +// >>> WARNING THIS PAGE WAS AUTO-GENERATED ON 2016-12-19 12:17:40.003901 - DO NOT EDIT!!! <<<
these still have timestamps, you can regenerate without

2016-12-19 15:47 UTC, benjefferies commented on app/data/schema/schema-v1.json
>                              "skip_condition": {
Who knows they appear on both in the state items!

2016-12-19 15:48 UTC, benjefferies commented on app/data/schema/schema-v1.json
>                              "skip_condition": {
Looks to be on questions

2016-12-19 16:16 UTC, jonnyshaw89 approved these changes

2016-12-19 16:32 UTC, iwootten requested changes

2016-12-19 16:32 UTC, iwootten commented on app/questionnaire/rules.py
> +                return evaluate_rule(when_rule, filtered[0]['value'])
Can't you just return False, given this is part of the if?

2016-12-19 16:39 UTC, iwootten commented on app/questionnaire/rules.py
> +                return evaluate_rule(when_rule, filtered[0]['value'])
In fact, think that's what it originally did right?

2016-12-19 16:44 UTC, benjefferies commented on app/questionnaire/rules.py
> +                return evaluate_rule(when_rule, filtered[0]['value'])
Fixed and rebase to speed up process of merging

2016-12-19 16:58 UTC, iwootten approved these changes

2016-12-19 16:58 UTC, merged