Fixing regression in census routing rules
ONSdigital/eq-survey-runner pull request #754
Opened 2016-12-16 13:39 UTC by jonnyshaw89

### What is the context of this PR?
Fixes https://github.com/ONSdigital/eq-survey-runner/issues/750
Also added tests to check routing rule

2016-12-16 14:09 UTC, ajmaddaford requested changes

2016-12-16 14:09 UTC, ajmaddaford commented on tests/functional/spec/census/issues/routing-last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I select multiple answers excluding none of the above, Then I am routed to 29. Were you actively looking for...?', function () {
Should this say '..Then I am routed to 35. In your main job, are (were) you?'

2016-12-16 14:12 UTC, ajmaddaford commented
@yoganandkunche I thought the original intent was that 'None of the above' overrode the other options, so that if it was ticked, regardless of the other options, we shouldn't skip the 5 questions.

2016-12-16 14:17 UTC, collisdigital commented
Please double check against the slides... I'll do the same

2016-12-16 14:18 UTC, collisdigital commented
```
Routing:
- if any of options 1-6 are selected next 5 questions are skipped irrespective of whether option 7 is selected.No options selected continue to next question. 
``

2016-12-16 14:34 UTC, collisdigital commented
Therefore:
- If option 1-6 selected goto Question 35 (skips 5 blocks)
- If option 7 (none of the above) OR no option selected: goto Question 29 (next block)

2016-12-16 14:35 UTC, jonnyshaw89 commented
@collisdigital what about if options 1,2 and 7 are selected?

2016-12-16 14:37 UTC, collisdigital commented
Updated my comment above ^^

2016-12-16 15:33 UTC, jonnyshaw89 commented
The tests in this PR match the scenario @collisdigital has illustrated.

2016-12-18 12:34 UTC, ajmaddaford requested changes
I think there should also be a test for what should happen when none of the above only is selected. 
Also, can we add this to the routing tests rather than the issues?

2016-12-18 12:34 UTC, ajmaddaford commented on tests/functional/spec/census/issues/routing-last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I select multiple answers excluding none of the above, Then I am routed to 35. In your main job, are (were) you?', function () {
This test description doesn't match up to the test - it doesn't check that you are routed to question 35, it checks that you are not routed to question 29.

2016-12-18 12:34 UTC, ajmaddaford commented on tests/functional/spec/census/issues/routing-last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I select multiple answers including none of the above, Then I am routed to 29. Were you actively looking for...?', function () {
I think the description is wrong, the test checks that you are _not_ routed to question 29.

2016-12-19 10:41 UTC, ajmaddaford approved these changes

2016-12-19 10:59 UTC, samiwel approved these changes
Looks okay. Just a general comment (not specifically to do with this PR) I'm finding it increasingly difficult to spot the "When" action in the Census selenium tests.

In future can we maybe add a comments such as
`// Given`, `// When`, `// Then` in the spec files just to make it a bit more obvious what's being tested?

2016-12-19 10:59 UTC, samiwel commented on tests/functional/spec/census/routing/last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I dont not select any response, Then I am routed to 29. Were you actively looking for...?', function () {
dont not

2016-12-19 11:12 UTC, ajmaddaford commented on tests/functional/spec/census/routing/last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I dont not select any response, Then I am routed to 29. Were you actively looking for...?', function () {
Also just spotted the weird spacing

2016-12-19 11:26 UTC, jonnyshaw89 commented on tests/functional/spec/census/routing/last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I dont not select any response, Then I am routed to 29. Were you actively looking for...?', function () {
This spacing doesn't appear in my IDE

2016-12-19 11:26 UTC, samiwel commented on tests/functional/spec/census/routing/last-week-were-you.spec.js
> +  it('Given I am answering question 28.	Last week were you.., When I dont not select any response, Then I am routed to 29. Were you actively looking for...?', function () {
I spotted that, but at least it was consistent across all tests.

2016-12-19 12:00 UTC, merged

2016-12-20 11:09 UTC, yoganandkunche commented
Defect passed retest following deployment on 20th Dec 2016