Fixes #749 answers retaining values after changing household.
ONSdigital/eq-survey-runner pull request #756
Opened 2016-12-16 14:41 UTC by samiwel

### What is the context of this PR?
Fixes #749.

### How to review 
Retest the defect. Going back after entering household members and adding an additional member should clear the next block's answer.

2016-12-16 15:25 UTC, benjefferies requested changes
We should have an integration tests to confirm it works - something like https://github.com/ONSdigital/eq-survey-runner/blob/master/tests/integration/questionnaire/test_questionnaire_remove_repeat_answers.py

2016-12-16 15:25 UTC, benjefferies commented on app/helpers/schema_helper.py
> +    def get_blocks_that_route_back_to_block(cls, completed_blocks, survey_json, block_id):
We should have test coverage of this

2016-12-16 15:25 UTC, benjefferies commented on app/helpers/schema_helper.py
> +    def get_answers_that_route_back_to_block(cls, blocks_that_route_back, survey_json):
We should have test coverage of this

2016-12-16 15:25 UTC, benjefferies commented on app/helpers/schema_helper.py
> +                for question in (q for q in section['questions'] if section['questions']):
Should we refactor get_questions() out now we do it in a couple of places

2016-12-16 15:26 UTC, samiwel commented on app/helpers/schema_helper.py
> +    def get_blocks_that_route_back_to_block(cls, completed_blocks, survey_json, block_id):
Yep, still in progress 👍

2016-12-16 15:27 UTC, benjefferies commented on app/helpers/schema_helper.py
> +    def get_blocks_that_route_back_to_block(cls, completed_blocks, survey_json, block_id):
Sorry missed the label

2016-12-16 15:31 UTC, samiwel commented on app/helpers/schema_helper.py
> +    def get_blocks_that_route_back_to_block(cls, completed_blocks, survey_json, block_id):
No worries, good to know about those integration tests anyway.

2016-12-19 16:09 UTC, samiwel commented
@ajmaddaford Could use another pair of eyes to understand why my integration test is not behaving as expected. I noticed different behaviour running the test versus running the application in the Navigator when building the path. I think it's because the answer store in my integration test is being mocked therefore has no real answers to determine the repeats. Yet, the block I'm expecting to find in the list, so not sure if there's a problem in the logic of `Navigator::build_path()` or not.

2016-12-20 12:14 UTC, samiwel commented
Closing this PR since the defect is resolved by another PR (#775)

2016-12-20 12:14 UTC, closed without merging