Add welsh census household survey json
ONSdigital/eq-survey-runner pull request #761
Opened 2016-12-17 13:36 UTC by ajmaddaford

### What is the context of this PR?
Adds a Welsh version of the Census Household survey JSON

### How to review 
- Select census_household.json from Schemas list and 'cy' from Language drop down on the dev page. 
- Verify translated version of Census is loaded and all screens have survey JSON text translated

2016-12-17 13:45 UTC, collisdigital commented
Thinking we might need Sam to review this one!

2016-12-17 13:45 UTC, collisdigital commented
Why aren't the commit messages in Welsh!

2016-12-17 13:47 UTC, collisdigital commented
Is there an argument for keeping the 'value' English along with the routing rules, just a risk that translating these causes a break (strings don't match?) unless it's easily verified.

2016-12-17 15:54 UTC, ajmaddaford commented
@chriscollis yeah, those value changes will break routing that is dependent on the value. The translation script does a simple search and replacement of strings, so we'll need to tweak it to get it to not translate the values.

2016-12-17 18:22 UTC, hamishtaplin commented on app/data/census_household_cy.json
> +                                            "guidance": "<p>Enter the current first, middle and last names of all the people who usually live here.</p><p>If you have not yet named your newborn, pleas
Why is this only half in Welsh?

2016-12-17 18:23 UTC, hamishtaplin commented on app/data/census_household_cy.json
> +                            "title": "You have successfully completed the ‘Pwy sy’n byw yma?’ section"
More English here

2016-12-18 11:43 UTC, ajmaddaford commented on app/data/census_household_cy.json
> +                                            "guidance": "<p>Enter the current first, middle and last names of all the people who usually live here.</p><p>If you have not yet named your newborn, pleas
There was an issue with the translation script after I made some changes to work from the spreadsheet rather than the text file. Fixed now.

2016-12-18 11:44 UTC, ajmaddaford commented on app/data/census_household_cy.json
> +                            "title": "You have successfully completed the ‘Pwy sy’n byw yma?’ section"
Same as above. Fixed now.

2016-12-18 17:41 UTC, samiwel commented on app/data/census_household_cy.json
> +                    "title": "Who lives here?",
Should the block title's not be updated to be the same as the sections? Granted, they are not displayed.

2016-12-18 17:41 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Include -> "Dylech gynnwys"

2016-12-18 17:48 UTC, samiwel requested changes

2016-12-18 17:48 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Include -> "Dylech gynnwys"

2016-12-18 17:49 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
GitHub is showing this on the wrong line, it's actually on line 3557

2016-12-19 10:44 UTC, ajmaddaford commented on app/data/census_household_cy.json
> +                    "title": "Who lives here?",
We don't have translations for a lot of the block titles (we only have translations where the block title is the same as another string somewhere else), so I thought it was better to be consistent and not translate any of them.

2016-12-19 10:50 UTC, ajmaddaford commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Good spot! Done.

2016-12-19 13:13 UTC, samiwel requested changes

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                                                    "label": "Ydw",
Should be "Oes"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                                                    "label": "Nac ydw",
Should be "Nac oes"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                                                    "label": "Nac ydw",
Should be "Nac ydy"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                                                    "label": "Ydw",
Could be "Do"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Line 3575: Should be "Nac Oes"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Line 4019: Should be "Oeddwn"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Line 4023: Should be "Nac oeddwn"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Line 4091: Should be "Oeddwn"

2016-12-19 13:13 UTC, samiwel commented on app/data/cy/census_household.json
> +                            "title": "{{[answers.first_name[group_instance], answers.la
Line 4095: Should be "Nac oeddwn"

2016-12-19 13:53 UTC, samiwel requested changes

2016-12-19 13:53 UTC, samiwel commented on app/data/cy/census_individual.json
> +                                                    "label": "Do",
Should be "Ydw"

2016-12-19 13:54 UTC, samiwel commented
In general, the same translation issues spotted for household schema above also appear in the corresponding individual question. I've not marked them all.

2016-12-19 13:55 UTC, collisdigital commented
Are these problems with the actual translations provided or the way we've integrated them? It may be better to merge this in so we can run more testing (and so can the translations team) and then raise any content issues so we can prioritise them.

2016-12-19 14:08 UTC, samiwel approved these changes

2016-12-19 14:48 UTC, jonnyshaw89 requested changes

2016-12-19 14:48 UTC, jonnyshaw89 commented on app/data/cy/census_household.json
> +                                                    "description": "Er enghraifft ail gyfeiriad neu dŷ gwyliau yw hwn"
This text does not display correctly in out current font.

2016-12-19 15:02 UTC, ajmaddaford commented on app/data/cy/census_household.json
> +                                                    "description": "Er enghraifft ail gyfeiriad neu dŷ gwyliau yw hwn"
The text is correct in the JSON, so it looks lie an issue with the font we're using. As the text is correct in the JSON I think we should get this pull request merged. I've created an issue to track this https://github.com/ONSdigital/eq-survey-runner/issues/769.

2016-12-19 15:05 UTC, samiwel commented on app/data/cy/census_household.json
> +                                                    "description": "Er enghraifft ail gyfeiriad neu dŷ gwyliau yw hwn"
Same with other accented characters elsewhere in the schema. 
![image](https://cloud.githubusercontent.com/assets/4097796/21317348/a0df9fc6-c5fc-11e6-9e52-51a53143900a.png)

2016-12-19 15:06 UTC, jonnyshaw89 approved these changes

2016-12-19 15:47 UTC, merged