Added welsh font characters
ONSdigital/eq-survey-runner pull request #801
Opened 2016-12-21 15:02 UTC by bennpearson

### What is the context of this PR?
Fixes #769 

### How to review 
Check fonts are compiled and loaded on in the survey

2016-12-21 15:22 UTC, hamishtaplin requested changes

2016-12-21 15:22 UTC, hamishtaplin commented on gulpfile.babel.js
> +  'build:fonts'
Add this to watch task too

2016-12-21 15:40 UTC, hamishtaplin approved these changes

2016-12-21 17:03 UTC, alexmorris commented
LGTM

2016-12-21 17:43 UTC, ajmaddaford requested changes
I just tried this and there is a noticeable delay between the screen being rendered and the text being rendered.

2016-12-21 20:27 UTC, hamishtaplin commented
@ajmaddaford There's not a great deal we can do about that for now, it's fairly standard and only occurs once.

2016-12-21 21:27 UTC, ajmaddaford commented
@hamishtaplin I was getting the delay on every page

2017-01-02 11:37 UTC, alexmorris commented
@ajmaddaford we need to look into how we have caching set up (or not as the case may be?) for static assets like these.

2017-01-06 11:58 UTC, ajmaddaford commented
I've raised a PR on the ONS assets CDN repo to add the Lato font - https://github.com/ONSdigital/cdn.ons.gov.uk-assets/pull/3

2017-01-06 12:27 UTC, ajmaddaford commented
The font has been added to the CDN, but cache headers aren't being set (it just uses Etags). A story has been added to the digital publishing teams backlog to enable cache headers and should be done some time in the next 2 weeks.

2017-01-06 15:31 UTC, ajmaddaford commented
Happy for this to go in while we wait for the CDN to be updated to add the cache headers (as Apache will cache the fonts in pre-prod and production).

2017-01-06 15:31 UTC, ajmaddaford approved these changes

2017-01-06 15:31 UTC, merged