Add percentage input, widget and validation.
ONSdigital/eq-survey-runner pull request #812
Opened 2017-01-03 14:44 UTC by samiwel

### What is the context of this PR?
Implement a Percentage input field.

### How to review 
I have included a test_percentage schema that can be used to test the new input field.
The percentage field should accept integer input and be limited to 0-100 inclusive.
The percentage sign should appear after the input field.

2017-01-04 10:20 UTC, benjefferies requested changes

2017-01-04 10:20 UTC, benjefferies commented on app/schema/widgets/percentage_widget.py
> +                'placeholder': '',
Can we delete placeholder if it's not used

2017-01-04 10:20 UTC, benjefferies commented on app/schema/widgets/percentage_widget.py
> +            'debug': {
We can delete the debug stuff as we can use the flask debug toolbar for this

2017-01-04 10:20 UTC, benjefferies commented on app/templates/partials/widgets/percentage_widget.html
> +    'placeholder': answer.placeholder,
Placeholder can be removed if it's not used

2017-01-04 15:21 UTC, jonnyshaw89 commented
@samiwel Does the % also need to be displayed on the summary screen?

2017-01-04 15:28 UTC, jonnyshaw89 requested changes
All looks good other than the few minor points ben has pointed out.

2017-01-04 15:59 UTC, jonnyshaw89 approved these changes

2017-01-05 09:15 UTC, bennpearson approved these changes

2017-01-05 10:56 UTC, benjefferies requested changes

2017-01-05 10:56 UTC, benjefferies commented on app/templates/partials/widgets/relationship_widget.html
> +              "pattern": "[0-9]*"
Is this supposed to be here?

2017-01-05 15:04 UTC, hamishtaplin commented on app/templates/partials/widgets/relationship_widget.html
> +              "pattern": "[0-9]*"
Err, no.

2017-01-05 15:05 UTC, samiwel commented on app/templates/partials/widgets/relationship_widget.html
> +              "pattern": "[0-9]*"
Not sure, @hamishtaplin should the relationship widget be changed as well? can you confirm if this is correct?

2017-01-05 15:25 UTC, samiwel commented on app/templates/partials/widgets/relationship_widget.html
> +              "pattern": "[0-9]*"
Cool, I'll revert the change in this file

2017-01-05 16:16 UTC, benjefferies approved these changes

2017-01-05 16:17 UTC, benjefferies commented
@samiwel can you squash?

2017-01-05 16:31 UTC, samiwel commented
@benjefferies squashed!

2017-01-05 17:08 UTC, merged