Removing eq id from url
ONSdigital/eq-survey-runner pull request #817
Opened 2017-01-04 16:55 UTC by benjefferies

### What is the context of this PR?
The eq_id is passed in as the payload of the session log in and is it
stored against the users session therefore we do not have to pass it on
every request.

[trello](https://trello.com/c/5wDJxaAi/338-remove-eq-id-from-url)

### How to review 
Tests pass
No downstream impact on other systems

2017-01-05 09:29 UTC, jonnyshaw89 requested changes

2017-01-05 09:29 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> +    if form_type != metadata["form_type"] or collection_id != metadata["collection_exercise_sid"]:
I like

2017-01-05 16:24 UTC, jonnyshaw89 commented
Pretty sure i made more comments here?

2017-01-05 16:26 UTC, benjefferies commented
I was a bit confused when I saw I like and then a changes requested. I haven't noticed any other comments

2017-01-06 10:15 UTC, jonnyshaw89 commented
I think i was questioning if form_type was also still needed in the url?

2017-01-06 15:52 UTC, collisdigital commented
form_type identified the questionnaire so I'd say yes

2017-01-06 16:00 UTC, jonnyshaw89 commented
@collisdigital but as with eq_id this is supplied in the metadata. so is purely in the url for show?

2017-01-06 16:06 UTC, collisdigital commented
I thought it was used to check if they'd launched a second survey; I think I'll leave it to you as I probably don't have the latest understanding of how that works.

2017-01-12 10:15 UTC, benjefferies commented
Closing as it has been moved to the backlog

2017-01-12 10:15 UTC, closed without merging