Backfilling jinja filter tests
ONSdigital/eq-survey-runner pull request #819
Opened 2017-01-05 10:42 UTC by benjefferies

### What is the context of this PR?
[trello](https://trello.com/c/csuYulm1/99-tests-for-jinja-filters)
Adding missing tests for jinja filters

### How to review 
All tests pass

2017-01-05 10:54 UTC, jonnyshaw89 requested changes

2017-01-05 10:54 UTC, jonnyshaw89 commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(format_value, '<p>this is on a<br>\nnew line</p>')
The name of this filter implies that is replaces the \n with a <br>?
But this test checks that there is a <br> before the \n

2017-01-05 10:54 UTC, jonnyshaw89 commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(str(format_value), '<p>&lt;</p>')
the adding of <p> tags also seems a bit implied

2017-01-05 11:00 UTC, benjefferies commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(format_value, '<p>this is on a<br>\nnew line</p>')
I don't think it has any impact but is confusing so will change the implementation

2017-01-05 11:09 UTC, benjefferies commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(str(format_value), '<p>&lt;</p>')
Is it clearer with the new method name?

2017-01-05 16:23 UTC, jonnyshaw89 commented on tests/app/test_jinja_filters.py
> +        self.assertEquals(str(format_value), '<p>&lt;</p>')
Much

2017-01-05 16:23 UTC, jonnyshaw89 approved these changes

2017-01-06 09:51 UTC, samiwel commented on app/jinja_filters.py
> +    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
It might be correct, but why are we joining with `u'\n\n'`? Isn't this method replacing \n with `<br>`?

2017-01-06 10:37 UTC, jonnyshaw89 commented on app/jinja_filters.py
> +    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
i think it maintains the line breaks in the source code but also added the br so it appears correct when rendered?

2017-01-06 10:39 UTC, jonnyshaw89 commented on app/jinja_filters.py
> +    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
So maybe my previous comment about removing the \n is incorrect?
Depends if we care how the source looks?

2017-01-06 10:42 UTC, benjefferies commented on app/jinja_filters.py
> +    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
As it's generated source then we probably don't care so I'll remove

2017-01-06 11:11 UTC, jonnyshaw89 requested changes

2017-01-06 11:11 UTC, jonnyshaw89 commented on app/jinja_filters.py
> +    result = u''.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
can probably remove the join completely?

2017-01-06 12:04 UTC, benjefferies commented on app/jinja_filters.py
> +    result = u''.join(u'<p>%s</p>' % p.replace('\n', '<br>') for p in _paragraph_re.split(escape(value)))
I have changed this a lot now as I think there was a bug in the code

2017-01-06 12:05 UTC, jonnyshaw89 approved these changes

2017-01-06 15:26 UTC, samiwel approved these changes
LGTM

2017-01-09 10:49 UTC, merged