Enabled Gzip compression on Elastic Beanstalk
ONSdigital/eq-survey-runner pull request #820
Opened 2017-01-05 14:46 UTC by jonnyshaw89

### What is the context of this PR?
Have enabled Gzip compression on Elastic Beanstalk
**Before**
<img width="318" alt="screen shot 2017-01-05 at 12 16 14" src="https://cloud.githubusercontent.com/assets/7594012/21684471/bd5d9fac-d355-11e6-8b78-7b25d47b24f6.png">
**After**
<img width="340" alt="screen shot 2017-01-05 at 13 07 28" src="https://cloud.githubusercontent.com/assets/7594012/21684479/c7b96e0e-d355-11e6-8b5c-be9eb86dbade.png">

2017-01-05 14:56 UTC, hamishtaplin requested changes
We should add webfonts to the list as per this answer on SO http://stackoverflow.com/questions/14005758/gzip-compression-htaccess-deflate

2017-01-05 15:50 UTC, jonnyshaw89 commented
@hamishtaplin im not sure that works. unless you can give me an example of what i need to add to my code then i can try that.

2017-01-05 16:31 UTC, hamishtaplin commented
@jonnyshaw89 Got any links? It's standard practise to compress webfonts (maybe not WOFF) as you can see in the (widely used) HTML5 boilerplate .htaccess: https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess#L756

2017-01-06 09:05 UTC, jonnyshaw89 commented
@hamishtaplin https://www.tunetheweb.com/performance/gzip/
"but don't compress content which is already compressed including images and woff and woff2 fonts"

2017-01-06 09:40 UTC, benjefferies approved these changes

2017-01-06 10:36 UTC, ajmaddaford commented
@jonnyshaw89 The link you posted mentions compressing fonts that aren't woff or woff2

2017-01-06 11:29 UTC, jonnyshaw89 commented
@ajmaddaford i had a chat with @hamishtaplin and as we arn't using these formats and our fonts are going onto a CDN i didn't see the point in adding. But i can if you see a benefit?

2017-01-06 12:08 UTC, hamishtaplin approved these changes

2017-01-06 14:34 UTC, merged