Add save and come back functionality
ONSdigital/eq-survey-runner pull request #822
Opened 2017-01-06 09:51 UTC by LJBabbage

### What is the context of this PR?
Adding the save and come back functionality on all surveys. Mandatory validation should be skipped if save and come back is clicked, however validation errors (i.e. text in a number) should be caught. A block should not be marked as completed if save and come back is clicked, meaning the user gets return to the same block on authentication.

### How to review 
1. Record your collection ID and user name, complete half of a survey without any potential validation errors and click close and come back (make sure data is on the page), confirm it goes to the correct page(sign-out.html) Now re-authenticate with the same details and make sure it goes to the last place with the data you entered.
2. Repeat the above but leave a mandatory question (1_0102 can be used on the first 2 questions)blank before clicking save and come back , make sure it goes to the sign out page
3. Repeat the above but now generate a validation error, like text in a number field. Make sure a validation error is generated and must be removed/corrected before save and come back later works.
4. Once save and continue has been used make sure you can't get back into the survey without re-authenticating, you should get a 401. You could do this by using back after seeing the sign-out page and trying to refresh.

2017-01-06 14:07 UTC, jonnyshaw89 requested changes

2017-01-06 14:07 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> +    if 'action[save_come_back]' in request.form:
Should we not make this its own endpoint as we have with submit_answers?

2017-01-06 14:07 UTC, jonnyshaw89 commented on app/questionnaire/questionnaire_manager.py
> +    def validate(self, location, post_data, skip_mandatory_validation=False):
Im not sure i like the approach of passing a boolean down the stack to change the behaviour of the validation at a lower level

2017-01-06 14:07 UTC, jonnyshaw89 commented on app/schema/questions/date_range_question.py
> +            if state.children[0].value and state.children[1].value:
do we need to check that state.children has a length of 2 instead? as `state.children[1].value` will error if there is no index of 1 whereas checking the existence of the indexes won't.

2017-01-09 15:35 UTC, yoganandkunche commented
Currently in QA
an issue has been raised #827

2017-01-10 10:38 UTC, yoganandkunche commented
@LJBabbage Census on Visitors pages gives Error 500 when user comes back and removes the visitors and click 'Save and Come back later'

2017-01-10 14:05 UTC, benjefferies requested changes

2017-01-10 14:05 UTC, benjefferies commented on app/questionnaire/questionnaire_manager.py
> +    def validate(self, location, post_data, skip_mandatory_validation=False):
It's know what your saying it feels nasty but it hard to say it's worth tackling because wtforms being on the horizon? I guess we need to know what is happening with that before we commit to the effort to refactor

2017-01-10 14:05 UTC, benjefferies commented on app/questionnaire/questionnaire_manager.py
> +    def update_questionnaire_store(self, location, save_come_back=False):
I wonder if it would be nicer to refactor this out into a method called save_and_come_back instead of the boolean logic?

2017-01-10 14:05 UTC, benjefferies commented on app/views/questionnaire.py
> +    if 'action[save_come_back]' in request.form:
I agree, it would be good if we could do this however I remember @hamishtaplin suggesting posting a form to a different URL is a html 5 thing

2017-01-10 14:05 UTC, benjefferies commented on tests/functional/spec/save-come-back.spec.js
> +  it('Given I am completing survey 0102, when I select save and come back later, then I am redirected to sign out page, showing a message that my survey has been saved and I cant continue without re-
Minor point, if this was split out into two tests it might read nicer:
- Given I am completing survey 0102, when I select save and come back later, then I am redirected to sign out page, showing a message that my survey has been saved
- Given I have saved to continue later, when I go back to the questionnaire, then I need to authenticate

2017-01-10 14:05 UTC, benjefferies commented on tests/functional/spec/save-come-back.spec.js
> +    startQuestionnaire('1_0102.json', 'test_user', collectionId)
'test_user' and collectionId don't need to be defined as they are optional

2017-01-10 14:05 UTC, benjefferies commented on tests/functional/spec/save-come-back.spec.js
> +  it('Given I am completing completing survey 0102 and I have not completed mandatory questions, when I select save and come back later, then the missing mandatory questions will be ignored and I wil
This is covered in the integration test `test_save_come_back_with_household_question`

2017-01-10 14:05 UTC, benjefferies commented on tests/functional/spec/save-come-back.spec.js
> +    it('Given I am completing survey 0102 and have outstanding validation failures, when I select save and come back later, then I must correct my response before my questionnaire can be saved and I
This is covered by `test_save_come_back_with_non_mandatory_validation_error`

2017-01-10 14:05 UTC, benjefferies commented on tests/functional/spec/save-come-back.spec.js
> +  it('Given whilst completing survey 0102 I have opted to save and come back later, when I return to the questionnaire after re-authenticating, then I am returned to the page I was on when I selected
This is covered by `test_save_come_back_complete_a_block_then_revist_it_and_use_save_and_come_back`

2017-01-10 14:05 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_save_come_back.py
> +    def test_save_come_back_complete_a_block_then_revist_it_and_use_save_and_come_back(self):
Should this test be name `test_save_come_back_complete_a_block_then_revist_it` minus `_and_use_save_and_come_back`

2017-01-10 15:10 UTC, LJBabbage commented on tests/functional/spec/save-come-back.spec.js
> +    startQuestionnaire('1_0102.json', 'test_user', collectionId)
This is a copy paste error, one of the tests logged back in and therefore I needed to hold the collectionId and user, I will remove the ones that don't log back in

2017-01-10 15:16 UTC, LJBabbage commented on tests/functional/spec/save-come-back.spec.js
> +  it('Given I am completing completing survey 0102 and I have not completed mandatory questions, when I select save and come back later, then the missing mandatory questions will be ignored and I wil
The household question has a bespoke view, and therefore its own call to save and come back, we will need both to cover it

2017-01-11 13:35 UTC, LJBabbage commented on app/views/questionnaire.py
> +    if 'action[save_come_back]' in request.form:
What Ben said, its the current pattern we are having to use for post_household_composition

2017-01-11 13:51 UTC, LJBabbage commented on tests/functional/spec/save-come-back.spec.js
> +  it('Given I am completing survey 0102, when I select save and come back later, then I am redirected to sign out page, showing a message that my survey has been saved and I cant continue without re-
Kept it as one to avoid duplication, but made it a lot shorter and easier to read

2017-01-11 13:53 UTC, LJBabbage commented on tests/functional/spec/save-come-back.spec.js
> +    it('Given I am completing survey 0102 and have outstanding validation failures, when I select save and come back later, then I must correct my response before my questionnaire can be saved and I
Slimed down the Selenium test to 2 major ones, which addresses the points below

2017-01-11 14:00 UTC, LJBabbage commented on app/questionnaire/questionnaire_manager.py
> +    def validate(self, location, post_data, skip_mandatory_validation=False):
Not sure what else we can do till WTF time as at the top level its just an array of messages with no validation type associated, so I can't tell if they are mandatory failures

2017-01-11 14:01 UTC, LJBabbage commented
Issues raised from QA have been fixed

2017-01-12 10:19 UTC, benjefferies approved these changes

2017-01-12 11:13 UTC, ajmaddaford requested changes

2017-01-12 11:13 UTC, ajmaddaford commented on app/views/questionnaire.py
> +@questionnaire_blueprint.route('sign-out', methods=["GET"])
I think this URL should be `signed-out`, as the page isn't for signing out, it's the page we display once a user has 'signed out'. This would also apply to the template name.

2017-01-12 11:13 UTC, ajmaddaford commented on app/templates/questionnaire.html
> +        <button class="btn btn--link mars" type="submit" name="action[save_come_back]">{% block save_come_back_button_text %}Save and come back later{% endblock %}</button>
Any reason this text is overridable? Also, the text should be 'Save and complete later'

2017-01-12 11:13 UTC, ajmaddaford commented on app/views/questionnaire.py
> +        return _save_come_back(collection_id, eq_id, form_type, questionnaire_manager, this_location)
I think we should replace all references to `save_come_back` with `save_sign_out` as that is the functionality we are implementing, it's up to the user if they come back later or not.

2017-01-12 12:00 UTC, jonnyshaw89 commented on app/questionnaire/questionnaire_manager.py
> +    def validate(self, location, post_data, skip_mandatory_validation=False):
ok lets review after WTForms

2017-01-12 12:00 UTC, jonnyshaw89 approved these changes

2017-01-12 15:38 UTC, ajmaddaford approved these changes

2017-01-13 07:53 UTC, yoganandkunche commented
@LJBabbage Save and come back later currently giving Error 500 (tested on 0112 & census household schemas)

2017-01-13 12:12 UTC, yoganandkunche commented
QA Done on this PR. Happy to sign off from QA perspective.

2017-01-16 10:19 UTC, merged