Caching schema between requests
ONSdigital/eq-survey-runner pull request #823
Opened 2017-01-06 16:44 UTC by jonnyshaw89

### What is the context of this PR?
Possible implementation of caching of survey json after the 1st request.

### How to review 
Feedback on approach please.

2017-01-11 13:16 UTC, benjefferies requested changes
Have we ran all the tests against the application in EQ_DEV_MODE=False?

2017-01-12 10:19 UTC, jonnyshaw89 commented
@benjefferies I have run all the functional tests with caching enabled.

2017-01-12 10:43 UTC, benjefferies requested changes

2017-01-12 10:43 UTC, benjefferies commented on app/__init__.py
> +        cache.init_app(application, config={'CACHE_TYPE': 'null'})  # Doesnt cache
cache.init_app(application) will default to the non-caching config

2017-01-12 10:43 UTC, benjefferies commented on tests/integration/test_schema_cache.py
> +            self.assertNotEquals(cache.cache._cache['app.utilities.schema.load_and_parse_schema_memver'], None)
`cache.cache._cache['app.utilities.schema.load_and_parse_schema_memver']` could be changed to use the public method cache.get('app.utilities.schema.load_and_parse_schema_memver')

2017-01-12 10:43 UTC, benjefferies commented on tests/integration/test_schema_cache.py
> +        for key_name, dev_location in settings._KEYS.items():
Would we be able to apply this to all of the integration tests to run closer to production?

2017-01-12 11:09 UTC, benjefferies approved these changes

2017-01-12 11:48 UTC, benjefferies commented on app/__init__.py
> +    if settings.EQ_ENABLE_CACHE:
👍

2017-01-12 15:12 UTC, iwootten requested changes

2017-01-12 15:12 UTC, iwootten commented on tests/integration/test_schema_cache.py
> +            self.assertEqual(len(cache.cache._cache), 0)
Hmm, this is a bit weird. Can we import from app.cache to save drilling down this far?

2017-01-12 15:12 UTC, iwootten commented on tests/integration/test_schema_cache_off.py
> +            self.assertTrue(isinstance(cache.cache, NullCache));
and again here?

2017-01-12 15:18 UTC, jonnyshaw89 commented on tests/integration/test_schema_cache.py
> +            self.assertEqual(len(cache.cache._cache), 0)
Im not sure what you mean? can you give an example?

2017-01-12 15:20 UTC, iwootten commented on tests/integration/test_schema_cache.py
> +            self.assertEqual(len(cache.cache._cache), 0)
from app.cache import cache
or
    
    from app.cache import cache as app_cache

2017-01-12 15:24 UTC, jonnyshaw89 commented on tests/integration/test_schema_cache.py
> +            self.assertEqual(len(cache.cache._cache), 0)
ah ok. but if i did that then i would still need to higher level import for the next assertion on the cache on line 20 `cache.get`

2017-01-12 15:25 UTC, iwootten commented on tests/integration/test_schema_cache.py
> +            self.assertEqual(len(cache.cache._cache), 0)
Oh, did spy that, fair enough.

2017-01-12 15:26 UTC, iwootten approved these changes

2017-01-13 08:49 UTC, benjefferies commented
Are there any outstanding questions to be answered or can this be merged?

2017-01-13 09:16 UTC, jonnyshaw89 commented
The only open question it how much of a performance gain we get. but we can't run that at the moment but i don't see a reason that should block merge?

2017-01-13 13:50 UTC, benjefferies commented
Discussed with @ajmaddaford and it's probably worth running a performance test locally before merging. This will save the overhead of rolling back if it's not better

2017-01-13 14:07 UTC, jonnyshaw89 commented
In progress

2017-01-13 14:57 UTC, jonnyshaw89 commented
Results from test with 100 users.
Average survey completion time
Before 693ms
After 607ms

2017-01-16 10:39 UTC, merged