Refactoring questionnaire
ONSdigital/eq-survey-runner pull request #825
Opened 2017-01-09 13:40 UTC by benjefferies

### What is the context of this PR?
* Removing unused code paths
* Merging identical logic
* Defining named parameters for clarity

### How to review 
All tests should pass, suggest further improvements or object any changes

2017-01-11 13:43 UTC, jonnyshaw89 approved these changes
nice tidy up. The naming of the parameters adds a lot more context

2017-01-11 13:43 UTC, jonnyshaw89 commented on app/questionnaire/location.py
> +        path_params = {
nice

2017-01-11 13:43 UTC, jonnyshaw89 commented on app/questionnaire/questionnaire_manager.py
> +    def build_block_state(self, location, answers):
hopefully this whole function should go with WTForms

2017-01-12 10:33 UTC, iwootten requested changes

2017-01-12 10:33 UTC, iwootten commented on app/questionnaire/location.py
> +                           eq_id=eq_id,
This can use path params as well can't it?

2017-01-12 10:33 UTC, iwootten commented on app/questionnaire/questionnaire_manager.py
> +    def build_block_state(self, location, answers):
Whole class :)

2017-01-12 10:33 UTC, iwootten commented on tests/integration/questionnaire/test_questionnaire_final_confirmation.py
> -
This is the best change of the whole PR

2017-01-12 10:49 UTC, benjefferies commented on app/questionnaire/location.py
> +                           eq_id=eq_id,
Done

2017-01-12 10:49 UTC, benjefferies commented on app/questionnaire/questionnaire_manager.py
> +    def build_block_state(self, location, answers):
Yeah at some point I hope we can remove it with WTForm but trying to make it maintainable in the short term

2017-01-12 10:49 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_final_confirmation.py
> -
Thanks for the acknowledgement 👍

2017-01-12 10:51 UTC, iwootten approved these changes

2017-01-12 12:24 UTC, merged