Remove previous links on thank you pages
ONSdigital/eq-survey-runner pull request #837
Opened 2017-01-12 16:52 UTC by iwootten

### What is the context of this PR?
Removed previous link from thank you pages and added tests to check where previous links appear.

Fixes #828 

### How to review 
Check tests still pass.

2017-01-13 08:48 UTC, benjefferies requested changes

2017-01-13 08:48 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        self.assertNotRegexpMatches(content, 'Previous')
I think we should use assertNotIn when we are checking for contains otherwise it's a bit misleading

2017-01-13 08:48 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        post_data = {
Do we need to post to the introduction page or can we just post the first page

2017-01-13 08:50 UTC, jonnyshaw89 commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        post_data = {
If the integration tests don't post in the same pages as the user would can we be sure that the state of the system will be the same?

2017-01-13 08:52 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        post_data = {
I guess either way it should behave the same because the user in theory could jump around by changing the URL

2017-01-13 08:55 UTC, benjefferies commented on app/views/questionnaire.py
> +    if previous_location is not None and not is_first_block_for_group and not current_location.block_id == 'thank-you':
A more general observation, I wonder if we should move the previous location logic into the navigation class after the previous location is a part of navigation even if it's not rendered in the same way

2017-01-13 09:21 UTC, samiwel commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        self.assertNotRegexpMatches(content, 'Previous')
I believe `assertNotRegexpMatches` has been deprecated in Python 3. It's been replaced by `assertNotRegex`.

2017-01-13 09:30 UTC, samiwel commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +    def test_previous_link_appears_on_all_non_start_end_pages(self):
What is a non-start end page? I wonder if there is any benefit of splitting this out into two tests for clarity? e.g. `test_previous_link_not_visible_on_page_immediately_after_introduction` and `test_previous_link_visible_on_subsequent_question_pages` or similar.

2017-01-16 08:57 UTC, iwootten commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +    def test_previous_link_appears_on_all_non_start_end_pages(self):
A page that isn't at the start or end? :)

I've renamed this for clarity.

2017-01-16 09:00 UTC, iwootten commented on app/views/questionnaire.py
> +    if previous_location is not None and not is_first_block_for_group and not current_location.block_id == 'thank-you':
That's a fair enough observation - the wtforms spike makes some changes in this regard too whereby the current location is also passed to jinja. Think tackling it is outside the scope of this issue though.

2017-01-16 10:57 UTC, jonnyshaw89 approved these changes

2017-01-16 11:09 UTC, yoganandkunche commented
Defect passed retest on branch

2017-01-16 11:14 UTC, iwootten commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        post_data = {
Yeah, the form is posting back - so I'm not sure why we'd change the integration test to do something else.

2017-01-16 11:18 UTC, benjefferies approved these changes

2017-01-16 11:18 UTC, benjefferies commented on tests/integration/questionnaire/test_questionnaire_previous_link.py
> +        post_data = {
I follow what's going on now, got misled by the prior test name

2017-01-16 11:55 UTC, merged