Add routing to UKIS
ONSdigital/eq-survey-runner pull request #840
Opened 2017-01-13 14:35 UTC by LJBabbage

### What is the context of this PR?
To add the routing rules into the UKIS schema.

### How to review 
Using the google slides, check that routing is going to the expected blocks. N.B the hiding of sections in 7-9 has not been implemented in this PR

2017-01-18 15:14 UTC, samiwel requested changes
Been through the google slides and checked the routing rules. Looks good to me. The only issue being that spurious exception during logging of the group that we discussed.

2017-01-18 15:28 UTC, LJBabbage commented
Spurious exception during logging fixed

2017-01-18 17:51 UTC, samiwel approved these changes

2017-01-19 10:30 UTC, benjefferies requested changes

2017-01-19 10:30 UTC, benjefferies commented on .travis.yml
> +    - EQ_FUNCTIONAL_TEST_SUITES="core,ukis"
Lets add this as another matrix?

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/generate_pages.py
>      elif (answer['type'] == 'TextField' or answer['type'] == 'Integer' or
We could probably tidy this up with `answer['type'] in ['TextField', 'Integer', 'PositiveInteger', 'TextArea', 'Currency', 'Percentage']`

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-market-introductions.spec.js
> +      .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent for continuation lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-goods.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I  select No as the response and Yes for 4.3, Then I will see questions 4.5, 4.6 & 4.7', function() {
Could be clearer to move the first part of the when `When I  select No as the response and Yes for 4.3` and clarify as `Given I have answered No to 4.2, When I  select and Yes for 4.3...` otherwise it could be confusing as it suggest you can select Yes and No to 4.3

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-goods.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I  select No as the response and No for 4.3, Then I will NOT see questions 4.5, 4.6 & 4.7', function() {
Ditto comment above

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-goods.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I do not select a respose for 4.1 and answer Yes for 4.3, Then I will see questions 4.5, 4.6 & 4.7', functio
Typo `select a respose` -> `select a response`

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-goods.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I do not select a respose for 4.1 and I do not answer 4.3, Then I will NOT see questions 4.5, 4.6 & 4.7', fu
Same typo as above

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-goods.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I answer NO for 4.1 and I do not answer 4.3, Then I will NOT see questions 4.5, 4.6 & 4.7', function() {
Isn't this test the same as the one on line 173?

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-services.spec.js
> +  it('Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I  select Yes for 4.1 and do not select a response for 4.3, Then I will see questions 4.5', function() {
Isn't this technically covered by 'Given I am answering question 4.1 under 4. Goods and Services Innovation block, When I  select No as the response and I do not answer 4.3, Then I will NOT see questions 4.5, 4.6 & 4.7' in `any-new-goods.spec.js`

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-public-support-from-central-gov.spec.js
> +    .clickPublicFinancialSupportCentralGovernmentAnswerYes()
We should indent continuation lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-public-support-from-central-gov.spec.js
> +  it('Given I am answering question 10.1 under 10. Public Financial Support for Innovation block, When I  select Yes as the response, Then I am routed to question 10.2', function() {
It might be worth adding context which answer the routing rule is on as I cannot work out if it should route to 10.2 for yes to any of the answers

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-public-support-from-central-gov.spec.js
> +  it('Given I am answering question 10.1 under 10. Public Financial Support for Innovation block, When I  select No as the response, Then I am routed to the end of section 10 (interstitial page)', fu
It might be worth adding context which answer the routing rule is on as I cannot work out if it should route to the end when no is the answer for any of the answers

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-public-support-from-central-gov.spec.js
> +  it('Given I am answering question 10.1 under 10. Public Financial Support for Innovation block, When I do not select a response, Then I am routed to the end of section 10 (interstitial page)', func
It might be worth adding context which answer the routing rule is on as I cannot work out if it should route to the end when no response is the answer for any of the answers

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-machinery-etc.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-acquire-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-design.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-design.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-design.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-internal-r-and-d.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-training.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-training.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/did-you-invest-in-training.spec.js
> +    .clickInvestmentPurposesInnovationAnswerComputerHardware()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickSignificantEventsTurnoverIncreaseAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickBusinessChangesOrganisingAnswerNo()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +    .clickYearsInternalInvestmentRDAnswer2014()
We should indent continued lines

2017-01-19 10:30 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +import GeographicMarkets from '../../../pages/surveys/ukis/geographic-markets.page.js'
We should look at which imports we actually have to import and which can be deleted. I wonder if atom or intellij has a optimise imports for node?

2017-01-19 10:40 UTC, LJBabbage commented on .travis.yml
> +    - EQ_FUNCTIONAL_TEST_SUITES="core,ukis"
As discussed, this is the most efficient way at the moment

2017-01-19 10:45 UTC, iwootten requested changes

2017-01-19 10:45 UTC, iwootten commented on tests/functional/pages/surveys/ukis/comments-block-107.page.js
> +class CommentsBlock107Page extends QuestionPage {
Does this need removing, given the block id no longer appears?

2017-01-19 11:10 UTC, LJBabbage commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +import GeographicMarkets from '../../../pages/surveys/ukis/geographic-markets.page.js'
Definitely agree, technically backlog?

2017-01-19 11:20 UTC, benjefferies commented on tests/functional/spec/ukis/routing/which-years.spec.js
> +import GeographicMarkets from '../../../pages/surveys/ukis/geographic-markets.page.js'
Makes sense

2017-01-19 11:21 UTC, benjefferies approved these changes

2017-01-19 11:22 UTC, benjefferies commented on .travis.yml
> +    - EQ_FUNCTIONAL_TEST_SUITES="core,ukis"
I've added this to further explore what can be done here https://trello.com/c/ZBL2289B/372-speed-up-build-time

2017-01-19 11:24 UTC, ajmaddaford approved these changes

2017-01-19 11:29 UTC, LJBabbage commented
Rebased, squashed and ready to merge

2017-01-19 11:30 UTC, LJBabbage commented on tests/functional/pages/surveys/ukis/comments-block-107.page.js
> +class CommentsBlock107Page extends QuestionPage {
Removed, as it is now redundant

2017-01-19 11:47 UTC, yoganandkunche commented
Passed QA on branch

2017-01-19 11:54 UTC, iwootten approved these changes

2017-01-19 11:54 UTC, merged