Add test that checks for duplicate keys in schemas.
ONSdigital/eq-survey-runner pull request #848
Opened 2017-01-17 14:31 UTC by samiwel

### What is the context of this PR?
Add a test which checks the schema files for any duplicate keys.
This PR addresses a tech debt task 367.

### How to review 
Please review the test in case there are any problems with the logic.
Otherwise observe that all schemas are checked by this test to ensure that no duplicate Id are present.

2017-01-17 14:46 UTC, benjefferies requested changes

2017-01-17 14:46 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +        print('Checking schema files for duplicate keys.')
Let's use the logger

2017-01-17 14:46 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                print('Checking %s...' % schema_file)
Let's use the logger

2017-01-17 14:46 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +                yield schema_json[k]
yield v?

2017-01-17 14:46 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +            elif k in ignored_keys:
I guess it doesn't matter much if we just evaluate all keys. The performance impact is going to be unnoticeable?

2017-01-17 14:49 UTC, samiwel commented on tests/app/data/test_schema_validation.py
> +            elif k in ignored_keys:
It isn't a performance optimisation, we genuinely need to skip routing_rules and skip_conditions or we'll get false-positives in terms of duplicate Ids.

2017-01-17 14:51 UTC, benjefferies commented on tests/app/data/test_schema_validation.py
> +            elif k in ignored_keys:
Oh yeah doh! Might would worth giving them a name to reflect that. That's a tough ask so might be worth a comment to state they contain id references which are likely to contain duplicates

2017-01-18 13:57 UTC, benjefferies approved these changes

2017-01-18 15:14 UTC, LJBabbage approved these changes

2017-01-18 15:16 UTC, merged