Eq 847 remove jquery
ONSdigital/eq-survey-runner pull request #854
Opened 2017-01-19 15:08 UTC by bennpearson

### What is the context of this PR?
Removed jQuery because it is only used for one pattern so have replaced this with javascript and used polyfills.js to add support to older browsers.  

### How to review 
Check focus on radio and checkbox inputs.
Also check browsers that don't support the following methods:
- https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
- https://developer.mozilla.org/en/docs/Web/API/Element/classList

2017-01-20 11:07 UTC, hamishtaplin requested changes

2017-01-20 11:07 UTC, hamishtaplin commented on app/assets/js/app/modules/focus-styles.js
> +    var siblings = []
don't use `var`—use `let` or `const` where appropriate

might be worth adding a linting rule for this too: http://eslint.org/docs/rules/no-var

2017-01-20 11:07 UTC, hamishtaplin commented on app/assets/js/app/modules/focus-styles.js
> +  function getNextSiblings(e, filter) {
move these into a helper called selectors and then `import`

2017-01-23 11:28 UTC, hamishtaplin commented
Still need to add linting rule to discourage use of `var`.

2017-01-24 08:29 UTC, hamishtaplin approved these changes

2017-01-24 09:11 UTC, benjefferies requested changes

2017-01-24 09:11 UTC, benjefferies commented on .eslintrc
> +    "no-var": [1]
Is this something we want to turn off globally or just ignore on the case by case scenario?

2017-01-24 09:19 UTC, hamishtaplin commented on .eslintrc
> +    "no-var": [1]
@benjefferies There's no reason to use `var` unless you specifically need to take advantage of the way it's scoped—which is highly unlikely.

2017-01-24 09:21 UTC, benjefferies approved these changes

2017-01-24 09:48 UTC, benjefferies commented on .eslintrc
> +    "no-var": [1]
Though this was disabling it as I thought it was enabled by default

2017-01-24 11:41 UTC, merged