added js hook to template for filtering out pre-existing errors on ho…
ONSdigital/eq-survey-runner pull request #866
Opened 2017-01-23 13:57 UTC by hamishtaplin

### What is the context of this PR?

Fixes #758.

- Added missing js hook used in filtering out pre-existing error messages when the new DOM elements are created for adding a person.

### How to review 

- As per bug repro steps.

2017-01-24 08:51 UTC, iwootten requested changes
This probably should have a selenium test to prove it the issue is resolved.

2017-01-24 10:41 UTC, benjefferies requested changes

2017-01-24 10:41 UTC, benjefferies commented on tests/functional/spec/census-household.spec.js
> +      expect(browser.elements('.js-household-person .js-has-errors').value.length).to.equal(1)
All of the page models have a method called errorExists() which could possibly be utilised instead of having arbitrary selectors

2017-01-24 10:51 UTC, hamishtaplin commented on tests/functional/spec/census-household.spec.js
> +      expect(browser.elements('.js-household-person .js-has-errors').value.length).to.equal(1)
@benjefferies Unfortunately that method only deals with the list of errors at the top of the page, whereas this bug relates to the error surrounding the fields themselves.

2017-01-24 10:57 UTC, iwootten approved these changes

2017-01-25 09:04 UTC, benjefferies approved these changes

2017-01-25 16:19 UTC, merged