added computed style fix
ONSdigital/eq-survey-runner pull request #873
Opened 2017-01-24 16:46 UTC by bennpearson

### What is the context of this PR?
Fixes #862 Scroll issue in safari 

### How to review 

- Use Safari
- Select UKIS 1_0001.json schema
- Try scrolling down the page

2017-01-25 16:01 UTC, hamishtaplin requested changes

2017-01-25 16:01 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_page.scss
> +  padding-bottom: 1px;
Can we at least add a comment in the code with a link to this bug so we know why this seemingly arbitrary bit of padding his here?

2017-01-25 16:01 UTC, hamishtaplin approved these changes

2017-01-26 12:37 UTC, ajmaddaford commented
@bennpearson I don't get this issue on master, I'm using Safari on a Mac
![image](https://cloud.githubusercontent.com/assets/1754822/22331559/00b6fcc0-e3c4-11e6-9681-56f13b428ab8.png)

2017-01-27 09:11 UTC, hamishtaplin commented
@ajmaddaford It's a definite issue, I can reproduce—it happens on the introduction page.

2017-01-27 10:53 UTC, ajmaddaford commented
@hamishtaplin I believe it's an issue, but I couldn't test that this fixes it! I do get an additional scroll bar without this fix, and it fixes that.

2017-01-27 10:54 UTC, ajmaddaford approved these changes

2017-01-27 11:19 UTC, merged