Make BEIS and DoF logos visible for NIR respondents.
ONSdigital/eq-survey-runner pull request #877
Opened 2017-01-26 10:49 UTC by samiwel

### What is the context of this PR?
BEIS and the NI department of finance have requested that the NI department of finance and BEIS logos are present on the NI UKIS questionnaire landing page.

This PR ensures that both logos are visible when UKIS survey is launched with a Northern Ireland Region code.

### How to review 
The UKIS landing page has both the NI and BEIS logo present when launched in the Northern Ireland region.
The NI logo is not present in non-Northern Ireland regions (i.e. just the BEIS logo is shown)

2017-01-26 11:05 UTC, collisdigital commented
Can you attach a screenshot. Note the BEIS logo has changed (see Trello).

2017-01-26 11:06 UTC, samiwel commented
Sure, I'll attach a screenshot once I've replaced the logo.

2017-01-26 12:44 UTC, collisdigital commented on app/themes/ukis/templates/introduction.html
> +      <img src="{{ theme_static('logo-beis.png') }}" alt="Department for Business, Energy and Industrial Strategy" width="200" />
If you swap the order of the IF statement you could always have the BEIS logo and only add the NI logo inside the IF; no need for an ELSE.

2017-01-26 16:04 UTC, jonnyshaw89 approved these changes

2017-01-26 16:19 UTC, ajmaddaford commented
The `gy` on the end of 'Strategy' in the BEIS logo is slightly cut off for me
![image](https://cloud.githubusercontent.com/assets/1754822/22339811/2f4b407c-e3e3-11e6-8809-1c6f86fc6f86.png)

2017-01-27 08:43 UTC, hamishtaplin commented
Can we get this closer to the design? There should be a margin between the logos and attention paid to how they stack on mobile. Also, the proportions of the logos are off—the BEIS one is too big and the file needs to be scaled down so we're not shipping a 900px wide image only to display it at 220px.

2017-01-27 08:44 UTC, hamishtaplin requested changes
Can we get this closer to the design? There should be a margin between the logos and attention paid to how they stack on mobile. Also, the proportions of the logos are off—the BEIS one is too big and the file needs to be scaled down so we're not shipping a 900px wide image only to display it at 200px. Ideally it would be re-sized to 400px wide so it scales nicely for @2x display.

2017-01-27 12:39 UTC, samiwel commented
![image](https://cloud.githubusercontent.com/assets/4097796/22371180/94b79294-e48d-11e6-868f-47fd04dd72cf.png)

I've updated the styling so that it more closely resembles the design.
I've also reduced the size of the image to 400px and removed the inline CSS.

2017-01-30 08:04 UTC, hamishtaplin approved these changes

2017-01-30 08:04 UTC, merged