Fixes ukis routing change on Q 5.1
ONSdigital/eq-survey-runner pull request #899
Opened 2017-01-30 14:28 UTC by yoganandkunche

### What is the context of this PR?
Fixes  #892

### How to review 
Retest defect  #892 and run the below selenium test:

yarn run test_functional -- --spec=ukis/routing/any-new-processes

2017-01-30 15:40 UTC, jonnyshaw89 requested changes

2017-01-30 15:40 UTC, jonnyshaw89 commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
"Expected to Navigate to Q: 5.3" is no longer correct?

2017-01-30 15:40 UTC, jonnyshaw89 commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
same as above

2017-01-30 15:41 UTC, benjefferies requested changes

2017-01-30 15:41 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
Same with the BDD title of the test

2017-01-30 15:41 UTC, benjefferies commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
Same with the BDD title of the test

2017-01-30 15:41 UTC, benjefferies commented on yarn.lock
>  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
I think you've accidentally checked in this file

2017-01-30 17:21 UTC, yoganandkunche commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
Made the change

2017-01-30 17:21 UTC, yoganandkunche commented on tests/functional/spec/ukis/routing/any-new-processes.spec.js
> +    expect(ProcessInnovationCompleted.isOpen()).to.equal(true, 'Expected to Navigate to Q: 5.3')
Made the change

2017-01-31 09:42 UTC, benjefferies approved these changes

2017-01-31 09:49 UTC, jonnyshaw89 approved these changes

2017-01-31 09:49 UTC, jonnyshaw89 commented
@yoganandkunche can you squash and rebase?

2017-01-31 09:53 UTC, yoganandkunche commented
@jonnyshaw89 I have this document which I'm going through. https://digitaleq.atlassian.net/wiki/pages/viewpage.action?spaceKey=EQ&title=Developer+Workflow#DeveloperWorkflow-RebasingGitHubPullRequestpriortofinalmerge

2017-01-31 11:00 UTC, merged