Eq 785 section numbers
ONSdigital/eq-survey-runner pull request #911
Opened 2017-02-01 11:29 UTC by bennpearson

### What is the context of this PR?
Section and question numbers 
 
### How to review 
Choose 1_0001.json schema and check section and question numbers

2017-02-01 13:06 UTC, collisdigital commented
@bennpearson please attach screenshots of Census and Business themes section and question numbers both left-hanging and in-line... thanks

2017-02-01 13:37 UTC, hamishtaplin requested changes

2017-02-01 13:37 UTC, hamishtaplin commented on app/assets/styles/partials/components/_question.scss
> +.question__title__number {
Double BEM 👎

2017-02-01 13:37 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_section.scss
> +  min-width: 48px;
Any reason not to use `rem` here?

2017-02-01 13:37 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_section.scss
> +.section__title__number {
Double BEM 👎

2017-02-01 13:39 UTC, hamishtaplin commented
![screenshot 2017-02-01 13 36 34](https://cloud.githubusercontent.com/assets/930398/22508838/a70b522e-e883-11e6-97a6-1c8b064a9183.png)

Section numbers a bit big on mobile maybe?

2017-02-01 13:42 UTC, hamishtaplin requested changes

2017-02-01 13:42 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_section.scss
> +    width: 48px;
Don't use magic numbers, use a var for this as it's repeated throughout.

2017-02-01 13:42 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_section.scss
> +    z-index: -1;
Risk of this ending up behind something if you use `-1`?

2017-02-01 13:43 UTC, hamishtaplin commented
I think there's an issue with using fixed values for positioning as it starts to look weird in some places: 

![Uploading Screenshot 2017-02-01 13.43.27.png…]()

2017-02-01 14:03 UTC, collisdigital commented
@hamishtaplin did a visual review with @alexmorris and @bennpearson at desk just now, some updates coming, including spacing on mobile, watch this space.

2017-02-01 14:09 UTC, hamishtaplin requested changes

2017-02-01 14:09 UTC, hamishtaplin commented on app/assets/styles/partials/components/_question.scss
> +    left: -48px;
If you use `text-align: right` and then give this a fixed width then it'll scale better with bigger numbers:

![screenshot 2017-02-01 14 08 16](https://cloud.githubusercontent.com/assets/930398/22509928/f3423eb0-e887-11e6-8a6a-3470c48f95ce.png)

![screenshot 2017-02-01 14 08 37](https://cloud.githubusercontent.com/assets/930398/22509935/fa33f6d2-e887-11e6-984f-c7570ef26336.png)

2017-02-01 15:44 UTC, hamishtaplin requested changes

2017-02-01 15:44 UTC, hamishtaplin commented on app/assets/styles/partials/objects/_section.scss
> +  top: 1px;
Some issue with positioning somewhere around here when errors exist in page

![screenshot 2017-02-01 14 59 41](https://cloud.githubusercontent.com/assets/930398/22512006/7a878d7e-e88f-11e6-94fe-f25d7b071ac8.png)

2017-02-02 13:55 UTC, hamishtaplin approved these changes

2017-02-02 14:39 UTC, merged