MWSS gross pay piping
ONSdigital/eq-survey-runner pull request #912
Opened 2017-02-01 15:30 UTC by jonnyshaw89

### What is the context of this PR?
Added the piping for gross pay into next question

### How to review 
Enter a gross pay into each section and see that appropriate value is piped into the question text

2017-02-01 18:23 UTC, ajmaddaford requested changes

2017-02-01 18:23 UTC, ajmaddaford commented on app/data/mwss_4.json
> +                                    "title": "Of the {{answers.weekly_total_gross}} paid to <em>weekly paid</em> employees in the <em>last week of December 2016</em>, what amount was:",
I think there should be a pound sign in this text, it currently looks like this:
![image](https://cloud.githubusercontent.com/assets/1754822/22520184/3e5106b6-e8ab-11e6-9579-5030979b5dbf.png)

Same for all other occurrences.

2017-02-01 18:47 UTC, jonnyshaw89 commented on app/data/mwss_4.json
> +                                    "title": "Of the {{answers.weekly_total_gross}} paid to <em>weekly paid</em> employees in the <em>last week of December 2016</em>, what amount was:",
@ajmaddaford i have updated this.

2017-02-01 18:48 UTC, ajmaddaford approved these changes

2017-02-01 18:49 UTC, ajmaddaford commented
I've added currency formatting for the piped gross pay values and pushed the rebased changes

2017-02-02 08:21 UTC, LJBabbage requested changes
ignore

2017-02-02 08:46 UTC, LJBabbage approved these changes

2017-02-02 08:46 UTC, merged