Eq 635 timeout
ONSdigital/eq-survey-runner pull request #917
Opened 2017-02-03 16:37 UTC by hamishtaplin

### What is the context of this PR?

https://trello.com/c/Wx4tvl1f/635-timeout-facility-13

WIP timeout PR

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

2017-02-13 14:57 UTC, benjefferies commented on app/views/questionnaire.py
> +    session_timeout = settings.EQ_SESSION_TIMEOUT - settings.EQ_SESSION_TIMEOUT_GRACE_PERIOD
Isn't this the session_timeout_warning?

2017-02-13 14:57 UTC, benjefferies commented on app/views/questionnaire.py
> +    session.permanent = True
Should we also set PERMANENT_SESSION_LIFETIME to EQ_SESSION_TIMEOUT?

2017-02-13 16:18 UTC, collisdigital commented on app/settings.py
> +EQ_SESSION_TIMEOUT = int(os.getenv('EQ_SESSION_TIMEOUT', '2700'))
I recommend adding _SECONDS to the name so it's clear this is in seconds, when dealing with times like this it's always hard to know if its milliseconds or not. Same below.

2017-02-14 09:35 UTC, bennpearson requested changes
Timeout doesn't appear on the summary screen

2017-02-14 09:42 UTC, jonnyshaw89 commented
@hamishtaplin its also missing on introduction page

2017-02-15 09:42 UTC, yoganandkunche commented
Observations:
1. Getting a timeout pop up on a session time out screen.
2. Hitting [esc] have the same effect as [Continue Survey] not sure if we want to fix it or leave it as a feature.
3. Pop up always displays ‘UK Innovation survey’ irrespective of the survey that we are currently filling.

Rest looks good. The button colour on the pop differs between census and other survey which is really good.

2017-02-15 09:51 UTC, jonnyshaw89 commented
@hamishtaplin should i put the same fix to the session timeout screen as i have to the thank you page?

2017-02-16 13:10 UTC, bennpearson approved these changes

2017-02-16 13:30 UTC, LJBabbage commented
We use "Save and sign out" on the time out screen but  "Save and complete later" on the survey screen, they are doing the same thing, should it not be consistent?

2017-02-16 13:31 UTC, LJBabbage requested changes
We use "Save and sign out" on the time out screen but "Save and complete later" on the survey screen, they are doing the same thing, should it not be consistent?

2017-02-16 14:09 UTC, hamishtaplin commented
@LJBabbage We're changing the label of the 'save and complete later' button anyway so probably doesn't matter.

2017-02-16 16:36 UTC, LJBabbage commented on app/views/errors.py
> +    return render_theme_template('default', 'session-expired.html'), 401
Not a fan of this, so we showing the session-expired page for all 401's. No token/unauthorised we are putting up the message "To help protect your information we have signed you out" and the page title is "Save Successful"

2017-02-16 16:39 UTC, jonnyshaw89 commented on app/views/errors.py
> +    return render_theme_template('default', 'session-expired.html'), 401
If you can find a way to distinguish the 2 in flask them I'm open to feedback. However the only reason someone would hit the 401 would be if they were up to no good, so showing them the Session expired page is probably ok.

2017-02-16 16:46 UTC, LJBabbage commented on app/views/errors.py
> +    return render_theme_template('default', 'session-expired.html'), 401
I don't have the answer. The analytics will be fun if anyone asks us how many people have tried to hackthe token and we have to say that includes timeouts.

2017-02-17 14:32 UTC, yoganandkunche commented
Retested on branch and works as expected (issues now resolved)

2017-02-17 14:44 UTC, jonnyshaw89 commented
@LJBabbage All on you :)

2017-02-17 14:49 UTC, hamishtaplin commented on app/views/errors.py
> +    return render_theme_template('default', 'session-expired.html'), 401
@LJBabbage @jonnyshaw89 Could we pass something to that page if someone actually times out vs no token/unauthorised to distinguish between the two? Even if it's a just a querystring.

2017-02-17 15:04 UTC, jonnyshaw89 commented on app/views/errors.py
> +    return render_theme_template('default', 'session-expired.html'), 401
@hamishtaplin not very easily. i spent a day looking at this and as soon as flask know that the session has expired it removes any trace of it.

2017-02-20 13:09 UTC, LJBabbage approved these changes

2017-02-20 13:33 UTC, merged