Issue 922: Add an OptionalForm validator
ONSdigital/eq-survey-runner pull request #928
Opened 2017-02-08 15:03 UTC by iwootten

This adds an OptionalForm validator, which can be applied to any single field on a form to correctly halt validation if all of the fields on the form are empty. 

We use this currently only with DateForms, but could be used on any formfield which has multiple subfields that is only deemed empty when all fields are empty.

Fixes issue #922 

### How to review 
Check it out, using Census/Individual see if you can proceed without entering a day in the date of birth field.

2017-02-08 17:48 UTC, collisdigital commented
Do we need a Selenium test that exercises the date question pattern in the way that the issue failed as well as the component test?

2017-02-09 09:53 UTC, yoganandkunche commented
@ian: a minor issue not related to this fix though.. I think it regressed (may be worth fixing in the same PR). The responded must be able to select the 'Select month' value even after selecting any month from the drop down.

2017-02-09 10:32 UTC, collisdigital commented
@yoganandkunche but only if the question is optional, otherwise they shouldn't be able to re-select 'Select month'; at least that's what I believe the behaviour is

2017-02-09 10:44 UTC, yoganandkunche commented
@collisdigital : Yes thats right.! However I am raising a separate defect as suggested by @iwootten

2017-02-09 12:21 UTC, ajmaddaford requested changes

2017-02-09 12:21 UTC, ajmaddaford commented on app/validation/validators.py
> +                           isinstance(formfield.raw_data[0], string_types) and not formfield.raw_data[0])
Can we break this down a bit so it's clearer?

2017-02-09 16:33 UTC, iwootten commented
I've added the fix for #930 into this, given the tests depended on the fix for #922 being in place.

2017-02-10 12:13 UTC, jonnyshaw89 approved these changes

2017-02-10 12:47 UTC, ajmaddaford approved these changes

2017-02-10 13:54 UTC, merged