Fixes #923 other text value retained even when other not selected.
ONSdigital/eq-survey-runner pull request #935
Opened 2017-02-09 16:06 UTC by samiwel

### What is the context of this PR?
Fixes #923 .

### How to review 
All automated tests should pass.
Open either `test_checkbox.json` and `test_radio.json` schemas.
Select the `Other` option and enter a value into the text field.
Save and continue.
Go back.
Select a different option.
Save and continue.
Go back.
Select the `Other` option again.
Confirm that the previous value is not in the Other text field.

Should also work when selecting multiple options (checkbox).

2017-02-10 09:49 UTC, iwootten requested changes

2017-02-10 09:49 UTC, iwootten commented on app/forms/questionnaire_form.py
> +def clear_other_text_field(block_json, data, form_data):
At the moment, the form_helper has some deserialisation logic around dates within it. I would think that this clearing of the other text field would be better placed alongside as the data wouldn't be manipulated as part of the form logic then.

2017-02-10 09:49 UTC, iwootten commented on app/forms/questionnaire_form.py
> +                    form_data.get(answer['id']) is not None and \
I think these last two conditions can simply be expressed as:

    and form_data.get(answer['id'])

2017-02-10 11:54 UTC, iwootten commented on app/forms/questionnaire_form.py
> +def clear_other_text_field(block_json, data, form_data):
Actually, this clear could possibly be achieved within the get_answer_fields method?

2017-02-13 10:43 UTC, jonnyshaw89 approved these changes

2017-02-13 11:36 UTC, iwootten approved these changes

2017-02-13 11:41 UTC, samiwel commented
Squashed and rebased ready to be merged.

2017-02-13 12:00 UTC, merged