fixing regression caused by WTForms
ONSdigital/eq-survey-runner pull request #947
Opened 2017-02-14 15:48 UTC by jonnyshaw89

### What is the context of this PR?
Re-implementing feature in https://github.com/ONSdigital/eq-survey-runner/pull/897 that was regressed in https://github.com/ONSdigital/eq-survey-runner/pull/885

### How to review 
Re-test https://github.com/ONSdigital/eq-survey-runner/issues/883

2017-02-14 16:00 UTC, benjefferies requested changes

2017-02-14 16:00 UTC, benjefferies commented on app/forms/household_relationship_form.py
> +    household_answers = answer_store.filter(block_id='household-composition', limit=settings.EQ_MAX_NUM_REPEATS)
Maybe a test to prevent regressions?

2017-02-15 14:36 UTC, iwootten requested changes

2017-02-15 14:36 UTC, iwootten commented on app/forms/household_relationship_form.py
> +    household_answers = answer_store.filter(block_id='household-composition', limit=settings.EQ_MAX_NUM_REPEATS * 2)
Why x 2?

2017-02-15 14:40 UTC, jonnyshaw89 commented on app/forms/household_relationship_form.py
> +    household_answers = answer_store.filter(block_id='household-composition', limit=settings.EQ_MAX_NUM_REPEATS * 2)
because it should have an answer for first-name and an answer for last-name

2017-02-15 14:47 UTC, iwootten commented on app/forms/household_relationship_form.py
> +    household_answers = answer_store.filter(block_id='household-composition', limit=settings.EQ_MAX_NUM_REPEATS * 2)
Won't it also return middle names? Maybe it would be better to query each answer_id individually?

2017-02-15 15:00 UTC, collisdigital commented on app/forms/household_relationship_form.py
> +    household_answers = answer_store.filter(block_id='household-composition', limit=settings.EQ_MAX_NUM_REPEATS * 2)
Last name isn't mandatory by the way

2017-02-15 15:13 UTC, iwootten requested changes

2017-02-15 15:13 UTC, iwootten commented on app/forms/household_relationship_form.py
> +    household_first_name_answers = answer_store.filter(block_id='household-composition', answer_id='first-name', limit=settings.EQ_MAX_NUM_REPEATS)
I guess the problem with this approach is that we can't guarantee that the last_names each match with the first_name as last_name is not mandatory.

2017-02-15 15:14 UTC, jonnyshaw89 commented on app/forms/household_relationship_form.py
> +    household_first_name_answers = answer_store.filter(block_id='household-composition', answer_id='first-name', limit=settings.EQ_MAX_NUM_REPEATS)
That problem comes with the zip? would the answer-instance maintain the gaps?

2017-02-15 15:17 UTC, iwootten commented on app/forms/household_relationship_form.py
> +    household_first_name_answers = answer_store.filter(block_id='household-composition', answer_id='first-name', limit=settings.EQ_MAX_NUM_REPEATS)
Ah yes, but I think if I remember correctly we are storing blank answers for this particular form where there's nothing entered, so probably not a problem.

2017-02-15 15:40 UTC, collisdigital commented on app/forms/household_relationship_form.py
> +    household_first_name_answers = answer_store.filter(block_id='household-composition', answer_id='first-name', limit=settings.EQ_MAX_NUM_REPEATS)
Assuming that change thats in another PR doesn't stop it storing blank entries, the trim thing?

2017-02-15 16:05 UTC, iwootten commented on app/forms/household_relationship_form.py
> +    household_first_name_answers = answer_store.filter(block_id='household-composition', answer_id='first-name', limit=settings.EQ_MAX_NUM_REPEATS)
Well, that will just strip it down to the empty string '' and is only for mandatory answers...so won't affect middle or last names. Middle and last names are stripped by the optional validator, but don't have to be populated and store blank entries. You can see some existing tests which haven't been altered in my branch for such behaviour here: https://github.com/ONSdigital/eq-survey-runner/blob/master/tests/app/forms/test_household_composition.py#L62

2017-02-15 16:07 UTC, iwootten approved these changes

2017-02-16 09:34 UTC, benjefferies approved these changes

2017-02-16 10:17 UTC, merged