Add retry mechanism for setup of database
ONSdigital/eq-survey-runner pull request #955
Opened 2017-02-15 18:54 UTC by collisdigital

### What is the context of this PR?
Currently when using `docker-compose up` the Postgres Docker image may not be ready when the app starts up. Due to the way wsgi does its importing at startup if the app dies at startup (which it does if it can't connect to the database) it cannot recover without restarting the docker image; this change introduces a retry mechanism for connecting to and setting-up the database with a configurable pause between attempts.

### How to review 
You should be able to run `docker-compose up` and see the database connects successfully after failing at least once (it always fails once for me); the app should work without having to restart docker.

2017-02-16 11:55 UTC, benjefferies requested changes

2017-02-16 11:55 UTC, benjefferies commented on .travis.yml
>  sudo: required
We might be able to do container builds now?

2017-02-16 11:55 UTC, benjefferies commented on .travis.yml
> +    - yarn
Do we need to run yarn? Won't this run in the container?

2017-02-16 11:55 UTC, benjefferies commented on .travis.yml
> +    - docker run onsdigital/eq-survey-runner-unit-tests
Should we do this on script?

2017-02-16 11:55 UTC, benjefferies commented on scripts/run_tests.sh
> +# ./scripts/run_tests.sh [-u] [-f]
Looks like we are adding a lot of logic to support option parameters. Why not split the two bits of logic into `run_tests_functional.sh` and `run_tests_unit.sh` where this run_tests.sh wraps both?

2017-02-16 11:57 UTC, collisdigital commented on .travis.yml
> +    - yarn
It's needed to run the Selenium tests; did discuss with Hamish about splitting the testing part out from the app part, they're currently all one thing.

2017-02-16 12:01 UTC, collisdigital commented on scripts/run_tests.sh
> +# ./scripts/run_tests.sh [-u] [-f]
good idea

2017-02-16 14:35 UTC, collisdigital commented on scripts/run_tests.sh
> +# ./scripts/run_tests.sh [-u] [-f]
done

2017-02-17 11:43 UTC, jonnyshaw89 approved these changes

2017-02-17 13:13 UTC, benjefferies approved these changes

2017-02-17 13:13 UTC, benjefferies commented on .travis.yml
> +    - pushd /tmp
Cool, didn't know about pushd/popd

2017-02-17 13:13 UTC, merged

2017-02-17 13:30 UTC, collisdigital commented on .travis.yml
> +    - pushd /tmp
yeah useful; standard *nix commands