Wrap with quotes to stop splitting
ONSdigital/eq-survey-runner pull request #971
Opened 2017-02-22 10:25 UTC by benjefferies

### What is the context of this PR?
Generating schemas will fail if there are spaces in the path.

### How to review 
Clone repository into a directory with spaces in `git clone https://github.com/ONSdigital/eq-survey-runner.git eq\ survey\ runner`

2017-02-22 13:52 UTC, jonnyshaw89 requested changes

2017-02-22 13:52 UTC, jonnyshaw89 commented on scripts/run_app.sh
>  if [ -z "$EQ_GIT_REF" ]; then
do we still need any of this? it was used to determine if the app had changed but no is only displayed on the status page?

2017-02-22 14:02 UTC, collisdigital commented on scripts/run_app.sh
>  if [ -z "$EQ_GIT_REF" ]; then
There was also discussion about it being somewhere in the log output at startup for Splunk, is it logged anywhere?

2017-02-22 14:02 UTC, benjefferies commented on scripts/run_app.sh
>  if [ -z "$EQ_GIT_REF" ]; then
Yeah it's logged out on start up

2017-02-22 14:23 UTC, jonnyshaw89 commented on scripts/run_app.sh
> +url=$(python token_generator.py)
Can we get rid of this yet? no one likes it :)

2017-02-22 14:55 UTC, benjefferies commented on scripts/run_app.sh
> +url=$(python token_generator.py)
I'm happy to get rid of it. Everyone goes to the dev page now surely?

2017-02-22 14:56 UTC, jonnyshaw89 commented on scripts/run_app.sh
> +url=$(python token_generator.py)
Yeh, probably just launch the dev page

2017-02-22 15:36 UTC, benjefferies commented on scripts/run_app.sh
> +url=$(python token_generator.py)
Done

2017-02-22 16:17 UTC, jonnyshaw89 approved these changes

2017-02-23 09:11 UTC, ajmaddaford approved these changes

2017-02-23 09:32 UTC, merged