Added resource to error logs
ONSdigital/eq-survey-runner pull request #976
Opened 2017-02-22 14:54 UTC by jonnyshaw89

### What is the context of this PR?
When errors are logged they don't contain enough context to be useful.
This PR adds the resource that was being requested when the error occurred.
We were seeing many 404 errors but the logs did not show what resource was being requested.

### How to review 
Hit an invalid url and observe that the resource you requested is in the logged error

2017-02-22 15:59 UTC, benjefferies approved these changes

2017-02-22 16:00 UTC, benjefferies requested changes
Should probably add to the else statement too?

2017-02-22 16:27 UTC, benjefferies commented on app/views/errors.py
> +    log_exception(error, 200)
Seems weird to return 200 here, maybe a 409 would be more applicable

2017-02-22 16:34 UTC, jonnyshaw89 commented on app/views/errors.py
> +    log_exception(error, 200)
This PR isn't really about changing the status that is returned. Its more adding disability of what is returned. @ajmaddaford what do you think about this?

2017-02-22 16:53 UTC, ajmaddaford commented on app/views/errors.py
> +    log_exception(error, 200)
Agreed, this pull request is to add the url and status code to the log output, if we want to change the behaviour we should do so in another pull request.

2017-02-22 16:53 UTC, ajmaddaford approved these changes

2017-02-23 08:23 UTC, benjefferies approved these changes

2017-02-23 09:06 UTC, merged