google analytics issue fix
ONSdigital/eq-survey-runner pull request #978
Opened 2017-02-22 18:11 UTC by bennpearson

### What is the context of this PR?
Fixs #977 Google analytics events were behaving erratically so this fixes the issue.

### How to review 

- Select schema `census_household.json`
- navigate to question that doesn't have a label and click on `guidance`, `help and support`, `previous`.
- cause an error on the page
- check google analytics

2017-02-22 19:21 UTC, collisdigital requested changes
You also need to remove everything under `app/analytics/` and the setup_analytics() function in `app/__init__.py` and calls to it.

2017-02-22 19:21 UTC, collisdigital commented on app/templates/layouts/_base.html
> +    <script>
I wonder if we should put this into a separate template and include it here to keep it separate?

2017-02-23 08:10 UTC, hamishtaplin requested changes

2017-02-23 08:10 UTC, hamishtaplin commented on app/assets/js/app/modules/analytics.js
> +    trackEvent = function(evt, data) {
If we're gonna change this then:

```javascript
trackEvent = (evt, data) => window.ga(evt, data)
```

is more concise

2017-02-23 11:46 UTC, hamishtaplin approved these changes

2017-02-23 12:37 UTC, collisdigital reviewed
Looks good to me, needs the team to review it

2017-02-23 12:40 UTC, collisdigital approved these changes

2017-02-23 12:43 UTC, merged