Reduce complexity of adding new relic
ONSdigital/eq-survey-runner pull request #983
Opened 2017-02-23 11:04 UTC by jonnyshaw89

### What is the context of this PR?
Fixing the build by reducing the complexity of the create_app method

### How to review 
Does the build pass?

2017-02-23 11:05 UTC, ajmaddaford approved these changes

2017-02-23 11:10 UTC, benjefferies approved these changes
I think create_app can be tidied up a lot more and we should look at doing it properly at some point but I understand this is a blocking issue for now

2017-02-24 09:59 UTC, benjefferies requested changes

2017-02-24 09:59 UTC, benjefferies commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
Is this something that needs to be configurable?

2017-02-24 09:59 UTC, benjefferies commented on tests/integration/test_application_variables.py
> +from mock import patch
Unused import?

2017-02-24 10:16 UTC, jonnyshaw89 commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
What do you mean?

2017-02-24 10:22 UTC, benjefferies commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
We could remove NEW_RELIC_APP_NAME  and do

```
def setup_newrelic():
    if settings.EQ_NEW_RELIC_ENABLED:
        import newrelic.agent
        newrelic.agent.initialize()
        newrelic.agent.register_application(name='eq-survey-runner')
```

2017-02-24 10:24 UTC, jonnyshaw89 commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
We could but what if we wanted to log both pre-prod and prod to the same New Relic account?

2017-02-24 10:27 UTC, benjefferies commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
I guess that's what NEW_RELIC_ENVIRONMENT is for according to https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-management-api#initialize

2017-02-24 11:15 UTC, jonnyshaw89 commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
They are much the same but this just means we don't need to add the ini file

2017-02-24 11:18 UTC, benjefferies commented on README.md
>  NEW_RELIC_APP_NAME - The name to display for the application in New Relic
Fair enough if they are. I didn't know if new relic had a view where you could see all of the same apps in their different environments or something.

2017-02-24 11:18 UTC, benjefferies approved these changes

2017-02-24 11:19 UTC, merged