Session timeout should save answers
ONSdigital/eq-survey-runner pull request #993
Opened 2017-02-27 15:20 UTC by benjefferies

### What is the context of this PR?
Session timeout should save answers when user clicks save and sign out. 
If a user times out before clicking save and sign out all answers but the latest page they had timed out on should be saved

### How to review 
Verify timeout.spec.js tests the scenario correctly

2017-02-27 15:22 UTC, jonnyshaw89 requested changes

2017-02-27 15:22 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> -    _delete_user_data()
you should replace this with logout_user() to kill the flask session

2017-02-27 15:23 UTC, benjefferies commented on app/views/questionnaire.py
> -    _delete_user_data()
Good spot, I'll also add an IT for it

2017-02-27 16:42 UTC, jonnyshaw89 commented on app/views/questionnaire.py
> +    session_storage.clear()
i still think we need to call logout_user if only just to stop a login attempt when they reload?

2017-02-28 14:07 UTC, LJBabbage approved these changes

2017-02-28 14:08 UTC, LJBabbage commented
Stick a "fixes" in the PR text so it closes the issue when its merged

2017-02-28 14:25 UTC, jonnyshaw89 approved these changes

2017-02-28 16:42 UTC, collisdigital commented
Would be good if this was in for the demo tomorrow!

2017-02-28 16:45 UTC, benjefferies commented
Tell travis that @collisdigital. Fix one intermittent timeout test another one fails.

2017-02-28 17:00 UTC, benjefferies commented
I lied. It was broken from the rebase. test_timeout.json now needs a summary block.

2017-02-28 17:56 UTC, collisdigital commented
👍

2017-02-28 19:08 UTC, merged

2017-03-01 09:15 UTC, collisdigital commented
Fixes #991