Reduce Template Logic
ONSdigital/eq-survey-runner pull request #994
Opened 2017-02-27 16:02 UTC by iwootten

### What is the context of this PR?
Removes some of the nasty template logic surrounding integers/other options and moves it to backend at a form level.

### How to review 
See if the existing tests continue to pass..

2017-02-28 15:58 UTC, benjefferies requested changes
Looks better

2017-02-28 15:58 UTC, benjefferies commented on app/forms/questionnaire_form.py
> +            self.options_with_children = SchemaHelper.get_parent_options_for_block(self.block_json)
Do we need to get all the options for just this answer_id?

2017-02-28 16:06 UTC, iwootten commented on app/forms/questionnaire_form.py
> +            self.options_with_children = SchemaHelper.get_parent_options_for_block(self.block_json)
Nope, but we will as part of the request for the block, which this call will cache.

2017-03-01 09:36 UTC, jonnyshaw89 approved these changes

2017-03-01 11:06 UTC, benjefferies approved these changes

2017-03-01 14:20 UTC, merged